### PR TITLE
Fix hmmm

### PR DESCRIPTION
**Pull request by srirambv**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
Fixes: https://github.com/brave/brave-browser/issues/1858

- Enable rewards and fail the CAPTCHA, error message  `Hmmm, not quite...` should be shown

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by NejcZdovc** [comment]
master (0.59.x) 8d440ef

**Comment by srirambv** [comment]
@kjozwiak @rebron @bbondy request to uplift as the original PR is already in 0.56.x

**Comment by kjozwiak** [comment]
Approved for `0.56.x` uplift 👍

**Comment by srirambv** [comment]
@NejcZdovc could you add it to 0.56.x and update the merged labels

**Comment by NejcZdovc** [comment]
@srirambv merged to 56

**Pull request merged**
