### PR TITLE
Remove copy clipboard dependency

### PR DESCRIPTION
**Pull request by orspetol**
Resolves [brave/brave-browser/issues/6855](https://github.com/brave/brave-browser/issues/6855)

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by ryanml — CHANGES_REQUESTED** [review]
Code changes look good! Can you squash the commits?

**Comment by orspetol** [comment]
Squashed

**Review by ryanml — APPROVED** [review]
++ thanks for picking this up

**Comment by mihaiplesa** [comment]
Is this accurate? Might need a rebase.
Screenshot 2021-02-10 at 12 20 48

**Comment by orspetol** [comment]
@mihaiplesa yes thats accurate. For some reason removal of the NPM package increased the package-lock file size. Tested locally just now on a new branch to confirm.

**Review by zenparsing — COMMENTED** [review]
Changes to rewards UI look good, but I think there have been changes to `package.json` since this PR's `package-lock.json` was generated, and the `package-lock.json` diff doesn't look quite right. I'm not sure what the easiest fix is, but I might try resetting both `package.json` and `package-lock.json` to `master`, then doing `npm uninstall clipboard-copy` again.

**Comment by orspetol** [comment]
@zenparsing yeah im not sure what is going on with my local npm then. Thanks for digging in. Let me see if I can get local to replicate what you are seeing and repush.

**Review by mihaiplesa — APPROVED** [review]

**Comment by orspetol** [comment]
After some Git and NPM wizardry I managed to resolve it. Thanks @zenparsing and @mihaiplesa for pointing this out. Not sure what happened.

**Comment by mihaiplesa** [comment]
It might have been because of https://github.com/brave/brave-core/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Frenovate and there's still some coming up. I can pause merging them until yours gets in.

**Comment by orspetol** [comment]
That might be whats causing it. Would love to get this in now to avoid another rebase with the lock files.

**Comment by mihaiplesa** [comment]
Feel free to merge now.

**Pull request merged**
