### PR TITLE
Fixes server error 500 can cause Confirmations to get stuck in the queue - 1.4.x

### PR DESCRIPTION
**Pull request by tmancey**
Fixes https://github.com/brave/brave-browser/issues/7654
Uplift of https://github.com/brave/brave-core/pull/4326

### CODE REVIEW

**Comment by kjozwiak** [comment]
Restarting `macOS` due to https://ci.brave.com/job/brave-browser-build-pr/job/issues%252F7654-1.4.x/1/execution/node/706/log/ failing.

**Comment by kjozwiak** [comment]
@tmancey can you double check and make sure the original PR is working as expected in Nightly `>=1.5.21`? Once that's completed, can you also add the below checklist into https://github.com/brave/brave-core/pull/4338#issue-360708202.

```
Approved, please ensure that before merging: 
- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [ ] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.
```

QA will also go through the original PR on Nightly to make sure things are working as expected. If everything looks good on our side, we'll start the uplift process.

**Comment by tmancey** [comment]
- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [ ] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

**Comment by tmancey** [comment]
@kjozwiak Tested on Nightly and working as expected, thanks

**Pull request merged**
