### PR TITLE
added macro for newly added method in tab_strip_model inside chromium…

### PR DESCRIPTION
**Pull request by ajayseeker**
…_src

Resolves [issue ](https://github.com/brave/brave-browser/issues/37125) along with this [PR](https://github.com/brave/chromium/pull/1)

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by ajayseeker** [comment]
@sangwoo108 I added the macro as asked by you. 
However, there is no brave/chromium_src/chrome/browser/ui/tabs/tab_strip_model.cc. 
I still lack the complete understanding behind adding macro here. 
I went through the [https://github.com/brave/brave-browser/wiki/Patching-Chromium](url) but couldn't understand this case where we are how just adding a #define macro is going to help. 

I see that we are including **"src/chrome/browser/ui/tabs/tab_strip_model.h"** in **"chromium_src/chrome/browser/ui/tabs/tab_strip_model.h"**
Is it that **"src/chrome/browser/ui/tabs/tab_strip_model.cc"** gets compiled because it is linked with **"chromium_src/chrome/browser/ui/tabs/tab_strip_model.h"*?

or, Is it that because the method name is a macro so while rebasing the chromium there are lesser chances of merge conflicts?

Pardon my ignorance, only trying to understand.

**Comment by ajayseeker** [comment]
@sangwoo108, 
Also, I moved the code from browser_frame_mac.mm to browser_command_controller.cc, it seemed like a more generic place to me.
However, I couldn't test the changes on windows and linux as I didn't have access to those OS.

looking forward to hearing from you.

**Comment by sangwoo108** [comment]
Likewise, you shouldn't directly modify any sources under `chrome/..`. Please use our Chromium patching strategy.

**Comment by ajayseeker** [comment]
> Likewise, you shouldn't directly modify any sources under `chrome/..`. Please use our Chromium patching strategy. The PR ([ajayseeker/chromium@032759f](https://github.com/ajayseeker/chromium/commit/032759f3fe6c70379c9ea4533e5743ffb576545a)) should be closed and this PR should include everything we address the issue.

Hi @sangwoo108,
I'm stuck at figuring out the correct way of patching. Can you please share a PR where this was done? It might help me understand the procedure.  
In case, you would like to do the patching part, that also is fine with me.

So far I understood that I'll have to create files in brave/chromium_src corresponding to the file I changed in src/chrome, 
furthermore, I'll have to override the methods I changed in src/chrome in new files and then run "npm run update_patches" and check-in the created patches. But sorry! I'm not confident if this is the right way.

**Comment by sangwoo108** [comment]
> So far I understood that I'll have to create files in brave/chromium_src corresponding to the file I changed in src/chrome,

Yes! You got it right. In the file under chomium_src, we usually use `#define` macro to replace code of the corresponding file. This is hacky way but we prefer this over `npm update patches` which produces new `.patch` file as it's hard to keep up with in terms of rebasing.

That said, I guess it must be really hard to override browser_command file with `define` macro. A many symbols are occurs multiple times, you might have experienced difficulties there. 

---

I'm curious if overriding browser_command.cc is also blocking 'right-click tab -> close' too, which we don't want. If then, it might be better to find other place to block ctrl/cmd + w. If so, can you try overriding `BrowserView::AcceleratorPressed` from `BraveBrowserView::AcceleratorPressed` ? That might be good place for our purpose.

**Comment by ajayseeker** [comment]
> > So far I understood that I'll have to create files in brave/chromium_src corresponding to the file I changed in src/chrome,
> 
> Yes! You got it right. In the file under chomium_src, we usually use `#define` macro to replace code of the corresponding file. This is hacky way but we prefer this over `npm update patches` which produces new `.patch` file as it's hard to keep up with in terms of rebasing.
> 
> That said, I guess it must be really hard to override browser_command file with `define` macro. A many symbols occur multiple times, you might have experienced difficulties there.
> 
> I'm curious if overriding browser_command.cc is also blocking 'right-click tab -> close' too, which we don't want. If then, it might be better to find other place to block ctrl/cmd + w. so, can you try overriding `BrowserView::AcceleratorPressed` from `BraveBrowserView::AcceleratorPressed` ? That might be a good place for our purpose.

@sangwoo108 I've tested this scenario and pinned tabs are not getting closed with 'right-click tab -> close'. 
If you observe the method **ExecuteCommandWithDisposition**(which is changed) it has following switch statement 
`switch (id) {
    // Navigation commands
    case IDC_BACK:
      GoBack(browser_, disposition);
      break;
    case IDC_FORWARD:
      GoForward(browser_, disposition);
      break;
    case IDC_RELOAD:
      Reload(browser_, disposition);
      break;
    case IDC_RELOAD_CLEARING_CACHE:
      ClearCache(browser_);
      [[fallthrough]];
    case IDC_RELOAD_BYPASSING_CACHE:
      ReloadBypassingCache(browser_, disposition);
      break;
    case IDC_HOME:
      Home(browser_, disposition);
      break;
.
.
.
`
here all the IDC_* macros correspond to the keyboard command(interpreted as int) and this method seems to be getting called only when shortcuts are used. 
But yes with my limited understanding changing inside src/brave must be preferred over src/chrome, I'll explore `BraveBrowserView::AcceleratorPressed` and other related methods.

**Comment by ajayseeker** [comment]
Hi @sangwoo108,
Post debugging I realised, `BrowserView::AcceleratorPressed` isn't getting called in the control flow corresponding to "ctrl+w" event.
I further debugged to understand if other methods related to handling keyboard events or close tab in _BrowserView_, _BrowserFrame_, _TabStrip_ and _Tab_ were getting called during _ctrl+w_ control flow. I realised they were not. 

Post some digging I realised that we already have **brave_browser_command_controller.cc** class which overrides **BrowserCommandController**. Also, I found a convincing way to handle this case. 

I've raised a different PR [here](https://github.com/brave/brave-core/pull/23409). Please, review it and share your comments. 
I shall close other unnecessary PRs.

**Pull request closed without merging**
