### PR TITLE
Update Wallet password policy

### PR DESCRIPTION
**Pull request by simoarpe**
## Resolves https://github.com/brave/brave-browser/issues/25780

https://github.com/brave/brave-core/assets/3308503/6c8a12ba-5033-428d-bf08-4c300da3d50a

Updates Wallet password policy to accept a password with a minimum length of 8 characters.
Modifies also UI strings to reflect the new policy (numbers and special characters are not required anymore).

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

- From Brave Wallet settings clear and reset any previous Wallet data, if any
- Navigate to Wallet section and create a new Wallet
- Type the password in both fields with a length less than 8 characters, tap Continue and observe an error message is shown accordingly
- Type a new password in both fields with a length greater than or equal to 8 characters and tap Continue
- Observe the Wallet is being created
- Clear and reset the Wallet again
- Navigate to Wallet section again and try to restore a Wallet
- Type the password in both fields with a length less than 8 characters and observe the error message is shown accordingly
- Type a new password in both fields with a length greater than or equal to 8 characters
- Observe the Wallet is being restored

### CODE REVIEW

**Review by mkarolin — APPROVED** [review]
`strings`++

**Review by fmarier — APPROVED** [review]
Strings and `components/brave_wallet/browser/keyring_service.cc` changes look good.

**Comment by SergeyZhukovsky** [comment]
We need to fix a bunch of unit tests inside `browser/brave_wallet/keyring_service_unittest.cc`

**Comment by simoarpe** [comment]
@SergeyZhukovsky, tests have been fixed.

**Comment by SergeyZhukovsky** [comment]
Do desktop and iOS use the same `KeyringService::IsStrongPassword`? I don't understand how they made that change already without changing the actual check? @simoarpe do you know? Could you check that on desktop at least? I just want to make sure we don't break anything. Logically thinking that function has to be changed as well when desktop, iOS work was done, otherwise if only a message was corrected we would still not allow passwords without special chars.

**Comment by simoarpe** [comment]
@SergeyZhukovsky, apparently Android is the only platform now dependent on this Core method.

* iOS uses its own implementation in `KeyringStore.swift` done in https://github.com/brave/brave-ios/pull/7182/files 
* Desktop uses its own implementation in `use-password-strength.ts` https://github.com/brave/brave-core/blob/2b6396051be106b6e5266d47c349f9f66bcb3aa7/components/brave_wallet_ui/common/hooks/use-password-strength.ts#L18-L29

They both check only the password length.

**Comment by SergeyZhukovsky** [comment]
> They both check only the password length.

Perhaps they were never migrated to using that common function after that PR has landed https://github.com/brave/brave-core/pull/11327

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Pull request merged**
