### PR TITLE
A new avatar icon set

### PR DESCRIPTION
**Pull request by petemill**
Replaces current set of icons with 35 new icons.

Intended to be uplifted to v70, which is the first version that contains a custom brave set of icons. The sooner this is uplifted, the less users who would be affected by changing icons. It was agreed not to add this set on to the previous set since we have not had a Release version with the previous set yet.

Fix https://github.com/brave/brave-browser/issues/6443

## Test plan
- Only new icons are displayed when choosing a new profile avatar in Settings
- All 35 icons are selectable (including the default).
- When a 2nd profile is created after a fresh user data directory is used, the first profile uses the new default icon (the first icon in https://github.com/brave/brave-browser/issues/6443).
- When a user data directory from the previous Brave browser version is used which has multiple profiles with brave avatar icons selected, those profiles now have the newer avatar icons.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
Built as debug (I know- it's slow!) and got this DCHECK error when switching icons:
```
[41979:775:1021/230535.189128:FATAL:profile_metrics.cc(441)] Check failed: false.
0   libbase.dylib                       0x0000000108c2bf5f base::debug::CollectStackTrace(void**, unsigned long) + 31
1   libbase.dylib                       0x00000001088d542b base::debug::StackTrace::StackTrace(unsigned long) + 75
2   libbase.dylib                       0x00000001088d54ad base::debug::StackTrace::StackTrace(unsigned long) + 29
3   libbase.dylib                       0x00000001088d5488 base::debug::StackTrace::StackTrace() + 40
4   libbase.dylib                       0x000000010891f573 logging::LogMessage::~LogMessage() + 131
5   libbase.dylib                       0x000000010891e2d5 logging::LogMessage::~LogMessage() + 21
6   libchrome_dll.dylib                 0x0000000115b7e929 ProfileMetrics::LogProfileAvatarSelection(unsigned long) + 1033
7   libchrome_dll.dylib                 0x000000011976aa40 settings::ManageProfileHandler::HandleSetProfileIconToDefaultAvatar(base::ListValue const*) + 1152
8   libchrome_dll.dylib                 0x000000011976c86b void base::internal::FunctorTraits<void (settings::ManageProfileHandler::*)(base::ListValue const*), void>::Invoke<void (settings::ManageProfileHandler::*)(base::ListValue const*), settings::ManageProfileHandler*, base::ListValue const*>(void (settings::ManageProfileHandler::*)(base::ListValue const*), settings::ManageProfileHandler*&&, base::ListValue const*&&) + 155
9   libchrome_dll.dylib                 0x000000011976c756 void base::internal::InvokeHelper<false, void>::MakeItSo<void (settings::ManageProfileHandler::* const&)(base::ListValue const*), settings::ManageProfileHandler*, base::ListValue const*>(void (settings::ManageProfileHandler::* const&)(base::ListValue const*), settings::ManageProfileHandler*&&, base::ListValue const*&&) + 102
10  libchrome_dll.dylib                 0x000000011976c6c5 void base::internal::Invoker<base::internal::BindState<void (settings::ManageProfileHandler::*)(base::ListValue const*), base::internal::UnretainedWrapper<settings::ManageProfileHandler> >, void (base::ListValue const*)>::RunImpl<void (settings::ManageProfileHandler::* const&)(base::ListValue const*), std::__1::tuple<base::internal::UnretainedWrapper<settings::ManageProfileHandler> > const&, 0ul>(void (settings::ManageProfileHandler::* const&)(base::ListValue const*), std::__1::tuple<base::internal::UnretainedWrapper<settings::ManageProfileHandler> > const&, std::__1::integer_sequence<unsigned long, 0ul>, base::ListValue const*&&) + 101
11  libchrome_dll.dylib                 0x000000011976c5cc base::internal::Invoker<base::internal::BindState<void (settings::ManageProfileHandler::*)(base::ListValue const*), base::internal::UnretainedWrapper<settings::ManageProfileHandler> >, void (base::ListValue const*)>::Run(base::internal::BindStateBase*, base::ListValue const*) + 92
12  libcontent.dylib                    0x000000013ec93e43 base::RepeatingCallback<void (base::ListValue const*)>::Run(base::ListValue const*) const & + 99
13  libcontent.dylib                    0x000000013ec93bf3 content::WebUIImpl::ProcessWebUIMessage(GURL const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, base::ListValue const&) + 275
14  libcontent.dylib                    0x000000013ec928ac content::WebUIImpl::OnWebUISend(content::RenderFrameHost*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, base::ListValue const&) + 652
```

**Comment by bsclifton** [comment]
Works great when compiled as a release build! 😄 Let me re-compile debug again to verify that there's an issue

**Comment by petemill** [comment]
@bsclifton I fixed the `NotReached` path via https://github.com/brave/brave-core/pull/3771/commits/9c2f9540a6e9351126b4748650346e6edc431806. Please re-review.

**Comment by bsclifton** [comment]
CI looks great! There is an unrelated Lint error (which @mihaiplesa and others are fixing by pre-installing a new pip library) and one browser test failed on macOS (known intermittent issue w/ rewards and anonize)

**Pull request merged**
