### PR TITLE
Update Brave Stat text on New Tab Page from "Ads and Trackers blocked" to "Trackers & ads blocked"

### PR DESCRIPTION
**Pull request by 0xedward**
Resolves https://github.com/brave/brave-browser/issues/9692
Resolves https://github.com/brave/brave-browser/issues/9838

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [x] Linux
  - [ ] macOS
  - [x] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [x] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

image

### CODE REVIEW

**Comment by bsclifton** [comment]
LGTM! @0xedward would you be able to take on https://github.com/brave/brave-browser/issues/9838 in this same pull request? 😄

**Comment by 0xedward** [comment]
@bsclifton Sure thing! I'm working on it now

**Comment by bsclifton** [comment]
Marked as `CI/skip` since CI doesn't run for branches in forks - but I did verify this builds locally and all tests pass (I ran unit tests and browser tests on Windows)

**Comment by bsclifton** [comment]
Thanks for the contribution, @0xedward 😄! I'll try and circle back on your other ones now

**Comment by rebron** [comment]
Thanks @0xedward Excellent!

@mkarolin @bsclifton Just to confirm that we do want this for 1.10.x as the stat will be updated then.

**Pull request merged**
