### PR TITLE
Tweak assistant seed

### PR DESCRIPTION
**Pull request by LorenzoMinto**
Resolves https://github.com/brave/brave-browser/issues/33664

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by nvonpentz — COMMENTED** [review]
Please also update https://github.com/brave/aichat/blob/223d4ff3cd89b91a417fb9f2174cc4a39e460c5e/aichat/serve/utils.py#L1

**Comment by petemill** [comment]
@nvonpentz how's that going to work when we have multiple releases with different iterations of the prompt? Can the server instead match the incoming prompt to find where the completion begins (if I'm understanding what that util does)?

**Comment by LorenzoMinto** [comment]
That would be one more reason to move prompt building to the server. But I guess that for parsing the last user input then we should disregard everything starting from the ASSISTANT tag, not regarding of what it is. It seems we are using the assistant seed to tell the normal prompts from suggested questions prompts (which use a different seed)

**Comment by LorenzoMinto** [comment]
Updated `brave/aichat` https://github.com/brave/aichat/pull/65 as requested

**Review by nvonpentz — APPROVED** [review]

**Comment by nvonpentz** [comment]
@petemill It's not, we're going to need to move prompt building to the server to support this feature

**Comment by petemill** [comment]
@nvonpentz what feature?

**Comment by nvonpentz** [comment]
@petemill Anything in which the server needs to the users's message - content filtering, canned answers, RAG, etc.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.62.3 Chromium: 119.0.6045.33 (Official Build) nightly (x86_64)
-- | --
Revision | 587c1d18e97653a3de32c3770ad54e2294fd0097
OS | macOS Version 11.7.10 (Build 20G1427)
```
### Followed my original steps to reproduce from https://github.com/brave/brave-browser/issues/33664#issue-1945846417, and confirmed the prompts are more natural, and don't merely repeat the last output


Screen Shot 2023-10-26 at 2 07 24 PM

**Pull request merged**
