### PR TITLE
Updated brave extension to wait for css selector

### PR DESCRIPTION
**Pull request by reaktivo**
Parent issue: https://github.com/brave/brave-browser/issues/2410
Copying description from https://github.com/brave/brave-extension/pull/94:

There's a performance issue when right-clicking on a Twitter timeline, this is due to the way Twitter builds it's elements (with dozens of css class names) which impacts the way the library `unique-selector` finds elements. This causes a few seconds delay every time anything on a Twitter timeline is clicked.

You can see a bit more details here: https://community.brave.com/t/right-click-hangs-on-mobile-twitter/43332/4

This PR rewrites brave extension's `content.ts` and `background/events/cosmeticFilterEvents.ts` so that the actual `unique` call only happens after the Context sub menu item is clicked.

FYI, I wasn't able to get this changes running locally, so I've wrote this PR blindly – I not 100% sure it's going to work. Any guidance on this would be appreciated.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on (Ran npm run test-unit instead)
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by reaktivo** [comment]
@cezaraugusto could you give this one a look?

**Comment by bsclifton** [comment]
@reaktivo did you need help with this? If you haven't already hit up @cezaraugusto, please do 😄 Or you can ask for help here. We'd love to help you get this across the finish line

**Comment by reaktivo** [comment]
@bsclifton I won't be able to continue to work on this, although I would still love to see this fixed. My machine literally didn't manage to get Brave to compile since I don't have enough disk space and I wasn't able to find a way of testing the extension without baking it into the full browser.

Hopefully somebody can take this PR forward or can advise on testing the extension without a full build.

**Comment by bsclifton** [comment]
Thanks for the patch, @reaktivo! 

This was a tough one- I have a proposed fix using a similar technique to what you did here. It's available for review, if you'd like to check it out:
https://github.com/brave/brave-core/pull/2043

Closing this PR in favor of that solution

**Pull request closed without merging**
