### PR TITLE
remove set default search engine screen for BR / AR

### PR DESCRIPTION
**Pull request by spylogsster**
Resolves https://github.com/brave/brave-browser/issues/26182
Resolves https://github.com/brave/brave-browser/issues/26181

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

- steps from issue

### CODE REVIEW

**Comment by bsclifton** [comment]
@spylogsster this also fixes https://github.com/brave/brave-browser/issues/26181 right?

**Review by iefremov — APPROVED** [review]
chromium_src lgtm

**Review by bsclifton — APPROVED** [review]
We'll want to link to https://github.com/brave/brave-browser/issues/26181 as the new defaults are set in this PR too (ex: this PR doesn't only remove default screen, it also changes default)

But changes LGTM! 😄 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64 VM` using the following build(s):

```
Brave | 1.47.36 Chromium: 107.0.5304.91 (Official build) nightly 64 bits
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 10 Version 22H2 (Build 19045.2193)
```

### `BR (Brazil) locale`

#### `Case #1` - https://github.com/brave/brave-browser/issues/26182

<details>
<summary>brave://welcome</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/26182#issue-1418874390 and ensured that the `Set default search engine screen` was removed from `brave://welcome` as per the following:

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
image | image | image

</details>

#### `Case #2` - https://github.com/brave/brave-browser/issues/26181

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------
image | image | image

</details>

<details>
<summary>Updated Profile (Google/Brave)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Google` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that `Google` is still the default SE for `Normal Windows`
  * ensured that `Google` wasn't replaced by `Brave` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------
image | image

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------
image | image

</details>

<details>
<summary>Updated Profile (Startpage/DDG)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Startpage` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------
image | image

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------
image | image

</details>

<details>
<summary>Updated Profile (Bing/Qwant)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Bing` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Qwant` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------
image | image

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------
image | image

**Comment by kjozwiak** [comment]
## `Android` verification

As per https://github.com/brave/brave-browser/issues/26318#issuecomment-1299587680, the onboarding part of the verification will be completed once @deeppandya fixes/addresses https://github.com/brave/brave-browser/issues/26318.

Verification **PASSED** on `Win 10 x64 VM` using the following build(s):

```
Brave | 1.47.36 Chromium: 107.0.5304.91 (Official build) nightly 64 bits
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 10 Version 22H2 (Build 19045.2193)
```

### `BR (Brazil) locale` (new addition)

#### `Case #1` - https://github.com/brave/brave-browser/issues/26318

* Still `Pending` as it hasn't been implemented. Will run through this case once it lands in `master`

#### `Case #2` - https://github.com/brave/brave-browser/issues/26181

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------
Screenshot_20221102-011741_Brave - Nightly | Screenshot_20221102-011745_Brave - Nightly | Screenshot_20221102-011749_Brave - Nightly

</details>

<details>
<summary>Updated Profile (Google/Google)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Google` was the default SE selected under `brave://settings/searchEngines` for both `Normal` & `PB` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that `Google` is still the default SE for both windows
  * ensured that `Google` wasn't replaced by `Brave` for `Normal` or `Private` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------
Screenshot_20221102-015220_Brave - Nightly | Screenshot_20221102-015257_Brave - Nightly

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------
Screenshot_20221102-015301_Brave - Nightly | Screenshot_20221102-015306_Brave - Nightly

</details>

<details>
<summary>Updated Profile (Qwant/Bing)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Qwant` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Bing` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that `Qwant` is still the default SE for `Normal` windows
* ensured that `Bing` is still the default SE for `Private` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------
Screenshot_20221102-020007_Brave - Nightly | Screenshot_20221102-020042_Brave - Nightly

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------
Screenshot_20221102-020046_Brave - Nightly | Screenshot_20221102-020051_Brave - Nightly

</details>

<details>
<summary>Updated Profile (Startpage/DDG)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Startpage` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that `Startpage` is still the default SE for `Normal` windows
* ensured that `DDG` is still the default SE for `Private` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------
Screenshot_20221102-021059_Brave - Nightly | Screenshot_20221102-021217_Brave - Nightly

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------
Screenshot_20221102-021221_Brave - Nightly | Screenshot_20221102-021226_Brave - Nightly

</details>

**Pull request merged**
