### PR TITLE
Update NoScript interface

### PR DESCRIPTION
**Pull request by cezaraugusto**
address https://github.com/brave/brave-browser/issues/2996
fix brave/brave-browser#4228
fix https://github.com/brave/brave-browser/issues/4572
fix https://github.com/brave/brave-browser/issues/4570
fix https://github.com/brave/brave-browser/issues/4567

Screen Shot 2019-05-23 at 19 09 48

## Design overview

Related to https://github.com/brave/brave-browser/issues/2996, the following have been addressed:

* Make script blocking shortcuts to "Allow once" as easy to access as Muon (legacy). Previously it took 2 clicks in Muon
* Enable scrolling on the detailed view
* Fix focus indicators
* All interactive UI elements in the scripts detail view should have keyboard support and the appropriate focus treatment.
* The interface should accommodate long strings when translated.
* Theme update
  * All design changes (space, color, size)
  * Script detail view (not the click-to-expand option)

The following have *not* being addressed:

* Fix functionality in scripts detail view so that users can allow/block all sources of Javascript or select individual sources to allow/block
* When looking at the scripts detail view, we should enable horizontal scrolling so that someone can see the full FQDN.
* If it's longer than the content area, the additional text to the left of the registered domain (ETLD+1) is initially truncated as an ellipses
* Theme update
  * Option to expand script row
  * Device recognition detail view
  * Connections upgraded to HTTPS view
  * Cross-site trackers detail view

## Test Plan:
1. All new code is covered by automated tests `npm run test-unit`
2. Except for changes explicitly not addressed, visual changes should match spec defined in https://github.com/brave/brave-browser/issues/2996
3. Each issue tagged as `fix` has a manual test plan that should be covered 

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
Unusual thing which I couldn't find an issue for:

When script blocking is enabled, you can also see the default Chrome behavior which I think we'd like to hide. That is outside the scope of this work, but would be great to make sure an issue is captured:
Screen Shot 2019-06-05 at 4 11 35 PM

**Comment by bsclifton** [comment]
here we go, found it! https://github.com/brave/brave-browser/issues/199

**Comment by cezaraugusto** [comment]
@bsclifton re https://github.com/brave/brave-core/pull/2485#pullrequestreview-246303467 this is due to the [blur handler](https://github.com/brave/brave-core/pull/2485/files#diff-8d48652835086af00f48b6c467d401e9R72) I added for updating blocked/allowed lists on close, which is, in fact, a temp fix.

other events such as `unload` or `beforeunload` would be better, but chrome extensions don't handle them properly. they do have a bug report, unfortunately, closed as stale (see https://bugs.chromium.org/p/chromium/issues/detail?id=31262).

there are other better workarounds such as using the messaging APIs to set up a port between the popup and background page (which can catch popup close), but since I fall into your test case before, this would require another round of changes which will bulk even more this PR.

if we all agree this is minor, I can create a tracking issue and work on that in a follow-up.

**Comment by bsclifton** [comment]
SGTM 👍

**Pull request merged**
