### PR TITLE
Update day-zero browser UI experiment

### PR DESCRIPTION
**Pull request by simonhong**
fix https://github.com/brave/brave-browser/issues/39810

Deleted one-day expiration timer. day-zero browser UI experiment will be activated when feature is enabled.
Disabled day-zero experiment when p3a is disabled.

Resolves

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

`DayZeroBrowserUIExptTest.PrefsTest`
`DayZeroBrowserUIExptBrowserTest`
`DayZeroBrowserUIExptSecondLaunchBrowserTest`

#### Fresh user
1. Launch with clean profile with `--enable-features=BraveDayZeroExperiment:variant/a` cmd args
2. Open NTP
3. Check day-zero UI change is applied (See https://github.com/brave/brave-core/pull/24116 for UI changes)

#### Existing user
1. Launch with existing profile with `--enable-features=BraveDayZeroExperiment:variant/a` cmd args
2. Check day-zero UI change is not applied

#### p3a testing
1. Launch with clean profile with `--enable-features=BraveDayZeroExperiment:variant/a` cmd args
2. Disable p3a in the welcome flow
3. Open NTP
4. Check day-zero UI change is not applied

#### For android testing
Please refer https://github.com/brave/brave-core/pull/24617
Like desktop, android also should off experiment when p3a is disabled
NOTE: don't need to check `One-day timeout test` part.

### CODE REVIEW

**Review by DJAndries — APPROVED** [review]
p3a++

**Review by deeppandya — APPROVED** [review]
LGTM. Thank you @simonhong for the change.

**Comment by kjozwiak** [comment]
## `Desktop/Win x64` verification(s):

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.70.36 Chromium: 127.0.6533.73 (Official Build) nightly (64-bit)
-- | --
Revision | 23e4fbbe30cb67e7592dbf19501231ddad555b2e
OS | Windows 11 Version 23H2 (Build 22631.3958)
```

### `Test Case #1` - Fresh/New User

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/24731#issue-2415152839, launched `Brave` using `--enable-features=BraveDayZeroExperiment:variant/a` and ensured the following:

* using the STR/Cases outlined via https://github.com/brave/brave-core/pull/24116, ensured the following:
  * both `rewards` & `wallet` buttons have been removed from the toolbar
  * both `Brave Rewards` & `Brave Talk` NTP cards have been removed
  * `Brave News` was removed from the NTP
  * `NTP SI` are not being displayed when opening NTP
* ensured that enabling `Brave News` via the `Customise dashboard` didn't cause any issues/crashes
* ensured that you can toggle `Show Brave Rewards button` via `brave://settings/appearance`
  * ensured that you can run through the `Rewards` onboarding via the panel without issues
* ensured that you can toggle `Show Brave Wallet button` via `brave://settings/appearance`
  * ensured that you can run through the `Wallet` onboarding via the panel without issues

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|-----------------
image | image | image | image

### `Test Case #2` - Existing User

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/24731#issue-2415152839, launched `Brave` using `--enable-features=BraveDayZeroExperiment:variant/a` and ensured that none of the `day-zero` UI changes were applied to my personal existing profile as per the following:

**`Example`** | **`Example`**
---------------|----------------
image | image

### `Test Case #3` - Existing User

Using the STR/Cases mentioned via https://github.com/brave/brave-core/pull/24731#issue-2415152839, launched `Brave` using `--enable-features=BraveDayZeroExperiment:variant/a` and went through the following:

* disabled `P3A` via the `brave://welcome` flow
* ensured that the UI elements that were removed from `Test Case #1` are not being removed when `P3A` has been disabled

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------
image | image | image | image | image

**Comment by kjozwiak** [comment]
## `Android` verification(s):

### `Test Case #1` - Fresh/New User

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/24617#issue-2404247933, connected the `Pixel 6 Pro` to a `Linux` VM and ran `adb shell "echo ' --enable-features=BraveDayZeroExperiment:variant/a' > /data/local/tmp/brave-test-day-zero-expt"` as per the following:

image

Once completed, installed `Brave` and ensured that the following items have been removed:

* ensured that the `rewards` button from toolbar is not visible anymore
* ensured that NTP SI images are not being displayed when opening new NTP tabs
* ensured that the `Brave News` peek onboarding card is not visible when swiping down via the NTP
* ensured that `Favorites` are still being added into the NTP when visiting websites

**`Example`** | **`Example`** | **`Example`**
---------------|----------------|-----------------
 |  | 

* ensured that you can enable the `Rewards` icon within the toolbar without any issues via `Appearance`
  * ensured that you can run through the `Rewards` onboarding within the panel without issues
* ensured that you can enable `Brave News` without any issues/crashes

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
---------------|----------------|-----------------|------------------
 |  |  | 

* ensured that inline `ads` are being displayed via `Brave News` once `Rewards` has been enabled
* ensured that `NTP SI` are being displayed/shown once `News tab page ads` are enabled via `brave://rewards`
* ensured the ad notifications are still being triggered without issues

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
---------------|----------------|-----------------|------------------
 |  | Screenshot_20240730-190808 |

**Pull request merged**
