### PR TITLE
Fix SR's Themes subpage is not loaded

### PR DESCRIPTION
**Pull request by simonhong**
auto importing of chromium resources by brave module doesn't work properly.
See https://github.com/brave/brave-core/pull/6029#issuecomment-655263184 for root cause.
Just converted to html_to_js.

Resolves https://github.com/brave/brave-browser/issues/10600

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
See Issue's STR

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by simonhong** [comment]
@petemill I'm not sure this is the right fix for this issue. PTAL. It seems `auto import` seems not working properly for chromium's module.
```
  auto_imports = settings_auto_imports + [
                   "ui/webui/resources/html/assert.html|assert",
                   "brave/browser/resources/settings/brave_appearance_page/brave_appearance_browser_proxy.html|BraveAppearanceBrowserProxy, BraveAppearanceBrowserProxyImpl",
                   "chrome/browser/resources/settings/appearance_page/appearance_browser_proxy.html|AppearanceBrowserProxy, AppearanceBrowserProxyImpl",
                   "chrome/browser/resources/settings/route.html|routes",
                   "chrome/browser/resources/settings/router.html|Router",
                 ]
```

**Comment by simonhong** [comment]
I checked that only `brave_appearance_page` has this issue.

**Comment by simonhong** [comment]
@petemill reverted to initial change. It seems difficult to do this with `html_to_js`.

**Comment by petemill** [comment]
@simonhong if we're going to change these, we should probably convert them to JS imports instead of HTML imports. As what you've done here is leave it halfway converted: it uses the JS imports but still converts the other HTML imports, and I'm not sure how long that will be supported.
You can convert to `html_to_js` by looking at other examples in the sync folder. You can even replace the JS file with the output from `src/out/Component/gen/brave/browser/resources/settings/brave_appearance_page/brave_theme.js` which should be a good or perfect starting point from moving the html imports to JS imports.

Chromium is moving everything to `html_to_js`. AFAIK `polymer_modulizer` is just temporary whilst migrating from HTML modules to JS modules, so if we're going to touch the GN we should change IMO. I already did a few with cr84 but not all.

**Comment by petemill** [comment]
@simonhong I pushed a commit which converts to `html_to_js` so that we can control what's imported.
Since I needed to change the import statements, I also took the opportunity to move them away from .patch and to brave_overrides. Please take a look when you are available.

**Comment by simonhong** [comment]
@petemill Thanks a lot!! I pushed one more commit that fixed some trivial bugs. PTAL again. :)
Tested with SR and w/o SR and works great.

**Comment by simonhong** [comment]
@bridiver Ping to give a good news - two patch files are deleted by @petemill 😄 PTAL!

**Comment by petemill** [comment]
@simonhong 👍 ha yes I had a similar change locally to prevent the early return

**Comment by simonhong** [comment]
@petemill good to merge now?

**Comment by kjozwiak** [comment]
Reproduced the original issue using the following build:

```
Brave | 1.13.17 Chromium: 84.0.4147.89 (Official Build) nightly (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.15.6 (Build 19G73)
```

Screen Shot 2020-07-22 at 5 12 40 PM

```
Uncaught ReferenceError: Router is not defined settings.js:2109 
    at HTMLElement.onThemeTap_ (settings.js:2109)
    at HTMLElement.handler (polymer_bundled.min.js:1)
onThemeTap_ @ settings.js:2109
handler @ polymer_bundled.min.js:1
```

Verification **PASSED** on `macOS 10.15.6 x64` using the following build:

```
Brave | 1.13.36 Chromium: 84.0.4147.89 (Official Build) nightly (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.15.6 (Build 19G73)
```

* verified the STR outlined via https://github.com/brave/brave-browser/issues/10600#issue-652825492
* ensured that clicking on `Theme` opened the `Appearance` section
* ensured that switching between themes worked as expected

Screen Shot 2020-07-22 at 5 15 05 PM

| TECHNIK Theme | Default Theme |
|:-------------:|:-------------:|
| Screen Shot 2020-07-22 at 5 15 32 PM | Screen Shot 2020-07-22 at 5 15 22 PM |

**Pull request merged**
