### PR TITLE
Sync: Move from brave-ui to brave-core

### PR DESCRIPTION
**Pull request by cezaraugusto**
address https://github.com/brave/brave-browser/issues/2335
close https://github.com/brave/brave-browser/issues/5198

### Test Plan

```
# ensure Sync is properly displayed
npm run storybook
# build is ok
npm run build
```

### CODE REVIEW

**Comment by cezaraugusto** [comment]
cc @petemill could you check this one?

**Comment by cezaraugusto** [comment]
ok updated

**Comment by cezaraugusto** [comment]
also rebased

**Comment by cezaraugusto** [comment]
rebased again

**Comment by szaimen** [comment]
Any update on this?

**Comment by AlexeyBarabash** [comment]
STR from PR 1st message: both `npm run storybook` and `npm run build` succeeded.

Browse on storybook:
http://localhost:35449/?path=/story/sync-popups-and-modals--reset-sync
http://localhost:35449/?path=/story/sync-popups-and-modals--remove-main-device
http://localhost:35449/?path=/story/sync-popups-and-modals--remove-other-device
 - the color is bright-red
others like http://localhost:35449/?path=/story/sync-popups-and-modals--enter-sync-code - the color is orange.
Though the same is on master.

Own Compiled browser sync ui cases:
1. Empty profile - OK;
2. Create chain - as on master, but needs to be redone;
3. Show codewords - OK;
4. Show QR code - OK;
5. Connect to chain by codewords - OK;
6. Display the list of devices - OK;
7. Leave sync chain - OK, but wrong color as on master;
8. Remove other device - OK, but wrong color as on master;
9. Show QR code or codephrase and cancel - as on master, but needs to be redone.

**Comment by AlexeyBarabash** [comment]
@cezaraugusto 
Maybe the commits containing `Merge` and `Revert` words could be squashed?
Other looks good.

**Comment by cezaraugusto** [comment]
@AlexeyBarabash thanks, rebased the first 5 commits. could you pls re-check?

**Pull request merged**
