### PR TITLE
[Android] Enable network service on android

### PR DESCRIPTION
**Pull request by simonhong**
Network service is enabled on c77.

Below crash code will not be run after enabling network service.
```
Crash: :storage_partition_impl_map.cc(425)] Check failed: partition->url_request_context_
```

Fix https://github.com/brave/brave-browser/issues/5941

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by SergeyZhukovsky** [comment]
@simonhong does ad blocking work with the service turned on?

**Comment by simonhong** [comment]
@SergeyZhukovsky Ads blocking seems not work. After loading `m.ebay.com`, its blocking count is zero. but released version shows non-zero count for same site.
This means android port also needs some works for using network service? cc: @iefremov

**Comment by simonhong** [comment]
If we can't disable network service from c77, I think this PR should be merged first and fix ad blocking. Can't run brave android now. cc: @iefremov

**Comment by simonhong** [comment]
@bridiver ping to owners

**Comment by bridiver** [comment]
android is currently broken in c77, but working with @SergeyZhukovsky to fix it. In any case there's no point in disabling network service anymore because the old code doesn't work

**Pull request merged**
