### PR TITLE
Don't hide media source API for streaming

### PR DESCRIPTION
**Pull request by sangwoo108**
Resolves https://github.com/brave/brave-browser/issues/25130

Hide MediaSource API only when it's not Youtube live streaming.

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by sangwoo108** [comment]
@bsclifton @simonhong This is what I told yesterday

**Comment by sangwoo108** [comment]
Hi, @petemill @fallaciousreasoning ! I'd like to consult with you about this hack. We were hiding MediaSource API from youtube in order to get downloadable URL of videos, which is not `blob://` scheme. But Youtube live streaming is broken with that, so I hacked some of youtube FE. I wonder how this code looks.

**Comment by fallaciousreasoning** [comment]
Just out of interest, is there any reason we can't download the content from the blob url? Does YouTube do something that means the blob can only be consumed once?

**Comment by sangwoo108** [comment]
> Just out of interest, is there any reason we can't download the content from the blob url? Does YouTube do something that means the blob can only be consumed once?

I'm not sure. We're just following what iOS has been doing. Also, when I pass blob: scheme to current implementation, it didn't work. Should it be possible to blob: generally?

**Comment by fallaciousreasoning** [comment]
Hmmm, well I don't know about from `ApiRequestHelper`, but blob urls are basically just whatever data the site requested a blob url for. As they're created by the browser, we can probably get the data out. I think this [README](https://chromium.googlesource.com/chromium/src/+/HEAD/storage/browser/blob/README.md#how-to-use-blobs-browser_side) has a bit more information on it.

That said, I don't think it really solves your problem - we'll still need to read the untrusted data

**Comment by sangwoo108** [comment]
One thing

> Hmmm, well I don't know about from `ApiRequestHelper`, but blob urls are basically just whatever data the site requested a blob url for. As they're created by the browser, we can probably get the data out. I think this [README](https://chromium.googlesource.com/chromium/src/+/HEAD/storage/browser/blob/README.md#how-to-use-blobs-browser_side) has a bit more information on it.
> 
> That said, I don't know if it will actually solve your problem, and it won't get us around the security folks concerns about reading untrusted data.
> 
> (also, what you have doesn't seem unreasonable to me).

Oh, didn't know. I agree that it'd be better to use blob: scheme as is if possilbe. Let me dig that first and check if Youtube doesn't reject the request.

**Pull request closed without merging**
