### PR TITLE
Hide search onboarding for private tab (Uplift 1.12.x)

### PR DESCRIPTION
**Pull request by deeppandya**
Uplift of #6271 
Fixes https://github.com/brave/brave-browser/issues/11021

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
Restarting `Android` as `dist` failed as per https://ci.brave.com/job/pr-brave-browser-hide_search_for_private_tab_dp_1.12.x-android/1/execution/node/383/log/.

```
04:06:17  FAILED: obj/chrome/android/chrome_java.javac.jar obj/chrome/android/chrome_java.javac.jar.info 
```

**Comment by kjozwiak** [comment]
@deeppandya looks like `Android` keeps failing `dist` as per https://ci.brave.com/job/pr-brave-browser-hide_search_for_private_tab_dp_1.12.x-android/2/execution/node/383/log/.

```
13:55:44  FAILED: obj/chrome/android/chrome_java.javac.jar obj/chrome/android/chrome_java.javac.jar.info 
```

Mind taking a look? Do we need a rebase?

**Comment by deeppandya** [comment]
> @deeppandya looks like `Android` keeps failing `dist` as per https://ci.brave.com/job/pr-brave-browser-hide_search_for_private_tab_dp_1.12.x-android/2/execution/node/383/log/.
> 
> ```
> 13:55:44  FAILED: obj/chrome/android/chrome_java.javac.jar obj/chrome/android/chrome_java.javac.jar.info 
> ```
> 
> Mind taking a look? Do we need a rebase?

@kjozwiak i am checking now

**Comment by kjozwiak** [comment]
`Win x64` failed due to losing the spot instance/agent was removed as per https://ci.brave.com/job/pr-brave-browser-hide_search_for_private_tab_dp_1.12.x-windows/2/execution/node/384/log/.

```
15:44:31  Cannot contact i-01d6f02cf19229dab: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@56730e9:i-01d6f02cf19229dab": Remote call on i-01d6f02cf19229dab failed. The channel is closing down or has closed down
15:49:33  Could not connect to i-01d6f02cf19229dab to send interrupt signal to process
```

Above PR only changes the following `Android` files so there's no need to restart `Win x64` as the above doesn't block uplift:

* `android/java/org/chromium/chrome/browser/onboarding/OnboardingPrefManager.java`
* `android/java/org/chromium/chrome/browser/toolbar/top/BraveToolbarLayout.java`

**Pull request merged**
