### PR TITLE
Brave Today: remove hint (scroll down arrow) animation

### PR DESCRIPTION
**Pull request by petemill**
Fix https://github.com/brave/brave-browser/issues/13194
Details in issue.

Also optimize scroll effects
> In order to avoid more expensive composition for child elements, don't even set filter and opacity on the page at 0, only set css properties that will be used for scroll affects after the scroll has started.

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
In issue

### CODE REVIEW

**Review by ryanml — APPROVED** [review]
lgtm

**Review by bsclifton — APPROVED** [review]
Tested it out - I just built `component` (default), so not getting the best perf when I test this... GPU process was getting as high as 45% locally vs maxing out at 35% on compiled official Nightly. Will do a release build here in a min to get a proper comparison, but changes look good! 😃

**Comment by bsclifton** [comment]
Tested out on Release build - looks good 😄 GPU usage is roughly the same for me, but I have a pretty beefy video card

**Comment by petemill** [comment]
Unrelated iOS failure, merging.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following builds:

```
Brave | 1.20.33 Chromium: 88.0.4315.5 (Official Build) nightly (64-bit)
-- | --
Revision | d2abe4588adaeb0d66aa0a0106675be1dff12c64-refs/branch-heads/4315@{#11}
OS | Windows 10 OS Version 2009 (Build 19042.685)
```

* ensured that the "arrow down" animation was removed from NTP
* ensured that scrolling through Brave Today works without any issues
* ensured that there's an improvement in performance once the animation was removed

**`With Animation`** | **`Without Animation`**
------------------------|---------------------------
CPU2 | CPU3

**Pull request merged**
