### PR TITLE
[Shortcuts]: Don't register System commands from the BrowserWindow

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Resolves https://github.com/brave/brave-browser/issues/31758

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
1. Register a shortcut from the MacOS system shortcut manager for `CMD` + `SHIFT` + `D` for `Move Tab to New Window` and `CMD` + `SHIFT` + `B` for `Bookmark All Tabs...`
image
2. Those shortcuts should not be modifiable from `brave://settings/system/shortcuts`
3. Those shortcuts should be updated in the Browser menu items
4. The shortcuts should work

### CODE REVIEW

**Comment by fallaciousreasoning** [comment]
@sangwoo108 do you mind checking if this works for letting you customize shortcuts via the system menu on MacOS?

**Review by sangwoo108 — APPROVED** [review]
Wow, this must have been hard to find out. So, this seems to fix the reported cases in the comment. Nice catch!

But on my env, both cases from the comments weren't reproducible😵‍💫 but I think I understand what's the motivation of this patch and this patch itself looks good to me.

Just noticed one interesting thing. I was following the steps from the https://github.com/brave/brave-browser/issues/31758#issuecomment-1647695848 , where command + shift + D is in conflict between 'Bookmarks all tabs' and 'Move tab to new window', and web ui seems to think those are duplicate 

image

When clicking the reset button on the command, then "bookmark all tabs" will be blank.

And interestingly, clicking "Reset all to default" makes both commands have the shorcut.

**Comment by fallaciousreasoning** [comment]
@sangwoo108 I think I've got a fix for that :smile:

**Review by sangwoo108 — APPROVED** [review]
Still LGTM!

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.59.56 Chromium: 116.0.5845.114 (Official Build) nightly (x86_64)
-- | --
Revision | 11676eb8c4bf058787c740d5fd2d089971f5d942
OS | macOS Version 11.7.9 (Build 20G1426)
```

**Pull request merged**
