### PR TITLE
Fixes smallvec rust vulnerability (1.19.x).

### PR DESCRIPTION
**Pull request by mkarolin**
Fixes brave/brave-browser#13446
Fixes brave/brave-browser#13101

Uplift from #7551 
Uplift from #7412

## Submitter Checklist:

- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by kjozwiak** [comment]
@mkarolin mind taking a look? Looks like CI is failing on every platform due to the following error/failure:

```
10:02:46  FAILED: brave_rust/out/x64/x86_64-unknown-linux-gnu/release/libbrave_rust.a 
10:02:46  python ../../brave/script/cargo.py --rustup_path=../../brave/build/rustup/ --cargo_path=../../brave/build/rustup/ --manifest_path=../../brave/build/rust/Cargo.toml --build_path=brave_rust/out/x64 --target=x86_64-unknown-linux-gnu --toolchain= --is_debug=false --rust_flags=\ -C\ link-arg=--sysroot=\ \ -C\ link-arg=-Wl,-rpath=\$ORIGIN\ 
10:02:46      Blocking waiting for file lock on package cache
10:02:46      Updating git repository `https://github.com/brave/adblock-rust`
10:02:46      Updating crates.io index
10:02:46  error: failed to select a version for `once_cell`.
10:02:46      ... required by package `adblock v0.3.4 (https://github.com/brave/adblock-rust?rev=c647890b6d065daf98cba540d2232c100698c498#c647890b)`
10:02:46      ... which is depended on by `adblock-ffi v0.1.0 (/home/ubuntu/workspace/pr-brave-browser-pr7551_maxk-fix-smallvec_1.19.x-linux/src/brave/vendor/adblock_rust_ffi)`
10:02:46      ... which is depended on by `brave-rust v0.1.0 (/home/ubuntu/workspace/pr-brave-browser-pr7551_maxk-fix-smallvec_1.19.x-linux/src/brave/build/rust)`
10:02:46  versions that meet the requirements `^1.5` are: 1.5.2, 1.5.1
10:02:46  
10:02:46  all possible versions conflict with previously selected packages.
10:02:46  
10:02:46    previously selected package `once_cell v1.4.0`
10:02:46      ... which is depended on by `adblock v0.2.11`
10:02:46      ... which is depended on by `speedreader v0.1.0 (/home/ubuntu/workspace/pr-brave-browser-pr7551_maxk-fix-smallvec_1.19.x-linux/src/brave/components/speedreader/rust/lib)`
10:02:46      ... which is depended on by `speedreader-ffi v0.1.0 (/home/ubuntu/workspace/pr-brave-browser-pr7551_maxk-fix-smallvec_1.19.x-linux/src/brave/components/speedreader/rust/ffi)`
10:02:46      ... which is depended on by `brave-rust v0.1.0 (/home/ubuntu/workspace/pr-brave-browser-pr7551_maxk-fix-smallvec_1.19.x-linux/src/brave/build/rust)`
10:02:46  
10:02:46  failed to select a version for `once_cell` which could resolve this conflict
10:02:46  None
10:02:46  Traceback (most recent call last):
10:02:46    File "../../brave/script/cargo.py", line 101, in <module>
10:02:46      sys.exit(main())
10:02:46    File "../../brave/script/cargo.py", line 95, in main
10:02:46      build(parse_args())
10:02:46    File "../../brave/script/cargo.py", line 70, in build
10:02:46      raise e
10:02:46  subprocess.CalledProcessError: Command '['cargo', 'build', '--release', '--manifest-path=../../brave/build/rust/Cargo.toml', '--target-dir=brave_rust/out/x64', '--target=x86_64-unknown-linux-gnu']' returned non-zero exit status 101
```

**Review by antonok-edm — COMMENTED** [review]
I believe it should be possible to fix this by running `cargo update -p once_cell` in the `build/rust` directory.

**Comment by kjozwiak** [comment]
Restarting `macOS` as it seems like `build` failed due to `Timeout has been exceeded` as per https://ci.brave.com/job/pr-brave-browser-pr7551_maxk-fix-smallvec_1.19.x-macos/4/execution/node/155/log/.

**Comment by kjozwiak** [comment]
`macOS` failed `test-browser` as per https://ci.brave.com/job/pr-brave-browser-pr7551_maxk-fix-smallvec_1.19.x-macos/5/execution/node/202/log/. Created https://github.com/brave/brave-browser/issues/13510 as this seems like a new intermittent issue that hasn't been logged before. Doesn't block uplift as the failure isn't related to this specific PR.

```
11:25:08  1 test timed out:
11:25:08      BraveBookmarkModelLoadedObserverBrowserTest.NoClearSyncV1MetaInfo (../../brave/browser/profiles/brave_bookmark_model_loaded_observer_browsertest.cc:114)
```

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.19.x` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
