### PR TITLE
Adds voice recognition for Leo prompts on Android

### PR DESCRIPTION
**Pull request by SergeyZhukovsky**
Resolves https://github.com/brave/brave-browser/issues/37053

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

1. Open Leo.
2. Tap a microphone icon in the input box.
3. Say something.
4. Observe Leo responses to your prompt.

https://github.com/brave/brave-core/assets/12011303/6c757ef4-8218-4833-a50b-38ff4ca72d2b

Screenshot_20240325-114529
Screenshot_20240325-114229

### CODE REVIEW

**Review by AlexeyBarabash — APPROVED** [review]
:+1:

**Review by samartnik — APPROVED** [review]
lgtm

**Review by nullhook — APPROVED** [review]

**Review by deeppandya — APPROVED** [review]
LGTM

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240216.010 release-keys
Brave build: 1.66.35 
Chromium: 123.0.6312.58 (Official Build) canary (64-bit) 
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-core/pull/22748#issue-2206036912
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Mic` is shown in the query text field
- Verified that tapping a `Mic` opens Android native permission message and then opens UI for the voice query
- Verified that the Android permission message opened only for the first attempt
- Verified that voice recognition is working, the query is sent automatically and the answer is received as expected 
- Verified the same in `English` and `Russian` languages

---------------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
|  |  |  |  |  |

https://github.com/brave/brave-core/assets/128532965/2ba26fc5-837a-4108-8ab0-6564898a66ed

https://github.com/brave/brave-core/assets/128532965/09857cf1-84a9-474e-8a44-c8d4c3fa8a37

**Pull request merged**
