### PR TITLE
allow first party iframes embedded in 3rd-party origins plus exceptio… (uplift to 1.9.x)

### PR DESCRIPTION
**Pull request by bsclifton**
Uplift of https://github.com/brave/brave-core/pull/5433
fix https://github.com/brave/brave-browser/issues/8629
fix https://github.com/brave/brave-browser/issues/9564
fix https://github.com/brave/brave-browser/issues/9105

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
Looks like `test-browser` failed on `macOS` as per https://ci.brave.com/job/pr-brave-browser-fix-google-drive-autoplay-bj-1.9.x/1/execution/node/498/log/. This is a known intermittent issue which will be addressed via https://github.com/brave/brave-browser/issues/9339 and doesn't block uplift.

```
19:59:08  [  FAILED  ] BraveRewardsBrowserTest.NotVerifiedWallet, where TypeParam =  and GetParam() =  (6148 ms)
19:59:08  [540/540] BraveRewardsBrowserTest.NotVerifiedWallet (6339 ms)
19:59:08  2 tests failed:
19:59:08      BraveNetworkDelegateBrowserTest.ThirdPartyCookiesBlockedNestedFirstPartyIframe (../../brave/browser/net/brave_network_delegate_browsertest.cc:252)
19:59:08      BraveRewardsBrowserTest.NotVerifiedWallet (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:2326)
```

`Travis` also failed due to `TEST_SUITE=test-security` because of the `yargs-parser` npm package which is a known issue and not blocking uplift.

**Comment by kjozwiak** [comment]
However, concerned about `test-browser` failing on `Linux` as per https://ci.brave.com/job/pr-brave-browser-fix-google-drive-autoplay-bj-1.9.x/1/execution/node/420/log/

```
19:16:17  [  FAILED  ] BraveNetworkDelegateBrowserTest.ThirdPartyCookiesBlockedNestedFirstPartyIframe, where TypeParam =  and GetParam() =  (760 ms)
19:16:17  [541/544] BraveNetworkDelegateBrowserTest.ThirdPartyCookiesBlockedNestedFirstPartyIframe (913 ms)
19:16:18  [542/544] PerfPredictorTabHelperTest.ScriptBlockHasSavings (651 ms)
19:16:19  [543/544] BraveRewardsBrowserTest.PanelShowsCorrectPublisherData (1307 ms)
19:16:25  [544/544] BraveRewardsBrowserTest.ProcessPendingContributions (5503 ms)
19:16:25  1 test failed:
19:16:25      BraveNetworkDelegateBrowserTest.ThirdPartyCookiesBlockedNestedFirstPartyIframe (../../brave/browser/net/brave_network_delegate_browsertest.cc:252)
```

I haven't seen the above before and it's a third party cookie failure which this issue touches. @bsclifton @bridiver can I get a confirmation/double check that the above is an intermittent issue and not related to the above chance?

**Comment by bsclifton** [comment]
Definitely not expected
cc: @bridiver

**Comment by bsclifton** [comment]
Given the failing test and also how close we are to shipping 1.9, I'm going to close this out

**Comment by bsclifton** [comment]
Re-opening as we pulled a few issues into 1.9 Hotfix 1... going to test locally 😄 

Gave PR a rebase so we can let CI run again

**Comment by bsclifton** [comment]
Found the problem with the test - definitely my bad; stemmed from when I left out test in merge for this PR:
https://github.com/brave/brave-core/pull/5410

Working on fix... Should only be affecting test. Code should be G2G!

**Comment by bsclifton** [comment]
Rebased and pushed latest 😄 I ran all browser tests locally and they're passing!

**Comment by pes10k** [comment]
I've confirmed that the original issue being solved here (the side panel widget on wordpress) works correctly on nightly now

**Comment by rebron** [comment]
Tested on Beta: https://github.com/brave/brave-browser/issues/9064#issuecomment-635024278

**Comment by bsclifton** [comment]
CI looks great - there was one browser test failure:
https://ci.brave.com/job/pr-brave-browser-fix-google-drive-autoplay-bj-1.9.x/5/execution/node/476/log/
```
18:39:20  [  FAILED  ] BraveRewardsBrowserTest.NotVerifiedWallet, where TypeParam =  and GetParam() =  (6248 ms)
18:39:20  [541/541] BraveRewardsBrowserTest.NotVerifiedWallet (6335 ms)
18:39:20  1 test failed:
18:39:20      BraveRewardsBrowserTest.NotVerifiedWallet (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:2331)
```
This is a known issue captured with https://github.com/brave/brave-browser/issues/9339 and it has been fixed in 1.11 😄

**Pull request merged**
