### PR TITLE
Customize user dir and app icon depending on channel on MacOS

### PR DESCRIPTION
**Pull request by simonhong**
Customize user dir/app icon regarding to channel on MacOS
This work is based on @darkdh 's https://github.com/brave/brave-core/tree/multi-channel.

Issue: https://github.com/brave/brave-browser/issues/10

Win/Linux customization will be handled in separate PR.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.

## Test Plan:
- [x] Manual test for checking whether different app icon is visible
- [x] Manual test for checking whether different user dir is created
## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions

### CODE REVIEW

**Comment by simonhong** [comment]
I'm trying to use different app icon that shown in launcher.
With current patch, appropriate app.icns is stored in `our/Release/Brave.app/Contents/Resources`.
However, release icon is still shown.
Should I modify another place for this?

**Comment by darkdh** [comment]
Please use this image resources 
[Brave_Desktop_iconset.zip](https://github.com/brave/brave-core/files/1870432/Brave_Desktop_iconset.zip)

The one in muon is out-dated.
`Brave Beta`->beta
`Brave Dev`->dev
`Brave Nightly`->canary

`Brave Dev_NPM` or `Brave TestBuild` -> local dev build

**Comment by simonhong** [comment]
@darkdh updated with new icons

**Comment by simonhong** [comment]
There is https://github.com/brave/brave-browser/pull/137 for waiting this PR :)
AFAIK, we prefer making a patch to copy strategy. @bbondy 
If not, how to determine whether changes should use patch or copy?

**Comment by darkdh** [comment]
We prefer override method and neither patch nor copy.
Since this is not class method you have to patch or copy and I was not asking you to copy entire file, just the function you modified. If you just modified one line of the function, I won't ask you to pull out the functions. I can accept `GetChannelString` and `GetChannel` as patch but you have to pull out `GetChannelSuffixForDataDir` which is new function to the file.

And if you go with patch on `GetChannelString` you need to reduce the patch size, too many duplicate part. Just comment out the part of `KSProductID` and change the define condition

**Comment by simonhong** [comment]
@darkdh Addressed your comments. Please check again.

**Comment by simonhong** [comment]
@darkdh Thanks :)

**Pull request merged**
