### PR TITLE
Add sitehacks and cosmetic filters from browser-laptop

### PR DESCRIPTION
**Pull request by bbondy**
Fix https://github.com/brave/brave-browser/issues/1874

Before merging I'd need to udpate DEPS for brave-extensions.

brave-extension related commit that this should be merged together with:
https://github.com/brave/brave-extension/pull/77

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by jonathansampson** [comment]
@bbondy Do the CSS files need the MPL-2.0 license header?

**Comment by bbondy** [comment]
skipped since it is just more to inject on page load, but normally ya.

**Comment by bbondy** [comment]
0.57.x: a7e7cf81da85ea064fffda9cd87d4a356bf1b365
master: a85c912aa9390b951251cfcbef9f3a10213f7c88

**Comment by bbondy** [comment]
Had to also pull into 0.56.x: b061ce9a3e59d27778d932176eb627d19c7db50b

Since we needed it for https://github.com/brave/brave-core/pull/768#issuecomment-434198634

**Pull request merged**
