### PR TITLE
[ads] Fixes intermittent crash during Brave Rewards reset

### PR DESCRIPTION
**Pull request by aseren**
Resolves https://github.com/brave/brave-browser/issues/40864

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

This is intermittent crash during Brave Rewards reset, which is hard to reproduce. No need to do manual testing.

### CODE REVIEW

**Comment by iefremov** [comment]
@aseren is there anything else? wondering why this one is not merged

**Comment by tmancey** [comment]
@iefremov we were going to add a better fix, however this is good for now due to other priorities. We will return with a nicer solution. @aseren lets merge :-)

**Comment by iefremov** [comment]
thanks everyone, pls uplift the PR

**Comment by btlechowski** [comment]
Verified with

Brave | 1.73.16 Chromium: 130.0.6723.58 (Official Build) nightly (64-bit)
-- | --
Revision | 6f264e47eba5071d88d1d312391a95e55be1793f
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/25453

<details>

Verified `Create Reward Confirmation` is sent to server

```
[9114:9114:1016/171252.305929:VERBOSE1:redeem_reward_confirmation.cc(78)] Redeem reward confirmation
[9114:9114:1016/171252.309060:VERBOSE1:redeem_reward_confirmation.cc(93)] Create reward confirmation
[9114:9114:1016/171252.309101:VERBOSE6:redeem_reward_confirmation.cc(97)] URL Request:
  URL: https://anonymous.ads.bravesoftware.com/v3/confirmation/cb80a5ea-0f76-4ec4-a480-37465c02dc50/eyJzaWduYXR1cmUiOiJUTlp3ckR6WE9kNDRXQ1VkdVR4NzlLZFBwZWRoSjZBa08zR2JpQkJOZTFUZGhHaFR4UVFrRGRqNUlDQTRScVlKLzJDUVU5U0VHQTlkUUpqVFdvRUVtZz09IiwidCI6ImhFckFrNmM3VTl3Y1VYVTBMNVJxUjY5NkFETDZPd1FTeGJhdzRKd01MTk9iTXVFNHFLM1IyWmNtVnN1VitoNlBmT3V3WVA5aFlicjd0elBua2VDSzh3PT0ifQ==
  Content: {"blindedPaymentTokens":["hiXA7talZe2uvZ9Yu+5Hf5aJCvafTnacXRJlyhaovws="],"buildChannel":"nightly","catalog":[{"id":"mzxg9HmwyH8vzoxFtRtbfDbvp313s91UB3ePxD4/SE4="}],"createdAtTimestamp":"2024-10-16T15:00:00.000Z","creativeInstanceId":"04064736-ea43-463a-bd6e-6c2be4408b4d","platform":"linux","publicKey":"hLaC3RQw5++hx8zaT+47CA8r8cOlAm+ygeky/ci6T1s=","rotatingHash":"y/KvGGzip0EH0RJo1X+kMoPujw3v4kfLqaw2eh9m7Rw=","segment":"untargeted","studies":[],"systemTimestamp":"2024-10-16T15:00:00.000Z","transactionId":"cb80a5ea-0f76-4ec4-a480-37465c02dc50","type":"view","versionNumber":"130.0.6723.58"}
  Content Type: application/json
  Method: kPost
[9114:9114:1016/171252.309137:VERBOSE7:redeem_reward_confirmation.cc(98)]   Headers:
    accept: application/json

```



Verified `Create Reward Confirmation` response from server

```
[9114:9114:1016/171252.964646:VERBOSE6:redeem_reward_confirmation.cc(111)] URL Response:
  URL: https://anonymous.ads.bravesoftware.com/v3/confirmation/cb80a5ea-0f76-4ec4-a480-37465c02dc50/eyJzaWduYXR1cmUiOiJUTlp3ckR6WE9kNDRXQ1VkdVR4NzlLZFBwZWRoSjZBa08zR2JpQkJOZTFUZGhHaFR4UVFrRGRqNUlDQTRScVlKLzJDUVU5U0VHQTlkUUpqVFdvRUVtZz09IiwidCI6ImhFckFrNmM3VTl3Y1VYVTBMNVJxUjY5NkFETDZPd1FTeGJhdzRKd01MTk9iTXVFNHFLM1IyWmNtVnN1VitoNlBmT3V3WVA5aFlicjd0elBua2VDSzh3PT0ifQ==
  Response Status Code: 201
  Response: {"id":"cb80a5ea-0f76-4ec4-a480-37465c02dc50","payload":{},"type":"view","createdAt":"2024-10-16T15:12:53.274Z","modifiedAt":"2024-10-16T15:12:53.274Z","creativeInstanceId":"04064736-ea43-463a-bd6e-6c2be4408b4d"}
[9114:9114:1016/171252.964746:VERBOSE7:redeem_reward_confirmation.cc(112)]   Headers:
    accept-ranges: bytes
    access-control-allow-credentials: true
    content-length: 211
    content-security-policy: sandbox
    content-type: application/json; charset=utf-8
    cross-origin-opener-policy: same-origin
    cross-origin-resource-policy: same-origin
    date: Wed, 16 Oct 2024 15:12:53 GMT
    referrer-policy: same-origin
    strict-transport-security: max-age=31536000; includeSubDomains; preload
    vary: Origin, Accept-Encoding
    via: 1.1 varnish
    x-cache: MISS
    x-cache-hits: 0
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-served-by: cache-hel1410022-HEL

```

Verified `Fetch payment token` is sent to server

```
[9114:9114:1016/171252.964844:VERBOSE1:redeem_reward_confirmation.cc(123)] Fetch payment token in 15 s
[9114:9114:1016/171307.980708:VERBOSE1:redeem_reward_confirmation.cc(135)] Fetch payment token
[9114:9114:1016/171307.980752:VERBOSE6:redeem_reward_confirmation.cc(139)] URL Request:
  URL: https://anonymous.ads.bravesoftware.com/v3/confirmation/cb80a5ea-0f76-4ec4-a480-37465c02dc50/paymentToken
  Method: kGet
[9114:9114:1016/171307.980801:VERBOSE7:redeem_reward_confirmation.cc(140)]   Headers:


```



Verified `Fetch payment token` response from server

```
[9114:9114:1016/171308.215644:VERBOSE6:redeem_reward_confirmation.cc(153)] URL Response:
  URL: https://anonymous.ads.bravesoftware.com/v3/confirmation/cb80a5ea-0f76-4ec4-a480-37465c02dc50/paymentToken
  Response Status Code: 200
  Response: {"id":"cb80a5ea-0f76-4ec4-a480-37465c02dc50","type":"view","createdAt":"2024-10-16T15:12:53.274Z","modifiedAt":"2024-10-16T15:12:55.397Z","creativeInstanceId":"04064736-ea43-463a-bd6e-6c2be4408b4d","paymentToken":{"publicKey":"gN4kY8+sw1vJ8NZ2tl8FsTM9Vwu8kfMjzbJLQaTXYkA=","batchProof":"iYvOuLZ3+aeyKjQEve+tNbZNo9ELuNYvRSejbGG6qwbp9TDQuGG6L4yLq//173efqX2M2OmrPAR9TDdk3XEUCg==","signedTokens":["kJMyaQT/ipYzfxK0SXA9hMMATkFGxAaJvQGnMDt+jBw="]}}
[9114:9114:1016/171308.215780:VERBOSE7:redeem_reward_confirmation.cc(154)]   Headers:
    accept-ranges: bytes
    access-control-allow-credentials: true
    content-length: 442
    content-security-policy: sandbox
    content-type: application/json; charset=utf-8
    cross-origin-opener-policy: same-origin
    cross-origin-resource-policy: same-origin
    date: Wed, 16 Oct 2024 15:13:08 GMT
    referrer-policy: same-origin
    strict-transport-security: max-age=31536000; includeSubDomains; preload
    vary: Origin, Accept-Encoding
    via: 1.1 varnish
    x-cache: MISS
    x-cache-hits: 0
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-served-by: cache-hel1410022-HEL
[9114:9114:1016/171308.217723:VERBOSE9:confirmation_state_manager.cc(80)] Saving confirmation state
[9114:9114:1016/171308.220366:VERBOSE1:redeem_reward_confirmation_util.cc(49)] You have 1 payment tokens which will be redeemed in 0 hours, 0 minutes, 33 seconds at 17:13:41.512

```


Verified no crash after resetting rewards
```
[9114:9114:1016/171613.364300:VERBOSE1:rewards_service_impl.cc(1216)] Shutting down rewards process
[9114:9114:1016/171613.389508:VERBOSE1:rewards_service_impl.cc(1283)] Successfully reset rewards service
[9114:9114:1016/171613.389536:VERBOSE1:rewards_service_impl.cc(1236)] Successfully shutdown rewards process
[9114:9114:1016/171613.410866:VERBOSE1:p2a.cc(93)] P2A histograms suspended
[9114:9114:1016/171613.410895:VERBOSE2:ads_service_impl.cc(1055)] Shutting down Bat Ads Service
[9114:9114:1016/171613.413547:VERBOSE2:ads_service_impl.cc(1084)] Shutdown Bat Ads Service
[9114:9114:1016/171613.413563:VERBOSE6:ads_service_impl.cc(520)] Clearing ads data
[9114:9114:1016/171613.413868:VERBOSE1:resource_component_registrar.cc(50)] Registering Brave Ads Resources (US) with id iblokdlgekdjophgeonmanpnjihcjkjj
[9114:9114:1016/171613.427344:VERBOSE6:ads_service_impl.cc(535)] Cleared ads data
[9114:9114:1016/171614.067720:VERBOSE8:resource_component.cc(119)] Manifest JSON: {
   "description": "Brave Ads Resources Component",
   "key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7xPk/eeslWG0VSSjMExUQtvn+8Ww8wCuluf97ACxiAoSspSrU1ftrjGw7U72YCKgPk1EdNKyOYpP1jQT0idxrhpTqihJQLlHm5EN3MiLDVf6MK8dqyG4PVAALMTGW6+4c77QhqnVWIRnfep96WBnJo0x5QieMWDZY79k4QMqJ2/NXMbGxyLWrNyXNy7zEnu5O/lLn68dM2it2KaQnXwCWj9DUoeaP6HTbBAgFYFE85b3nuSNX4RJfuEAod4lqdOgGsUuF/99AyCPVijuveYPrKxiBzvTcHb5GWoeKqjLi9rrqEwgxHgHZEANtIvORNQT40Q5OX+WntI1rkhn9UgMiwIDAQAB",
   "manifest_version": 2,
   "name": "Brave Ads Resources",
   "version": "1.0.199"
}

[9114:9114:1016/171614.068032:VERBOSE8:resource_component.cc(146)] Resource JSON: {"schemaVersion":1,"resources":[{"id":"bejenkminijgplakmkmcgkhjjnkelbld","filename":"kkjipiepeooghlclkedllogndmohhnhi","version":1,"status":"stable"},{"id":"nnqccijfhvzwyrxpxwjrpmynaiazctqb","filename":"dnryisldmaqljgwaxeqbuuhuvrbboqlf","version":1,"status":"stable"}]}
[9114:9114:1016/171614.068196:VERBOSE1:resource_component.cc(203)] Updating bejenkminijgplakmkmcgkhjjnkelbld resource to version 1
[9114:9114:1016/171614.068324:VERBOSE1:resource_component.cc(203)] Updating nnqccijfhvzwyrxpxwjrpmynaiazctqb resource to version 1
[9114:9114:1016/171614.068459:VERBOSE1:resource_component.cc(213)] Notifying resource component observers

```






</details>

**Pull request merged**
