### PR TITLE
Updated zoom constants and pages to resolve issue #6943

### PR DESCRIPTION
**Pull request by fow5040**
Fix https://github.com/brave/brave-browser/issues/6943

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist. - see https://github.com/brave/brave-browser/issues/6943
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [x] Linux
  - [x] macOS
  - [x] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [x] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
1. Verify you can set Zoom level in brave://settings to 133% and 140%
2. Open a PDF
3. Verify you can use Zoom level 133% and 140% (icon shows in omnibar)
4. Try to print the page
5. Print preview will come up
6. Verify you can zoom to 133% and 140%

## Reviewer Checklist:

- [x] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [x] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
Very nice! I think we can do this without patches (we have a mechanism that overrides the files at the GN level). Let me see if I can re-work your PR... 😄

**Comment by fow5040** [comment]
Ahh, thank you, got it! Just for my reference, is it the subclass/override method listed in the [patching chromium wiki](https://github.com/brave/brave-browser/wiki/Patching-Chromium#subclass-and-override), or something else entirely?

**Comment by bsclifton** [comment]
@fow5040 I thought it would be a slam dunk, but it's actually a little trickier...

That wiki entry is exactly what would work for the C/C++ ones; I made an edit which does that here: https://github.com/brave/brave-core/pull/4092/commits/e3b534cb5a45b015d2ce59922877043d3c0c6542

The JavaScript ones are a bit tougher; we do have a template system in which you can define a "behavior" which would then (at runtime) replace the array. I have this working... but only if I change the array to be `readonly=false`. Here's the settings override JavaScript we have (which gets ran on Polymer pages):
https://github.com/brave/brave-core/blob/master/browser/resources/settings/brave_settings_overrides.js

My edit (so far) looks like this:
```diff
--- a/browser/resources/settings/brave_settings_overrides.js
+++ b/browser/resources/settings/brave_settings_overrides.js
@@ -103,8 +103,40 @@ const BraveClearSettingsMenuHighlightBehavior = {
   }
 }

+const BraveAddZoomLevelsBehavior = {
+  ready: function() {
+    console.log('BSC]] START ', this.pageZoomLevels_)
+    this.set('pageZoomLevels_.readonly', false)
+    this.pageZoomLevels_ = [
+        1 / 4,
+        1 / 3,
+        1 / 2,
+        2 / 3,
+        3 / 4,
+        4 / 5,
+        9 / 10,
+        1,
+        11 / 10,
+        5 / 4,
+        4 / 3,
+        7 / 5,
+        3 / 2,
+        7 / 4,
+        2,
+        5 / 2,
+        3,
+        4,
+        5,
+      ]
+    console.log('BSC]] END')
+  }
+}
+
```

**Comment by bsclifton** [comment]
Here we go- second one fixed and working 😄 https://github.com/brave/brave-core/pull/4092/commits/589db3f5ac4f80bba228ef4d38d40809008e1e2f

The last one I was talking through how to make the fix with @bridiver. It'll be the hardest, as we don't have any examples (currently)

**Comment by fow5040** [comment]
Got it! Thanks for updating this thread with examples, will keep it in mind for any potential future contributions. :)

**Comment by bsclifton** [comment]
You're very welcome! Thanks for taking the time to fix this, it's greatly appreciated 😄 

We try to be more careful about patching (as you saw in the guide) to help keep rebases (when new Chromium versions come out) much easier. Will help with this last example (it's a little trickier) then we can accept this! 😎 

This fix would be a great one to upstream, honestly- I could help you push it to Chromium if you were interested. Let me know 😄

**Comment by fow5040** [comment]
Absolutely - will keep these changes in mind (including the fancy viewport .js overrides). If you think it'd be a valuable change to merge with Chromium I'd be happy to put it there as well! 

As far as I'm concerned I just did a little bit of digging and some minor tweaking, but always happy to push it if it'll be useful to the customer base at large.

Thanks again for all the guidance 🙌

**Comment by bsclifton** [comment]
@fow5040 with the help of @simonhong I was able to solve the last one 😄 No more patches! Please take a look; you should be able to pull this PR down now and verify it works for you

@bridiver this is now ready for review 😄👍

**Comment by bsclifton** [comment]
and whoops; a little too quick there. I loaded up print preview and noticed this error:
```
[20247:775:1128/003811.688271:ERROR:CONSOLE(6)] "Uncaught SyntaxError: Cannot use import statement outside a module", source: chrome://print/pdf/viewport.js (6)
[20247:775:1128/003811.799828:ERROR:CONSOLE(187)] "Uncaught (in promise) ReferenceError: Viewport is not defined", source: chrome://print/pdf/pdf_viewer.js (187)
```

**Comment by bsclifton** [comment]
Fix found! Thanks @simonhong 

OK - @bridiver, this is ready for review 😄

**Comment by bsclifton** [comment]
and merged! Thanks for the PR, @fow5040 😄

**Pull request merged**
