### PR TITLE
Mitigate scriptlet injection races

### PR DESCRIPTION
**Pull request by antonok-edm**
Resolves https://github.com/brave/brave-browser/issues/18228

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

The issue probably only ever occurred with a fast internet connection, so a wired connection is ideal for trying to reproduce it.

1. Copy the URL `https://icloud.com` into your clipboard.
1. Hold down <kbd>Ctrl</kbd> + <kbd>Shift</kbd>, and while holding those modifiers hit the <kbd>N</kbd> <kbd>V</kbd> <kbd>Enter</kbd> keys in rapid succession (releasing after each press). The idea is to open a new private tab, paste the URL into the URL bar, and navigate to the page in a new window, all within as short a time as possible. This maximizes the chance of triggering the race condition from my testing.
1. The page should never redirect to a "Your browser is not supported" message (located at https://icloud.com/unsupported_browser for reference).

The failure is not consistent, so repeat 5 times at maximum speed once you've had sufficient finger practice (I guess some kind of hotkey scripting would work here too, if you're feeling fancy :smile:).

### CODE REVIEW

**Review by bridiver — APPROVED** [review]

**Review by iefremov — APPROVED** [review]
as a quick patch it looks good

**Comment by atuchin-m** [comment]
And the are other things:
1. Why we reset `ready_` on any `ReadyToCommitNavigation`? Looks like same-document navigations should be excluded.
2. Why we don't get url from `document_loader->GetUrl()` but saving some it on `DidStartNavigation` (it can be the next navigation, not about the current frame)?

**Comment by antonok-edm** [comment]
@atuchin-m I believe @SergeyZhukovsky had put those in initially - @SergeyZhukovsky do you know?

**Comment by SergeyZhukovsky** [comment]
@atuchin-m I think @bridiver can explain better about the `OneShotEvent` as it has been applied by him there when we tried to make the logic of js insertion as close as extension had.
2. Not sure really, it could be done perhaps as you suggest, I haven't tried it that way, you can check that url is used what we have in `DidStartNavigation`, if you check `DistillerJsRenderFrameObserver` as well for example.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.32.16 Chromium: 94.0.4606.54 (Official Build) nightly (64-bit)
-- | --
Revision | c8191a1d5cccbf64e8fe7269043f8ace8d74dd05-refs/branch-heads/4606@{#1130}
OS | Windows 10 Version 20H2 (Build 19042.1237)
```

Unfortunately I couldn't reproduce the issue after opening ~500 window using the STR/Cases mentioned via https://github.com/brave/brave-core/pull/10192#issue-1003749203 with both `1.32.8 Chromium: 94.0.4606.54` & `1.32.11 Chromium: 94.0.4606.54`.

Using `1.32.16 Chromium: 94.0.4606.54`, I opened another ~500 windows using the STR/Cases and ensured that Brave was never redirected to https://icloud.com/unsupported_browser when loading `https://icloud.com`.

**Pull request merged**
