### PR TITLE
Fixes wallet reporting to the user

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves https://github.com/brave/brave-browser/issues/2535

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:

- enable rewards
- close browser
- modify ledger_state and delete paymentId
- start browser
- make sure that you get error about corrupted wallet

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by NejcZdovc** [comment]
master (0.61) 9d816e7

**Comment by bbondy** [comment]
@NejcZdovc Please run tests before requesting review, this is causing unit tests to fail on master.
@tmancey there's a spot in the template for if the submitter ran tests.  It's not checked correctly, but that should be cause for not letting something merge. Thanks.

**Comment by kjozwiak** [comment]
Waiting till https://github.com/brave/brave-browser/issues/2545 is resolved and unit tests are passing before approving request to uplift `0.58.x` as per @bbondy earlier message above.

**Comment by NejcZdovc** [comment]
@kjozwiak https://github.com/brave/brave-core/pull/1089 merged

**Comment by kjozwiak** [comment]
@NejcZdovc uplift request to `0.58.x` approved as tests have been fixed with #1089  👍 Please add/remove the required labels and ensure that the associated issue is moved into the correct milestone.

**Pull request merged**
