### PR TITLE
[Brave News] Don't use the |is_enabled| flag when determining if the publisher is subscribed.

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Resolves https://github.com/brave/brave-browser/issues/26324

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by petemill — APPROVED** [review]

**Comment by petemill** [comment]
Looks like you just need to run `npm run format` to fix the lint issue in CI

**Comment by stephendonner** [comment]
@petemill @fallaciousreasoning what's the test plan for this?  My original steps don't readily apply, since we're now enabled with `Brave News V2`.

**Comment by fallaciousreasoning** [comment]
Right, yeah:
1. On a new profile (with the subscribe button enabled, and Brave News opted in)
2. Following **only** the top sources channel
3. Navigate the theatlantic.com
4. The atlantic should **NOT** show as followed in the Brave News button

(previously it was showing up as followed).

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.91 Chromium: 108.0.5359.48 (Official Build) nightly (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)


### Steps:
1. install `1.47.91`
2. launch Brave
3. open `brave://flags`
4. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
5. clicked `Relaunch`
6. opened a new-tab page
7. clicked on `Customize`
8. clicked on `Brave News`
9. clicked on `Turn on Brave News`
10. confirmed I was default following `Top Sources`, in the `Following` column
11. loaded `theatlantic.com`
12. clicked on the `Manage Subscriptions` button
13. examined the `The Atlantic` and `Best of the Atlantic` feeds' statuses

#### Confirmed neither `The Atlantic` nor `Best of the Atlantic` were `Followed`/shown as `Followed`

example | example (issue https://github.com/brave/brave-browser/issues/26262) | example | example
---------|---------|----------|---------
Screen Shot 2022-11-21 at 12 21 36 PM | Screen Shot 2022-11-21 at 12 22 36 PM | Screen Shot 2022-11-21 at 12 25 10 PM | Screen Shot 2022-11-21 at 12 25 23 PM

**Pull request merged**
