### PR TITLE
Add brave:// pages and redirect about: and chrome: URLs to brave://

### PR DESCRIPTION
**Pull request by bbondy**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions

### CODE REVIEW

**Comment by bridiver** [comment]
I'm concerned that all these patches to add `kBraveUIScheme` are going to be very fragile with chrome changes. We would have to search the entire codebase on every update to make sure there are no new checks added anywhere

**Comment by bbondy** [comment]
@bridiver do you have another suggestion? I considered patching for url->SchemeIs to return true when kChromeUIScheme is passed for kBraveUIScheme.

**Comment by bridiver** [comment]
not sure, but I can look at it tomorrow

**Comment by bbondy** [comment]
Changing approach to forward brave:// to chrome:// and we can look at patching urlbar display only later.  So closing this.

**Pull request closed without merging**
