### PR TITLE
Allow forwarding parameter to GTest via npm run test

### PR DESCRIPTION
**Pull request by mariospr**
Allow passing parameters unknown to our npm run test command into the
GTest-based binary, so that we can do things such as specifying a
maximum timeout per test using GTest's --test-launcher-timeout with
a command line like the following one:

npm run test brave_browser_tests -- Debug --test-launcher-timeout=10

Resolves https://github.com/brave/brave-browser/issues/13725

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

N/A

### CODE REVIEW

**Comment by bbondy** [comment]
I think we automatically forward command line arguments now don't we?

**Comment by mariospr** [comment]
> I think we automatically forward command line arguments now don't we?

Hmmm... I don't think we do, or at least I can't see any hint of that in `commands.js` nor in `test.js`. And if I try to pass this GTest parameter to `npm run tests` I do get an error:
```
$ testing/xvfb.py npm run test -- brave_browser_tests Debug --test-launcher-timeout=10
Additional test environment:
    CHROME_DEVEL_SANDBOX=/home/mario/work/chromium/chrome_sandbox
    CHROME_HEADLESS=1
    LANG=en_US.UTF-8
Command: npm run test -- brave_browser_tests Debug --test-launcher-timeout=10

Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml"

> brave@1.21.25 test /home/mario/work/brave-browser
> npm --prefix src/brave run test -- "brave_browser_tests" "Debug" "--test-launcher-timeout=1000"


> brave-core@1.21.25 test /home/mario/work/brave-browser/src/brave
> node ./build/commands/scripts/commands.js test "brave_browser_tests" "Debug" "--test-launcher-timeout=1000"

Recursing through GRD to find GRDP files...
Done recursing through GRD to find GRDP files.
error: unknown option `--test-launcher-timeout'
```

Am I perhaps missing something?

**Comment by bbondy** [comment]
Sorry I remembered us doing this but I can't find it either. I think it would be best to make it work in a general way so we don't need to 1-off these things though. Could you just forward on the extra command line params?

**Comment by mariospr** [comment]
> Sorry I remembered us doing this but I can't find it either. I think it would be best to make it work in a general way so we don't need to 1-off these things though. Could you just forward on the extra command line params?

Sure, I can prepare a different PR that does that instead. I didn't do it because reading `commands.js` I got the impression that the preference was to have some control over which flags get passed and which doesn't, but I'm personally more than happy to be able to simply forward them instead.

**Comment by mariospr** [comment]
@bbondy Just force-pushed the PR now, following the lead of the `npm run test` command. PTAL and let me know if this is more what you'd have in mind, thanks!

**Review by bbondy — APPROVED** [review]
Thanks!

**Comment by mariospr** [comment]
I confirmed that the Windows failure is totally unrelated, merging.

**Pull request merged**
