### PR TITLE
Tie Clipboard Write permission to Read

### PR DESCRIPTION
**Pull request by ShivanKaul**
Resolves https://github.com/brave/brave-browser/issues/25145

TODO:
- [ ] Browser tests
- [x] UI update for content settings in brave://settings/content/clipboard (get text approved)

## Screenshots of Settings Pages

image
**(Update text to say 'access')**

image
**(Update text to say 'access')**

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

1. Go to https://async-clipboard-text.glitch.me/
2. Confirm that clicking on clicking on Copy results in a permission prompt.
3. Confirm that permission prompt mentions writing AND reading, not just "see text and images copied to clipboard".
4. Denying it prevents both Copy and Paste from working.
5. Approving makes both work.
6. The text in brave://settings/content/clipboard is updated to mention reading and writing, not just reading.
7. Adding a website to Allow or Deny lists on brave://settings/content/clipboard is respected.

### CODE REVIEW

**Comment by ShivanKaul** [comment]
@pes10k just confirming that after this change, websites will need both user gesture AND permission prompt to read AND write to clipboard. The user gesture requirement was re-added in #14901. So in Nightly, https://shivankaul.com/brave/clipboard-read.html and https://shivankaul.com/brave/clipboard-paste.html will always error out because there's no gesture captured, even though (after this change) both will prompt for Clipboard permission.

**Comment by pes10k** [comment]
@ShivanKaul that doesn't seem right.  Unless spec'ed otherwise, my understanding is that permission requests (by default) require user gestures, and that (unless spec'ed otherwise) sites can't even trigger a permission request unless they're consuming (or maybe just responding to) a user activiation.

If that doesn't match what you see though, that is surprising and useful information; possibly the above got caught up in a editors draft and never made it to REC

**Comment by ShivanKaul** [comment]
> @ShivanKaul that doesn't seem right. Unless spec'ed otherwise, my understanding is that permission requests (by default) require user gestures, and that (unless spec'ed otherwise) sites can't even trigger a permission request unless they're consuming (or maybe just responding to) a user activiation.

It seems to be spec'd that way: user gestures are not mandatory because that would [break remote desktop use-cases](https://www.w3.org/TR/clipboard-apis/#remote-clipboard-sync). The question is what we should do if we allow Clipboard permission in brave://settings/content/clipboard for a website - as it stands, with this PR, we still require user gesture. But [Chromium's change](https://chromium.googlesource.com/chromium/src/+/10300ac7da93a7e322274f1ed89395a7c639986e%5E%21/#F3) doesn't require it, either site permission or user gesture is sufficient.

**Comment by ShivanKaul** [comment]
Given https://chromium.googlesource.com/chromium/src/+/10300ac7da93a7e322274f1ed89395a7c639986e%5E%21/, clipboard writes require permission prompt or permission grant. This seems sufficient. Read still requires permission prompt.

**Pull request closed without merging**
