### PR TITLE
[Android] Fixed creating new tab from Tab Groups UI

### PR DESCRIPTION
**Pull request by samartnik**
Resolves https://github.com/brave/brave-browser/issues/16263

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Review by deeppandya — APPROVED** [review]
LGTM

**Comment by samartnik** [comment]
1 test failed, bot related to this PR
```
Failed
BatAdsAdRewardsIntegrationTest.GetCachedAdRewardsIfGetPaymentsEndPointReturnsNonHttpOk

Failing for the past 1 build (Since #1 )
Took 0 ms.
Error Message
failed
Stacktrace
[ RUN      ] BatAdsAdRewardsIntegrationTest.GetCachedAdRewardsIfGetPaymentsEndPointReturnsNonHttpOk
[FATAL:unittest_util.cc(214)] Check failed: false. Missing MockUrlRequest endpoint response for https://ads-serve.brave.software/v1/confirmation/payment/c387c2d8-a26d-4451-83e4-5c0c6fd942be
[ERROR:test_suite.cc(546)] Currently running: BatAdsAdRewardsIntegrationTest.GetCachedAdRewardsIfGetPaymentsEndPointReturnsNonHttpOk
```

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 11` using `1.27.48 Chromium: 91.0.4472.88`.

* ensured that following the STR/Cases via https://github.com/brave/brave-browser/issues/16263#issue-913566472 didn't keep opening SI via the NTP
* ensured that SI tabs are opened once every four times when opening within `Tab Groups`
* ensured that tapping on the SI correctly opens a new tab that points to the sponsor/campaign
* ensured that the rewards onboarding modal that appears under SI NTP can still be used once grouped via Group Tabs

**Pull request merged**
