### PR TITLE
Update sync references to versions without npm vulnerability (uplift to 0.70.x)

### PR DESCRIPTION
**Pull request by bsclifton**
Fixes brave/brave-browser#6163
Uplift of https://github.com/brave/brave-core/pull/3532

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
@bsclifton looks like the `npm run audit_deps` check is failing via:

```
02:36:56                         === npm audit security report ===                        
02:36:56                                                                                  
02:36:56  # Run  npm update handlebars --depth 6  to resolve 1 vulnerability
02:36:56  ┌───────────────┬──────────────────────────────────────────────────────────────┐
02:36:56  │ High          │ Prototype Pollution                                          │
02:36:56  ├───────────────┼──────────────────────────────────────────────────────────────┤
02:36:56  │ Package       │ handlebars                                                   │
02:36:56  ├───────────────┼──────────────────────────────────────────────────────────────┤
02:36:56  │ Dependency of │ jest [dev]                                                   │
02:36:56  ├───────────────┼──────────────────────────────────────────────────────────────┤
02:36:56  │ Path          │ jest > jest-cli > @jest/core > @jest/reporters >             │
02:36:56  │               │ istanbul-reports > handlebars                                │
02:36:56  ├───────────────┼──────────────────────────────────────────────────────────────┤
02:36:56  │ More info     │ https://npmjs.com/advisories/1164                            │
02:36:56  └───────────────┴──────────────────────────────────────────────────────────────┘
02:36:56  
02:36:56  
02:36:56  found 1 high severity vulnerability in 873743 scanned packages
02:36:56    run `npm audit fix` to fix 1 of them.
```

Assuming this is expected as the above is a known problem. Safe to uplift this even with the above dependency issue?

**Comment by bsclifton** [comment]
@kjozwiak no- that needs to be clear for this PR.  I think we fixed the problem, but I'm going to re-run with a clean work-space

**Comment by bsclifton** [comment]
Only failure on Android during init:
https://staging.ci.brave.com/job/brave-browser-build-pr/job/fix-sync-vulnerability-0.70.x/5/execution/node/118/log

**Comment by bsclifton** [comment]
Merging as this fixes `npm audit` problems and has been approved prior to rebasing/re-running tests. 😄

All tests have passed- labels were added to only re-run Android after a problem on the initial run

**Pull request merged**
