### PR TITLE
Default shield advanced view to TRUE for existing users. (uplift to 0.69.x) 

### PR DESCRIPTION
**Pull request by bsclifton**
Fixes https://github.com/brave/brave-browser/issues/5582

Uplift of #3154

Approved, please ensure that before merging: 
- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by bsclifton** [comment]
NOTE: not ready to be merged; there is a failing browser test on WINDOWS only... investigating...

**Comment by bsclifton** [comment]
Ready for consideration 😄 Above issue fixed

**Comment by bsclifton** [comment]
@kjozwiak I believe we need to accept https://github.com/brave/brave-core/pull/3187 first (and then I can rebase this). Will mark as blocked

**Comment by bsclifton** [comment]
Rebased - ready for approval / merge (after CI runs)

**Comment by kjozwiak** [comment]
@bsclifton looks like the following checks have failed under `CI/Jenkins`:

`npm run test -- brave_browser_tests Release --output brave_browser_tests.xml` under `linux` via the following:

* https://staging.ci.brave.com/job/brave-browser-build-pr/job/pr3154-0.69.x/1/execution/node/595/log/

`npm run test -- brave_browser_tests Release --output brave_browser_tests.xml` via under `MacOS` via the following:

* https://staging.ci.brave.com/job/brave-browser-build-pr/job/pr3154-0.69.x/1/execution/node/493/log/

**Comment by bsclifton** [comment]
Problem found + fixed - when uplifting, I missed the removal of the check in `browser/brave_profile_prefs_browsertest.cc`. Added this back in (so it matches other branches) and CI is re-running now

**Pull request merged**
