### PR TITLE
Add setting options to toggle NTP widgets

### PR DESCRIPTION
**Pull request by imptrx**
Spec: https://github.com/brave/brave-browser/issues/4510 (Current scope of this PR does not include right clicking on the widgets to open up a mini-menu)
Brave-ui Sister PR: https://github.com/brave/brave-ui/pull/503
Quick View:
toggle-widgets
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
1. Open new tabs page with a fresh profile - all NTP elements should appear
2. Open settings menu from the settings icon - 3 new settings should exist below show background
3. Toggle the three options; show clock; show stats; show top sites - they should disappear/reappear on the page
4. Settings should persist after browser is closed and reopened

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
@imptrx is there an issue captured that this PR fixes?

**Comment by petemill** [comment]
@cezaraugusto I'm going to PR the change to either this, or to master if this is merged first. I'm happy with either scenario but if this is merged first, any users who change the setting will have their setting reset back to default once the prefstore change lands

**Comment by petemill** [comment]
Pushed a rebase on master. We'll still want to update brave-ui sha with the result of merging https://github.com/brave/brave-ui/pull/503 when that happens

**Comment by petemill** [comment]
Here's a branch which adds these remaining toggles to the pref store, for integrating perhaps by @imptrx when https://github.com/brave/brave-core/pull/2831 is merged to master and this is rebased. The branch is a rebase of this PR on that, and then adds the prefs.
https://github.com/brave/brave-core/compare/toggle-on-profile-prefs

**Comment by cezaraugusto** [comment]
set PR as blocked until https://github.com/brave/brave-core/pull/2831 is resolved

**Comment by bsclifton** [comment]
Don't forget to add a test plan and link to it from https://github.com/brave/brave-browser/issues/4510

**Pull request merged**
