### PR TITLE
Fixed ui string casing for menu items

### PR DESCRIPTION
**Pull request by nullhook**
Resolves https://github.com/brave/brave-browser/issues/17308 and 
Resolves https://github.com/brave/brave-browser/issues/17309

This should fix casing on all os. 

Here is the screenshot on mac OS:
image

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by nullhook** [comment]
@bsclifton can you test this on windows please?
@keur can you help test this on linux?

**Comment by keur** [comment]
Screenshot_20210803_114115
I applied your patch and got this.

**Comment by bsclifton** [comment]
image

**Review by bsclifton — APPROVED** [review]
LGTM! 😄 👍

**Review by karenkliu — APPROVED** [review]
Looks great! 🚀

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.30.4 Chromium: 92.0.4515.131 (Official Build) nightly (x86_64)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | macOS Version 11.5.1 (Build 20G80)



### Issue 17308 - `Restore title case for macOS menu items`

## Steps:
1. new profile
2. launch Brave
3. click on the `"hamburger`" menu
4. look carefully at the casing of the menu items

For macOS, they should be all Title Case.

`1.30.4` `nightly` | 1.27.111
----------------|----------
Screen Shot 2021-08-05 at 3 58 16 PM | Screen Shot 2021-08-05 at 4 05 15 PM

### Issue 17309 - ` Inconsistent capitalizations in main menu`

## Steps:
1. new profile
2. launch Brave
3. click on the `"hamburger`" menu
4. look carefully at the casing of the menu items

Linux and Windows have sentence case, along with capitalized proper nouns.

Mostly fixed; filed https://github.com/brave/brave-browser/issues/17377 to take care of the remaining `New Private window` case.

Screen Shot 2021-08-05 at 1 46 48 PM

**Comment by stephendonner** [comment]
@nullhook can we get this uplifted to `1.29.x`?

**Pull request merged**
