### PR TITLE
Allow delete device which doesn't support self-delete (desktop).

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
This PR adds ability to remove  from the sync chain the devices which does not support self-delete, i.e. devices which have no PR https://github.com/brave/brave-core/pull/6732 and doesn't do proper actions when receive DELETE device record.

For such devices warning is displayed:
```
The device you are trying to delete has an old browser version and doesn't have full support of self-delete. However, if you are sure that the browser on that device will not be launched again, you may continue. If by some reasons the browser on that device will be launched, it will be in the chain invisible for other devices, but it will have access to the synchronized data. Are you sure you want to delete selected device from sync chain?
```
Also see the screenshots below

Q: _What will happen, if the deleted device will go back online?_

A: If device does not support self-delete and will be deleted despite of the warning and then the browser on that device will be launched - it will actually be in the sync chain. it will be able to get updates/commit changes to another device, but another device will not see it in their devices lists.

Resolves https://github.com/brave/brave-browser/issues/13499

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one // This PR needs privacy review
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

1. Take browser of version 1.18.18 or below, `browser A` ;
2. Take browser of version with the PR, desktop,`browser B`;
3. Take browser of version with the PR, Android, `browser C`;
4. Put them into one sync chain;
5. Close the `browser A`;
6. From Android device, `browser C`, try to delete `device A` - you should see the warning, press Cancel; 
7. From desktop device `browser B`, try to delete `device A` - you should see the warning, press OK - device should be removed from the list for `browser B` and `browser C`;

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
Screenshots:
Desktop:
image

Android:
Screenshot_20210322-180651

**Review by darkdh — APPROVED** [review]

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Comment by pedro7** [comment]
No no no no. I see your point -- me, some rando on Twitter, complains about the ever growing list of devices and you implement a fancy *permanent* hide. Thank you for that -- seriously.

However allowing for (even if improbable) hidden devices syncing is a big nono IMO. I will not use the delete on such conditions.

**Comment by AlexeyBarabash** [comment]
Rebased to the latest master and updated strings to the reviewed by @jsecretan

**Review by mkarolin — APPROVED** [review]
++ on `chromium_src` change.

**Comment by bbondy** [comment]
Closing as stale

**Pull request closed without merging**
