### PR TITLE
Fixes Reset Profile dialog.

### PR DESCRIPTION
**Pull request by mkarolin**
Fixes brave/brave-browser#2708

Instead of patching the html/js of the reset_profile_dialog, introduced
Brave behavior that hides/unchecks/disables the checkbox we don't want
seen along with the entire footer of the dialog since it contains
nothing else.

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests && npm run test-security`) on
  - [x] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:

1. Start Brave browser and navigate to brave://settings
2. Scroll down and click 'Advanced', scroll down again and click 'Restore settings to their original defaults'.
3. In the 'Reset settings' dialog, click 'Reset settings' button.
4. Verify that the dialog closes.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by mkarolin** [comment]
Just a ping @petemill & @bsclifton. That is all.

**Comment by bsclifton** [comment]
Checking this out now...

**Comment by mkarolin** [comment]
Passed the CI. @bsclifton, could you re-approve, please.

**Comment by bsclifton** [comment]
@mkarolin merged! 😄 Any uplifts needed for this one? 
cc: @rebron

**Comment by rebron** [comment]
@mkarolin @clifton I think we should take this up to 64.x.

**Pull request merged**
