### PR TITLE
Hide google microphone from https://github.com/brave/brave-browser/issues/2690

### PR DESCRIPTION
**Pull request by ryanbr**
Fixes https://github.com/brave/brave-browser/issues/2690

Since the google microphone doesn't work, the microphone is hidden on Firefox (possibly a user agent checks by google)

This patch will hide the microphone icon on all google regional sites, tested on `www.google.com`, `www.google.co.nz`, `www.google.com.au`, `www.google.co.uk`, `www.google.de`  This patch works both in desktop and mobile versions of google.

- [x] Main home page, microphone hidden
- [x] When google searching, microphone hidden

### CODE REVIEW

**Comment by bsclifton** [comment]
@ryanbr can you rebase and squash the commits? 😄 And then update the commit message to include `Fixes https://github.com/brave/brave-browser/issues/2690`. Will give it a review after that 😄

Sorry that this seems to have gotten lost among the sea of other PRs

**Comment by bbondy** [comment]
FYI this was reverted here:
https://github.com/brave/brave-core/pull/4371

Because of test failures that this introduced:
```
[357/357] BraveWalletAPIBrowserTest.DappDetectionWithMetaMaskTestCancel (TIMED OUT)
3 tests timed out:
    BraveWalletAPIBrowserTest.DappDetectionTestAccept (../../brave/browser/extensions/api/brave_wallet_api_browsertest.cc:158)
    BraveWalletAPIBrowserTest.DappDetectionWithMetaMaskTestAccept (../../brave/browser/extensions/api/brave_wallet_api_browsertest.cc:175)
    BraveWalletAPIBrowserTest.DappDetectionWithMetaMaskTestCancel (../../brave/browser/extensions/api/brave_wallet_api_browsertest.cc:191)
```

I'll re-open the issue.

**Comment by bsclifton** [comment]
@ryanbr as noted above, this caused some test failures. I believe the content script changes were causing the Brave extension to crash, which also hid the Shields (Lion) icon

Tests were missed because this was a fork. Would you be able to re-submit this PR as a branch? Let me know if you don't have privs for branching and I can create for you 😄 Then we'll just need to track down why it's causing a problem

**Comment by ryanbr** [comment]
Yeah can create branch PR, is the orginal code sound? We could simplify it more to something like this:

`var selection = document.querySelector('[aria-label="Search by voice"]'); selection.style.display = 'none'; `

**Comment by DrMWEcker** [comment]
Just sticking in my two cents.
Tried Brave on one of my many PCs last summer. I didn't make it the default or use it since.
Today (20 January 2020) I gave it a try again, but allowing Google as default search because of certain advantages. Unfortunately, voice search and dictation are a big part of the Chrome + Google advantage for me, and I was disappointed that voice search is still a problem in 2020.

Perhaps it will eventually get fixed and I will hear of this, as I would likely come back to Brave. Alas, until this is fixed, I will have to be brave without using Brave. Ciao!

**Comment by ryanbr** [comment]
ping @bsclifton  not sure you missed my comment ^, not sure how the Shields icon was affected, but would simplified check be better?

**Comment by bsclifton** [comment]
@ryanbr really sorry for missing this (finally getting to older GitHub notifications, doh)

Simplified check would be better- I'm not sure what the root cause was before. In Nightly, the Brave extension was crashing so maybe it's just a matter of pulling down the code and trying it, in case you wanted to submit another PR. Feel free to ping me on Slack too! 😄

**Pull request merged**
