### PR TITLE
Greaselion: allow scripts to customize run_at

### PR DESCRIPTION
**Pull request by petemill**
Resolves https://github.com/brave/brave-browser/issues/8667

Still defaults to document_end.

## Test plan
- [Edit local greaselion config directory in user data directory](https://github.com/brave/brave-site-specific-scripts#developing-new-greaselion-scripts)
- Add a new file test.js
```
console.log("greaselion", document.readyState)
```
- Add to greaselion.json
```
[
  {
    "urls": [
      "*://*/*"
    ],
    "scripts": [
      "test.js"
    ],
    "run_at": "document_start"
  }
]
```
- Restart Brave
- Open devtools on any website
- **Observe: `greaselion loading`**
- Change `run_at` to `document_end`
- Restart Brave
- Open devtools on any website
- **Observe: `greaselion interactive`**
- Remove `"run_at"` property
- Restart Brave
- Open devtools on any website
- **Observe: `greaselion interactive`**

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by petemill** [comment]
Jenkins seems to be failing for a number of reasons:
- Unrelated test crash
```
1 test crashed:
17:10:19      PerfPredictorTabHelperTest.ScriptBlockHasSavings 
```
- All the lint scripts are failing (lint is fine for this PR)
- Mac fails building browser tests due to
```
18:32:45  dyld: Library not loaded: @loader_path/../../Libraries/libspeedreader.dylib
18:32:45    Referenced from: /Users/jenkins/jenkins/workspace/owser-build-pr_greaselion-run-at/src/out/Release/brave_browser_tests
18:32:45    Reason: image not found
18:32:45  null
```

**Comment by petemill** [comment]
Now added some browser tests for this option

**Comment by petemill** [comment]
Seems like CI failed because of unrelated flakey test and test-install failing.
```
 1 test timed out:
18:33:04      BraveRewardsBrowserTest.TipConnectedPublisherAnonAndConnected 
```

**Comment by bsclifton** [comment]
CI passed without any warnings or errors, except on macOS. Build failed there unzipping rust deps. Going to restart to verify that is working as expected

**Pull request merged**
