### PR TITLE
Update speedreader Ruest dependencies dep

### PR DESCRIPTION
**Pull request by rillian**
Resolves brave/brave-browser#19330

Update dependent crates to address cargo audit reports:

- [crossbeam-deque 0.8.0 Data race](https://rustsec.org/advisories/RUSTSEC-2021-0093)
- crossbeam-epoch 0.9.3 yanked
- [hyper 0.14.4 request smuggling](https://rustsec.org/advisories/RUSTSEC-2021-0078)
- [hyper 0.14.4 `Transfer-Encoding` data loss](https://rustsec.org/advisories/RUSTSEC-2021-0079)
- [tokio 1.4.0 Task dropped in wrong thread when aborting `LocalSet` task](https://rustsec.org/advisories/RUSTSEC-2021-0072)
- [Potential segfault in localtime_r invocations in chrono crate](https://rustsec.org/advisories/RUSTSEC-2020-0159)
- [Potential segfault in the time crate](https://rustsec.org/advisories/RUSTSEC-2020-0071)

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

Verify Speedreader reformats articles as before. In particular, please check that the generated "Updated" date at the top of the speedreader version of articles is formatted the same.

### CODE REVIEW

**Review by antonok-edm — APPROVED** [review]
:+1:

**Review by diracdeltas — DISMISSED** [review]
see comments in https://github.com/brave/security/issues/655; also i just added the run-audit-deps label so this should run that job in CI now

**Comment by rillian** [comment]
Removed the `chrono` and `time` exemptions from audit-deps, per discussion on slack.

**Comment by rillian** [comment]
Runs seem ok except for `tslint` failures:

```
ERROR: /home/ubuntu/workspace/pr-brave-browser-speedreader-dep-linux/src/brave/components/brave_extension/extension/brave_extension/background/webDiscoveryProject.ts:30:5 - Expression is always true.
ERROR: /users/jenkins/jenkins/workspace/pr-brave-browser-speedreader-dep-macos/src/brave/components/brave_extension/extension/brave_extension/background/webdiscoveryproject.ts:30:5 - Expression is always true.
ERROR: c:/-dep/src/brave/components/brave_extension/extension/brave_extension/background/webdiscoveryproject.ts:30:5 - Expression is always true.
```
And pylint warnings:
```
line-too-long in audit_deps.py
```

These are unrelated, so this PR should be good to land.

**Pull request merged**
