### PR TITLE
Updated Sync QR text error for valid too long case (uplift to 1.34.x)

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Uplift of #11652
Resolves https://github.com/brave/brave-browser/issues/20170

Pre-approval checklist: 
- [ ] You have tested your change on Nightly. 
- [ ] This contains text which needs to be translated. 
    - [ ] There are more than 7 days before the release. 
    - [ ] I've notified folks in #l10n on Slack that translations are needed. 
- [ ] The PR milestones match the branch they are landing to. 

Pre-merge checklist: 
- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 

Post-merge checklist: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
macOS CI is marked as unstable by the reason of 
https://ci.brave.com/job/pr-brave-browser-pr11652_sync_qr_valid_for_text_1.34.x-macos/1/execution/node/248/log/
```

15:47:58  [  FAILED  ] EphemeralStorageBrowserTest.BroadcastChannelIsPartitioned, where TypeParam =  and GetParam() =  (7260 ms)
15:47:58  [978/978] EphemeralStorageBrowserTest.BroadcastChannelIsPartitioned (7357 ms)
15:47:58  1 test failed:
15:47:58      EphemeralStorageBrowserTest.BroadcastChannelIsPartitioned (../../brave/browser/ephemeral_storage/ephemeral_storage_browsertest.cc:833)
```
not related to the PR

**Comment by kjozwiak** [comment]
> macOS CI is marked as unstable by the reason of https://ci.brave.com/job/pr-brave-browser-pr11652_sync_qr_valid_for_text_1.34.x-macos/1/execution/node/248/log/
> 
> ```
> 
> 15:47:58  [  FAILED  ] EphemeralStorageBrowserTest.BroadcastChannelIsPartitioned, where TypeParam =  and GetParam() =  (7260 ms)
> 15:47:58  [978/978] EphemeralStorageBrowserTest.BroadcastChannelIsPartitioned (7357 ms)
> 15:47:58  1 test failed:
> 15:47:58      EphemeralStorageBrowserTest.BroadcastChannelIsPartitioned (../../brave/browser/ephemeral_storage/ephemeral_storage_browsertest.cc:833)
> ```
> 
> not related to the PR

We have an issue created for the above via https://github.com/brave/brave-browser/issues/20130.

**Comment by stephendonner** [comment]
We should double-check this PR before merging in; I'm having trouble getting the `This code is invalid` message and have been getting the `This code has expired` one, instead: https://github.com/brave/brave-core/pull/11652#issuecomment-1002225748.

**Comment by kjozwiak** [comment]
Going to close this off as per the conversation between @jsecretan @samartnik @Brave-Matt re: letting this ride the channels via `1.35.x`. If we get more user reports that the above is a problem, we can revisit uplifting into `1.34.x` and getting the fix out via a HF.

**Pull request closed without merging**
