### PR TITLE
Update brave-sync and brave-crypto DEPS

### PR DESCRIPTION
**Pull request by diracdeltas**
fix https://github.com/brave/brave-browser/issues/2393

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by diracdeltas** [comment]
master: 755d4c36b9c6c156deff48d3b57be8d6d78238d9
0.59.x: a1af9a8e212d1a735495a50495b57a82aab38de1

**Comment by diracdeltas** [comment]
Adding uplift request, per https://github.com/brave/brave-browser/issues/2380#issuecomment-445077338

**Comment by kjozwiak** [comment]
@diracdeltas approving uplift request to `0.58.x` after deliberating with @rebron & @srirambv 👍Please make sure that all the appropriate labels are removed/added and the corresponding issue is moved to the correct milestone.

**Comment by diracdeltas** [comment]
sgtm. who will do the 0.58.x uplift? i am happy to but not clear if i should based on https://github.com/brave/brave-browser/wiki/Triage-Guidelines#uplift-approvers

**Comment by kjozwiak** [comment]
@diracdeltas the developer that's usually requesting the uplift is responsible for merging the PR to the appropriate channels and updating the labels/moving the issue to the correct milestone 👍

> i am happy to but not clear if i should based on https://github.com/brave/brave-browser/wiki/Triage-Guidelines#uplift-approvers

Updated 👍

**Comment by diracdeltas** [comment]
0.58.x: 69948b854e9b22a230ac9422078e254216588b88

**Pull request merged**
