### PR TITLE
don't show force_hide selectors on cosmetic filters iterations

### PR DESCRIPTION
**Pull request by SergeyZhukovsky**
Resolves https://github.com/brave/brave-browser/issues/14294

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)
- [ ] Requested a security/privacy review as needed

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

described in the original issue

### CODE REVIEW

**Comment by SergeyZhukovsky** [comment]
post-init failed due to a known audit problem, not related to the PR

**Review by antonok-edm — COMMENTED** [review]
Seems to work on some sites, but when I try this out with the following rule in the custom filters:
```
reddit.com##div
```
I still don't see anything at all hidden on https://reddit.com.

Edit: worked after browser restart. I assume this will get fixed along with the other race condition issues.

**Comment by SergeyZhukovsky** [comment]
> Seems to work on some sites, but when I try this out with the following rule in the custom filters:
> 
> ```
> reddit.com##div
> ```
> 
> I still don't see anything at all hidden on https://reddit.com.

are you sure? As that's exactly what that PR fixes and where I tested at.

**Review by antonok-edm — APPROVED** [review]

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.23.2 Chromium: 89.0.4389.58 (Official Build) nightly (64-bit)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | Windows 10 OS Version 2009 (Build 19042.804)
```

* ensured that adding/removing `reddit.com##div` worked as expected

**`Without Custom Filter`** | **`Without Customer Filter`**
---------------|----------------
image  | image


**`With Custom Filter`** | **`With Customer Filter`**
---------------|----------------
image | image

Verification **PASSED** on `Samsung S10+` running `Android 11` using the following build:

```
Brave 1.23.2 Chromium: 89.0.4389.58
```

**`Without Custom Filter`** | **`Without Customer Filter`**
---------------|----------------
Screenshot_20210224-171959_Brave - Nightly | Screenshot_20210224-171936_Brave - Nightly

**`With Custom Filter`** | **`With Customer Filter`**
---------------|----------------
Screenshot_20210224-172024_Brave - Nightly | Screenshot_20210224-172034_Brave - Nightly

**Pull request merged**
