### PR TITLE
Clang formatted Brave Ads

### PR DESCRIPTION
**Pull request by tmancey**
Resolves https://github.com/brave/brave-browser/issues/11066

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by moritzhaller — APPROVED** [review]
LGTM as per screen share!

**Comment by tmancey** [comment]
CI failed for unrelated reasons:
```
18:18:50  Error running format check:
18:18:50  Traceback (most recent call last):
18:18:50    File "/home/ubuntu/workspace/pr-brave-browser-issues-11066-post-init/src/brave/build/commands/scripts/lint.py", line 35, in RunFormatCheck
18:18:50      if HasFormatErrors():
18:18:50    File "/home/ubuntu/workspace/pr-brave-browser-issues-11066-post-init/src/brave/build/commands/scripts/lint.py", line 26, in HasFormatErrors
18:18:50      print(diff)
18:18:50  UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 190844: ordinal not in range(128)
18:18:50  ```

**Comment by tmancey** [comment]
If code reviewing please ignore changes to lint.py as these are temporary while I work out why printing unicode is not working

**Comment by tmancey** [comment]
Known test failing on macOS:
```
1 test failed:

[2021-02-05T23:57:10.791Z]     AdBlockServiceTest.CosmeticFilteringProtect1p (../../brave/browser/brave_shields/ad_block_service_browsertest.cc:928)
```

**Comment by tmancey** [comment]
Restarting Linux build. macOS failed as above. All other CI passed.

**Comment by tmancey** [comment]
CI failed for known test `BraveShieldsAPIBrowserTest.AllowScriptsOnceIframe (../../brave/browser/extensions/api/brave_shields_api_browsertest.cc:185)`

**Pull request merged**
