### PR TITLE
Reland "Fix deps in //brave/components/content_settings/renderer"

### PR DESCRIPTION
**Pull request by Gyuyoung**
Resolves Resolves brave/brave-browser#10637.

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [x] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by Gyuyoung** [comment]
@mkarolin The original PR was reverted because it broke the brave unit test - https://github.com/brave/brave-core/pull/6322. Now this PR passes all CI bots. I'm supposed that this PR won't break the brave unit test. PTAL.

**Comment by mkarolin** [comment]
@Gyuyoung, unfortunately the CI only builds Release. The reason for reverting was only seen in Debug (probably also Component) build (at least on Windows). I am seeing the same errors as in #6322 with this re-land as well.

I think we need to use `//third_party/blink/public/mojom:mojom_platform_blink_headers` instead.

**Comment by Gyuyoung** [comment]
@mkarolin Ah, I see. I replace third_party/blink/public/mojom:mojom_platform_blink with  //third_party/blink/public/mojom:mojom_platform_blink_headers in this PR. Could you check it again? Thanks a lot!

**Comment by mkarolin** [comment]
@Gyuyoung with the latest change there are no build errors and gn check passes.

**Comment by mkarolin** [comment]
@Gyuyoung you may need to rebase on the latest master.

**Comment by Gyuyoung** [comment]
> @Gyuyoung you may need to rebase on the latest master.

ok, l'm uploading a PR after rebasing it. Let me merge this PR after passing CI. Thanks!

**Comment by Gyuyoung** [comment]
I think that windows CI was failed by the flaky tests unrelated to this PR. So, merging...

**Pull request merged**
