### PR TITLE
Fixes balance being an empty string (uplift to 1.11.x)

### PR DESCRIPTION
**Pull request by NejcZdovc**
Uplift of https://github.com/brave/brave-core/pull/5883
Resolves https://github.com/brave/brave-browser/issues/10315

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
@NejcZdovc mind taking a look? Seems like we have multiple failures on `test-browser` & `test-unit` due to the following:

```
FAILED: obj/brave/test/brave_browser_tests/rewards_service_browsertest.o 
```

Are these intermittent issues? I don't usually see the above failing intermittently but could be wrong.

**Comment by NejcZdovc** [comment]
@kjozwiak fixed

**Comment by kjozwiak** [comment]
> @kjozwiak fixed

@NejcZdovc looks like `init` is still failing on every platform:

* `Android` --> https://ci.brave.com/job/pr-brave-browser-rewards-bat-support-11-1.11.x/2/execution/node/213/log/
* `iOS` --> https://ci.brave.com/job/pr-brave-browser-rewards-bat-support-11-1.11.x/2/execution/node/180/log/
* `Linux` --> https://ci.brave.com/job/pr-brave-browser-rewards-bat-support-11-1.11.x/2/execution/node/145/log/
* `macOS` --> https://ci.brave.com/job/pr-brave-browser-rewards-bat-support-11-1.11.x/2/execution/node/166/log/
* `Win x64` --> https://ci.brave.com/job/pr-brave-browser-rewards-bat-support-11-1.11.x/2/execution/node/385/log/

Seems like there's an issue applying the patch?

```
07:22:17  1 failed patches:
07:22:17  chrome/VERSION
07:22:17    - Patch applied because: No corresponding .patchinfo file was found.
07:22:17    - Error - Program git exited with error code 1.
07:22:17  -------------------------------
07:22:17  Done applying patches.
07:22:17  npm
07:22:17   ERR! code ELIFECYCLE
07:22:17  npm ERR! errno 1
07:22:17  npm ERR! brave@1.11.74 init: `node ./scripts/sync.js --init`
07:22:17  npm ERR! Exit status 1
07:22:17  npm ERR! 
07:22:17  npm ERR! Failed at the brave@1.11.74 init script.
07:22:17  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kjozwiak** [comment]
Going to restart this again. If it fails again during `init` on all the platforms, @NejcZdovc or @AndriusA will need to take a look to move this along.

**Comment by kjozwiak** [comment]
@NejcZdovc @AndriusA looks like restarting didn't help as per https://ci.brave.com/job/pr-brave-browser-rewards-bat-support-11-1.11.x/4/flowGraphTable. Looks like `init` basically failed on all the platforms.

**Comment by NejcZdovc** [comment]
@kjozwiak fixed

**Comment by emerick** [comment]
Any ETA on when we might uplift this? I think it's potentially related to https://github.com/brave/brave-browser/issues/10329.

**Pull request merged**
