### PR TITLE
10967: Use Chromium's testing/xvfb.py utility to run tests

### PR DESCRIPTION
**Pull request by mariospr**
Always use this testing utility to run tests, as it will improve the
experience on Linux-based environments while preserving the current
state on other platforms.

Fixes: #10967

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [x] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [x] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection

## Test Plan:

Run the following tests locally, and check that they run/work as expected:
```
npm run test -- brave_unit_tests
npm run test -- brave_browser_tests
```

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions.

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by mariospr** [comment]
@mkarolin @bridiver This is the updated PR (based on https://github.com/brave/brave-browser/pull/10970) now that this needs to be submitted against brave-core.

As mentioned earlier, I could only test this one on Linux, it would be great if any of you could apply this locally and test it as well on Windows & Mac, to be extra sure that xvfb.py does work as the pass-through script it is meant to be on those platforms.

**Comment by mkarolin** [comment]
@mariospr, failed on Windows for me:
<pre>
C:\bb2\brave-browser\src
> C:\bb2\brave-browser\src\testing\xvfb.py C:\bb2\brave-browser\src\out\Release\brave_browser_tests.exe --enable-logging=stderr --v=0 --test-launcher-jobs=4
Traceback (most recent call last):
  File "C:\bb2\brave-browser\src\testing\xvfb.py", line 11, in <module>
    import psutil
ImportError: No module named psutil
</pre>

**Comment by mariospr** [comment]
@mkarolin Looks like you don't have the psutil python module installed. Do you know whether there anything we should do inside Brave repo about it (e.g. add some dependency to some install-build-deps script or the like)? Or is this something that needs to be installed on your system manually (and perhaps added to https://github.com/brave/brave-browser/wiki/Windows-Development-Environment)?

**Comment by mkarolin** [comment]
There is an option to install additional python modules like we do here https://github.com/brave/brave-core/blob/master/build/commands/lib/util.js#L11, but it would be odd to install a module on a platform to run a script that isn't actually useful on that platform. Maybe it's better to preemptively limit your change to linux in test.js after all?

**Comment by mkarolin** [comment]
CI for Android is also failing with the same error, so I am guessing psutil module is something that Chromium adds only for Linux.
<pre>
 /home/ubuntu/workspace/pr-brave-browser-issues-10967/src
 > /home/ubuntu/workspace/pr-brave-browser-issues-10967/src/testing/xvfb.py /home/ubuntu/workspace/pr-brave-browser-issues-10967/src/out/android_Release_x86/brave_unit_tests --enable-logging=stderr --test-launcher-jobs=4
 Traceback (most recent call last):
   File "/home/ubuntu/workspace/pr-brave-browser-issues-10967/src/testing/xvfb.py", line 11, in <module>
     import psutil
 ImportError: No module named psutil
</pre>

**Comment by mariospr** [comment]
> There is an option to install additional python modules like we do here https://github.com/brave/brave-core/blob/master/build/commands/lib/util.js#L11, but it would be odd to install a module on a platform to run a script that isn't actually useful on that platform. Maybe it's better to preemptively limit your change to linux in test.js after all?

I see, thanks for the clarification. I agree it probably makes sense then to limit this to Linux but, since this is not urgent at all, I'll prepare a better one along these lines once I'm back on August 17th, if that's ok. Thanks again!

**Comment by kjozwiak** [comment]
Removing this from the `1.14.x` milestone as it was just released as per https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule. However, this PR hasn't been completed so it shouldn't be in a milestone till it's completed as per https://github.com/brave/brave-browser/wiki/Triage-Guidelines#milestones-and-pull-requests. Once the above gets merged, it should go into the current `master` milestone.

**Comment by mariospr** [comment]
I gave some more thought to this and I actually think it's not that necessary after all since (1) it only improves Linux and (2) you can always run the tests manually using `testing/xvfb.py` by doing something like this (which is what I'm doing):
```
testing/xvfb.py  out/Release/brave_browser_tests
```
So I'm closing this PR for now, sorry for the back and forth.

**Pull request closed without merging**
