### PR TITLE
Fixes a crash when a large amount is entered in From or To fields (uplift to 1.35.x)

### PR DESCRIPTION
**Pull request by SergeyZhukovsky**
Uplift of https://github.com/brave/brave-core/pull/12148
Resolves https://github.com/brave/brave-browser/issues/20881

### CODE REVIEW

**Comment by SergeyZhukovsky** [comment]
do we have any problems with lint in 1.35.x? I don't understand why does it check lots of files as the PR only changed 2 Java files.

**Comment by kjozwiak** [comment]
> do we have any problems with lint in 1.35.x? I don't understand why does it check lots of files as the PR only changed 2 Java files.

@SergeyZhukovsky yup, known problem and not related to your PR. It's been like this since `1.35.x` hit release. I believe @bsclifton was looking into it but is having a hard time pinpointing the issue. It's a blocker.

**Comment by Tyjuan1980** [comment]
D..

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.35.x` approved after deliberating with @brave/uplift-approvers. QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/12148#issuecomment-1031025964.

**Pull request merged**
