### PR TITLE
[Android] Fix Bravenews settings header 

### PR DESCRIPTION
**Pull request by tapanmodh**
Resolves https://github.com/brave/brave-browser/issues/21725
Resolves https://github.com/brave/brave-browser/issues/21833

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by alexsafe — APPROVED** [review]
LGTM

**Review by deeppandya — APPROVED** [review]
LGTM

**Comment by kjozwiak** [comment]
Moving into `1.39.x` as this landed in `master` ~8 days ago which was `1.39.x` and not `1.38.x`. These fixes are not in `1.38.x` until https://github.com/brave/brave-core/pull/12931 as been uplifted into `1.38.x`.

**Comment by kjozwiak** [comment]
Reproduced both https://github.com/brave/brave-browser/issues/21725 & https://github.com/brave/brave-browser/issues/21833 using `1.37.110 Chromium: 100.0.4896.60`.

Verification **PASSED** on `Pixel 6` running `Android 12` using `1.39.41 Chromium: 100.0.4896.79`

#### `Test Case #1` - https://github.com/brave/brave-browser/issues/21725

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/21725#issue-1171840199 as per the following:

https://user-images.githubusercontent.com/2602313/162361189-fd994ca3-d6f7-41ab-9008-2a3050f4f076.mp4

#### `Test Case #2` - Brave News header missing when interrupting page load by tapping Home button #21833

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/21725#issue-1171840199 as per the following:

https://user-images.githubusercontent.com/2602313/162361841-4227ea25-c450-42fe-a117-768fefa70db5.mp4

**Pull request merged**
