### PR TITLE
Updated Brave Ads UI copy to "Ads received this month" - 1.17.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/7163
Resolves https://github.com/brave/brave-browser/issues/12719

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by LaurenWags** [comment]
Restarted `macOS`, `Linux`, `Windows`

**Comment by kjozwiak** [comment]
@tmancey looks like the above needs to be rebased.

**Comment by kjozwiak** [comment]
Restarting `Win x64` via https://ci.brave.com/job/pr-brave-browser-issues-12719-1.17.x-windows/4/ due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-issues-12719-1.17.x-windows/3/execution/node/200/log/. Looks like there was issues with the node connectivity.

```
23:56:05  Cannot contact i-04a534545b6634a7a-windows-swarm-0c31abab: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException
00:01:06  Could not connect to i-04a534545b6634a7a-windows-swarm-0c31abab to send interrupt signal to process
```

Restarting `macOS` via https://ci.brave.com/job/pr-brave-browser-issues-12719-1.17.x-macos/4/ due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-issues-12719-1.17.x-macos/3/execution/node/204/log/.

```
23:51:21  FAILED: obj/third_party/webrtc/common_audio/third_party/spl_sqrt_floor/spl_sqrt_floor/spl_sqrt_floor.o 
```

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.17.x` approved after deliberating with @brave/uplift-approvers. QA has also verified the PR on Nightly as per https://github.com/brave/brave-core/pull/7163#issuecomment-732190565.

**Pull request merged**
