### PR TITLE
Fix wrong default service name and account name are used when getting

### PR DESCRIPTION
**Pull request by darkdh**
keychain password. Also fix getting correct keychain password when
importing from chrome, brave and chromium

In C94 `GetServiceName` and `GetAccountName` were calling upstream one from upstream `GetPassword`
Import didn't work correctly because `BRAVE_KEYCHAIN_PASSWORD_GET_PASSWORD` had no effect

Resolves https://github.com/brave/brave-browser/issues/18138

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### Check keychain access
1. Open `Keychain Access.app`
2. Under `Local Items`->`All Items` and find `Chromium Safe Storage` and `Brave Safe Storage`
3. Open them separately and delete all items in access control list
4. Launch Brave with this fix
5. Brave should prompts asking the access to `Brave Safe Storage` instead of `Chromium Safe Storage`

### Import
1. Make sure chrome have stored passwords
2. Open Brave and import passwords from chrome
3.  Allow access to chrome safe storage
4. passwords should be successfully imported
5. change chrome to chromium and repeat step 1-4

### Migration
1. Store passwords, credit cards and setup sync in pre C94 Brave
2. Upgrade to C94 Brave 
3. check passwords, credit cards are gone and sync is not working
4. Upgrade to Brave with this fix
5. Passwords, credit cards in step 1 should be back and sync is working

### CODE REVIEW

**Comment by darkdh** [comment]
test will be addressed in follow up https://github.com/brave/brave-browser/issues/18145

**Review by bbondy — COMMENTED** [review]
Can we check this in a test to make sure the Brave service and account name is returned?

**Review by bbondy — APPROVED** [review]
> test will be addressed in follow up brave/brave-browser#18145
Sorry just saw that now.

**Review by mkarolin — APPROVED** [review]
++

**Comment by darkdh** [comment]
https://ci.brave.com/job/pr-brave-browser-keychain_mac_fix-macos/3/execution/node/218/log/
unrelated failure due to using release node to run macos CI

**Comment by rebron** [comment]
Updated to 1.31.46 from 1.31.41.

Brave | 1.31.46 Chromium: 94.0.4606.41 (Official Build) nightly (arm64)
-- | --
Revision | 333e85df3c9b656b518b5f1add5ff246365b6c24-refs/branch-heads/4606@{#845}
OS | macOS Version 12.0 (Build 21A5506j)
JavaScript | V8 9.4.146.13
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.41 Safari/537.36

Verified that all of my passwords (164) are restored and sync settings brave://settings/braveSync/setup are back to normal.

**Pull request merged**
