### PR TITLE
SKUs: fixes a bug preventing cancelled state from getting credentials

### PR DESCRIPTION
**Pull request by evq**
this was introduced in #20667

Resolves https://github.com/brave/brave-browser/issues/34556

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by rillian — APPROVED** [review]

**Review by husobee — APPROVED** [review]
lgtm

**Comment by stephendonner** [comment]
## I ran through this and it looks to have fixed the original problem for me (which I can also reproduce).


## Original issue of appearing to have credentials, but they're actually `null` in regular `nightly`, `1.62.88`:


Screen Shot 2023-11-29 at 12 19 52 PM

## Then, I ran with the fix using the `pr-build` of `1.62.86`

example | example
---------|---------
Screen Shot 2023-11-29 at 12 26 45 PM | Screen Shot 2023-11-29 at 12 42 01 PM


## NOTE: 💥 I do, however, also see a crash/crashers which looked/looks like this:

```
[20811:20811:1129/135726.760131:VERBOSE1:component_installer.cc(53)] Skipping registration of Brave-unsupported component ojhpjlocmbogdgmfpkhlaaeamibhnphh.
[20811:20811:1129/135726.760195:VERBOSE1:autofill_states_component_installer.cc(117)] Registering Autofill States data component.
[20811:20811:1129/135726.760248:VERBOSE1:component_installer.cc(53)] Skipping registration of Brave-unsupported component eeigpngbgcognadeebkilcpcaedhellh.
[20811:20811:1129/135726.760429:VERBOSE1:tpcd_metadata_component_installer.cc(181)] Third Party Cookie Deprecation Metadata component.
[20811:20827:1129/135726.760578:VERBOSE1:component_installer.cc(428)] StartRegistration for Third-Party Cookie Deprecation Metadata
[20811:20827:1129/135726.760609:VERBOSE1:component_installer.cc(245)] Relative install dir does not exist: /opt/brave.com/brave-nightly/TpcdMetadata
[20811:20811:1129/135726.761853:VERBOSE1:variations_service.cc(744)] Resource requests were not allowed. Waiting for notification.
[20811:20811:1129/135726.762322:VERBOSE1:keep_alive_registry.cc(169)] Notifying KeepAliveStateObservers: KeepingAlive changed to: 1
[20811:20811:1129/135726.762406:VERBOSE1:keep_alive_registry.cc(176)] Notifying KeepAliveStateObservers: Restart changed to: 0
[20811:20811:1129/135726.762460:VERBOSE1:keep_alive_registry.cc(137)] New state of the KeepAliveRegistry: {registered_count_=1, restart_allowed_count_=0, KeepAlives=[SESSION_RESTORE (1)]}
[20811:20811:1129/135726.762541:VERBOSE1:profile_manager.cc(1335)] AddKeepAlive(Default, kBrowserWindow). keep_alives=[kWaitingForFirstBrowserWindow (1), kBrowserWindow (1)]
[20811:20811:1129/135726.762613:VERBOSE1:profile_manager.cc(1408)] ClearFirstBrowserWindowKeepAlive(Default). keep_alives=[kBrowserWindow (1)]
[20811:20829:1129/135726.762946:VERBOSE1:command_storage_backend.cc(591)] CommandStorageBackend::ReadLastSessionCommands, reading commands from: /home/sdonner/.config/BraveSoftware/Brave-Browser-Development/Default
[20811:20827:1129/135726.762977:VERBOSE1:command_storage_backend.cc(591)] CommandStorageBackend::ReadLastSessionCommands, reading commands from: /home/sdonner/.config/BraveSoftware/Brave-Browser-Development/Default/Sessions/Session_13345768536583923
[20811:20829:1129/135726.762981:FATAL:file_posix.cc(470)] Check failed: 0 != saved_errno (0 vs. 0)
#0 0x55f0d100e662 (/opt/brave.com/brave-nightly/brave+0xbceb661)
#1 0x55f0d0ff50c3 (/opt/brave.com/brave-nightly/brave+0xbcd20c2)
#2 0x55f0d0ef54b3 (/opt/brave.com/brave-nightly/brave+0xbbd24b2)
#3 0x55f0d0edae30 (/opt/brave.com/brave-nightly/brave+0xbbb7e2f)
#4 0x55f0d0edac77 (/opt/brave.com/brave-nightly/brave+0xbbb7c76)
#5 0x55f0d0fe68a2 (/opt/brave.com/brave-nightly/brave+0xbcc38a1)
#6 0x55f0cf116b2a (/opt/brave.com/brave-nightly/brave+0x9df3b29)
#7 0x55f0cf11507f (/opt/brave.com/brave-nightly/brave+0x9df207e)
#8 0x55f0cf114fea (/opt/brave.com/brave-nightly/brave+0x9df1fe9)
#9 0x55f0ceb4de71 (/opt/brave.com/brave-nightly/brave+0x982ae70)
#10 0x55f0cbaf1658 (/opt/brave.com/brave-nightly/brave+0x67ce657)
#11 0x55f0cf11b33a (/opt/brave.com/brave-nightly/brave+0x9df8339)
#12 0x55f0ca2b6230 (/opt/brave.com/brave-nightly/brave+0x4f9322f)
#13 0x55f0ca299550 (/opt/brave.com/brave-nightly/brave+0x4f7654f)
#14 0x55f0d0fa3b89 (/opt/brave.com/brave-nightly/brave+0xbc80b88)
#15 0x55f0d0fa3c75 (/opt/brave.com/brave-nightly/brave+0xbc80c74)
#16 0x55f0ca299550 (/opt/brave.com/brave-nightly/brave+0x4f7654f)
#17 0x55f0d0f5c909 (/opt/brave.com/brave-nightly/brave+0xbc39908)
#18 0x55f0d0fa8c27 (/opt/brave.com/brave-nightly/brave+0xbc85c26)
#19 0x55f0d0fa8d11 (/opt/brave.com/brave-nightly/brave+0xbc85d10)
#20 0x55f0d0fa84b5 (/opt/brave.com/brave-nightly/brave+0xbc854b4)
#21 0x55f0d0fa7e34 (/opt/brave.com/brave-nightly/brave+0xbc84e33)
#22 0x55f0d0fc095f (/opt/brave.com/brave-nightly/brave+0xbc9d95e)
#23 0x55f0d0fc04cd (/opt/brave.com/brave-nightly/brave+0xbc9d4cc)
#24 0x55f0d0fc0383 (/opt/brave.com/brave-nightly/brave+0xbc9d382)
#25 0x55f0d0fe96d8 (/opt/brave.com/brave-nightly/brave+0xbcc66d7)
#26 0x7f5841297ada (/usr/lib/x86_64-linux-gnu/libc.so.6+0x97ad9)
#27 0x7f584132847c (/usr/lib/x86_64-linux-gnu/libc.so.6+0x12847b)
Task trace:
#0 0x55f0cf11a565 (/opt/brave.com/brave-nightly/brave+0x9df7564)
Crash keys:
  "extension-1" = "mafpmfcccpbjnhfhjnllmmalhifmlcie"
  "num-extensions" = "1"
  "switch-13" = "--component-updater=url-source=https://go-updater.brave.com/exte"
  "reentry_guard_tls_slot" = "unused"
  "variations-seed-version" = "1"
  "variations" = "4b935545-3d47f4f4,9a38bae3-3d47f4f4,6948f188-f23d1dea,2d1e43a3-3d47f4f4,386dc267-3d47f4f4,"
  "num-experiments" = "5"
  "switch-12" = "--variations-insecure-server-url=https://variations.brave.com/se"
  "switch-11" = "--variations-server-url=https://variations.brave.com/seed"
  "switch-10" = "--lso-url=https://no-thanks.invalid/"
  "switch-9" = "--sync-url=https://sync-v2.brave.com/v2"
  "switch-8" = "--origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld"
  "switch-7" = "--enable-distillability-service"
  "switch-6" = "--enable-dom-distiller"
  "switch-5" = "--disable-domain-reliability"
  "switch-4" = "--disable-gpu"
  "switch-3" = "--env-ai-chat-premium.bsg=dev"
  "switch-2" = "--env-ai-chat.bsg=dev"
  "switch-1" = "--env-leo=staging"
  "num-switches" = "17"
  "osarch" = "x86_64"
  "pid" = "20811"
  "ptype" = "browser"

[1129/135726.782682:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1129/135726.787500:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[1129/135726.787637:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
[20869:20869:1129/135726.810361:VERBOSE1:memory_linux.cc(77)] Adjusting oom_score_adj of 20869 to 200
[20869:20869:1129/135726.819160:VERBOSE1:power_monitor.cc(156)] PowerStateChange: Off battery
[20869:20869:1129/135726.819223:VERBOSE1:power_monitor.cc(205)] ThermalStateChange: Unknown
[20869:20869:1129/135726.819238:VERBOSE1:power_monitor.cc(219)] SpeedLimitChange: 100
/usr/bin/brave-browser-nightly: line 48: 20811 Trace/breakpoint trap   (core dumped) "$HERE/brave" "$@"
[20847:20874:0100/000000.798738:VERBOSE1:persistent_histogram_allocator.cc(958)] 18 histograms were created before persistence was enabled.
[20847:20874:0100/000000.943117:VERBOSE1:ipc_sync_channel.cc(436)] Canceling pending sends
```

**Comment by stephendonner** [comment]
LGTM too from QA - I'll post updated verification notes here, but I didn't want to block or stall this further.  🚢  it!

**Review by stephendonner — APPROVED** [review]
LGTM after running through the fix using both macOS and linux builds on x64 👍 

(confirmed the issue using vanilla `1.60.88` first)

**Comment by evq** [comment]
going to merge this despite most recent linux failure as https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-fix-submit-creds-linux-x64/detail/pr-brave-browser-fix-submit-creds-linux-x64/1/pipeline/ succeeded and is identical in content

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

`https://build-artifacts.brave.com/brave-browser-build-pr/fix-submit-creds/bef83f165d63f80c95b586160c0fb47566a154c5/macos/Brave Browser Nightly.dmg`

### Steps:
1. installed build w/fix
2. launched Brave
3. purchased `Leo` using `account.bravesoftware.com`
4. cancelled subscription
5. logged out of the account website
6. launched a new profile with the special build
7. logged back in using `issue34556-mac@mailinator.com`
8. clicked on `Refresh Leo`

### Confirmed I was re-issued working credentials, from a cancelled plan with a new profile

example | example | example | example | example
---------|----------|---------|----------|---------
Screen Shot 2023-11-29 at 3 17 10 PM | Screen Shot 2023-11-29 at 3 21 16 PM | Screen Shot 2023-11-29 at 3 30 04 PM | Screen Shot 2023-11-29 at 3 31 06 PM | Screen Shot 2023-11-29 at 3 31 32 PM

**Pull request merged**
