### PR TITLE
Use override method for ChromeBrowserMainExtraPartsView

### PR DESCRIPTION
**Pull request by simonhong**
With this, we don't need to subclass ChromeBrowserMainExtraPartsView and
touch ChromeContentBrowserClient.

Issue: https://github.com/brave/brave-browser/issues/461

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.

## Test Plan:
`yarn test brave_browser_tests Release --filter=*.GetDefaultWindowIconTest`

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions

### CODE REVIEW

**Comment by simonhong** [comment]
Found that this PR work with `yarn start` but test is failed.

**Comment by simonhong** [comment]
Test is enabled only in release mode.
PTAL.

**Comment by simonhong** [comment]
Kindly ping..

**Comment by bbondy** [comment]
Thanks for cleaning up and removing an old patch

**Pull request merged**
