### PR TITLE
Remove custom css filtering in Brave. Fixes brave/brave-browser#8209

### PR DESCRIPTION
**Pull request by ryanbr**
Since we have cosmetic filtering in Brave, we can safely remove these specific css hooks in Brave (as per discussion in https://github.com/brave/brave-core/pull/4603#issuecomment-597509272.

This will overrule: https://github.com/brave/brave-core/pull/4603 and will fix https://github.com/brave/brave-browser/issues/8209

## Submitter Checklist:

- [ ] Removed the brave_extension/assets/*.css files (leaving the .js files)
- [ ] Adjusted the Manifest
- [ ] Adjusted resources.grd

Any questions let me know. If it looks good @bsclifton

### CODE REVIEW

**Comment by ryanbr** [comment]
**marketwatch.com: (Generic blocks)**
```
easylist/easylist_general_hide.txt:##.container--bannerAd
easylist/easylist_general_hide.txt:##.element--ad
easylist/easylist_general_hide.txt:##.ad.module
```
**marketwatch.com. Dead filters: (no hits):**
```
marketwatch.com###brass-rail
marketwatch.com##iframe[src*="smartads.epl"]
```
**cointmarketcap.com. Dead filters: (no hits):**
```
coinmarketcap.com###leaderboard
coinmarketcap.com###leaderboard-bottom
coinmarketcap.com###icobanner-wrapper
```
**Generic Blocks:**
```
easylist/easylist_general_hide.txt:##.ad-hideable
easylist/easylist_general_hide.txt:##.ad-div
easylist/easylist_general_hide.txt:##.masthead-ad-control
easylist/easylist_general_hide.txt:##.video-ads
easylist/easylist_specific_hide.txt:youtube.com##.promoted-sparkles-text-search-root-container
easylist/easylist_specific_hide.txt:youtube.com##.ytd-compact-promoted-video-renderer
easylist/easylist_specific_hide.txt:youtube.com##ytd-promoted-sparkles-web-renderer
easylist/easylist_specific_hide.txt:youtube.com##ytm-promoted-sparkles-text-search-renderer
easylist/easylist_specific_hide.txt:youtube.com###pla-shelf
easylist/easylist_specific_hide.txt:youtube.com###merch-shelf
easylist/easylist_general_hide.txt:###ad_creative_3
easylist/easylist_general_hide.txt:###footer-ads
easylist/easylist_general_hide.txt:###watch7-sidebar-ad
easylist/easylist_general_hide.txt:##.ytp-ad-progress-list
easylist/easylist_specific_hide.txt:youtube.com##.ad-container
easylist/easylist_specific_hide.txt:youtube.com###video-masthead
easylist/easylist_specific_hide.txt:youtube.com###watch-channel-brand-div
easylist/easylist_general_hide.txt:###player-ads
easylist/easylist_general_hide.txt:###masthead-ad
```
**Not seen:**
`#Billboard-ad`

**Comment by ryanbr** [comment]
This removal won't affect IOS/Android?

**Comment by bsclifton** [comment]
@ryanbr it will affect Android as we're moving towards Android Core (sharing same code-base)

**Comment by ryanbr** [comment]
Missed the Glen Beck  script.

**Comment by ryanbr** [comment]
Safe to land/merge this @bsclifton ?

**Comment by bsclifton** [comment]
NOTE: if this gets uplifted, please also uplift https://github.com/brave/brave-core/pull/5403

**Pull request merged**
