### PR TITLE
Show profile names instead of browser name

### PR DESCRIPTION
**Pull request by spylogsster**
Resolves https://github.com/brave/brave-browser/issues/27566

Replaced browser name by profile name for the importing dialog view.

image

Chrome browser:
image

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
- Create multiple profiles in Firefox
- Try to import via new brave://welcome page
- Check all profiles have correct names

### CODE REVIEW

**Review by nullhook — COMMENTED** [review]
How does this look for Chromium based browser imports?

**Comment by spylogsster** [comment]
> How does this look for Chromium based browser imports?

added screenshot

**Review by nullhook — APPROVED** [review]
lgtm

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.49.3 Chromium: 109.0.5414.74 (Official Build) nightly (64-bit)
-- | --
Revision | e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}
OS | Windows 11 Version 22H2 (Build 22621.963)
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/27566#issue-1513831589 & https://github.com/brave/brave-core/pull/16490#issue-1513832890 and ensured the following:

* ensured that the correct profile names are being listed under `Firefox/Mozilla`, `Edge` & `Chrome`
* ensured that you can import a single profile without any issues
* ensured that you can import multiple profiles without any issues
* ensured that you can import multiple profiles from multiple browsers without any issues (Chrome/Chrome Dev etc..)

For each of the above, I made sure that extensions, history, passwords and bookmarks were being imported. The exception being Firefox were importing extensions/passwords doesn't work which I believe is expected.

**`Firefox` Examples**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|-----------------|--------------
firefoxProfiles0 | firefoxProfiles1 | firefoxProfiles2 | firefoxProfiles3 | firefoxProfiles4

**`Chrome` Examples**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|-----------------|---------------|-----------------
chromeProfiles0 | chromeProfiles1 | chromeProfiles2 | chromeProfiles3 | chromeProfiles4 | chromeProfiles5

**`Edge` Examples**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|-----------------|--------------
edgeProfiles0 | edgeProfiles1 | edgeProfiles2 | edgeProfiles3 | edgeProfiles4

Also ensured that profiles are correctly being listed via `brave://settings/importData` as per the following:
 
importData

**Pull request merged**
