### PR TITLE
Hotfix for si centerpoint 1.9.x (Uplift to 1.9.x)

### PR DESCRIPTION
**Pull request by deeppandya**
Uplift of https://github.com/brave/brave-core/pull/5349

### CODE REVIEW

**Comment by kjozwiak** [comment]
Restarting `Android` as `dist` failed as per https://ci.brave.com/job/brave-browser-build-pr/job/hotfix_for_SI_centerpoint_1.9.x/1/execution/node/397/log. Looks like the spot instance was disconnected:

```
12:12:47  Cannot contact i-0f82655f08140fa9b: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@12371ad3:i-0f82655f08140fa9b": Remote call on i-0f82655f08140fa9b failed. The channel is closing down or has closed down
12:17:50  Could not connect to i-0f82655f08140fa9b to send interrupt signal to process
```

Restarting `macOS` as `build` failed as per https://ci.brave.com/job/brave-browser-build-pr/job/hotfix_for_SI_centerpoint_1.9.x/1/execution/node/284/log/.

**Comment by kjozwiak** [comment]
Restarting `macOS` as both `test-browser` and `test-install` failed as per the following:

* https://ci.brave.com/job/brave-browser-build-pr/job/hotfix_for_SI_centerpoint_1.9.x/2/execution/node/419/log/
* https://ci.brave.com/job/brave-browser-build-pr/job/hotfix_for_SI_centerpoint_1.9.x/2/execution/node/436/log/

**Comment by bsclifton** [comment]
@kjozwiak those are both known issues; the browser-test failure one is captured here:
https://github.com/brave/brave-browser/issues/6515

I don't think we have an issue captured for the `test-install`, but it's not a blocker 👍

**Comment by kjozwiak** [comment]
QA verified https://github.com/brave/brave-core/pull/5349 on Nightly as per https://github.com/brave/brave-core/pull/5349#issuecomment-619256783.

**Pull request merged**
