### PR TITLE
chore(wallet): refactor async handler logic into action creators

### PR DESCRIPTION
**Pull request by onyb**
This is an experimental PR. The idea is to extract logic used in async handlers out into smaller action creators. No optimisation has been done as part of this PR. Just looking for feedback on this design for now.

Here's the new structure of the `async` directory:

```
components/brave_wallet_ui/common/async
├── bridge.ts
├── handlers.ts
├── lib.ts
└── types.ts
```

`lib.ts` contains async functions and action creators. Here's an example of an action creator:

```ts
// action creator
export function myActionCreator (param: Param) {
  return async (dispatch: Dispatch, getState: () => State) => {
    // logic
  }
}

// dispatching myActionCreator normally
myActionCreator(param)(store.dispatch)

// dispatching myActionCreator with redux-thunk
store.dispatch(myActionCreator(param))
```

⚠️ Added the thunk middleware to Redux, which makes dispatching such action-creators simpler, but it's not a requirement.
👉  Action creators can be unit-tested independently by simply calling them with mocked values of `dispatch` and `getState`.

Resolves https://github.com/brave/brave-browser/issues/18873.

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by Douglashdaniel — APPROVED** [review]
Nice refactor!!

**Comment by petemill** [comment]
I'm wondering about the logic of the split made in this PR, as it wasn't immediately understandable to me ([and I'm seeing an anti-pattern attempt to creep in via subsequent PRs adding random async functions to lib.ts](https://github.com/brave/brave-core/pull/10681/files#diff-b85091d7cf18c04a6a4ddd6a277db8bbe711a12299e16e98c0a3e7e11f96c00e)).

So if I'm getting this right:
- `handlers.ts` are functions which respond to existing dispatched actions and do things, e.g. fetch data, and dispatch further actions with the data.
- `lib.ts` are thunks which are themselves dispatch-able and can do things and dispatch further actions.

So first confusing things is naming - maybe `lib.ts` should be `thunks.ts`, otherwise devs will put "lib" things in here (see above example).

But the main confusion is that there are now two different philosophies in the same UI for redux async middleware: 1. our `AsyncActionHandler` and now 2. `redux-thunk`. They both do exactly the same thing but with slight difference:
- `AsyncActionHandler` takes a regular redux action already dispatched and performs side-effects at the same time as the regular redux reducer can handle the action (e.g. the reducer will set an 'inProgress` flag in the state, and the async handler will fetch the data).
- `redux-thunk` creates its own dispatch-able actions, which when called do the async calls and then dispatches further redux actions.

So now there are 2 ways for a developer to make an action that will do something async: either make an action in `wallet_actions` and handle it accordingly in `handlers.ts` or make a thunk and handle it in `lib.ts`. If there is a difference in when to use which then it needs to be clear and commented.

Since wallet is a large app, we should encourage 1 easy-to-follow pattern for developers in order to keep this complex and central part of the code as readable and maintainable as possible. 

We started the pattern of using `AsyncActionHandler` across our code so that we can encourage developers to build responsiveness to their apps and show that things are happening in progress whilst still reducing boilerplate and cognitive load that redux has had complaints about.

If the intention was to clean up and have smaller modules, perhaps just splitting some of the handlers and actions by a category would do the job (e.g. `keyring_{actions,handlers}`, `transaction_actions`, `account_actions`, `balance_actions`)?

Or if the preferred pattern for this UI really is to use redux-thunk and dispatch more actions to relay start progress back to the reducer, then it's probably best to use redux-thunk instead of `AsyncActionHandler`.

**Comment by petemill** [comment]
https://github.com/brave/brave-browser/issues/19225
https://github.com/brave/brave-browser/issues/19226

**Comment by onyb** [comment]
@petemill Thanks for your remarks on the design. Your understanding about the intent of the refactoring is correct, and I agree that there are now two competing ways of dispatching actions. I chose redux-thunk to avoid the boilerplate of creating dedicated actions using the redux-act pattern.

Currently, the actions in `components/brave_wallet_ui/common/actions/wallet_actions.ts` are mostly dispatched by the components, so they mean something at the UI level. Do you have any ideas on how we can keep this logical separation between UI-actions and internal actions that are dispatched by other UI-actions? Or maybe such a separation is not that relevant? Just concerned about pollution of redux-act actions. Splitting the handlers does solve this issue to a large extent, so I'm fine with this solution.

I'd argue that we still need the `lib.ts` for certain async functions like `getERC20Allowance()` and `getBalance()` that are not dispatched through actions (i.e., directly imported and called). Perf issues were not tackled in this PR, but thanks for creating one. 👍

**Pull request merged**
