### PR TITLE
Fix audit issues with url-loader and follow-redirects

### PR DESCRIPTION
**Pull request by spylogsster**
Resolves https://github.com/brave/brave-browser/issues/21070

Fixing audit issues:
- https://github.com/advisories/GHSA-v88g-cgmw-v5xw
```
├─┬ url-loader@0.6.2
│ └─┬ schema-utils@0.3.0
│   └── ajv@5.5.2 
```
- https://github.com/advisories/GHSA-pw2r-vq6v-hr8c
```
└─┬ @ledgerhq/hw-app-eth@6.22.3
  └─┬ axios@0.24.0
    └── follow-redirects@1.14.7 
```

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

- no manual tests required

### CODE REVIEW

**Comment by spylogsster** [comment]
just one web-discovery issue left https://github.com/advisories/GHSA-pw2r-vq6v-hr8c @remusao any fixes for this?

**Comment by spylogsster** [comment]
> @spylogsster Can you point me to where follow-redirect is used in wdp? I am not able to find the advisory there.

https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-audit-ajv-noplatform/detail/pr-brave-browser-audit-ajv-noplatform/11/pipeline#step-199-log-536
```
Auditing (npm) /home/ubuntu/workspace/pr-brave-browser-audit-ajv-noplatform/src/brave/vendor/web-discovery-project
Result: Audit failed due to vulnerabilities
[
"https://github.com/advisories/GHSA-pw2r-vq6v-hr8c
]
```

**Comment by remusao** [comment]
Thanks @spylogsster. I see that I can get it with `npm audit` but it seems like there was no dependabot alert.

I have created a PR to bump the version and we can merge as soon as CI is green. https://github.com/brave/web-discovery-project/pull/130 Then we can bump the version of WDP used in brave-core.

**Comment by diracdeltas** [comment]
++ from me, https://github.com/brave/brave-core/pull/12219 and https://github.com/brave/brave-core/pull/12239 can both be closed in favor of this @mihaiplesa

**Comment by diracdeltas** [comment]
went ahead and pushed the DEPS update since this is blocking CI, thanks all

**Review by iefremov — APPROVED** [review]

**Review by remusao — APPROVED** [review]

**Pull request merged**
