### PR TITLE
Fetches a default search engine on Android from Native if it was set via JS API

### PR DESCRIPTION
**Pull request by SergeyZhukovsky**
Resolves https://github.com/brave/brave-browser/issues/16516

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by samartnik — APPROVED** [review]
lgtm

**Review by petemill — COMMENTED** [review]
I'll let others approve since I'm not an expert on the way we do private search override on Android. Though perhaps we should create an issue and commit to not only removing this additional pref, but also the additional java override pref that Android has for private search, and have Android use the same Desktop implementation for private search override. It hooks directly in to the search providers.

**Comment by SergeyZhukovsky** [comment]
> I'll let others approve since I'm not an expert on the way we do private search override on Android. Though perhaps we should create an issue and commit to not only removing this additional pref, but also the additional java override pref that Android has for private search, and have Android use the same Desktop implementation for private search override. It hooks directly in to the search providers.

Created and issue for that https://github.com/brave/brave-browser/issues/16525

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.28.15 x64 Nightly build
- Verified able to set default search engine via the set default modal on search page
- Encountered https://github.com/brave/brave-browser/issues/16515
- Logged https://github.com/brave/brave-browser/issues/16528 for setting default on both normal and private tabs

https://user-images.githubusercontent.com/17010094/122709334-02260a80-d256-11eb-9a96-f9c6fd2bea0b.mp4

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.28.16 x64 Nightly build
- Verified default SE is changed only for normal tabs when setting it via default SE call out on search.brave.com

https://user-images.githubusercontent.com/17010094/122763994-e3943380-d296-11eb-9244-ada0821b3c1d.mp4

**Pull request merged**
