### PR TITLE
Update welcome layout for BRE (Uplift to 1.18.x)

### PR DESCRIPTION
**Pull request by deeppandya**
Resolves https://github.com/brave/brave-browser/issues/13195

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by deeppandya** [comment]
PR for master : https://github.com/brave/brave-core/pull/7447

**Comment by kjozwiak** [comment]
`Android` failed due to `audit-deps` failing as per https://ci.brave.com/job/pr-brave-browser-welcome_layout_update_1.18.x-android/1/execution/node/157/log/. However, this is a known issue which has been fixed on `master` and doesn't block uplift.

```
03:02:44  Crate:         arc-swap
03:02:44  Version:       0.4.7
03:02:44  Title:         Dangling reference in `access::Map` with Constant
03:02:44  Date:          2020-12-10
03:02:44  ID:            RUSTSEC-2020-0091
03:02:44  URL:           https://rustsec.org/advisories/RUSTSEC-2020-0091
03:02:44  Solution:      Upgrade to >=1.1.0 OR >=0.4.8
```

As per @mihaiplesa, we don't need to worry about `continuous-integration/post-init/pr-head`.

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.18.x` approved after deliberating with @brave/uplift-approvers. QA has also verified the above PR in a custom build that @deeppandya provided @GeetaSarvadnya who confirmed the above was fixed.

**Comment by GeetaSarvadnya** [comment]
Verified a one-off build from @deeppandya

Verified the STR from the description https://github.com/brave/brave-browser/issues/13195#issue-767021980

**Pull request merged**
