### PR TITLE
Reload active tab when widevine library is ready to use (uplift to 1.7.x)

### PR DESCRIPTION
**Pull request by bsclifton**
Uplift of #4978
Fixes https://github.com/brave/brave-browser/issues/4646

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by bsclifton** [comment]
redo of https://github.com/brave/brave-core/pull/5049 after discussion on Slack:
https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1585160096007100

**Comment by bsclifton** [comment]
Related (reported when testing this issue) - https://github.com/brave/brave-browser/issues/8862

**Comment by kjozwiak** [comment]
Restarting `macOS` as `test-browser` failed as per https://ci.brave.com/job/brave-browser-build-pr/job/pr4978_issue_4646_widevine_1.7.x/3/execution/node/494/log/

```
14:28:39  [508/508] BraveRewardsBrowserTest.TipConnectedPublisherAnonAndConnected (TIMED OUT)
14:28:39  1 test timed out:
14:28:39      BraveRewardsBrowserTest.TipConnectedPublisherAnonAndConnected (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:2762)
```

Even though the above isn't related to Widevine, restarting just in case to make sure the above failure is intermittent.

**Comment by kjozwiak** [comment]
`Travis` is failing `TEST_SUITE=test-security` due to the `minimist` npm package being vulnerable. It's a known issue as per https://github.com/brave/brave-browser/issues/8722 and doesn't block the PR from being uplifted.

**Comment by kjozwiak** [comment]
Looks like it timed out as per the following:

```
19:53:45  [507/507] BraveRewardsBrowserTest.TipConnectedPublisherAnonAndConnected (TIMED OUT)
19:53:45  1 test timed out:
19:53:45      BraveRewardsBrowserTest.TipConnectedPublisherAnonAndConnected (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:2762)
```

@bsclifton created https://github.com/brave/brave-browser/issues/8881 to address the above timeout.

**Pull request merged**
