### PR TITLE
Fixed line-wrapping of IPFS peer deletion string

### PR DESCRIPTION
**Pull request by deepxcode**
Fixed Issue [#16742](https://github.com/brave/brave-browser/issues/16742)
Instead of truncating the string, changed the message in the dialog box to - 

```
[peer ID]
Are you sure you want to delete this IPFS peer?
```

Resolves [#16742](https://github.com/brave/brave-browser/issues/16742)

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by deepxcode** [comment]
@srirambv Can you assign this PR to me?
and @petemill and @stephendonner  can you review this PR?

**Comment by stephendonner** [comment]
@deepxcode thanks for the patch!  mind fixing the commit message up to be a little more explicit about the change?  Thanks!

**Comment by deepxcode** [comment]
@stephendonner  Does this commit message seems good?

**Comment by stephendonner** [comment]
> @stephendonner Does this commit message seems good?

"Fixed line-wrapping of IPFS string" would be a little more descript, but I'm ok with what you have.

**Comment by deepxcode** [comment]
@stephendonner  Made the requested changes, I hope this is good now.

**Comment by bbondy** [comment]
Did you try building this to see if the newline works like you mentioned?

**Comment by deepxcode** [comment]
I haven't tried to build that. I think it should work.
I am trying to install brave's code on my laptop, but I randomly get some errors. I have been able to fix most of them, some more to go.
Also, do we also need to clone the brave-core repo? Like the changes, I made for this issue are in the brave-core repo, do I need clone brave-core too?

**Comment by bbondy** [comment]
Closing as stale

**Pull request closed without merging**
