### PR TITLE
Update Startpage icons

### PR DESCRIPTION
**Pull request by bsclifton**
Fixes https://github.com/brave/brave-browser/issues/15515

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ x There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
1. Android fresh install
2. Go through Onboarding
3. Verify new icon is used during onboarding (for Startpage)

### CODE REVIEW

**Review by deeppandya — APPROVED** [review]
LGTM

**Comment by deeppandya** [comment]
@jamesmudgett at some point, we should think about changing all search engine icons to vector drawable of possible. I can create a separate issue to track the change.

**Comment by bsclifton** [comment]
@deeppandya sure, that would be great 😄

**Review by alexsafe — APPROVED** [review]

**Comment by bsclifton** [comment]
Merging as errors are unrelated; this is just modifying an existing image (no tests around this)

**Comment by bsclifton** [comment]
Whoops; turns out I had added an image (unintentionally) which broke things on Android build. Should have looked a bit closer at CI ☹️ If this PR is uplifted, please be sure to also uplift https://github.com/brave/brave-core/pull/8656

**Comment by bsclifton** [comment]
Follow up - icons in this PR were too large; fixed with https://github.com/brave/brave-core/pull/8701 (so if this is uplifted, that would be needed too)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.11 x64 Nightly build
- Verified StartPage icon is similar to the other ones during onboarding

**Pull request merged**
