### PR TITLE
Skip DeleteDeviceInfo if sync engine is not active (Android)

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
fixes brave-browser#10861

This is change from https://github.com/brave/brave-core/pull/6173 adapted for Android

Resolves https://github.com/brave/brave-browser/issues/10861

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
Use steps from issue https://github.com/brave/brave-browser/issues/10856 but on the Android device

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
CI failed for:
- Linux `test-browser`
```
02:05:33  ../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:276: Failure
02:05:33  Value of: base::StartsWith( current_url.spec(), braveledger_uphold::GetUrl() + "/signup/step2", base::CompareCase::INSENSITIVE_ASCII)
02:05:33    Actual: false
02:05:33  Expected: true
```

- macos `build | gn-check | audit-network | test-unit | test-browser | dist | test-install | s3-upload`

```
02:01:47  In file included from /Users/jenkins/jenkins/workspace/pr-brave-browser-android_sync_fix_10861/src/brave/chromium_src/content/browser/browser_main_loop.cc:8:
02:01:47  In file included from ../../brave/browser/brave_browser_main_loop.cc:8:
02:01:47  In file included from ../../brave/browser/brave_browser_main_parts.h:10:
02:01:47  ../../chrome/browser/chrome_browser_main.h:18:10: fatal error: 'chrome/common/buildflags.h' file not found
02:01:47  #include "chrome/common/buildflags.h"
02:01:47           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
02:01:47  1 error generated.
```

Will keep CI for Android and macOS, rebase and re-run CI

**Comment by AlexeyBarabash** [comment]
CI for Android succeeded
CI failed for macOS on init phase
```
07:50:53  Error: Command 'git -c core.quotePath=false diff --name-status 5bb0d577dd78472536480496ace115bc593ed0e1' returned non-zero exit status 128 in /Users/jenkins/jenkins/workspace/pr-brave-browser-android_sync_fix_10861/src/ios/third_party/motion_transitioning_objc/src
```
this is not caused by this PR

**Comment by AlexeyBarabash** [comment]
CI succeeded for Android, merged

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.14.10 x64 nightly build.
- Verified test plan form https://github.com/brave/brave-browser/issues/10856
- Verified no crash if device comes online when its trying to create sync chain and trying to get device id.

**Pull request merged**
