### PR TITLE
Stats dtoi and stats api key (uplift to 1.11.x)

### PR DESCRIPTION
**Pull request by keur**
Uplift of https://github.com/brave/brave-core/pull/5720, https://github.com/brave/brave-core/pull/5758, https://github.com/brave/brave-browser/pull/10225, https://github.com/brave/brave-core/pull/5823

Fixes https://github.com/brave/brave-browser/issues/10061, https://github.com/brave/brave-browser/issues/10130, https://github.com/brave/brave-browser/issues/9911, https://github.com/brave/brave-browser/issues/10230

Approved, please ensure that before merging:

 - [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
 - [x] You have tested your change on Nightly.
 - [x] The PR milestones match the branch they're landing to.

After you merge:
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by keur** [comment]
Request by @aekeus

**Comment by bsclifton** [comment]
Updated top post to call out:
- which PRs this is uplifting
- which issues are fixed by those PRs

Also:
- assigned @keur as owner
- assigned @brave/uplift-approvers as the approvers
- updated title to be similar to what the uplift tool does

**Comment by keur** [comment]
Failed on `test-install`. I think this is OK? cc @bsclifton

**Comment by kjozwiak** [comment]
> Failed on `test-install`. I think this is OK? cc @bsclifton

Failed `test-install` on `macOS` as per https://ci.brave.com/job/pr-brave-browser-uplift_stats_dtoi/4/execution/node/619/log/. Failure is a known intermittent issue and doesn't block uplift.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64 Catalina` using the following build:

```
Brave | 1.12.77 Chromium: 84.0.4147.68 (Official Build) nightly (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.15.5 (Build 19F101)
```

**`Test Case #1 - STR from:`** https://github.com/brave/brave-browser/issues/10061

Ensured that `dtoi=2020-07-07` on initial install as per the following:

```
https://laptop-updates.brave.com/1/usage/brave-core?platform=osx-bc&channel=nightly&version=1.12.72&daily=true&weekly=true&monthly=true&first=true&woi=2020-07-06&dtoi=2020-07-07&ref=BRV001
```

Screen Shot 2020-07-07 at 11 11 41 AM

Moved the MBP time ~14 days ahead and ensured that `dtoi=null` as per the following:

https://laptop-updates.brave.com/1/usage/brave-core?platform=osx-bc&channel=nightly&version=1.12.72&daily=true&weekly=true&monthly=false&first=false&woi=2020-07-06&dtoi=null&ref=BRV001

Screen Shot 2020-07-22 at 11 14 00 AM

**Pull request merged**
