### PR TITLE
Fixes issue with ads per day incorrectly limited to ads per hour

### PR DESCRIPTION
**Pull request by tmancey**
Resolves https://github.com/brave/brave-browser/issues/13215

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [x] New files have MPL-2.0 license header.
- [x] Adequate test coverage exists to prevent regressions
- [x] Major classes, functions and non-trivial code blocks are well-commented
- [x] Changes in component dependencies are properly reflected in `gn`
- [x] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [x] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

See https://github.com/brave/brave-browser/issues/13215

### CODE REVIEW

**Review by moritzhaller — APPROVED** [review]
LGTM!

**Comment by tmancey** [comment]
Unrelated CI failures

**Review by moritzhaller — APPROVED** [review]
migration path LGTM!

**Review by mihaiplesa — APPROVED** [review]

**Comment by kjozwiak** [comment]
Reproduced the original issue on `macOS 11.0.1` using the following build:

```
Brave | 1.20.33 Chromium: 88.0.4315.5 (Official Build) nightly (x86_64)
--- | ---
Revision | d2abe4588adaeb0d66aa0a0106675be1dff12c64-refs/branch-heads/4315@{#11}
OS | macOS Version 11.0.1 (Build 20B29)
```

Set `Maximum number of ads displayed` to `2` and went through the following:

* installed ` 1.20.33 CR: 88.0.4315.5` and viewed an ad (received without issues)
* waited ~30mins and viewed another ad without any issues
* waited ~30mins and never received an ad due to hitting the daily limit

Verification **PASSED** on `macOS 11.0.1` using the following build:

```
Brave | 1.20.36 Chromium: 88.0.4315.5 (Official Build) nightly (x86_64)
--- | ---
Revision | d2abe4588adaeb0d66aa0a0106675be1dff12c64-refs/branch-heads/4315@{#11}
OS | macOS Version 11.0.1 (Build 20B29)
```

Went through the same STR mentioned above and ensured that the third ad appears in the second hour.

**`Example`** | **`Example`**
---------------|----------------
Screen Shot 2020-12-17 at 2 40 17 AM | Screen Shot 2020-12-17 at 2 40 01 AM

**Comment by trankimtrong** [comment]
wTgJA4QMAgGKzjd

**Pull request merged**
