### PR TITLE
Non-referral downloads should use generic refcode

### PR DESCRIPTION
**Pull request by emerick**
Fixes brave/brave-browser#2547

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [x] Windows
  - [ ] macOS
  - [ ] Linux
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:

- Download a non-referral stub installer (i.e., no referral code embedded in its filename)
- Delete existing profile
- Run the installer
- After the installer completes, launch Brave and wait ~10 seconds
- Confirm that `Local State` file (e.g., `/c/Users/emerick/AppData/Local/BraveSoftware/Brave-Browser-Development/User Data/Local State`) contains `"promo_code":"BRV001"` entry
- Confirm with server team that daily ping for this run looked similar to this (in particular, `ref` is `BRV001`):

    `https://laptop-updates.brave.com/1/usage/brave-core?platform=winx64-bc&channel=release&version=0.64.4&daily=true&weekly=true&monthly=true&first=true&w oi=2019-03-11&ref=BRV001`

- Should also confirm that regular referral downloads continue to work as normal

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by emerick** [comment]
@bbondy Two things to note here:

1. The default referral code will revert to `none` 90 days after first run, just like normal referral codes.
1. Since the referral code check is only performed on first run after install, pre-existing non-referral installations will continue to send `none`.

My reading of brave/brave-browser#2547 is that this is the expected/intended behavior, but if not please let me know!

**Comment by bbondy** [comment]
Yes reset after 90 days is expect. Thanks so much!

**Comment by diracdeltas** [comment]
if i'm not mistaken, this should be blocked on https://github.com/brave/vault-updater/issues/90 and also https://github.com/brave/internal/issues/542#issuecomment-473574540, the latter of which i am working on

**Comment by fmarier** [comment]
@diracdeltas said she will take care of reviewing this.

**Comment by diracdeltas** [comment]
looks good to go as soon as https://github.com/brave/vault-updater/issues/90 is closed

**Comment by ob857** [comment]
Well am quite interested to the breave\ non referral downloader code 1982. And that is goes, better for My own safety, we'll will give it a try and see how it goes, with spirit,  journey of my this BIGGEST Jon's, AF just shooting, to hondales. So for All users and Beret in tables finders, let's lead's theme the Brave Ideas, with the technology, 
motorvaive's Skiller's, GitHub Run theme's there's Skill's. Reason some how, maybe it's a ideas Change's to a better leading to the NEXT generation's Coming, So in this Case, for all of au, the reviews, let's give them a try, and always we back to GitHub's the technology's expertise Motorvaitv's Doctor's. So at the END, ONE LOVE, and We all in this toooooooogether.🙂☁️❤️😁🙃

**Pull request merged**
