### PR TITLE
Drop patch for channel_info_win.cc and use chromium_src instead

### PR DESCRIPTION
**Pull request by mariospr**
Similarly to what is already done for Mac and POSIX channels, we
can use a chromium_src override to have our modified version of
GetChannelName() available without requiring a patch, which can
be dropped.

Fixes https://github.com/brave/brave-browser/issues/14239

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)
- [ ] Requested a security/privacy review as needed

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

Load brave://settings/help and check proper channel string is et

### CODE REVIEW

**Comment by mariospr** [comment]
**Important note**: Being a patch for Windows, I was not able to test it locally, so I'm waiting for the bots to run

**Comment by mariospr** [comment]
@simonhong I'm adding you as an extra pair of eyes here as the original author of this code in https://github.com/brave/brave-core/pull/158, since it's unclear to me how to propose a test plan to make sure things continue to work as expected after this cleanup change. 

PTAL and feel free to update the "Test Plan" section if needed, thanks!

**Comment by simonhong** [comment]
@mariospr I added one more commit. I think just enabling `GOOGLE_CHROME_BRANDING` buildflags here seems sufficient.
WDYT? and added test plan.

**Comment by mariospr** [comment]
> @mariospr I added one more commit. I think just enabling GOOGLE_CHROME_BRANDING buildflags here seems sufficient.
WDYT? and added test plan.

@simonhong I thought that the other day but I was hesitant to rely on Chrome branding for that... but now I look into your patch (which defines and also undefines it right after applying) I do think it's the right way to go, thanks!

**Review by simonhong — APPROVED** [review]

**Comment by mariospr** [comment]
@mkarolin PTAL when you have a moment on behalf of patch-reviewers, thanks!

**Review by mkarolin — APPROVED** [review]
++

**Comment by mariospr** [comment]
The failure in the post-init CI bot is unrelated to this PR and the one in the mac bot can't be related either because **this is a Windows-specific change** :innocent: , so merging now. Thanks

**Pull request merged**
