### PR TITLE
allow first party subdomains when blocking 3rd-party cookies to match… (uplift to 1.8.x)

### PR DESCRIPTION
**Pull request by bsclifton**
Uplift of https://github.com/brave/brave-core/pull/5318
Fixes https://github.com/brave/brave-browser/issues/9337

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by bsclifton** [comment]
Passed on all platforms except [Windows](https://ci.brave.com/job/brave-browser-build-pr/job/issue-9337-1.8.x/1/execution/node/239/log/)- due to a `depot_tools` issue that hit a few other PRs. Should be fixed by https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/fef5cf8e227b8c515bb320f7b2cf5e270ed5263f

Going to restart for Windows only...

**Comment by bsclifton** [comment]
Last build timed out - restarted 😄

**Comment by bsclifton** [comment]
[CI finished successfully](https://ci.brave.com/job/brave-browser-build-pr/job/issue-9337-1.8.x/2/flowGraphTable/) - the last run did hit a Jenkins timeout as it was finishing and uploading binaries to S3. Good to go - ready for approval/consideration

**Comment by kjozwiak** [comment]
QA verified https://github.com/brave/brave-core/pull/5318 on Nightly via desktop as per https://github.com/brave/brave-core/pull/5318#issuecomment-619634723.

However, it doesn't appear to be fixed on Android as per https://github.com/brave/brave-core/pull/5318#issuecomment-619679544, https://github.com/brave/brave-core/pull/5318#issuecomment-619711110 and https://github.com/brave/brave-core/pull/5318#issuecomment-619899524. The Android issue will be addressed in another issue once @jumde takes a look and creates the issue.

**Pull request merged**
