### PR TITLE
Improve Android first run experience for better retention

### PR DESCRIPTION
**Pull request by mherrmann**
Resolves https://github.com/brave/brave-browser/issues/41203
Resolves https://github.com/brave/brave-browser/issues/41205
Resolves https://github.com/brave/brave-browser/issues/41204

The implementation is hidden behind default-disabled Griffin flag `BraveDayZeroExperiment`, so can be A/B-tested.

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
If day zero feature is enabled,
- We are forcing `Set default browser` system dialog on first page of onboarding
- We are showing an onboarding page to `add search widget`

**Test 1**

1. Run brave with clean profile and apply adb shell "echo ' --enable-features=BraveDayZeroExperiment:variant/a' > /data/local/tmp/brave-test-day-zero-expt"
2. Open brave
3. Observe `Set default browser` system dialog shows up on first page of onboarding
4. Observe an onboarding page to `add search widget`

**Test 2**

1. Run brave with clean profile and apply adb shell "echo ' --enable-features=BraveDayZeroExperiment:variant/b' > /data/local/tmp/brave-test-day-zero-expt"
2. Observe `Set default browser` system dialog or `add search widget` onboarding should not be shown.

### CODE REVIEW

**Review by mkarolin — APPROVED** [review]
`strings`++, but please let the Android team review the java changes.

**Comment by SergeyZhukovsky** [comment]
I don't see any griffin flags that were mentioned
`The implementation is hidden behind default-disabled Griffin flags AndroidForceDefaultBrowserPrompt and AndroidOnboardingOfferSearchWidget, so can be A/B-tested.`

**Comment by mherrmann** [comment]
Sorry @SergeyZhukovsky, I changed the flag to `BraveDayZeroExperiment` following the discussion on Slack. I'll update the PR description.

**Review by iefremov — APPROVED** [review]

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 15` using the following build(s):

```
Brave | 1.73.76 Chromium: 131.0.6778.24 (Official Build) canary (64-bit)
--- | ---
Revision | fa36788bc0d6c1c87cacd28f8508e0403b0d8a2f
OS | Android 15; Build/AP41.240925.009; 35; REL
```

### `Test Case #1`

* connected the `Pixel 6` to the `Ubuntu 24.04 x64` VM and ran the following command via the terminal
  * `adb shell "echo '--enable-features=BraveDayZeroExperiment:variant/a' > /data/local/tmp/brave-test-day-zero-expt"`



* launched `Brave` and ensured that `Set default browser` system dialog is displayed right after Brave has launched
  * ensured that selecting `Brave` as the default worked without any issues
  * ensured that selecting other browsers other than `Brave` as the default worked without any issues
  * ensured that selecting `Cancel` worked without any issues and left the current browser as the default
* ensured that `Add search widget` onboarding modal is being displayed right after the `Set default browser` system dialog
  * ensured that tapping on `Now now` dismisses the modal without initiating the `Add Widget` modal
  * ensured that tapping on `Add to home screen` initiates the widget modal
     * ensured that clicking on `Cancel` closes the modal and you can continue onboarding via the `diagnostic/P3A` modal
     * ensured that clicking on `Add to home screen` adds the `Brave` widget to the `Home` screen without any issues
     * ensured that touching/holding lets you drag/drop the `Brave` widget to the `Home` screen without any issues
* ensured that the `Diagnostic` & `P3A` modals work as before (this hasn't been modified/touched)

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|-----------------
 |  |  | 

https://github.com/user-attachments/assets/a146ba97-2bdc-42d6-b17a-91e8fbcc6afd

**Pull request merged**
