### PR TITLE
Make ConnectHW screen working for both Trezor/Ledger devices 

### PR DESCRIPTION
**Pull request by spylogsster**
Resolves https://github.com/brave/brave-browser/issues/19495
Resolves https://github.com/brave/brave-browser/issues/19485

- Added screen to Ledger/Trezor messages and transaction signing operations
- Added cancel event to keyrings to reset state and close popups if user rejected operation
- Reworked statuses indication for ConfirmationView
- Added Ledger device disconnect detection and update the panel status accordingly
- Added new status to open correct app:
image

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

- Sign transactions and messages by Ledger/Trezor
- Make sure it shows connect HW screen with correct statuses
- Disconnect, connect, device in different state during transaction confirmation, all statuses should be visible on screen
- Try to enable not Ethereum Apps on Ledger device, the panel should detect it and ask to enable Ethereum app

### CODE REVIEW

**Comment by onyb** [comment]
Seeing a regression while testing this branch. For Ledger, when the hardware wallet is not connected, the connect screen only appears momentarily and then we fallback to the main screen. The expected behaviour is that the connect screen should stay open until:
- transaction is approved
- transaction is rejected
- user clicks on the "Cancel" button in the connect screen.

https://user-images.githubusercontent.com/3684187/142819531-f671466c-1412-498e-82c7-104e9d9169a5.mov

**Comment by spylogsster** [comment]
> Seeing a regression while testing this branch. For Ledger, when the hardware wallet is not connected, the connect screen only appears momentarily and then we fallback to the main screen. The expected behaviour is that the connect screen should stay open until:
> 
> * transaction is approved
> * transaction is rejected
> * user clicks on the "Cancel" button in the connect screen.
> 
>  Screen.Recording.2021-11-22.at.12.47.09.PM.mov

already fixed. please recheck with new updates

**Review by onyb — APPROVED** [review]
Approving this PR, but there are some remaining issues that should be fixed in a subsequent PR. Until then, I suggest holding off uplift to release.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.34.41 Chromium: 96.0.4664.45 (Official Build) nightly (arm64)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified able to Sign transactions and messages by Ledger and Trezor
- Verified Ledger throws error when trying to connect without enabling Ethereum app 
- Encountered https://github.com/brave/brave-browser/issues/19757 and https://github.com/brave/brave-browser/issues/19793

**Pull request merged**
