### PR TITLE
[Beta 1.32.x] Backport a patch that fixes an a18y Spoken Content crash.

### PR DESCRIPTION
**Pull request by iefremov**
Resolves https://github.com/brave/brave-browser/issues/19230

See https://source.chromium.org/chromium/chromium/src/+/155091ea3c05a67cf724208034d9f1130858c58c

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by iefremov** [comment]
We already have it in master

**Review by goodov — APPROVED** [review]

**Comment by LaurenWags** [comment]
`continuous-integration/macos/pr-head` failed due to https://bravesoftware.slack.com/archives/CA5FPHWLF/p1636120850082300. Per replies in that thread, this failure is being fixed separately and does not block uplift. See https://bravesoftware.slack.com/archives/CA5FPHWLF/p1636121974083100?thread_ts=1636120850.082300&cid=CA5FPHWLF.

However, since the fix is in Chromium 96 and 1.32.x branch will be getting Chromium 96 uplifted, it seems possible that this PR is not needed. Discussed with @iefremov.  cc @kjozwiak

**Comment by kjozwiak** [comment]
> `continuous-integration/macos/pr-head` failed due to https://bravesoftware.slack.com/archives/CA5FPHWLF/p1636120850082300. Per replies in that thread, this failure is being fixed separately and does not block uplift. See https://bravesoftware.slack.com/archives/CA5FPHWLF/p1636121974083100?thread_ts=1636120850.082300&cid=CA5FPHWLF.
> 
> However, since the fix is in Chromium 96 and 1.32.x branch will be getting Chromium 96 uplifted, it seems possible that this PR is not needed. Discussed with @iefremov. cc @kjozwiak

yup, lets wait till https://github.com/brave/brave-core/pull/10888 & https://github.com/brave/brave-browser/pull/19235 are uplifted into `1.32.x`. Once we get an RC for `1.32.x`, we'll double check https://github.com/brave/brave-browser/issues/19230 and see if it's fixed. If the crash is still reproducible, we'll get this uplifted.

Adding `PR/Blocked` for now until we get a `1.32.x`  RC build.

**Comment by LaurenWags** [comment]
Looks like the crash doesn't reproduce on the below 1.32.x version for me, @stephendonner could you check as well?

```
Brave | 1.32.97 Chromium: 96.0.4664.35 (Official Build) (x86_64)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | macOS Version 11.6.1 (Build 20G224)
```

Could not reproduce using the scenarios from https://github.com/brave/brave-browser/issues/19230#issuecomment-960953923 and https://github.com/brave/brave-browser/issues/19230#issuecomment-961285259.

**Comment by stephendonner** [comment]
I also cannot reproduce the crash using https://github.com/brave/brave-browser/issues/19230#issuecomment-960953923 or https://github.com/brave/brave-browser/issues/19230#issuecomment-961285259 on build:

Brave | 1.32.97 Chromium: 96.0.4664.35 (Official Build) (x86_64)
-- | --
Revision | 8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}
OS | macOS Version 11.6.1 (Build 20G224)

Screen Shot 2021-11-10 at 8 18 03 AM

**Comment by kjozwiak** [comment]
Thanks for the check @LaurenWags & @stephendonner. Going to close this off as it looks like uplifting C96 into `1.32.x` resolved the issue so there's no need to cherry pick this into `1.32.x` 👍

**Comment by iefremov** [comment]
Thanks @kjozwiak !

**Pull request closed without merging**
