### PR TITLE
Remove dapp detection for calendar.brave.com and nytimes.com

### PR DESCRIPTION
**Pull request by bbondy**
The dapp detection script will be removed in the future, but for now we just want to uplift some false positives so it doesn't appear.

Resolves https://github.com/brave/brave-browser/issues/12709

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by marshall — APPROVED** [review]
looks good, just two clarification questions:

- should we allow for more than just www subdomain on nytimes?
- is `action.url` guaranteed to be validly formed at this stage? IOW, can `new URL(action.url)` potentially throw an exception if it's invalid?

**Comment by bbondy** [comment]
> should we allow for more than just www subdomain on nytimes?

I don't think so, the report came in as www.nytimes.com

> is action.url guaranteed to be validly formed at this stage? IOW, can new URL(action.url) potentially throw an exception if it's invalid?

I believe so but I'll add a try/catch just in case

**Comment by ryanml** [comment]
FWIW when I was debugging I did see it come up once on https://cooking.nytimes.com/, re: subdomain check

**Review by ryanml — APPROVED** [review]

**Review by marshall — APPROVED** [review]

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.20.13 Chromium: 87.0.4280.88 (Official Build) nightly (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2009 (Build 19042.630)
```

**`Test Case 1:`** - https://github.com/brave/brave-browser/issues/12942

* ensured that dApp detection was occurring under GCal when upgrading to `1.20.13 CR: 87.0.4280.88`
* ensured that dApp detection was occurring under GCal on a clean install
  * ensured that  dApp detection was occurring while using `GCa`l,` Gmail`, `GDrive` & `Photos`

**Pull request merged**
