### PR TITLE
Remove left-over "Theme" content from welcome screen

### PR DESCRIPTION
**Pull request by bsclifton**
"Theme" screen was originally added with https://github.com/brave/brave-core/pull/2909

Fixes https://github.com/brave/brave-browser/issues/7461

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
N/A

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by simonhong** [comment]
It would be good to delete also the related extension apis like `brave.theme.setBraveThemeType` and `dark_mode::SetBraveDarkModeType(const std::string&)`.

**Comment by bsclifton** [comment]
> It would be good to delete also the related extension apis like `brave.theme.setBraveThemeType` and `dark_mode::SetBraveDarkModeType(const std::string&)`.

Those might still be used by the appearance page- I'll check on that

**Comment by simonhong** [comment]
> > It would be good to delete also the related extension apis like `brave.theme.setBraveThemeType` and `dark_mode::SetBraveDarkModeType(const std::string&)`.
> 
> Those might still be used by the appearance page- I'll check on that

I think left as-is would be better than deleting.
appearance handler doesn't use it for setting/getting brave theme type, instead custom message handlers are used.
I think re-reuse this extension apis at there instead of using message handler.
I can  do this  cleanup later.

**Comment by bsclifton** [comment]
Only failed on optional `test-install` (macOS) step; should be good to go! 😄👍 
https://ci.brave.com/job/brave-browser-build-pr/job/bsc-remove-welcome-theme/1/execution/node/706/log/

**Pull request merged**
