### PR TITLE
Fixes ad rewards not updated at brave://rewards due to loss of precision

### PR DESCRIPTION
**Pull request by tmancey**
Resolves https://github.com/brave/brave-browser/issues/15801

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

See https://github.com/brave/brave-browser/issues/15801

### CODE REVIEW

**Review by evq — APPROVED** [review]
seems reasonable, we should definitely follow up with a larger fix for https://github.com/brave/brave-browser/issues/15833 and the equivalent issue on ads serve

**Comment by tmancey** [comment]
CI failed due to known reasons

**Review by moritzhaller — APPROVED** [review]
LGTM (as per screen share)

**Review by jsecretan — APPROVED** [review]

**Comment by tmancey** [comment]
Linux failed due to known JUnit test failures

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.27.8 Chromium: 91.0.4472.70 (Official Build) nightly (64-bit)
--- | ---
Revision | fe095368270a32c92959403754bf6fd357dd9953-refs/branch-heads/4472@{#1172}
OS | Windows 10 OS Version 2009 (Build 19042.964)
```

* ensured that the STR/Cases outlined via https://github.com/brave/brave-browser/issues/15801#issue-890449648 worked as expected and the correct message was logged via the terminal

```
[25364:8148:0521/171916.656:VERBOSE1:ad_rewards.cc(268)] OnGetPayments
[25364:8148:0521/171916.656:VERBOSE6:ad_rewards.cc(270)] URL Response:
  URL: https://ads-serve.brave.com/v1/confirmation/payment/c45a4098-c774-47b5-89a5-c453201c60a3
  Response Status Code: 200
  Response: [{"balance":"0","month":"2021-05","transactionCount":"0"}]
[25364:8148:0521/171916.657:INFO:ad_rewards.cc(280)] Payment balance is not ready
```

**Pull request merged**
