### PR TITLE
Ran `npm audit fix` to fix open npm audit warnings

### PR DESCRIPTION
**Pull request by bsclifton**
Fixes https://github.com/brave/brave-browser/issues/9578
Related https://github.com/brave/brave-browser/pull/9608

## TODO list:
- [x] Review / merge https://github.com/brave/sync/pull/385
- [x] Review / merge https://github.com/brave/sync/pull/386
- [x] Update `DEPS` for `components/brave_sync/extension/brave-sync` to be SHA from https://github.com/brave/sync/pull/385
- [x] Remove `WIP: ` from this PR and https://github.com/brave/brave-browser/pull/9608 and have a clean CI run
- [x] Verify `npm run audit_deps` passes in CI 👍 

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
Note: this does have a SEMVER breaking change for `parse-domain`. Specifically, I ran `npm install parse-domain@3.0.1 --save`. See notes about here:
https://github.com/peerigon/parse-domain/blob/master/CHANGELOG.md#breaking-changes

I ran `npm run test-unit` and everything passed. I'm not sure if that is sufficient

**Comment by bsclifton** [comment]
Clean CI run taking place with https://ci.brave.com/job/pr-brave-browser-bsc-fix-npm-audit/3/console

**Comment by cezaraugusto** [comment]
Did a rebase since CI was failing. Had to replicate last commits since git seemed to lost the originals. Waiting CI before merge.

**Comment by bsclifton** [comment]
For some reason, Travis-CI is failing ☹️ It's passing locally- not sure what the problem is

**Comment by jumde** [comment]
@bsclifton - 

Try running these in `src/brave`:

```
- npm install parse-domain@3.0.1
- npm install --save-dev ts-jest@25.4.0
- npm update yargs-parser --depth 4
```

To resolve the travis security issues.

**Comment by bsclifton** [comment]
A few things:
- `init` failed on iOS; gotta restart for that
- There was one browser test failure [on Linux](https://ci.brave.com/job/pr-brave-browser-bsc-fix-npm-audit/13/execution/node/394/log/) and [macOS](https://ci.brave.com/job/pr-brave-browser-bsc-fix-npm-audit/13/execution/node/452/log/) which is intermittent; captured by https://github.com/brave/brave-browser/issues/5397
- Known [test-install issue]() on macOS captured by https://github.com/brave/brave-browser/issues/9480
- Windows ran into an issue with `create_dist`; I don't think this is related to this PR. https://ci.brave.com/job/pr-brave-browser-bsc-fix-npm-audit/13/execution/node/552/log/

**Comment by jumde** [comment]
iOS looks good: https://ci.brave.com/job/pr-brave-browser-bsc-fix-npm-audit/15/flowGraphTable/

**Pull request merged**
