### PR TITLE
Fixes duplicate/bad confirmations retry logic - 1.8.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/5260/files
Resolves https://github.com/brave/brave-browser/issues/9242

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
Looks like `init` is failing on `macOS` as per https://ci.brave.com/job/brave-browser-build-pr/job/issues%252F9242-1.8.x/6/execution/node/165/log/.

**Comment by bsclifton** [comment]
Ran into intermittent issue
```
15:39:27  ../../chrome/browser/themes/theme_properties.h:13:10: fatal error: 'chrome/common/buildflags.h' file not found
15:39:27  #include "chrome/common/buildflags.h"
15:39:27           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
15:39:27  1 error generated.
```

restarting

**Comment by bsclifton** [comment]
hmm running into issue during init
```
17:35:54  Error: Command 'git ls-tree HEAD third_party/libgav1/src' returned non-zero exit status 128 in /Users/jenkins/jenkins/workspace/owser-build-pr_issues_9242-1.8.x/src
17:35:54  fatal: not a tree object
```
https://ci.brave.com/job/brave-browser-build-pr/job/issues%252F9242-1.8.x/9/console

**Comment by kjozwiak** [comment]
QA verified https://github.com/brave/brave-core/pull/5260 as per https://github.com/brave/brave-core/pull/5260#issuecomment-615456746. This was also QA'd and released in `1.7.x` as per https://github.com/brave/brave-browser/issues/9242#issuecomment-616524957.

**Pull request merged**
