### PR TITLE
Add search onboarding exception for BR and AR

### PR DESCRIPTION
**Pull request by deeppandya**
Resolves https://github.com/brave/brave-browser/issues/26318

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by sujitacharya2005 — APPROVED** [review]
LGTM

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Review by tapanmodh — APPROVED** [review]
LGTM

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy S10+` running `Android 12` using the following build(s):

```
Brave | 1.47.46 Chromium: 107.0.5304.91 (Build oficial) canary (32 bits)
--- | ---
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Android 12; Build/SP1A.210812.016
```

### `BR (Brazil) locale` (new addition)

<details>
<summary>Onboarding remove (added into exception list)</summary>

* ensured that the default SE for `Normal` windows is set as `Brave`
* ensured that the default SE for `Private` windows is set as `Brave`
* ensured that tapping on the URL doesn't display the SE onboarding modal (need to tap on the URL on two occasions)

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|-----------------
Screenshot_20221104-152920_Settings | Screenshot_20221104-152048_Brave - Nightly | Screenshot_20221104-152052_Brave - Nightly | Screenshot_20221104-152057_Brave - Nightly

</details>

### `AR (Argentina) locale` (new addition)

<details>
<summary>Onboarding remove (added into exception list)</summary>

* ensured that the default SE for `Normal` windows is set as `Brave`
* ensured that the default SE for `Private` windows is set as `Brave`
* ensured that tapping on the URL doesn't display the SE onboarding modal (need to tap on the URL on two occasions)

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|-----------------
Screenshot_20221104-152936_Settings | Screenshot_20221104-153403_Brave - Nightly | Screenshot_20221104-153407_Brave - Nightly | Screenshot_20221104-153411_Brave - Nightly

</details>

### `FR (France) locale` (existing locale with Brave Search as default)

<details>
<summary>Onboarding remove (added into exception list)</summary>

* ensured that the default SE for `Normal` windows is set as `Brave`
* ensured that the default SE for `Private` windows is set as `Brave`
* ensured that tapping on the URL doesn't display the SE onboarding modal (need to tap on the URL on two occasions)

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|-----------------
Screenshot_20221104-153752_Settings | Screenshot_20221104-153843_Brave - Nightly | Screenshot_20221104-153847_Brave - Nightly | Screenshot_20221104-153851_Brave - Nightly

</details>

### `PL (Poland) locale` (doesn't have Brave Search as default)

<details>
<summary>Onboarding remove (added into exception list)</summary>

* ensured that the default SE for `Normal` windows is set as `Google`
* ensured that the default SE for `Private` windows is set as `Google`
* ensured that tapping on the URL on the second attempt displays the SE onboarding modal without issues
* ensured that `Google` is selected as the default SE via the onboarding modal
* ensured that both `Normal` & `Private` are updated correctly if another SE is selected from the onboarding modal

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|---------------
Screenshot_20221104-154430_Settings | Screenshot_20221104-152219_Brave - Nightly | Screenshot_20221104-152234_Brave - Nightly | Screenshot_20221104-152238_Brave - Nightly | Screenshot_20221104-152242_Brave - Nightly

*`Selecting another SE from the onboarding and ensuring Normal & Private windows were updated`*

**`Example`** | **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|---------------|------------------
Screenshot_20221104-154652_Brave - Nightly | Screenshot_20221104-154700_Brave - Nightly | Screenshot_20221104-154708_Brave - Nightly | Screenshot_20221104-154704_Brave - Nightly

</details>

### `RU (Russia) locale` (Yandex as the default SE)

<details>
<summary>Onboarding remove (added into exception list)</summary>

* ensured that the default SE for `Normal` windows is set as `Yandex`
* ensured that the default SE for `Private` windows is set as `Yandex`
* ensured that tapping on the URL on the second attempt displays the SE onboarding modal without issues
* ensured that `Google` is selected as the default SE via the onboarding modal
* ensured that both `Normal` & `Private` are updated correctly if another SE is selected from the onboarding modal

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|---------------
Screenshot_20221104-155058_Settings | Screenshot_20221104-155108_Brave - Nightly | Screenshot_20221104-155258_Brave - Nightly | Screenshot_20221104-155122_Brave - Nightly | Screenshot_20221104-155127_Brave - Nightly

*`Selecting another SE from the onboarding and ensuring Normal & Private windows were updated`*

**`Example`** | **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|---------------|------------------
Screenshot_20221104-155310_Brave - Nightly | Screenshot_20221104-155323_Brave - Nightly | Screenshot_20221104-155326_Brave - Nightly | Screenshot_20221104-155329_Brave - Nightly

</details>

**Pull request merged**
