### PR TITLE
Validate payload for ipfs onboarding page messages

### PR DESCRIPTION
**Pull request by spylogsster**
Resolves https://github.com/brave/brave-browser/issues/21234

- Added origin validation and some tests around it
- Moved all strings to constant resources and passing only numbers in messages

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

- Check that ipfs onboarding page works as expected without console errors

### CODE REVIEW

**Comment by diracdeltas** [comment]
as mentioned in https://bravesoftware.slack.com/archives/C7VLGSR55/p1645560425184459, https://github.com/brave/brave-core/blob/3b6920e5dee384b4624579ff283856d79c006cd0/components/ipfs/ipfs_onboarding_page.cc#L29-L31 should also specify the target origin instead of `*`. thanks!

**Comment by spylogsster** [comment]
> as mentioned in https://bravesoftware.slack.com/archives/C7VLGSR55/p1645560425184459,
> 
> https://github.com/brave/brave-core/blob/3b6920e5dee384b4624579ff283856d79c006cd0/components/ipfs/ipfs_onboarding_page.cc#L29-L31
> 
> should also specify the target origin instead of `*`. thanks!

as discussed in slack wrapped it to `if (window.location.href === ...) { window.postMessage(...) }` because we cannot pass origin for interstitial pages

**Review by diracdeltas — APPROVED** [review]
lgtm, thanks for doing this

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.37.73 Chromium: 99.0.4844.45 (Official Build) dev (x86_64)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | macOS Version 11.6.3 (Build 20G415)

### Steps:

Case 1: `Use a Brave local IPFS node`
1. install `1.37.73`
2. launch Brave
3. load `ipns://ipfs.io`
4. click on `Use a Brave local IPFS node`
5. wait for installation

example | example | example | example
---------|-----------|--------|---------
Screen Shot 2022-02-24 at 1 47 23 PM | Screen Shot 2022-02-24 at 1 47 26 PM | Screen Shot 2022-02-24 at 1 47 28 PM | Screen Shot 2022-02-24 at 1 47 42 PM



Confirmed it loaded `ipns://ipfs.io`

Case 2: `Use a public gateway`
1. install `1.37.73`
2. launch Brave
3. load `ipns://io`
4. click on `Use a public gateway`

Confirm it loaded `https://ipfs-io.ipns.dweb.link/` via public gateway

example | example
---------|---------
Screen Shot 2022-02-24 at 1 47 23 PM | Screen Shot 2022-02-24 at 1 46 31 PM

**Pull request merged**
