### PR TITLE
Fixes inline tip for twitter

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resovles https://github.com/brave/brave-browser/issues/7324

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
- enable rewards
- go to twitter.com and log in
- go to one profile and click BAT icon
- make sure that publisher banner with correct data is displayed

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by diracdeltas** [comment]
The main security change seems to be this CSP modification, which lgtm: https://github.com/brave/brave-core/pull/4215/files#diff-5f09202371edf46a4198a0f0ae7adf5dR65

**Comment by diracdeltas** [comment]
Sorry closed the wrong thing

**Comment by NejcZdovc** [comment]
CI failed on `test-install` and windows as currently we don't have working windows CI

**Comment by bsclifton** [comment]
All passed except Windows; going to rebase the CI-generated `brave-browser` branch and then rebase this too, so it pulls in the fix by @mkarolin. Labels added to skip other platforms

**Comment by petemill** [comment]
@nejczdovc could you explain a little more about this change (ideally in the commit message which at the moment is a little too generic)?

I couldn't see why you moved the requests from content script to background script. This makes future greaselion conversion a little more tricky. Although not impossible since we were going to try to get background script support in greaselion.

**Comment by bsclifton** [comment]
Seems there was a signing error on Windows; but otherwise CI looks great:
https://ci.brave.com/job/brave-browser-build-pr/job/twitter-inline/4/execution/node/424/log/

**Pull request merged**
