### PR TITLE
Eliminate ANRs (uplift to 1.8.x)

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Uplift of #5299
Fixes https://github.com/brave/brave-browser/issues/9388

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
command `npm run init -- --target_os=android` failed with 
```
Cannot contact i-04305cf1703bed4f4: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@66ea35a1:i-04305cf1703bed4f4": Remote call on i-04305cf1703bed4f4 failed. The channel is closing down or has closed down
19:06:09  Could not connect to i-04305cf1703bed4f4 to send interrupt signal to process
```
restarting

**Comment by AlexeyBarabash** [comment]
I have it again
```
19:21:41  Cannot contact i-07ecc189919e0a356: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@31aae17:i-07ecc189919e0a356": Remote call on i-07ecc189919e0a356 failed. The channel is closing down or has closed down
19:26:50  Agent i-07ecc189919e0a356 was deleted; cancelling node body
19:26:50  Could not connect to i-07ecc189919e0a356 to send interrupt signal to process
```

**Comment by bsclifton** [comment]
@AlexeyBarabash did you get a chance to test on Nightly? Please let us know if it works 😄 (you can check the box in the template!)

**Comment by AlexeyBarabash** [comment]
@bsclifton 
I didn't do this yet, but now I am on it.

**Comment by AlexeyBarabash** [comment]
I have tested the changes on Nightly
https://github.com/brave/brave-core/pull/5299#issuecomment-619393582

**Pull request merged**
