### PR TITLE
Replace incognito marker svg file

### PR DESCRIPTION
**Pull request by simonhong**
Fix https://github.com/brave/brave-browser/issues/5368

This should be merged together with https://github.com/brave/brave-browser/pull/5671

Screen Shot 2020-01-23 at 11 23 10 AM
Screen Shot 2020-01-23 at 11 23 30 AM

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by rossmoody** [comment]
Cleaned up the SVG code a bit and removed the id attr. This one is worth a shot: 

```
<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g fill="none" fill-rule="evenodd">
    <path d="M8 0C3.578 0 0 3.578 0 8c0 4.422 3.578 8 8 8 4.422 0 8-3.578 8-8 0-4.422-3.578-8-8-8z" fill="#5F6368" fill-rule="nonzero"/>
    <path d="M2.212 7.54c.092.299.276 2.029.827 2.528.568.514 2.713.506 3.123.283.92-.498 1.292-2.107 1.454-2.812C7.708 7.14 8 7.14 8 7.14s.308 0 .4.4c.163.704.519 2.318 1.437 2.815.41.223 2.555.231 3.125-.282.55-.5.734-2.235.826-2.534.091-.299.551-.598.643-.698.092-.1.092-.498 0-.598-.184-.2-2.352-.377-4.686-.1-.466.055-.643.2-1.746.2-1.102 0-1.28-.145-1.745-.2-2.333-.277-4.501-.1-4.685.1-.092.1-.092.499 0 .599.092.1.551.399.643.698z" fill="#FFFFFF" fill-rule="nonzero"/>
  </g>
</svg>
```

**Comment by simonhong** [comment]
hmm, still got same result with latest one...

**Comment by simonhong** [comment]
I think I found why this new svg doesn't work.
this svg file is used as a mask image not for background image.
So, only circle is drawn captured at description.

@rebron, I think proper mask svg image is needed to show like below.
image who can help this?

**Comment by rebron** [comment]
@karenkliu @bradleyrichter Need some help here with the right svg image. We're getting a circle it looks like and not the whole icon.

**Comment by karenkliu** [comment]
@simonhong Is the circle part of the icon or do you only need the sunglasses part?

**Comment by simonhong** [comment]
@karenkliu I need both (circle part and sunglass)
Below is the css code where our mask svg file will be used.
```
  #incognito {
    -webkit-mask-image: url(images/incognito_marker.svg);
    background-color: var(--cr-secondary-text-color);
    bottom: 20px;
    height: 16px;
    position: absolute;
    right: 16px;
    width: 16px;
  }
```

**Comment by karenkliu** [comment]
@simonhong Okay, not sure exactly what you needed but here is the sunglasses SVG both with and without the circle background. I have minimized the SVG file and removed all masks; hopefully it will work now.
[sunglasses.zip](https://github.com/brave/brave-core/files/4100758/sunglasses.zip)

**Comment by simonhong** [comment]
CI all passed :)

**Pull request merged**
