### PR TITLE
[Dependency]: Bump Nala

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Changes https://github.com/brave/leo/compare/99fe83ce417b4dadc22e6c9989f8f52f9e39daa5...e26237f69ecb4885df6e5381b261b1f306511df6
- Update icons
- **[Breaking]:** Add event typings (this should only break if you weren't using an event properly)
- Conditionally render title row in Dialog
- Svelte 4
- Event type fixes
- Tooltip fixes
- [Button]: Custom color support (via `--leo-button-color`)

### CODE REVIEW

**Review by nullhook — APPROVED** [review]

**Review by kdenhartog — DISMISSED** [review]
LGTM - no additional transitive dependencies

**Review by fmarier — APPROVED** [review]

**Review by Douglashdaniel — APPROVED** [review]
++ Wallet Front-end

**Comment by fallaciousreasoning** [comment]
Blocked on https://github.com/brave/leo/pull/485

**Comment by fallaciousreasoning** [comment]
@kdenhartog transitive dependencies have changed now, as Nala has bumped Svelte & Storybook :/

**Comment by fallaciousreasoning** [comment]
@kdenhartog I've also added a new Babel transform, as Webpack4 was struggling with the output from the Svelte4 compiled :cry:

**Comment by fallaciousreasoning** [comment]
pinging @brave/js-deps-reviewers

**Review by kdenhartog — APPROVED** [review]
I took a look through the transitive dependencies being added with socket, and am generally fine with this. The supply chain risk seems to present the biggest concern, but most of them are related to semver/authors/etc with one library gaining shell access which is being used to update the browserlists db. I've reviewed the script running and it doesn't appear to present any issues in my opinion.

This combined with speaking with @fallaciousreasoning about the goal of this and we are thinking it might be possible to remove this dependency again once webpack is finished being bumped.

**Comment by fallaciousreasoning** [comment]
@kdenhartog - Webpack 5 landed, and I've removed the babel dependencies! Seems to work nicely.

**Pull request merged**
