### PR TITLE
Update DEPS for sync windows cp

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
fix https://github.com/brave/brave-browser/issues/1994

Sync PR https://github.com/brave/sync/pull/234 .

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Windows
  - [ ] macOS
  - [x] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
Ensure build succeeded

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
0.57.x https://github.com/brave/brave-core/commit/7bc45afe15792bf385041e451ef059fc40bfe8e3

**Comment by bsclifton** [comment]
@AlexeyBarabash I believe this also needs to get merged to `0.58.x` (since we created that branch when the code-freeze happened, last Tuesday)

**Comment by AlexeyBarabash** [comment]
@bsclifton , thanks, I just do build of 0.58.x branch with this change [3500/7000], wait it to complete and then will push to 0.58.x.

**Comment by bbondy** [comment]
Only one label for smallest place this is merged to, thanks!

**Pull request merged**
