### PR TITLE
Disable safebrowsing by default

### PR DESCRIPTION
**Pull request by rht**
## Submitter Checklist:

This is a subset of inox-patchset-0006 (see https://github.com/brave/brave-browser/issues/1431#issuecomment-442246164, https://github.com/Eloston/ungoogled-chromium/blob/master/patches/inox-patchset/0006-modify-default-prefs.patch#L207), which prevents from contacting google server for resolving potentially malicious urls.
See also https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#why-is-safe-browsing-disabled, https://github.com/Eloston/ungoogled-chromium/issues/50.

The risks stated above do not apply to brave-browser because the functionality is already covered by the built-in client-side [ad-block engine](https://github.com/brave/ad-block) (via https://github.com/brave/ad-block/blob/master/lists/malware.h), while ungoogled-chromium doesn't have uBlock Origin (with malware domains enabled) installed by default.

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by rht** [comment]
I tested that https://www.xn--bbox-vw5a.com/login is detected by the safe browsing, but passes through ad-block and uBlock Origin unscathed.

**Comment by srirambv** [comment]
Please link the issue which is closed by this PR Also please review the checklist in PR template and update it accordingly.

cc: @diracdeltas @tomlowenthal

**Comment by rht** [comment]
@srirambv the most relevant issue is https://github.com/brave/brave-browser/issues/864, which would require some time to be implemented. I think this PR is on deciding whether safe browsing is recommended in the default settings or not, at least until the long term solution via proxy has arrived.

**Comment by tomlowenthal** [comment]
I'm confused about what this change is trying to achieve. AFAIK, Brave (the browser) currently uses the Safe Browsing service via a Brave-(the-company)-operated proxy. Isn't this change just going to turn that off by default?

**Comment by rht** [comment]
Huh, I see, indeed that the endpoint is safebrowsing.brave.com [1]. On another note, then why is  https://github.com/brave/brave-browser/issues/864 fixed by https://github.com/brave/brave-browser/pull/865 by moving the Google API key to the proxy?

[1] https://github.com/brave/brave-browser/blob/14478b7ac9cdc9b18247249fd8b06f860cd1b2bc/lib/config.js#L40

**Comment by tomlowenthal** [comment]
The Brave proxy still makes requests to Google — for which we use Google-provided API keys. Those keys are not included in the browser. We don't say anything about Google in the settings page — only someone who recognizes Safe Browsing as being a Google service would make that leap. Our help content makes clear that Brave only connects to Brave for Safe Browsing: https://support.brave.com/hc/en-us/articles/360017989132-How-do-I-change-my-Privacy-Settings .  But a recent change to the settings layout broke the way that we link to help content inline.

**Pull request closed without merging**
