### PR TITLE
Cleanup untracked files from chrome/android/java/res 

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Resolves https://github.com/brave/brave-browser/issues/11011

Sometimes after switching branch or Chromium updates the Brave resources which are not longer needed are left in chrome/android/java/res . This causes build error `Error: Found files not listed in the sources list of the BUILD.gn target: ...` 

This PR removes untracked those files from `chrome/android/java/res` which were not copied there by Brave build script purpose.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
1. Create some files at paths, the content is not important:
```
brave-browser/src/chrome/android/java/res/xml/custom_dialog_preferences.xml
brave-browser/src/chrome/android/java/res/xml/background_video_playback_preference.xml
brave-browser/src/chrome/android/java/res/drawable/ic_new_tabs_in_customtabs.xml
brave-browser/src/chrome/android/java/res/drawable/ic_report.xml
```
2. Delete these files from your out directory to trigger resources re-build:
```
apks/*
obj/chrome/android/chrome_app_java_resources.resources/*
```
3. Run Android build
4. Ensure there is no error `Found files not listed in the sources list of the BUILD.gn target: ...`

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
This PR is a draft by 2 reasons

1. With this change rebuild time of untouched dir increases from 18 to 140 sec
2. I cannot reproduce the case of failure, so I cannot yet verify it helps actually

**Comment by AlexeyBarabash** [comment]
After updating `master` I run into the issue and verified the PR helps.

**Comment by AlexeyBarabash** [comment]
Closing as stale and useless.

**Comment by AlexeyBarabash** [comment]
People meet  this  issue again and again.
Maybe this can be improved, probably I can list resources in `brave` dir, then get list of untracked files  from `chrome` dir and then make smart deletion of leftovers instead of `git clean -f`.
Reopening as a draft.

**Review by bridiver — APPROVED** [review]

**Comment by AlexeyBarabash** [comment]
Post-init CI  is unstable. failed `audit_deps`, https://ci.brave.com/job/pr-brave-browser-fix_11011-post-init/1/execution/node/145/log/, not related to the PR.

**Review by mihaiplesa — APPROVED** [review]

**Pull request merged**
