### PR TITLE
Fixes site banner formatting for media publisher

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves https://github.com/brave/brave-browser/issues/1924

UI implementation: https://github.com/brave/brave-ui/pull/259
Native implementation: https://github.com/brave-intl/bat-native-ledger/pull/167

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
1.
- enable rewards
- go to brave.com
- click on bat logo and click donate
- make sure that you see brave.com written in the banner (favicon will not work yet)

2.
- enable rewards
- go to https://www.youtube.com/channel/UCFNTTISby1c_H-rm5Ww5rZg
- click on bat logo and click donate
- make sure that you see Brave written in the banner (favicon should work as well)

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by jasonrsadler** [comment]
@NejcZdovc please rebase

**Comment by NejcZdovc** [comment]
@jasonrsadler rebased

**Comment by jasonrsadler** [comment]
master (0.59.x): 467d06e

**Comment by NejcZdovc** [comment]
per @mandar-brave request adding uplift label

**Comment by kjozwiak** [comment]
Approved uplift to `0.57.x` after deliberating with @rebron.

**Pull request merged**
