### PR TITLE
Skip initialization of referral system for the default referral code

### PR DESCRIPTION
**Pull request by bsclifton**
Fixes https://github.com/brave/brave-browser/issues/14428

Security review here:
https://github.com/brave/security/issues/349

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [x] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [x] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
See https://github.com/brave/brave-core/pull/8103#issuecomment-788902175

### CODE REVIEW

**Review by emerick — APPROVED** [review]
LGTM

**Comment by jonathansampson** [comment]
# Test Plan

1. Close all Brave instances
2. Delete `%localappdata%/BraveSoftware`
3. Create empty text-file at `%localappdata%/BraveSoftware/Brave-Browser/User Data/promoCode`
4. Launch Brave

No call to https://laptop-updates.brave.com/promo/initialize/nonua should be observed.

**Review by jonathansampson — APPROVED** [review]

**Comment by bsclifton** [comment]
Updated approach after talking out with @aekeus and @jsecretan 😄 Much more simple

**Review by simonhong — APPROVED** [review]

**Comment by bsclifton** [comment]
Created security review - we'll need approval here before we can merge

**Review by keur — APPROVED** [review]
LGTM

**Comment by bsclifton** [comment]
Updated test plan to assume that this patch is included in the build 😄 Original steps by @jonathansampson help prove the code path works (without having this patch present)

**Review by emerick — APPROVED** [review]
LGTM

**Comment by stephendonner** [comment]
Verified `FIXED` on `nightly` using 

Brave | 1.23.14 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

Verified using `Charles Proxy` that I can no longer see the `referral_code:` `BRV001` section in a JSON blob under `initalize`, `nonua`, as I can, with release build `1.20.110`

| Before (`1.20.110`) | After (`1.23.13`) |
|:--------|-------:|
Screen Shot 2021-03-02 at 3 11 47 PM | Screen Shot 2021-03-02 at 4 25 00 PM

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 11` using the following build:

```
1.23.14 CR: 89.0.4389.72
```

* ensured that the `download_id` was removed/not present in `brave://local-state` via the referral header

**`1.21.71 CR: 89.0.4389.72 (not fixed)`** | **`1.23.14 CR: 89.0.4389.72 (fixed)`**
--------------------------------------------|-------------------------------------------
Screenshot_20210302-195311_Brave | Screenshot_20210302-195759_Brave - Nightly

**Pull request merged**
