### PR TITLE
Fixed extensions import

### PR DESCRIPTION
**Pull request by spylogsster**
Resolves https://github.com/brave/brave-browser/issues/27487

Extensions import was broken in new import UI, fixed it.

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

- steps from issue

### CODE REVIEW

**Comment by simonhong** [comment]
Could we delete this define https://github.com/brave/brave-core/blob/master/chromium_src/chrome/browser/ui/webui/settings/import_data_handler.cc#L9?
As we re-implement `StartImport()` at `BraveImportDataHandler`?

**Review by simonhong — APPROVED** [review]
++

**Comment by spylogsster** [comment]
> Could we delete this define https://github.com/brave/brave-core/blob/master/chromium_src/chrome/browser/ui/webui/settings/import_data_handler.cc#L9? As we re-implement `StartImport()` at `BraveImportDataHandler`?

follow up https://github.com/brave/brave-browser/issues/27515

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.48.97 Chromium: 109.0.5414.46 (Official Build) nightly (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 22H2 (Build 22621.963)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/27487#issue-1506421014,  ensured that extensions from `Chromium` based browsers can be imported into Brave without any issues as per the following:

* ensured that extensions installed by users via other browsers are being imported via `brave://welcome`
* ensured that extensions installed by users via other browsers are being imported via `brave://settings/importData`
* ensured that `cookies` are not being imported (for example, passwords)
* ensured that `Settings` are being imported without any issues
* ensured that all the extensions are being listed under `brave://extensions`

**Importing from `Chrome`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------|-----------------
chromeExtensions | braveChromeExtensions | braveChromeExtensionsImporting | braveChromeExtensions1 | braveChromeExtensions2

**Importing from `Edge`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------|-----------------
edgeExtensions | braveEdgeExtensions1 | braveEdgeExtensions2 | braveEdgeExtensions3 | braveEdgeExtensions4

**Pull request merged**
