### PR TITLE
Warmup Filecoin Ledger account before transaction (uplift to 1.43.x)

### PR DESCRIPTION
**Pull request by cypt4**
Uplift of #14767
Fixes https://github.com/brave/brave-browser/issues/24824
Also fixed showing of error dialogs when sign with filecoin HW acc.

Pre-approval checklist: 
- [x] You have tested your change on Nightly. 
- [ ] This contains text which needs to be translated. 
    - [ ] There are more than 7 days before the release. 
    - [ ] I've notified folks in #l10n on Slack that translations are needed. 
- [x] The PR milestones match the branch they are landing to. 

Pre-merge checklist: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 

Post-merge checklist: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Review by yrliou — APPROVED** [review]
++ for 1.43.x specific fix

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.43.81 Chromium: 104.0.5112.102 (Developer Build) (64-bit) 
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified able to submit transactions via Ledger for Filecoin
- Encountered [25012](https://github.com/brave/brave-browser/issues/25012)

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.43.x` approved 👍 QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/14805#issuecomment-1228806393.

**Pull request merged**
