### PR TITLE
Update rewards verified icon

### PR DESCRIPTION
**Pull request by sujitacharya2005**
Resolves https://github.com/brave/brave-browser/issues/28209

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
Screenshot_20230613_120524
Screenshot_20230613_120557
Screenshot_20230613_120631

### CODE REVIEW

**Review by tapanmodh — APPROVED** [review]
lgtm

**Comment by deeppandya** [comment]
@sujitacharya2005 we should also update BAT verified icon as well in this PR. CC @Miyayes

**Comment by Miyayes** [comment]
> @sujitacharya2005 we should also update BAT verified icon as well in this PR. CC @Miyayes

Yes, all places where the blue checkmark appear should be updated to the new icon.

**Comment by sujitacharya2005** [comment]
> @sujitacharya2005 we should also update BAT verified icon as well in this PR. CC @Miyayes

@deeppandya bat_verified icon is replaced with rewards_verified_tick_icon
Please let me know any other drawable or screen I have missed.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.55.3 Chromium: 115.0.5790.32 (Official Build) canary (64-bit)
--- | ---
Revision | f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS | Android 14; Build/UPB3.230519.008; 34; REL
```

Ensured that the verification icon was replaced using the STR/Cases from https://github.com/brave/brave-core/pull/18878#issue-1754156240 & https://github.com/brave/brave-browser/issues/28208#issuecomment-1571437872 as per the following:

### Rewards icon in the address bar & Panel

**`Example`** | **`Example`**
----------------|----------------
Screenshot_20230621-163912 | Screenshot_20230621-164532
Screenshot_20230621-163950 | Screenshot_20230621-164548
Screenshot_20230621-164224 | Screenshot_20230621-164607

### Rewards page via `brave://settings` (Tips/Monthly Tips)

**`Example`** | **`Example`**
----------------|----------------
Screenshot_20230621-164156 | Screenshot_20230621-164555

### Tipping Banner

**`Example`** | **`Example`**
----------------|----------------
Screenshot_20230621-164022 | Screenshot_20230621-164626
Screenshot_20230621-164852 | Screenshot_20230621-164829

**Pull request merged**
