### PR TITLE
NTP: Fix page crash as a result of changes in Binance API format

### PR DESCRIPTION
**Pull request by petemill**
Some strings changed to numbers.

Fix https://github.com/brave/brave-browser/issues/14778
Fix https://github.com/brave/brave-browser/issues/14782

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by emerick — APPROVED** [review]
LGTM

**Review by bbondy — APPROVED** [review]

**Comment by petemill** [comment]
CI still failing with unrelated errors, now:

```
[2021-03-18T23:20:24.563Z] In file included from ../../brave/browser/ui/tabs/brave_tab_strip_model.cc:10:

[2021-03-18T23:20:24.563Z] In file included from ../../brave/browser/ui/brave_browser_window.h:10:

[2021-03-18T23:20:24.563Z] In file included from ../../chrome/browser/ui/browser_window.h:19:

[2021-03-18T23:20:24.563Z] In file included from ../../chrome/browser/translate/chrome_translate_client.h:18:

[2021-03-18T23:20:24.563Z] In file included from ../../components/translate/content/browser/per_frame_content_translate_driver.h:13:

[2021-03-18T23:20:24.563Z] ../../components/services/language_detection/public/cpp/language_detection_service.h:8:10: fatal error: 'components/services/language_detection/public/mojom/language_detection.mojom.h' file not found

[2021-03-18T23:20:24.563Z] #include "components/services/language_detection/public/mojom/language_detection.mojom.h"

[2021-03-18T23:20:24.563Z]          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[2021-03-18T23:20:24.563Z] 1 error generated.
```

**Comment by petemill** [comment]
Pushed a fix for the browsertests

**Comment by bsclifton** [comment]
@petemill is this still required? I think Binance fixed on their side

**Comment by petemill** [comment]
Yes they reverted the feed format. However, I'm considering using part of this PR to harden the widget against crashing the whole NTP when it gets a value it doesn't understand (or more specifically when the NTP widget gets _no_ values as a result of no known data received by the API. Happy to close this and leave as a branch though, and make a separate related issue. We also need a few more issues about how these Widgets don't handle bad or missing data very well.

**Comment by bsclifton** [comment]
Definitely ++ on the handling logic better 😄 Maybe we can repurpose the original issue?

**Pull request closed without merging**
