### PR TITLE
Remove binance widget android

### PR DESCRIPTION
**Pull request by deeppandya**
Resolves https://github.com/brave/brave-browser/issues/19546

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by deeppandya** [comment]
i have all labels for CI, just to be sure.

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Comment by bsclifton** [comment]
Whoops - just needs a rebase; otherwise, looks G2G

**Review by bsclifton — APPROVED** [review]

**Comment by kjozwiak** [comment]
**`Test Case #1 - Clean Install/New User`**

* installed `1.35.4 Chromium: 96.0.4664.55`
* ensured that Binance isn't visible under widgets via NTP
* ensured that Binance isn't being listed under `Edit Stack` via NTP (should only be `Privacy Stats` & `Top Sites`)
* ensured that Binance isn't being listed under `Settings` -> `New Tab Page` -> `Widget Stack`

**`Example`** | **`Example`**
---------------|----------------
Screenshot_20211202-194101 | Screenshot_20211202-194106

**`Test Case #2 - Existing User (Binance not authenticated & Privacy stats set as active`**

* installed `1.34.34 Chromium: 96.0.4664.45` and left `Privacy stats` as the active widget
* upgraded to `1.35.4 Chromium: 96.0.4664.55`
* ensured that `Privacy stats` is still the default widget under NTP after upgrading
* ensured that Binance has been removed from the widget stack
* ensured that Binance has been removed from `Edit Stack` via NTP (should only be `Privacy Stats` & `Top Sites`)
* ensured that Binance isn't being listed under `Settings` -> `New Tab Page` -> `Widget Stack`

**`Test Case #3 - Existing User (Binance not authenticated & Top Sites set as active`**

* installed `1.34.34 Chromium: 96.0.4664.45` and set `Top Sites` as the active widget
* upgraded to `1.35.4 Chromium: 96.0.4664.55`
* ensured that `Top Sites` is still the default widget under NTP after upgrading
* ensured that Binance has been removed from the widget stack
* ensured that Binance has been removed from `Edit Stack` (should only be `Privacy Stats` & `Top Sites`)
* ensured that Binance isn't being listed under `Settings` -> `New Tab Page` -> `Widget Stack`

**`Test Case #4 - Existing User (Binance not authenticated set as the active widget`**

* installed `1.34.34 Chromium: 96.0.4664.45` and set `Binance` as the active widget
* upgraded to `1.35.4 Chromium: 96.0.4664.55`
* ensured that `Privacy Stats` is set as the default widget under NTP
* ensured that Binance has been removed from the widget stack
* ensured that Binance has been removed from `Edit Stack` (should only be `Privacy Stats` & `Top Sites`)
* ensured that Binance isn't being listed under `Settings` -> `New Tab Page` -> `Widget Stack`

**Comment by kjozwiak** [comment]
Went through the above cases but waiting on an answer re: the following:

* should we be removing the Binance widget if it's currently set as the active widget and the user is not logged in/authenticated
* should we be removing the Binance widget if a user has logged in/authenticated and the widget is not set as the active widget
* should we be removing the Binance widget if a user has logged in/authenticated and set Binance as the active widget

**Pull request merged**
