### PR TITLE
Revert "[Storybook]: Upgrade to version 8"

### PR DESCRIPTION
**Pull request by petemill**
Reverts brave/brave-core#24289 due to https://github.com/brave/brave-core/pull/24289#discussion_r1653357723

### CODE REVIEW

**Review by diracdeltas — APPROVED** [review]
approving as the sec issue is DoS and this is not worse than it was before the storybook8 ugprade

**Comment by diracdeltas** [comment]
@SocketSecurity ignore npm/ws@6.2.2

**Comment by petemill** [comment]
Holding off on merge as https://github.com/brave/brave-core/pull/24374 fixes the issue and might pass CI within a similar timeframe

**Comment by petemill** [comment]
Not necessary

**Pull request closed without merging**
