### PR TITLE
Onboarding v2 dp 1.13.x (uplift to 1.13.x)

### PR DESCRIPTION
**Pull request by deeppandya**
Uplift of #6234 

Approved, please ensure that before merging: 
- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [ ] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
@deeppandya mind taking a look at this? Looks like the following files have conflicts as per the above:

* `android/brave_java_resources.gni`
* `android/java/org/chromium/chrome/browser/BraveActivity.java`

**Comment by kjozwiak** [comment]
@deeppandya mind rebasing as as there's the following conflict?

* `browser/ui/android/strings/android_brave_strings.grd`

**Comment by deeppandya** [comment]
> @deeppandya mind fixing the following merge conflict?
> 
> * `browser/ui/android/strings/android_brave_strings.grd`

@kjozwiak it's done

**Review by srirambv — APPROVED** [review]
Uplift to 1.13.x approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
