### PR TITLE
Issue 2520: Proxy requests for default google components through componentupdater.brave.com

### PR DESCRIPTION
**Pull request by jumde**
fix https://github.com/brave/brave-browser/issues/2520

In 

https://github.com/brave/brave-core/blob/1a388e4eb359536813903d834e53611b739be826/chromium_src/components/component_updater/configurator_impl.cc#L9

we added a proxy to retract any user identifiable information for default google components. The change in `kUpdaterDefaultURL` was not propagated to `IsUpdaterURL` that handles update requests for Brave's Components. Updated the code to handle update requests for google components more cleanly.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:

1. Run brave
2. Navigate to `brave://components` and verify that CRLSet and Ads components are updated.
3. Browser <data-dir>/CertificateRevocation/ to verify that the CRLSet component is loaded correctly.
4. Navigate to `https://cnn.com` to check if the ads and trackers are being blocked as expected.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by simonhong** [comment]
I think this should be merged into 0.60.x also because https://github.com/brave/brave-core/pull/997 is also there.

**Comment by jumde** [comment]
There is no uplift keyword for 0.60. Waiting for that to be created.

**Comment by simonhong** [comment]
We can uplift to dev branch w/o approving.

**Comment by jumde** [comment]
master - 3428c54
0.60.x - 595299cf862b146e7f52e9f5d13757effe2ab36b

**Comment by bbondy** [comment]
Reverted in this PR: 
https://github.com/brave/brave-core/pull/1103

master (0.61.x): d596445ea720f6797a817c572e835fed9f5b6e2a
0.60.x: 8aa0e3e06383e9963bcb3d0be1d70b6536cc567e

I think the logic is wrong and cause problems because we are ignoring query params. Also I think we can simplify this a lot just by getting rid of brave_redirect=true on brave/go-update repo and using the proxy base URL instead.

I talked to @diracdeltas on the #brave-core channel and she helped decide that plan.

**Pull request merged**
