### PR TITLE
Storybook: Built out Swap Tab UI

### PR DESCRIPTION
**Pull request by Douglashdaniel**
## Description 
The attention for this PR is to build out the UI components for the `Swap` tab and implement in storybook.
The UI will be visible in the actual Wallet, but implementation will be wired up in a future PR.

1) Built out the UI components for the `Swap` tab.
2) Built a `Select Network` component that can be reused in the wallet panel.
3) Built a `Select Account` component that can be reused in the wallet panel.
4) Built a `Select Asset` component that can be reused in the wallet panel.
5) Built a `Input` component that can be reused between `Buy`, `Send` and `Swap`.

Resolves <https://github.com/brave/brave-browser/issues/15412>

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

https://user-images.githubusercontent.com/40611140/125876431-e8680efb-5e05-439b-ac8a-41f773893c8a.mov

### CODE REVIEW

**Comment by onyb** [comment]
Is it intended to display the "Expires in" when doing a "Market" swap?

**Comment by onyb** [comment]
A couple of remarks about asset selection:
* It seems that there's no unselected state for the asset, as we see in Uniswap.
    Screenshot 2021-07-16 at 01 17 55
* Can we prevent the possibility of having BAT-BAT swap, as seen in your recording? See how it works in Uniswap and ethereum-remote-client's Swap. The unselected state will come in handy here.

**Comment by Douglashdaniel** [comment]
> A couple of remarks about asset selection:
> 
> * It seems that there's no unselected state for the asset, as we see in Uniswap.
>   Screenshot 2021-07-16 at 01 17 55
> * Can we prevent the possibility of having BAT-BAT swap, as seen in your recording? See how it works in Uniswap and ethereum-remote-client's Swap. The unselected state will come in handy here.

Just added some logic to hide an already selected asset from either list. So now you wont be able to select the same asset! 
As far as the `Unselected State` I will need to get with James to talk it over and get a design for those UI changes. 😊

**Review by onyb — APPROVED** [review]
Looks great!

**Pull request merged**
