### PR TITLE
Search update 1.12.x (uplift to 1.12.x)

### PR DESCRIPTION
**Pull request by deeppandya**
Uplift of #6201 
Fixes https://github.com/brave/brave-browser/issues/10890

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by bsclifton** [comment]
Notes:
- Verified changes on Nightly 
    - It's been in Nightly for over 24 hours and we're seeing attributed queries come through
    - After train migration, it should be in Beta now too 👍 
    - I tested Desktop and Android
- On Android, 1.12 was slightly different than 1.13 - @deeppandya maybe you can help me verify that the patch we did worked well
- I tested this branch on 1.12 manually on Desktop (Windows). Besides the test steps working, all unit and browser tests pass 🎉

**Comment by deeppandya** [comment]
We need to have https://github.com/brave/brave-core/pull/6273 uplift for 1.12

**Comment by bsclifton** [comment]
@deeppandya can you cherry-pick that into here too?

**Comment by deeppandya** [comment]
> @deeppandya can you cherry-pick that into here too?

yeah so i was thinking the same. but wanted to check first. i will update this PR

**Comment by bsclifton** [comment]
Looks like there was a timeout on Windows; all other platforms passed just fine. Restarting for Windows only

**Comment by bsclifton** [comment]
Leaving skipped tags for other platforms; pinged @deeppandya about rebase of Android only file. We can resolve and let CI run for Android, then it's ready for approval 😄

**Comment by bsclifton** [comment]
Rebased! 😄👍

**Pull request merged**
