### PR TITLE
Disable distro check for linux builds to fix failing builds

### PR DESCRIPTION
**Pull request by bkero**
## Submitter Checklist:

- [X] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [X] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [X] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.

## Test Plan:
Run a linux build after committed. Test that the packages are installable on Trusty, Xenial, Jessie, Sid, F27.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions

### CODE REVIEW

**Comment by mbacchi** [comment]
I just remembered there's already a patch for this same file[1], are they applied serially and do we have other files with more than 1 patch in brave-core/patches?

[1]: https://github.com/brave/brave-core/blob/master/patches/chrome-installer-linux-BUILD.gn.patch

**Comment by bkero** [comment]
This includes the previous patch contents. The pattern that I see in brave-core/patches is that it is 1 patch file per in-repo file.

**Comment by bridiver** [comment]
it isn't necessary to patch for this. Anything in `declare_args` section can be overridden in our args.gn using config.js - `enable_distro_version_check`

**Comment by bridiver** [comment]
but why are we disabling this? Is there an issue it should be linked to that describes the problem?

**Comment by bridiver** [comment]
`Submitted a ticket for my issue if one did not already exist.` is checked, but I don't see a reference to a ticket or a `fix` comment in the commit

**Comment by bkero** [comment]
Referenced issue is https://github.com/brave/brave-browser/issues/305

**Comment by bridiver** [comment]
some of the errors from the issue look like real problems.
```
01:00:29 Dependency libcairo-gobject2 (>= 1.10.0) not satisfiable on distro Ubuntu 16.04 (Xenial) caused by binary brave
01:00:29 Dependency zlib1g (>= 1:1.1.4) not satisfiable on distro Ubuntu 16.04 (Xenial) caused by binary brave
```
sounds like these builds may have runtime errors on those platforms

**Comment by bkero** [comment]
I double-checked these, and packages are available for them.
For example, zlib1g on Trusty: https://packages.ubuntu.com/trusty/zlib1g
and libcairo-gobject2: https://packages.ubuntu.com/trusty/libcairo-gobject2

**Comment by bridiver** [comment]
they are available, but are they part of a minimal install? If not are we including them as required deps in our packages? If we are sure everything works correctly then we should probably update the list instead of turning off the check

**Comment by bkero** [comment]
Okay, I've adjusted the PACKAGE_FILTER in `src/chrome/installer/linux/debian/update_dist_package_versions.py` to include libz1g and libcairo-gobject2, regenerated the package list, and confirmed they were added.

Afterwards I ran the create_dist target again, and took a look at the resulting deb file:

```
$ dpkg-deb -I ../../../../out/Release/brave-amd64.deb
 new debian package, version 2.0.
 size 393769320 bytes: control archive=10408 bytes.
    1193 bytes,    13 lines      control              
   16961 bytes,   460 lines   *  postinst             #!/bin/sh
   12991 bytes,   344 lines   *  postrm               #!/bin/sh
    1364 bytes,    42 lines   *  prerm                #!/bin/sh
 Package: brave-browser
 Version: 67.0.3396.62-1
 Architecture: amd64
 Maintainer: Brave Software <support+laptop@brave.com>
 Installed-Size: 384722
 Pre-Depends: dpkg (>= 1.14.0)
 Depends: ca-certificates, fonts-liberation, libappindicator3-1, libasound2 (>= 1.0.16), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 1.12.4), libc6 (>= 2.14), libcairo-gobject2 (>= 1.10.0), libcairo2 (>= 1.6.0), libcups2 (>= 1.4.0), libdbus-1-3 (>= 1.2.14), libexpat1 (>= 2.0.1), libgcc1 (>= 1:3.0), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.31.8), libgtk-3-0 (>= 3.9.10), libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.22), libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libx11-6 (>= 2:1.4.99.1), libx11-xcb1, libxcb1 (>= 1.6), libxcomposite1 (>= 1:0.3-1), libxcursor1 (>> 1.1.2), libxdamage1 (>= 1:1.1), libxext6, libxfixes3 (>= 1:5.0), libxi6 (>= 2:1.2.99.4), libxrandr2 (>= 2:1.2.99.3), libxrender1, libxss1, libxtst6, lsb-release, wget, xdg-utils (>= 1.0.2), zlib1g (>= 1:1.1.4)
 Recommends: libu2f-udev
 Provides: www-browser
 Section: web
 Priority: optional
 Description: The web browser from Brave
  Browse faster by blocking ads and trackers that violate your privacy and cost you time and money.
```

So it seems updating this would be the way forward.

**Comment by bkero** [comment]
Closing in favor of patching the package list generation to include these new packages.

**Pull request closed without merging**
