### PR TITLE
Change payment token redemption timing 0.63.x Beta

### PR DESCRIPTION
**Pull request by tmancey**
Uplift for https://github.com/brave/brave-core/pull/2071
Fixes https://github.com/brave/brave-browser/issues/3659

### CODE REVIEW

**Comment by yrliou** [comment]
@tmancey You could see the PR builder has build error at https://staging.ci.brave.com/job/brave-browser-build-pr/job/issues%252F3659-0.63.x/2/execution/node/160/log/
I believe it's because https://github.com/brave/brave-core/commit/3de67e5e533ea80aeceb5b09818cf01d96268691#diff-3409657bf97c62b58b3422d998e0cbb8L175 is only in master and not in the dev for the json stuff in confirmations_impl.cc, I think you would have to revise your commit to make it work in 0.63.x in order to uplift.

**Comment by kjozwiak** [comment]
Will wait till the above concerns that were raised by @yrliou have been addressed before bringing up the following PR with the @brave/uplift-approvers team.

**Comment by tmancey** [comment]
@kjozwiak concerns addressed, thanks

**Comment by kjozwiak** [comment]
> @kjozwiak concerns addressed, thanks

@tmancey lets wait till `0.64.x` stabilizes a bit as we're having a bunch of issues building `0.64.x` right now. Once `0.64.x` stabilizes and we get new builds, let's make sure this is working before uplifting it into `0.63.x` as per the new process @bbondy implemented via https://github.com/brave/brave-browser/wiki/Uplifting-a-pull-request#uplift-templates.

**Comment by tmancey** [comment]
@kjozwiak I can confirm all works as expected in the latest Nightly build

**Comment by tmancey** [comment]
@kjozwiak I can confirm the failures are not to do with this PR, thanks

**Pull request merged**
