### PR TITLE
WebTorrent: Connect to WebRTC torrent peers

### PR DESCRIPTION
**Pull request by feross**
Fixes: https://github.com/brave/brave-browser/issues/5374 See that issue for rationale.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [x] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:

   1. Go to https://instant.io and drop any file onto the page to create a torrent and start seeding it
   2. Right click the "[Magnet URI]" link and "Copy Link Address" to the clipboard
   3. Open a new tab and navigate to the copied magnet URI.
   4. Tell Brave to start torrenting.
   5. Confirm that file is downloaded by Brave (from the https://instant.io tab)

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by diracdeltas** [comment]
Does this respect webrtc IP handling policies set in either shields or in the global settings (https://support.brave.com/hc/en-us/articles/360017989132-How-do-I-change-my-Privacy-Settings-#webrtc)? i would assume so but just double checking

**Comment by diracdeltas** [comment]
Just as a reminder, webtorrent doesn't work in private tabs and in regular tabs, we show this warning:

```
Privacy Warning: When you click "Start Torrent" Brave will begin downloading pieces of the torrent file from other users and uploading to them in turn. This action will share that you're downloading this file. Others may be able to see what you're downloading and/or determine your public IP address.
```

i don't think the addition of webrtc peers make would make this warning any worse?

**Comment by feross** [comment]
> Just as a reminder, webtorrent doesn't work in private tabs and in regular tabs

Yep, not an issue.

> i don't think the addition of webrtc peers make would make this warning any worse?

Yep, it shouldn't introduce any additional privacy risk. Peers that you connect to will know what you're torrenting, as usual. But since WebRTC is E2E encrypted, the situation is slightly better than for unencrypted TCP connections.

> Does this respect webrtc IP handling policies set in either the global fingerprinting protection setting or in the global webrtc setting

At the moment, it doesn't seem to respect the global WebRTC setting. I changed the setting to 'Default public interface only' and confirmed that https://www.expressvpn.com/webrtc-leak-test doesn't show the local IP address anymore. But the WebTorrent extension continues to be able to access local IP addresses.

Are we sure that the user's WebRTC setting is being applied to Chrome extension background pages?

**Comment by diracdeltas** [comment]
> Are we sure that the user's WebRTC setting is being applied to Chrome extension background pages?

I don't think we ever tested this. cc @yrliou 

> I changed the setting to 'Default public interface only' and confirmed that https://www.expressvpn.com/webrtc-leak-test doesn't show the local IP address anymore. But the WebTorrent extension continues to be able to access local IP addresses.

@feross did you test this with 'Disable non-proxied UDP' by chance?

**Comment by feross** [comment]
> @feross did you test this with 'Disable non-proxied UDP' by chance?

I just tested with 'Disable non-proxied UDP' and the chrome extension can see my local IP address. Now I wonder if this applies to all chrome extensions or just the webtorrent one.

Side note: I don't fully understand the intent of 'Disable non-proxied UDP'. It seems to disable ICE candidate gathering entirely, but I thought the goal was just to disable UDP when the proxy server that is in use does not support UDP.

**Comment by diracdeltas** [comment]
I (not strongly) feel that this should be blocked on making sure that the global webrtc setting is respected by extensions. cc @yrliou

**Comment by bsclifton** [comment]
Closing as stale

**Pull request closed without merging**
