### PR TITLE
[Shortcuts]: Enable shortcuts by default (#18856) (uplift to 1.56.x)

### PR DESCRIPTION
**Pull request by emerick**
Uplift of https://github.com/brave/brave-core/pull/18856

### CODE REVIEW

**Comment by fallaciousreasoning** [comment]
Hey, I think let's hold of landing this until https://github.com/brave/brave-core/pull/19285 is merged/uplifted

**Comment by kjozwiak** [comment]
> Hey, I think let's hold of landing this until #19285 is merged/uplifted

Thanks @fallaciousreasoning 👍 As discussed with @rebron, going to hold off merging this until `1.56.x` goes out. We'll get the above into the `1.56.x` maintenance release.

**Comment by fallaciousreasoning** [comment]
The uplifts this depends on are:
- https://github.com/brave/brave-core/pull/19326
- https://github.com/brave/brave-core/pull/19323

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.56.x` approved 👍 QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/18856#issuecomment-1640981727.

**Pull request merged**
