### PR TITLE
uplift group policy for tor to 0.73.x(#3692)

### PR DESCRIPTION
**Pull request by simonhong**
Uplift of https://github.com/brave/brave-core/pull/3692

Should be merged with https://github.com/brave/brave-browser/pull/6830 together.

Issue: https://github.com/brave/brave-browser/issues/454
Issue: https://github.com/brave/brave-browser/issues/6044

Approved, please ensure that before merging: 
- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [ ] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by mihaiplesa** [comment]
Has passed for Android, Linux, Windows so applied skip labels and will need to be re-built only on iOS and macOS (unless no new changes pushed).

**Comment by kjozwiak** [comment]
Restarting `macOS` due to both https://ci.brave.com/job/brave-browser-build-pr/job/PR-6830/6/execution/node/469/log/ and https://ci.brave.com/job/brave-browser-build-pr/job/PR-6830/6/execution/node/486/log/ failing.

**Comment by kjozwiak** [comment]
@simonhong mind taking a look at these? Looks like it the PR's on `macOS` failed again at the same exact spot as https://github.com/brave/brave-core/pull/3919#issuecomment-552227257.

**Comment by simonhong** [comment]
@kjozwiak Hmm, rebuilding with clean repo had a same issue. Re-trying after rebasing onto latest `0.73.x` branch.

**Comment by simonhong** [comment]
CI spent more than 5 hours for build phase. and aborted before finishing it.

**Pull request closed without merging**
