### PR TITLE
Merge pull request #2076 from brave/sync_show_wrong_time_info

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Show error about wrong time on sync init

Uplift of #2076.

Works fine on Nightly.

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
Closing for now.
Will reopen after https://github.com/brave/brave-core/pull/2191 will be merged to Nightly and updating DEPS and string.

**Comment by AlexeyBarabash** [comment]
Re-opening, as going to fix strings, DEPS and rebase by  force-push.

**Comment by AlexeyBarabash** [comment]
CI failed because of lint error on vendor/bat-native-ledger/*

**Comment by rebron** [comment]
@AlexeyBarabash Can you close out this pr. No longer valid as 63.x is out.

**Comment by AlexeyBarabash** [comment]
@rebron sure, thanks.

**Pull request closed without merging**
