### PR TITLE
Fix P3A submission delay

### PR DESCRIPTION
**Pull request by rillian**
In https://github.com/brave/brave-browser/issues/23147 we disabled P3A protobuf submission by returning early before submitting the network request in the old BraveP3AUploader. This meant that the completion callback was never called, triggering submission backoff.

This moves the completion callback logic to the new uploader, so a measurement is considered submitted if the json version has been delivered successfully, instead of the old protobuf version. Protobuf submission can then be disabled without issue.

We intend to remove the old protobuf uploader code entirely, but this is still blocked on confirmation that the p2a-json endpoint is working. Hopefully only a week or two away, but I wanted to address this before next week's migration date.

Resolves https://github.com/brave/brave-browser/issues/23754

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [x] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [x] New files have MPL-2.0 license header
- [x] Adequate test coverage exists to prevent regressions
- [x] Major classes, functions and non-trivial code blocks are well-commented
- [x] Changes in component dependencies are properly reflected in `gn`
- [x] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [x] Test plan is specified in PR before merging

## After-merge Checklist:

- [x] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [x] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

Same as https://github.com/brave/brave-core/pull/13539 but confirm P2A submission too, to be safe.

### CODE REVIEW

**Review by DJAndries — APPROVED** [review]
lgtm

**Comment by rillian** [comment]
NB reviewers: windows-x86 ci job keeps timing out. I don't think it's related to this patch. Other pipelines are green.

**Review by iefremov — APPROVED** [review]

**Comment by kjozwiak** [comment]
Merging as everything appears green on `CI` and the needed reviews have been completed. Merging so when we do channel migrations, this will be included in both `1.43.x` & `1.42.x`.

**Comment by GeetaSarvadnya** [comment]
Fixes https://github.com/brave/brave-browser/issues/23902

**Pull request merged**
