### PR TITLE
Fixes Niceware unit tests

### PR DESCRIPTION
**Pull request by jasonrsadler**
Fixes brave/brave-browser#2464

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:

Run `npm run test brave_unit_tests -- --filter="NicewarePartialUnitTests.*"` and verify passing status

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by jasonrsadler** [comment]
master (0.60.x): 4b4f969

**Comment by jasonrsadler** [comment]
@kjozwiak @rebron @srirambv Uplift request to 0.58.x to fix failing unit tests.

**Comment by kjozwiak** [comment]
@jasonrsadler uplift request for `0.58.x` approved after deliberating with @rebron. 👍Please make sure this lands into `0.59.x` before merging to `0.58.x`. Usually you would merge into `master` and `dev` before requesting uplift into `beta`.

Please make sure the correct labels are added/removed and the appropriate issue is moved to the correct milestone.

**Comment by jasonrsadler** [comment]
Thanks @kjozwiak. Done.

**Pull request merged**
