### PR TITLE
Revert "[WIP] Remove passkey entitlement"

### PR DESCRIPTION
**Pull request by emerick**
Resolves https://github.com/brave/brave-browser/issues/31258

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by goodov — APPROVED** [review]

**Review by mkarolin — APPROVED** [review]
++ pending QA testing

**Comment by LaurenWags** [comment]
Verification in progress with PR build from https://bravesoftware.slack.com/archives/CU5UXM3EC/p1687882211614169?thread_ts=1687009981.243379&cid=CU5UXM3EC:

```
Brave | 1.55.16 Chromium: 115.0.5790.40 (Official Build) (x86_64)
-- | --
Revision | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | macOS Version 13.4.1 (Build 22F82)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.55.18 Chromium: 115.0.5790.40 (Official Build) nightly (arm64)
-- | --
Revision | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | macOS Version 11.7.8 (Build 20G1351)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.55.14 Chromium: 115.0.5790.40 (Official Build) nightly (arm64) 
Revision	071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS	macOS Version 13.4.1 (Build 22F82)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 


...

**Binary used:** `https://build-artifacts.brave.com/test-brave-browser-build-macos-arm64/375/Brave-Browser-Nightly-arm64.dmg`

* confirmed able to launch build
* confirmed no errors on install/launch
* confirmed build is signed:
```
stephendonner@Stephens-MBP-3 ~ % spctl --assess --verbose /Applications/Brave\ Browser\ Nightly.app
/Applications/Brave Browser Nightly.app: accepted
source=Notarized Developer ID
```

Confirmed entitlement

```

stephendonner@Stephens-MBP-3 /Applications % codesign -d --entitlements - /Applications/Brave\ Browser\ Nightly.app
Executable=/Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly
��qq9<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.application-identifier</key>
	<string>KL8N8XSYF4.com.brave.Browser.nightly</string>
	<key>com.apple.developer.associated-domains.applinks.read-write</key>
	<true/>
	<key>com.apple.developer.networking.vpn.api</key>
	<array>
		<string>allow-vpn</string>
	</array>
	<key>com.apple.developer.web-browser.public-key-credential</key>
	<true/>
	<key>com.apple.security.device.audio-input</key>
	<true/>
	<key>com.apple.security.device.bluetooth</key>
	<true/>
	<key>com.apple.security.device.camera</key>
	<true/>
	<key>com.apple.security.device.print</key>
	<true/>
	<key>com.apple.security.device.usb</key>
	<true/>
	<key>com.apple.security.personal-information.location</key>
	<true/>
	<key>keychain-access-groups</key>
	<array>
		<string>KL8N8XSYF4.com.brave.Browser.nightly.devicetrust</string>
		<string>KL8N8XSYF4.com.brave.Browser.nightly.webauthn</string>
	</array>
</dict>
</plist>
stephendonner@Stephens-MBP-3 /Applications %

```

On a clean profile, I verified the following:

- brave://version loads
- each section under brave://settings loads and no errors are displayed in browser console
- tabs have the expected shape (it's slightly different from Chrome)
- clearing browser data on exit works as expected
- videos play properly on YouTube and that the media device toolbar button works correctly
- tab-muting works as expected (spot checked using audio icon on tab and the "Mute tab" and "Mute site" options from the right-click tab menu)
- spot check of vertical tabs (enabling/disabling
- able to join Rewards on fresh profile
- able to enable sidebar and select each of the options (Talk, Wallet, Bookmarks, Reading List)
- able to create a second profile
- private and Tor windows worked as expected
- websites loaded as expected
- able to open/load DevTools

Other items checked on a clean profile:
* cookies are retained on app relaunch
* `brave://components` does not show any errors
* can create bookmarks

Simulated an "upgrade" to PR build:

1. Installed 1.52.126 (`Nightly` Channel)
2. Populated a profile with tabs, windows, browsing data, rewards data, cookies, etc.
3. "upgraded" to PR build (`1.55.14` on `Nightly` channel)
4. Confirmed no errors on launch or while browsing
5. Confirmed expected data was retained after upgrade: tabs, windows, browsing data, Rewards data, cookies, stats, saved login info, Shield settings, etc.

**Comment by LaurenWags** [comment]
Verification in progress with CI build

```
Brave | 1.55.84 Chromium: 115.0.5790.56 (Official Build) nightly (x86_64)
-- | --
Revision | 5aab64d48fedf51a7663986e3ab5381ac3981486
OS | macOS Version 13.4.1 (Build 22F82)
```

**Comment by LaurenWags** [comment]
Verification in progress with CI build

```
Brave	1.55.84 Chromium: 115.0.5790.56 (Official Build) nightly (arm64) 
Revision	5aab64d48fedf51a7663986e3ab5381ac3981486
OS	macOS Version 13.4.1 (Build 22F82)
```

**Comment by stephendonner** [comment]
## Verification `PASSED` using 


```
...

```


...

**Binary used:**

`https://build-artifacts.brave.com/test-brave-browser-build-macos-x64/1012/Brave-Browser-x64.dmg`

* confirmed able to launch build
* confirmed no errors on install/launch
* confirmed build is signed:
```
stephendonner@Stephens-MBP ~ % spctl --assess --verbose /Applications/Brave\ Browser.app
/Applications/Brave Browser.app: accepted
source=Notarized Developer ID
```

Confirmed entitlement:

```
stephendonner@Stephens-MBP ~ % codesign -d --entitlements - /Applications/Brave\ Browser.app
Executable=/Applications/Brave Browser.app/Contents/MacOS/Brave Browser

...

```

On a clean profile, I verified the following:

- `brave://version` loads
- each section under brave://settings loads and no errors are displayed in browser console
- tabs have the expected shape (it's slightly different from Chrome)
- clearing browser data on exit works as expected
- videos play properly on YouTube and that the media device toolbar button works correctly
- tab-muting works as expected (spot checked using audio icon on tab and the "Mute tab" and "Mute site" options from the right-click tab menu)
- spot check of vertical tabs (enabling/disabling
- able to join Rewards on fresh profile
- able to enable sidebar and select each of the options (Talk, Wallet, Bookmarks, Reading List)
- able to create a second profile
- private and Tor windows worked as expected
- websites loaded as expected
- able to open/load DevTools

Other items checked on a clean profile:
* cookies are retained on app relaunch
* `brave://components` does not show any errors
* can create bookmarks

Simulated an "upgrade" to PR build:

1. Installed `1.52.129` (`Release` Channel)
2. Populated a profile with tabs, windows, browsing data, rewards data, cookies, etc.
3. "upgraded" to PR build (`1.55.84` on `Nightly` channel)
4. Confirmed no errors on launch or while browsing
5. Confirmed expected data was retained after upgrade: tabs, windows, browsing data, Rewards data, cookies, stats, saved login info, Shield settings, etc.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

Brave | 1.55.85 Chromium: 115.0.5790.56 (Official Build) nightly (arm64)
-- | --
Revision | ec8df437c76e6b5594372583e6dab78c03f4594c
OS | macOS Version 11.7.8 (Build 20G1351)

**Pull request merged**
