### PR TITLE
fix(wallet): prevent flicker in hardware wallet connect screen

### PR DESCRIPTION
**Pull request by onyb**
**What's new:**
1. The flicker issue after opening the Ethereum app of Ledger, has been resolved.
2. Removed "Cancel" button from the connect screen when transaction is being confirmed on the device. The only two permissible actions are Accept/Reject on the hardware wallet. This fixes https://github.com/brave/brave-browser/issues/19485 which has been already marked as closed, although I'm not sure it was fixed.

Continuation of https://github.com/brave/brave-core/pull/11152 (hence, uplifts to release and/or beta must also match).

Resolves https://github.com/brave/brave-browser/issues/19480.
Resolves https://github.com/brave/brave-browser/issues/19485.

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Demo

https://user-images.githubusercontent.com/3684187/143373489-637eb10e-bb67-4707-8566-b7dfa5fadf5c.mov

### CODE REVIEW

**Comment by spylogsster** [comment]
`cancelHardwareOperation` added in brave-browser#19485  to cancel transactions correctly and reset transport

**Review by spylogsster — APPROVED** [review]
LGTM

**Review by Douglashdaniel — APPROVED** [review]
Looks good!

**Comment by srirambv** [comment]
Verified PR on 1.34.46 but ran into https://github.com/brave/brave-browser/issues/19823 & https://github.com/brave/brave-browser/issues/19824

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.34.48 Chromium: 96.0.4664.45 (Official Build) nightly (x86_64 translated)
-- | --
Revision | `76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}`
OS | macOS Version 12.0.1 (Build 21A559)

- Verified when hardware wallet is connected there is no flickering 
- Verified when hardware wallet is connected, cancel button on connect hardware popup is disabled/not shown making it only possible to approve or reject the transaction via Ledger
- Verified connect hardware popup is dismissed when a transaction is approved or rejected via the hardware device

https://user-images.githubusercontent.com/17010094/144174761-2cd035a9-8947-4baf-84ed-64bb971d929c.mov

**Pull request merged**
