### PR TITLE
Panel fixes

### PR DESCRIPTION
**Pull request by NejcZdovc**
Fixes panel favicon
Fixes panel create wallet
Fixes on restart panel show
Fixes panel not clearing after a switch

Resolves https://github.com/brave/brave-browser/issues/1719
Resolves https://github.com/brave/brave-browser/issues/1792
Resolves https://github.com/brave/brave-browser/issues/1777
Resolves https://github.com/brave/brave-browser/issues/1660

Ledger implementation https://github.com/brave-intl/bat-native-ledger/pull/154

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
- go to one site
- click on BAT logo
- click join now
- make sure that you see publisher data of the site that you are currently on
- restart browser
- click on BAT logo
- make sure that you see publisher data of the site that you are currently on

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [x] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by jasonrsadler** [comment]
Getting a warning when creating wallet from OptIn screen:
`Button component not provided an onClick handler as a prop` (2 instances)

**Comment by NejcZdovc** [comment]
@jasonrsadler this is not related to this PR, but @ryanml fixed it in brave-ui, so is part of new version.

**Comment by NejcZdovc** [comment]
master 9ff9849
0.57.x 06b8446c
0.56.x 2a4bac46
0.55.x da82010a

**Comment by bbondy** [comment]
Changed merged label to 0.56.x since this won't appear in 0.55.x hotfix2.

**Pull request merged**
