### PR TITLE
Empty icons for cards flip operations

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Replaced the icons 
```
drawable-hdpi/logo_card_back.png
drawable-mdpi/logo_card_back.png
drawable-xhdpi/logo_card_back.png
```
with empty stubs without Chromium icons.

If we want to put the Brave icons, PR must be updated

Resolves https://github.com/brave/brave-browser/issues/9867

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

Use STR from https://github.com/brave/brave-browser/issues/9867

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
Here is how the updated build looks, no Chromium logo during flips:


https://user-images.githubusercontent.com/24739341/110244864-6c49c680-7f69-11eb-9961-b0275a084130.mp4

@jamesmudgett is that enough, or we must to put the Brave logo?
Note, that Chromium logo has a horizontal symmetry and Brave doesn't, so with the Brave logo animation will have either begin or stop frame in upside down position.

**Comment by deeppandya** [comment]
@AlexeyBarabash can we use vector images  instead of different .pngs?

**Comment by AlexeyBarabash** [comment]
> @AlexeyBarabash can we use vector images instead of different .pngs?

@deeppandya with our organisation of patching it is hard, pls see https://github.com/brave/brave-core/pull/8170/commits/e18cbcbb22cbe1c5ce11c68cfe45c62a14b0bde0 . Also I had to remove Chromium these pngs:
```
src$ git status chrome/android/java/res/drawable-hdpi/logo_card_back.png chrome/android/java/res/drawable-mdpi/logo_card_back.png chrome/android/java/res/drawable-xhdpi/logo_card_back.png 
HEAD detached at 89.0.4389.72
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    chrome/android/java/res/drawable-hdpi/logo_card_back.png
	deleted:    chrome/android/java/res/drawable-mdpi/logo_card_back.png
	deleted:    chrome/android/java/res/drawable-xhdpi/logo_card_back.png
```
, but patches were not generated by `npm run update_patches`

Otherwise Chromium fails the build with error it found resources not listed on `chrome_java_resources.gni`.

So the best still seems to use overwrite of png.

**Comment by jonathansampson** [comment]
Why not place a Brave logo in there instead of an empty graphic?

**Comment by jamesmudgett** [comment]
No need for additional graphic on flip.

**Review by jamesmudgett — APPROVED** [review]
Looks great, we don't need to keep this graphic element, adds extra bulk.

**Comment by AlexeyBarabash** [comment]
Rebased to latest master, post init CI failed on audit-deps, not related to the PR.

**Pull request merged**
