### PR TITLE
Updates countries for uphold promotion

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves https://github.com/brave/brave-browser/issues/12372

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`, `npm run gn_check`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [x] Added appropriate QA labels (`QA/Yes` or `QA/No`) to the associated issue
- [x] Added appropriate release note labels (`release-notes/include` or `release-notes/exclude`) to the associated issue
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
- set locale to one of the countries in the list and make sure that you see the promotion

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Review by emerick — APPROVED** [review]
LGTM

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.18.19 Chromium: 87.0.4280.27 (Official Build) nightly (x86_64)
-- | --
Revision | d8c1fe98de8d9c6bd46ebe8b0cc9d2b6bdccca1e-refs/branch-heads/4280@{#556}
OS | macOS Version 10.15.7 (Build 19H2)
```

* ensured that the equities uphold card wasn't being displayed when using `US`, CA` & `UA`
* ensured that the equities uphold card was being correctly dislayed when using `BA`, `CN`, `AR` & `VE`
* ensured that the equities uphold card is visible when refreshing/re-opening `brave://rewards`
* ensured that the equities uphold card is visible after restarting Brave several times
* ensured that clicking on `X` closes the promo and ensured that it's never visible again (refreshing/re-loading/restarting)
* ensured that clicking on the card opens a new tab and loads the following:
  * https://uphold.com/en/buy-fractional-shares/brave --> https://uphold.com/en/buy-fractional-shares
* Found https://github.com/brave/brave-browser/issues/12406 while running through the above cases

Countries without promo | Countries with promo
-------------------------|-------------------------
Screen Shot 2020-10-29 at 10 44 53 PM | Screen Shot 2020-10-29 at 11 01 35 PM

**Comment by kjozwiak** [comment]
@NejcZdovc @mandar-brave should https://uphold.com/en/buy-fractional-shares/brave be redirected to https://uphold.com/en/buy-fractional-shares? Right now it basically opens the above link using `/brave` and than redirects. Expected?

**Comment by NejcZdovc** [comment]
expected, this is fully controlled by uphold

**Comment by kjozwiak** [comment]
@NejcZdovc do we need to remove the `U.S` part from the card now that US was removed from the list of supported regions?

Screen Shot 2020-10-30 at 10 14 45 AM

CCing @LaurenWags

**Comment by NejcZdovc** [comment]
@kjozwiak nope all good, this is more meant as that you can trade with US companies

**Pull request merged**
