### PR TITLE
Fixes Firebase issues brave/brave-browser#10367   brave/brave-browser#9852

### PR DESCRIPTION
**Pull request by ryanbr**
Fixes issues with sites using firebaseapp,  brave/brave-browser#10367 and brave/brave-browser#9852

Probably affecting many other sites using firebase

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

Any questions let me know

### CODE REVIEW

**Comment by ryanbr** [comment]
Also affecting https://github.com/brave/brave-browser/issues/5075

**Comment by ryanbr** [comment]
Looks good @bridiver @pes10k ?

**Comment by pes10k** [comment]
Also, discussing with @bridiver if we should fold this into the google auth toggle.

**Comment by pes10k** [comment]
Closing this in favor of https://github.com/brave/brave-core/pull/5952

**Pull request closed without merging**
