### PR TITLE
Show unavailable message if user is in disconnected state

### PR DESCRIPTION
**Pull request by zenparsing**
Resolves https://github.com/brave/brave-browser/issues/20991

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Screenshots

Screen Shot 2022-05-17 at 5 11 29 PM
Screen Shot 2022-05-17 at 5 24 58 PM
Screen Shot 2022-05-17 at 5 25 10 PM
Screen Shot 2022-05-17 at 5 25 25 PM

## Test Plan

- Open browser with a fresh profile.
- Enable Rewards and verify with an external wallet provider.
- Invalidate the authentication tokens for the wallet provider.
  - For Uphold, this can be accomplished by visiting your account page, clicking the "3 dots" more menu, and selecting "Integrations". The integration for "Brave Browser" can then be removed.
- Visit the NPT and verify that "login" messaging appears.
- Open the Rewards panel and verify that "login" messaging appears.
- Visit the Rewards page and verify that "login" messaging appears.
- Verify that clicking on the login messaging box will take the user to the wallet provider authorization page.

### CODE REVIEW

**Comment by szilardszaloki** [comment]
@zenparsing Do we want to handle the case where `fetch balance` returns with an error?

**Comment by zenparsing** [comment]
@szilardszaloki We do, I'll mark this as a draft until that's been added.

**Review by szilardszaloki — APPROVED** [review]
LGTM

**Review by aguscruiz — APPROVED** [review]
Everything looks great!

**Comment by bsclifton** [comment]
Tested - my account might be different (since it's older?) but integrations showed for me here (instead of 3 dot menu):
image

**Pull request merged**
