### PR TITLE
Enable Widevine on Arm64 Linux

### PR DESCRIPTION
**Pull request by mherrmann**
Resolves https://github.com/brave/brave-browser/issues/28903

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by theofficialgman** [comment]
@mherrmann I do not think this fully resolves the issue.
Even with the enable_widevine argument set, `widevine.gni` will disable it if it is not x64 linux

refer to the patch in https://github.com/brave/brave-browser/issues/33081

**Comment by mherrmann** [comment]
Thanks @theofficialgman :) I'll check it out when I resume work on this issue.

**Comment by mherrmann** [comment]
I'm closing this PR because it contributes little and Widevine on Arm64 Linux will be harder than expected. See https://github.com/brave/brave-browser/issues/28903#issuecomment-1701436727.

**Comment by theofficialgman** [comment]
@mherrmann hi please re-open. I am happily using widevine on chromium on arm64 Linux as are hundreds of thousands of other people who are users of the distros who already have done the glitch and widevine patching necessary to the arm64 chromeOS widevine. 

Just an fyi, what you write about Netflix is no different on x86_64 linux.

We aren't asking for you to package widevine is you do not want to. We need the browser to just check for it if we provide it. Right now it does not and is impossible to use widevine on non-x64 Linux architectures even if we provide the necessary binaries.

**Comment by mherrmann** [comment]
@theofficialgman I only closed this PR. You can follow https://github.com/brave/brave-browser/issues/28903 for updates on the implementation.

**Comment by theofficialgman** [comment]
@mherrmann I gave you the final patch necessary already in a comment above. Just add it, re-open the PR, merge and you are done.

Better to match what other distros are doing (enabling and allowing for checking for widevine on all architecture) while not providing widevine themselves.

Not implementing this asap slows down development and adoption of widevine on non-x64 architectures as described above.

**Comment by theofficialgman** [comment]
Understood.

> I closed this draft PR because the first approach (automatic installation of Widevine) seems infeasible at the moment. Closing the PR does not mean we will abandon any work that helps Linux users on Arm64 play content with Widevine. Indeed, the issue you created and patch you attached look like a promising route for giving a Arm64 Linux users a way to watch protected content. But that work will not be performed in this PR. So this PR will remain closed. But there can be new PRs.

Just to add a bit of info on this. Yeah its pretty much out of the question for browsers to provide widevine for arm64 linux themself. Simply because there is no arm64 linux widevine available publicly. The only option we have is to extract the chromeOS arm64 widevine (eg: https://gist.github.com/teacupx/9393507ad6250429707f0318b04f1a3b?permalink_comment_id=4465275#gistcomment-4465275) and that is what I did and what raspi did as well. There are downsides to this, some of which have been stated already, with the main issue being that chromeOS is not GNU linux. bionic (chromeOS's libc implementation) has implemented `DT_RELR` without the `GLIBC_ABI_DT_RELR` symbol that GNU glibc added as a failsafe check. This causes an error on loading the library on modern GNU GLIBC and the current method has been to patch glibc to ignore this requirement if the binary name is libwidevine.

There are a couple of more functions that are missing that the chromeOS libwidevine binary requires (normally supplied by the chromeOS chrome binary) but those are easily supplied through another binary that we rename to libwidevine and have dynamically link to the original chromeOS libwidevine.

As for the non-4k pagefile support, thats only an issues for kernels that use non-4k pages (so on the desktop world, basically only Asahi linux)

**Comment by mherrmann** [comment]
Thank you for clarifying :) That's in much better detail what I roughly remembered from reading online.

**Comment by leifliddy** [comment]
Fedora aarch64 has a widevine installer package that works for Firefox and Chromium
The package contains a script -- and then you run the script to install widevine.
https://src.fedoraproject.org/rpms/widevine-installer/blob/rawhide/f/widevine-installer.spec

Perhaps someone could submit a PR to the upstream project to get Brave supported as well. 
https://github.com/AsahiLinux/widevine-installer

**Comment by theofficialgman** [comment]
> Fedora aarch64 has a widevine installer package that works for Firefox and Chromium The package contains a script -- and then you run the script to install widevine. https://src.fedoraproject.org/rpms/widevine-installer/blob/rawhide/f/widevine-installer.spec
> 
> Perhaps someone could submit a PR to the upstream project to get Brave supported as well. https://github.com/AsahiLinux/widevine-installer

this will not work for the targets that brave intends to support. it requires GLIBC 2.36+ (needs glibc support for SHT_RELR) which even the current ubuntu LTS does not have.

**Pull request closed without merging**
