### PR TITLE
Fixes upgrade from 0.63.x to 1.3.x AC switch OFF and wallet creation failed - 1.3.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/4449
Fixes https://github.com/brave/brave-browser/issues/7833

### CODE REVIEW

**Comment by kjozwiak** [comment]
Looks like `test-install` on `macOS` is the only failure as per https://ci.brave.com/job/brave-browser-build-pr/job/issues%252F7833-1.3.x/1/execution/node/698/log/:

```
if [ ${CHANNEL} = "release" ]; then CHANNEL_CAPITALIZED_SPACED=""; else CHANNEL_CAPITALIZED="$(tr '[:lower:]' '[:upper:]' <<< ${CHANNEL:0:1})${CHANNEL:1}"; fi if [ ${CHANNEL} = "release" ]; then BROWSER="Brave Browser"; else BROWSER="Brave Browser ${CHANNEL_CAPITALIZED}"; fi OUT_DIR="${WORKSPACE}/src/out/${BUILD_TYPE}" if [ ${SKIP_SIGNING} = true ] ; then hdiutil attach -nobrowse "${OUT_DIR}/unsigned_dmg/${BROWSER}.dmg" else hdiutil attach -nobrowse "${OUT_DIR}/${BROWSER}.dmg" fi sleep 10 open "/Volumes/${BROWSER}/${BROWSER}.app" sleep 10 pkill Brave VOLUME=$(diskutil list | grep "Brave Browser" | awk -F'MB ' '{ print $2 }') declare -a arr=($VOLUME) # loop through the above array to eject all volumes for i in "${arr[@]}" do diskutil unmountDisk force $i diskutil eject $i done
```

This is a known issue that's not due to this specific PR.

**Comment by bsclifton** [comment]
marked as `blocked` since we'll want to merge https://github.com/brave/brave-core/pull/4449 and check on Nightly 👍

**Comment by tmancey** [comment]
@kjozwiak

- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

**Comment by bsclifton** [comment]
marking as unblocked as this was verified on Nightly 🎉

**Pull request merged**
