### PR TITLE
Fix problem where HTTPSE toggle doesn't work (always upgrades)

### PR DESCRIPTION
**Pull request by bsclifton**
Fixes https://github.com/brave/brave-browser/issues/9099
Unfixes https://github.com/brave/brave-browser/issues/4381

Introduced via https://github.com/brave/brave-core/pull/4314

--------

Revert "Merge pull request #4537 from jonathanKingston/bug-4381"

This reverts commit 86bf5edd4b46caa2f843670164223d310126ed9e, reversing
changes made to affeac4c61e3f390313f0c2a6030b2e73a4381fb.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
It's possible the behavior described by https://github.com/brave/brave-browser/issues/4381 is preferred; if that's the case we can always un-revert this once we have a way to address the UI.

Problem being reported is that https upgrades still occur after turning shields off / turning off upgrades via toggle.

**Comment by bsclifton** [comment]
Used the [build-bisect.py](https://github.com/brave/brave-core/blob/master/script/build-bisect.py) script to find this. First build containing the problem was 1.6.35; 1.6.32 was OK

**Comment by fmarier** [comment]
> Introduced via #4314

Am I missing something or is this wrong?

It seems like this has nothing to do with DoH and you don't appear to be reverting that PR either.

**Comment by bsclifton** [comment]
oh shoot- sorry, I copy/pasted wrong one there :( Meant to link https://github.com/brave/brave-core/pull/4537

Per our Slack conversation, this is not actually a bug 😄 I'll go ahead and close this PR and we can leave notes in original issue

**Pull request closed without merging**
