### PR TITLE
Fixes text color of the download shelf buttons.

### PR DESCRIPTION
**Pull request by mkarolin**
Fixes brave/brave-browser#20210

Chromium 97 change that caused this regression:

https://chromium.googlesource.com/chromium/src/+/4f653fca62670389f2d13571d1f64ddc34b5d88c

commit 4f653fca62670389f2d13571d1f64ddc34b5d88c
Author: Allen Bauer <kylixrd@chromium.org>
Date:   Mon Oct 18 21:02:26 2021 +0000

    Remove HasCustomColor from DownloadShelfView code.

    This also pushes the calculation of the colors into the ThemeHelper. It will slightly change the themed color calculations while keeping the colors the same for non-themed cases.

    Provided ColorProvider color mapping and calculation recipes.

    Bug: 1056953

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by simonhong — APPROVED** [review]
++
One more: How about overriding `AddChromeColorMixer()` for these colors also?
When color provider is used in download shelf, I think this regression can be happened again.

**Comment by mkarolin** [comment]
Thanks @simonhong! Added `chromium_src/chrome/browser/ui/color/chrome_color_mixer.cc` override. PTAL.

**Review by simonhong — APPROVED** [review]
++ 👍🏼

**Review by goodov — APPROVED** [review]

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.4 Chromium: 97.0.4692.56 (Official Build) nightly (x86_64)
-- | --
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
OS | macOS Version 11.6.1 (Build 20G224)


example | example | example
---------|----------|---------
Screen Shot 2021-12-29 at 4 53 59 PM | Screen Shot 2021-12-29 at 4 54 02 PM | Screen Shot 2021-12-29 at 4 54 07 PM

**Pull request merged**
