### PR TITLE
[Brave News]: FeedV2 should provide notifications when new data is available

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Resolves https://github.com/brave/brave-browser/issues/34819

[Screencast from 2023-12-12 15-11-47.webm](https://github.com/brave/brave-core/assets/7678024/443df7e6-b5fb-4336-b175-17f43d645ee4)

Note: This button will only show up if
1. Feeds have changed
2. Data on the server has changed

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

1. Scroll down to the Brave News feed
2. Click the Customize button
3. Subscribe to a feed - after a short delay the `New content available` button should show up
4. Unsubscribe from the feed - the button should disappear again
5. Subscribe to the feed again
6. Close the customize dialog
7. Click the button - the feed should reload and the button should disappear.

### CODE REVIEW

**Review by mkarolin — APPROVED** [review]
`strings`++

**Review by simonhong — APPROVED** [review]
++ 👍🏼

**Comment by fallaciousreasoning** [comment]
Thanks @simonhong! It was a recent change which we can do now we have automatic button color derivation in Nala!

```tsx
import Button from '@brave/leo/react/button'
const YellowButton = styled(Button)`
    --leo-button-color: yellow;
`
```

I'm really happy with how it's working! I've got another PR with a Button update https://github.com/brave/brave-core/pull/21347 which does the refresh/customize ones now Martin has a design for them :smile:

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.63.39 Chromium: 120.0.6099.115 (Official Build) nightly (64-bit)
-- | --
Revision | bcae24a93be6f24374f957cf3f030a35e351fba3
OS | Windows 10 Version 22H2 (Build 19045.3803)
```

**Pull request merged**
