### PR TITLE
Update rewards panel behaviour dp 1.12.x (Uplift to 1.12.x)

### PR DESCRIPTION
**Pull request by deeppandya**
Uplift of #6378 

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by deeppandya** [comment]
Need to close this PR

**Comment by deeppandya** [comment]
@srirambv onboarding notification behaviour would be same as it would open the url on notification click. i didn't include it as the implementation is part of retention notification. so it would be covered in 1.13.

**Comment by deeppandya** [comment]
Uplift for https://github.com/brave/brave-core/pull/6395 is blocked until we merge this PR

**Comment by kjozwiak** [comment]
Looks like `Win x64` failed due to not being able to upload binaries into `S3` as per https://ci.brave.com/job/pr-brave-browser-update_rewards_panel_behaviour_dp_1.12.x-windows/2/execution/node/461/ and https://ci.brave.com/job/pr-brave-browser-update_rewards_panel_behaviour_dp_1.12.x-windows/2/execution/node/488/. However, this doesn't block uplift as it's not related to the specific PR.

Above changes only touch Android code which passed `CI` for Android so there's no reason to restart any other platforms.

**Pull request merged**
