### PR TITLE
Upgrade from Chromium 97 to Chromium 98 (uplift to 1.35.x).

### PR DESCRIPTION
**Pull request by mkarolin**
Fixes https://github.com/brave/brave-browser/issues/19664
Fixes https://github.com/brave/brave-browser/issues/20648
Uplift from #11223

Also uplifts the following:

**SKUs uplifts**

Fixes https://github.com/brave/brave-browser/issues/17614
Fixes https://github.com/brave/brave-browser/issues/17254
Uplift from #10847

Fixes https://github.com/brave/brave-browser/issues/20542
Uplift from #11878

Fixes https://github.com/brave/brave-browser/issues/20547
Uplift from #11887

Fixes https://github.com/brave/brave-browser/issues/20693
Uplift from #11992

Fixes https://github.com/brave/brave-browser/issues/19959
Uplift from #11461

**Cr98 follow-ups**

Fixes https://github.com/brave/brave-browser/issues/20696
Uplift from #12004

Fixes https://github.com/brave/brave-browser/issues/20686
Uplift from #11987

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### Verify SKU functionality is disable on allow-list domains
1. Visit https://account.brave.software and enter basic auth credentials (reach out to @bsclifton for details)
2. Open dev tools (F12, etc) and go to `Console` tab
3. Paste in: `await window.chrome.braveSkus.refresh_order('0ee1e3ee-afc3-4f2f-b2a2-3d1e401e1530')` and hit enter. It should show
    ```
    Uncaught TypeError: Cannot read properties of undefined (reading 'refresh_order')
    at <anonymous>:1:31
    ```
4. Steps 1-3 can be repeated on https://account.brave.com or https://account.bravesoftware.com

## Verify SKU functionality is disabled on non-allowed domains
1. Visit any non-Brave website
2. Open dev tools (F12, etc) and go to `Console` tab
3. Paste in: `await window.chrome.braveSkus.refresh_order('0ee1e3ee-afc3-4f2f-b2a2-3d1e401e1530')` and hit enter. It should show
    ```
    Uncaught TypeError: Cannot read properties of undefined (reading 'refresh_order')
    at <anonymous>:1:31
    ```

### CODE REVIEW

**Comment by mkarolin** [comment]
Rebased on 1.35.x.

**Comment by kjozwiak** [comment]
Added `CI/skip-android`, `CI/skip-linux` & `CI/skip-windows` as they've already passed so they don't get restarted when @mkarolin pushes a fix for `iOS` due to the following:

```
 ../../brave/ios/browser/skus/skus_sdk_factory_wrappers.mm:24:9: error: use of undeclared identifier 'SkusSkusServiceMojoImpl'
18:17:17        [[SkusSkusServiceMojoImpl alloc] initWithSkusService:std::move(service)];
18:17:17          ^
18:17:17  1 error generated.
```

**Comment by mkarolin** [comment]
Adding `CI/skip-macos` since it passed.

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.35.x` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
