### PR TITLE
Update audit_deps ignore list and add npm 7 compatibility

### PR DESCRIPTION
**Pull request by diracdeltas**
fix https://github.com/brave/brave-browser/issues/16080
remove entries that are no longer needed
make the results parser compatible with breaking changes in npm 7 for `npm audit --json`: https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

1. npm run audit_deps should pass
2. deleting any entry from https://github.com/brave/brave-core/pull/8928/files#diff-a69e633bdbae5d870abc8b9c5b0086be91e75569ea3526810d107598d6df478fR31 should make it fail

### CODE REVIEW

**Comment by diracdeltas** [comment]
this needs some changes because CI is still running npm 6

**Comment by wknapik** [comment]
npm 7 will not work with the project in general - ci is just following that requirement.

**Comment by diracdeltas** [comment]
> npm 7 will not work with the project in general - ci is just following that requirement.

this is npm 7 compatible now

**Comment by diracdeltas** [comment]
@wknapik @petemill @mihaiplesa this is passing CI now, please review

**Review by mihaiplesa — APPROVED** [review]

**Review by petemill — APPROVED** [review]
lgtm! Thanks for maintaining backwards compat with npm 6!

**Pull request merged**
