### PR TITLE
WebUI: Remove title for History page pre-load UI

### PR DESCRIPTION
**Pull request by petemill**
As requested by @bbondy , this is a quick fix to get a smoother transition on the Navigation Bar between pages. We would also like to visit a nicer solution via static HTML to encourage the renderer to 'cache' the UI layer across page navigations, though this likely won't happen between the different 'host' URL contexts of the different WebUIs.

Fix https://github.com/brave/brave-browser/issues/3826

This should be uplifted to wherever the Navigation Bar landed (https://github.com/brave/brave-core/pull/1422), which is 0.63.x

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
On https://github.com/brave/brave-browser/issues/3826

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by bbondy** [comment]
Thanks!

**Comment by bsclifton** [comment]
NOTE: will be pushing a rebase (testing locally) 😄

**Comment by bbondy** [comment]
dev will be updated after a day or two of bake time to 74 as well btw.

**Comment by petemill** [comment]
Closing in favor of #1909 which will achieve this goal via css

**Pull request closed without merging**
