### PR TITLE
Updated Improved Search Suggestions default value

### PR DESCRIPTION
**Pull request by simonhong**
fix https://github.com/brave/brave-browser/issues/29517

We'll turn it on when Brave Search is default provider in specific countries.
This PR doesn't change current value if user updated that option's value already.

In private(and tor) window, search suggestion doesn't work.
`SearchProvider` suggestions from a search engine and it blocks request for OTR profile.
```
bool SearchProvider::IsQuerySuitableForSuggest(bool* query_is_private) const {
  *query_is_private = IsQueryPotentiallyPrivate();

  // Don't run Suggest in incognito mode, if the engine doesn't support it, or
  // if the user has disabled it.  Also don't send potentially private data
  // to the default search provider.  (It's always okay to send explicit
  // keyword input to a keyword suggest server, if any.)
  const TemplateURL* default_url = providers_.GetDefaultProviderURL();
  const TemplateURL* keyword_url = providers_.GetKeywordProviderURL();
  return !client()->IsOffTheRecord() && client()->SearchSuggestEnabled() &&
         ((default_url && !default_url->suggestions_url().empty() &&
           !*query_is_private) ||
          (keyword_url && !keyword_url->suggestions_url().empty()));
}
```

Search suggestions option is moved to search engines section.
Screenshot 2023-04-24 at 11 36 10 AM

Resolves 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

`SearchEngineProviderServiceTest.DefaultSearchSuggestEnabledTest`

1. Set os country one of `"IN", "CA", "DE", "FR", "GB", "US", "AT", "ES", "MX", "BR", "AR"`
2. Launch with clean profile
3. Set Brave Search as default provider
4. Check Improve Search Suggestions option is turned on
5. Set Non Brave Search and check Search Suggestions are turned off

### CODE REVIEW

**Comment by simonhong** [comment]
@fmarier Can you check this PR needs another security review?

**Comment by fmarier** [comment]
Yes, let's file a sec/priv review for this since (I think) search suggestions involve sending keystrokes to the Brave Search server when something is typed in the URL bar.

**Comment by simonhong** [comment]
> Yes, let's file a sec/priv review for this since (I think) search suggestions involve sending keystrokes to the Brave Search server when something is typed in the URL bar.
> 
> In that sec review, please make sure to mention explicitly whether or not this affects private windows (and Tor windows).

@fmarier Filed https://github.com/brave/security/issues/1255 👍🏼

**Comment by simonhong** [comment]
@rebron @aguscruiz Moved `Improve search suggestions` option to search engines section like above screenshot.

**Comment by bsclifton** [comment]
Closing as stale. @simonhong I think you've been working with @rebron on this one- not sure if there's a newer version of the code. But please resubmit when it's ready. This one is out of date

**Pull request closed without merging**
