### PR TITLE
Drop imports for build/config/features.gni from buildflags.gni files

### PR DESCRIPTION
**Pull request by mariospr**
These imports are not strictly needed and can be the source of
dependency cycles if certain GN/GNI files get imported in some
ways, so we better remove them and eliminate that friction.

Additionally, this change implies that we need to explicitly add
an import for brave/components/decentralized_dns/buildflags in
brave/browser/profiles/BUILD.gn now, since that file needs the
definitions for decentralized_dns that were previously being
imported via brave/components/tor/buildflags/buildflags.gni:
```
brave/browser/profiles/BUILD.gn
└─> brave/components/tor/buildflags/buildflags.gni
     └─> build/config/features.gni
          └─> build/config/chrome_build.gni
               └─> brave/build/config/brave_build.gni
                    └─> brave/net/sources.gni
                         └─> brave/components/decentralized_dns/buildflags/buildflags.gni
```
... but now that build/config/features.gni is no longer being
imported from brave/components/tor/buildflags/buildflags.gni, we
need to explicitly add the import to brave/browser/profiles/BUILD.gn
or we'll get a new gn check failure.

Resolves brave/brave-browser#15171

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
After removing of all these lines
```
import("//build/config/features.gni")
```

how `//build/config/features.gni` is imported? I guess there is another imports path, but I don't understand, which is that.

**Comment by mariospr** [comment]
> how `//build/config/features.gni` is imported? I guess there is another imports path, but I don't understand, which is that.

They get imported anyway via the many `BUILd.gn` files that still include the `import()` statements (both upstream Chromium's and Brave's `BUILD.gn` files), note that this CL only removes that import from `buildflags.gni` files, but doesn't touch those other imports.

**Review by bridiver — APPROVED** [review]

**Comment by bridiver** [comment]
> After removing of all these lines
> 
> ```
> import("//build/config/features.gni")
> ```
> 
> how `//build/config/features.gni` is imported? I guess there is another imports path, but I don't understand, which is that.

It was never needed in the first place. I think this was likely a copy/paste issue where it was just added to files whether it was needed or not. It only contains
```proprietary_codecs = is_chrome_branded || is_chromecast

  # libudev usage. This currently only affects the content layer.
  use_udev = (is_linux || is_chromeos) && !is_chromecast

  use_dbus = (is_linux || is_chromeos) && !is_chromecast

  use_gio = is_linux && !is_chromecast```

**Review by AlexeyBarabash — APPROVED** [review]

**Comment by AlexeyBarabash** [comment]
I never had opened `//build/config/features.gni`, but by its name I was sure it contains accumulated list of features, so it is important

**Comment by mariospr** [comment]
Looks like I still need a code owner review: @iefremov @tmancey would you mind taking a quick look?

**Review by iefremov — APPROVED** [review]

**Review by tmancey — APPROVED** [review]
LGTM++

**Pull request merged**
