### PR TITLE
Show the QR code in Brave Rewards (brave://rewards)

### PR DESCRIPTION
**Pull request by bsclifton**
Fixes https://github.com/brave/brave-browser/issues/13159

----------

Revert "Merge pull request #7350 from brave/bsc-remove-qr-code"

This reverts commit 858ca76af10ebda54333034c50679510bc5066ca, reversing
changes made to ba5983c26181ddd05b4cce22d25cd1732a27c5e3.

Resolves 

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by emerick — APPROVED** [review]
LGTM

**Review by zenparsing — APPROVED** [review]

**Comment by bsclifton** [comment]
Partially blocked on https://github.com/brave-intl/bat-go/pull/611

**Comment by kjozwiak** [comment]
Restarting `macOS` as `build` failed as per https://ci.brave.com/job/pr-brave-browser-bsc-show-qr-code-macos/1/execution/node/207/log/.

```
02:42:05  FAILED: gen/chrome/browser/resources/extensions/extensions.rollup.js gen/chrome/browser/resources/extensions/build_manifest.json 
```

**Comment by bsclifton** [comment]
iOS failing is not related to this; created https://github.com/brave/brave-browser/issues/13210 to cover that

**Comment by kjozwiak** [comment]
awesome, thanks for getting this PR in good shape @bsclifton 👍 As soon as we're done with https://github.com/brave/internal/issues/739, we'll get it merged.

**Pull request merged**
