### PR TITLE
fix(wallet): Capitalize Ledger in Translation

### PR DESCRIPTION
**Pull request by Douglashdaniel**
## Description 
`Ledger` was missing capitalization in `<translation>` string

Wallet String: https://github.com/brave/brave-core/blob/master/components/resources/wallet_strings.grdp#L195
Translation String: https://github.com/brave/brave-core/blob/master/components/resources/strings/brave_components_resources_en-GB.xtb#L1013

Resolves <https://github.com/brave/brave-browser/issues/25616>

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
1. Connect Ledger
2. Initiate an import from Ledger account
3. Ledger should be `Capitalized`

Before:

image

After:

Screen Shot 2022-09-27 at 10 12 33 AM

### CODE REVIEW

**Review by mkarolin — COMMENTED** [review]
The .xtb files are replaced each time we pull the l10n files down from Transifex. I've updated the translation in Transifex here https://www.transifex.com/brave/brave_en/translate/#en_GB/$/433505757?q=key%3ABRAVE_WALLET_CONNECT_HARDWARE_AUTHORIZATION_NEEDED, so we should be good in the future.

Approving as a temporary fix.

**Review by mkarolin — APPROVED** [review]
++

**Comment by Douglashdaniel** [comment]
> 



> The .xtb files are replaced each time we pull the l10n files down from Transifex. I've updated the translation in Transifex here https://www.transifex.com/brave/brave_en/translate/#en_GB/$/433505757?q=key%3ABRAVE_WALLET_CONNECT_HARDWARE_AUTHORIZATION_NEEDED, so we should be good in the future.
> 
> Approving as a temporary fix.

Thank you @mkarolin!!

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.17 Chromium: 106.0.5249.65 (Official Build) nightly (64-bit) 
-- | --
Revision | `3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified Ledger is properly capitalized now
image

**Pull request merged**
