### PR TITLE
fix(22645): Toggle color fix for disable state

### PR DESCRIPTION
**Pull request by wadehrarshpreet**
Resolves 
https://github.com/brave/brave-browser/issues/22645

https://user-images.githubusercontent.com/15067013/170547626-7b16b8d2-8096-4c88-8f0d-9941ae261948.mov

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by wadehrarshpreet** [comment]
@yrliou can you review

**Comment by yrliou** [comment]
cc @bsclifton for finding the right person in desktop UI team to review this.

**Review by petemill — APPROVED** [review]
Thanks for the contribution!

**Comment by bsclifton** [comment]
Created https://github.com/brave/brave-core/pull/13510 so we can watch CI run 😄

**Comment by bsclifton** [comment]
@wadehrarshpreet ok we're seeing a linting error here:
```
[2022-05-27T23:15:51.105Z] /home/ubuntu/workspace/pr-brave-browser-fix-22645-linux/src/brave/components/brave_new_tab_ui/components/toggle/style.ts
[2022-05-27T23:15:51.105Z]   85:23  error  Missing space before =>  arrow-spacing
[2022-05-27T23:15:51.105Z]   86:51  error  Extra semicolon          @typescript-eslint/semi
[2022-05-27T23:15:51.105Z]   87:45  error  Extra semicolon          @typescript-eslint/semi
```

**Comment by wadehrarshpreet** [comment]
@bsclifton I ran the `eslint --fix` which fix the spacing & semicolon...but it made changes to whole file(part which I didn't touched)...so I just updated/fixed the part which I touched. Can you run the suite again.

**Comment by bsclifton** [comment]
Sorry for the delay here - just pushed this latest to https://github.com/brave/brave-core/pull/13510 so we can watch over the change 😄 If things look good, I'll squash + merge

**Comment by bsclifton** [comment]
OK - all CI passed in https://github.com/brave/brave-core/pull/13510; I'll get this squashed up and then we can merge 😄

**Review by bsclifton — APPROVED** [review]

**Pull request merged**
