### PR TITLE
Fixed: Exit IP address doesn't change in the Tor window.

### PR DESCRIPTION
**Pull request by boocmp**
Resolves https://github.com/brave/brave-browser/issues/35996

The commit that leads to this issue:
https://chromium-review.googlesource.com/c/chromium/src/+/5189272

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by iefremov — APPROVED** [review]
patching changes look ok

**Comment by iefremov** [comment]
@fmarier do you or someone else from the sec-team would want to take a look?

**Review by darkdh — COMMENTED** [review]
Can we have a unit test case like `ProxyChain.SerializeAndDeserialize` in `//services/network/public/cpp/network_param_mojom_traits_unittest.cc` but with username and password? This doesn't block this PR from being merged, it can be done as follow-up.

**Review by fmarier — APPROVED** [review]
I took a look at the changes and they look sensible to me. Given that the patching has been reviewed in details by @goodov and @iefremov and that @darkdh also had a look at the Tor-specific bits, this looks good to go.

**Comment by boocmp** [comment]
@darkdh 
I'll add the test in a separate PR.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.65.22 Chromium: 122.0.6261.57 (Official Build) nightly (64-bit)
-- | --
Revision | 65f8e6ca5faa2acddbc7a1fa6b871f3510688554
OS | Windows 11 Version 23H2 (Build 22631.3155)
```

1. Installed 1.65.22
2. launched Brave
3. visited https://check.torproject.org/ in Tor window
4. note down exit node IP address. Did a hard refresh (Ctrl+Shift+R/Cmd+Shift+R),
5. note down exit node IP address. Clicked New Tor connection for this site in app menu
6. verified rest of the Tor functionality working as expected
 
step 3 | step 4 | step 5
---- | ---- | ----
image|image|image

**Pull request merged**
