### PR TITLE
Update "Do not track" dialog text 

### PR DESCRIPTION
**Pull request by wadehrarshpreet**
Resolves
https://github.com/brave/brave-browser/issues/17177 

Updated Text Preview
Screenshot 2022-05-27 at 10 56 19 PM

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [x] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [x] New files have MPL-2.0 license header
- [x] Adequate test coverage exists to prevent regressions
- [x] Major classes, functions and non-trivial code blocks are well-commented
- [x] Changes in component dependencies are properly reflected in `gn`
- [x] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [x] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
* Run brave Browser
* Go to Settings > Privacy and security
* Click `Cookies and other site data`
* Select `Send a 'Do not Track' request...'
* Dialog text is updated

### CODE REVIEW

**Comment by wadehrarshpreet** [comment]
@bsclifton @petemill can you help in review?

**Comment by wadehrarshpreet** [comment]
@bsclifton

**Comment by bsclifton** [comment]
cc: @rebron on copy change

**Comment by bsclifton** [comment]
cc: @rmcfadden3 on copy

**Comment by rmcfadden3** [comment]
@bsclifton — overall this lgtm. I rewrote slightly to:

Do not track

Enabling “Do not track” means that a request to not be tracked will be included each time you browse to a new website. Any effect depends on whether the website responds to this request, and how it’s interpreted. For example, some websites may respond by only showing you ads that aren’t based on other sites you’ve visited. Even with this “Do not track” request in place, many websites will still collect and use your browsing data. Learn more.

- Note that, unless "Do Not Track" really needs to be in title case, we should shift to sentence case instead. (In rewrite above, I shifted to sentence case for both the notif header and in first sentence of the body copy.)

**Comment by wadehrarshpreet** [comment]
@rmcfadden3 I have updated the text. Please check.

**Review by rmcfadden3 — APPROVED** [review]
LGTM!

**Comment by rmcfadden3** [comment]
@wadehrarshpreet — just gave it the LGTM, but will defer to @bsclifton & @rebron on whether this is good to ship. (Not sure if sec team needs to review?)

**Comment by bsclifton** [comment]
Thanks for the copy edit @rmcfadden3! 😄 And thanks for your patience @wadehrarshpreet. I just gave this a rebase and I'll get a CI run happening so we can get this merged

**Comment by bsclifton** [comment]
OK created https://github.com/brave/brave-core/pull/13626 which we can watch over 👍

**Review by bsclifton — APPROVED** [review]

**Pull request merged**
