### PR TITLE
Only include Widevine Host Verification on official builds

### PR DESCRIPTION
**Pull request by bsclifton**
## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Needed or QA/No-QA-Needed) to include the closed issue in milestone 

## Test Plan:
1. Don't have a file at`src/third_party/widevine/scripts/signature_generator.py`
2. Run `npm run build` (not an official build)
3. Build should succeed

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by ryanml** [comment]
master: cf79da0150f1e19706c81d5881a14c34fd208d62
0.55.x: 6abdc6e04af4c361ffc3bb5e54d523f0558655a2
0.56.x: 753561a2231ebb94ea5f89c10636887a007117d1

**Comment by darkdh** [comment]
@bbondy @bsclifton we should really control `enable_cdm_host_verification` from brave-browser by override the value or passing the new arg to control it.
Because developers often need to build Release build and we can't expect them to have signing script

**Comment by bsclifton** [comment]
@darkdh doh - I think that was a miss on my part. Folks building release will have `official_build` set to true?

**Comment by darkdh** [comment]
yea, see https://github.com/brave/brave-browser/blob/5d9002808ad37a26f12e453c2d615985d8f8c50a/lib/config.js#L246

**Pull request merged**
