### PR TITLE
Fixed string for sync on device with wrong time

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
This is fix according the comment https://github.com/brave/brave-core/pull/2155#discussion_r272385955 
For issue https://github.com/brave/brave-browser/issues/3962 .

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues/3962) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [x] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests && npm run test-security`) on
  - [ ] Windows
  - [ ] macOS
  - [x] Linux
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:

1. Adjust computer time 20 minutes forward.
2. Create a sync chain
3. Actual result:
See error of `You might be having wrong system time or timezone setup on your device. Please setup the correct time and timezone`
Expected result:
See error of `Your computer's clock may be set to the wrong time or time zone. Check your clock settings.`

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
Screenshot from 2019-04-10 20-26-24

**Comment by AlexeyBarabash** [comment]
@brave/uplift-approvers , @bradleyrichter , @tomlowenthal  CI finally succeeded, so could please you review it?

**Comment by tomlowenthal** [comment]
The only thing I'd be reviewing is a text match. So that lg2m.

**Comment by bbondy** [comment]
`@brave/uplift-approvers` is only for PR's against Dev and Beta channels which are currently at `0.64.x` and `0.63.x`. Does this need to be uplifted to those too? 

Please merge.

**Comment by AlexeyBarabash** [comment]
Yes, once I will see it in nightly, I will update https://github.com/brave/brave-core/pull/2161 and https://github.com/brave/brave-core/pull/2155 with proper strings and DEPS for brave-sync.

Will not use `brave/uplift-approvers` for PRs agains master anymore.

**Comment by AlexeyBarabash** [comment]
This is already in Nightly:
image

**Pull request merged**
