### PR TITLE
WIP: Implement Tor profile based on incognito profile

### PR DESCRIPTION
**Pull request by yrliou**
Fix https://github.com/brave/brave-browser/issues/2307
## Submitter Checklist:
- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by yrliou** [comment]
TODO:
- Try to eliminate more patches if possible
- make `Open Link in Private Window with Tor` in context menu to use the new tor profile
- remove unused codes from current tor impl
- tests

**Comment by yrliou** [comment]
@riastradh-brave @bridiver @iefremov @darkdh This is still a WIP that have some todo items listed in above comment, but I would like to ask for feedbacks first.
I think it would be easier to go through each commit instead of looking at all files at the same time, thanks in advance.
cc @bbondy @tomlowenthal

**Comment by simonhong** [comment]
Question - With this PR, we will have two OTR(for private and tor). Should we need another OTR for Tor instead of sharing one OTR with private and Tor?

**Comment by yrliou** [comment]
We want to have separate profiles between Private Window with Tor and Private Window, @riastradh-brave please correct me if I'm wrong.

**Comment by simonhong** [comment]
@yrliou Yup, I just worried about using two different OTR with one normal profile because upstream uses 1:1 matching between them.
If there is no regression with this, I'm also fine. :)

**Comment by rulatir** [comment]
Is this PR abandoned?

**Comment by szaimen** [comment]
> Is this PR abandoned?

Seems so, because https://github.com/brave/brave-browser/issues/2307 is already closed.

**Comment by yrliou** [comment]
This has been superseded by https://github.com/brave/brave-core/pull/3319.

**Pull request closed without merging**
