### PR TITLE
Add sponsored image P3A instrumentation for New Tab Page (uplift to 1.17.x)

### PR DESCRIPTION
**Pull request by bsclifton**
Uplift of https://github.com/brave/brave-core/pull/6924
Resolves https://github.com/brave/brave-browser/issues/12267

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by bsclifton** [comment]
Tested on Nightly - put a detailed test plan in https://github.com/brave/brave-browser/issues/12267

**Comment by kjozwiak** [comment]
`test-browser` failed on `Linux` as per https://ci.brave.com/job/pr-brave-browser-bsc-ntp-p3a-1.17.x-linux/2/execution/node/249/log. However, this is a known intermittent issue and will be fixed via https://github.com/brave/brave-browser/issues/12351. Doesn't block uplift.

```
02:37:30  1 test failed:
02:37:30      AdBlockServiceTest.SubFrame (../../brave/browser/brave_shields/ad_block_service_browsertest.cc:527)
```

Restarting `Win x64` via https://ci.brave.com/job/pr-brave-browser-bsc-ntp-p3a-1.17.x-windows/3/ due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-bsc-ntp-p3a-1.17.x-windows/2/execution/node/85/log/.

**Comment by kjozwiak** [comment]
Restarting `Win x64` via https://ci.brave.com/job/pr-brave-browser-bsc-ntp-p3a-1.17.x-windows/5/ as we ran into `Agent was removed` as per https://ci.brave.com/job/pr-brave-browser-bsc-ntp-p3a-1.17.x-windows/4/execution/node/189/log/.

```
16:20:04  Cannot contact i-00b3575ae47a19053-windows-swarm-dec75eeb: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException
16:25:04  Could not connect to i-00b3575ae47a19053-windows-swarm-dec75eeb to send interrupt signal to process
```

Restarting `macOS` via https://ci.brave.com/job/pr-brave-browser-bsc-ntp-p3a-1.17.x-macos/4/ as `test-unit` and `test-browser` failed as per https://ci.brave.com/job/pr-brave-browser-bsc-ntp-p3a-1.17.x-macos/3/execution/node/234/log/ and https://ci.brave.com/job/pr-brave-browser-bsc-ntp-p3a-1.17.x-macos/3/execution/node/247/log/.

```
18:11:41  FAILED: obj/media/base/test_support/fake_demuxer_stream.o 
```

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.17.x` approved after deliberating with @brave/uplift-approvers. QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/6924#issuecomment-724459202.

**Pull request merged**
