### PR TITLE
Remove redundant Block cookies setting

### PR DESCRIPTION
**Pull request by emerick**
Resolves https://github.com/brave/brave-browser/issues/37305

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A
  
 ## UI:

### brave://settings/shields
shields

### brave://settings/privacy
privacy-and-security

### brave://settings/cookies
cookies

### Shields panel
shields-panel

### CODE REVIEW

**Comment by emerick** [comment]
@bridiver @rebron suggested having you review this one, in particular the commit here https://github.com/brave/brave-core/pull/23106/commits/1d211a9bead6cec48788a37d5f49194713f00ea1 to make "block third-party cookies" a site-specific setting accessible only via Shields vs. a setting that can be applied to all sites across the board.

**Comment by simonhong** [comment]
Sorry for missing this. I'll check soon.

**Comment by simonhong** [comment]
All looks good to me but it seems there is one more thing to do - `Highlight Shields in the left navigation menu on brave://settings/cookies`

**Comment by emerick** [comment]
@simonhong We decided to drop "Highlight Shields" item from this PR, but I'll update the issue to reflect that. Will send you a Slack to ask you a follow-up question about that one, as maybe it is something that can be supported in the future.

**Review by simonhong — APPROVED** [review]
++

**Review by mkarolin — APPROVED** [review]
`strings`++

**Comment by ShivanKaul** [comment]
We should also update https://support.brave.com/hc/en-us/articles/360017905612-How-do-I-turn-Do-Not-Track-on-or-off, will work on that.

**Comment by emerick** [comment]
@petemill Mind taking a look at this one, since it involves some TypeScript-related changes?

**Review by fallaciousreasoning — APPROVED** [review]
LGTM - thanks @emerick!

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.53 Chromium: 124.0.6367.91 (Official Build) nightly (64-bit)
-- | --
Revision | 418087e12068ca8ff9a74f346b9aac5032cd10de
OS | Windows 11 Version 23H2 (Build 22631.3527)
```
`Block cookies`  - UI 
1. Installed 1.67.53
2. launched Brave
3. opened brave://settings/shields in a new tab
4. confirmed redundant `Block cookies` setting in `brave://settings/shields`, the one that links to `brave://settings/cookies` is no longer shown
5. confirmed correct labels in the drop down menu for `Block cookies` settings 
6. confirmed labels in Block cookies drop menu is updated in the Shields panel  and global defaults page and per site labels match 
    - "All" => "Block all cookies"
    - "Only cross-site" => "Block third-party cookies"
    - "Disabled" =>"Allow all cookies"

`brave://settings/shields` | per-site `shields panel`
----- | ------
<image width = "300" alt="image" src ="https://github.com/brave/brave-core/assets/98358127/e7677663-814f-4669-8cae-8998e57fdbf6">|<image width = "700" alt="image" src ="https://github.com/brave/brave-core/assets/98358127/2cd3dd4b-8fc5-40bd-b4d6-21af3466a0ec">
<image width = "500" alt="image" src ="https://github.com/brave/brave-core/assets/98358127/4b3702e9-cbf9-4833-b719-8a3f62b34fa8">|<image width = "500" alt="image" src ="https://github.com/brave/brave-core/assets/98358127/e8b8c142-5c45-443b-8d1b-78617451c28c">

brave://settings/cookies - UI

1. continue from above case
2. opened brave://settings/cookies
3. confirmed `Default behavior` section is removed and no longer shown
4. confirmed "Do Not Track" setting is moved to be under the top-level `brave://settings/privacy` below  "Go Off-The-Record..." and disabled as a default as an existing behavior

1.65.x | 1.67.x | Default behavior section
---- | --- | -----
image|image|image

**Pull request merged**
