### PR TITLE
Sync fix bookmarks object id duplication (uplift to 1.5.x)

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Sync fix bookmarks object id duplication

Uplift of https://github.com/brave/brave-core/pull/4710, created manually because had conflicts.

Fixes https://github.com/brave/brave-browser/issues/8325

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
accidentally closed, opening

**Comment by kjozwiak** [comment]
Looks like it never started the `b-b` job and timed out after ~6mins. Restarting.

**Comment by AlexeyBarabash** [comment]
failed on iOS only, 
```
ios_deployment_target=\"12.0\" ios_enable_code_signing=false cc_wrapper=\"/Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/brave/script/redirect-cc.py\" "
20:30:46  ERROR at //build/timestamp.gni:31:19: Script returned non-zero exit code.
20:30:46  build_timestamp = exec_script(compute_build_timestamp,
20:30:46                    ^----------
20:30:46  Current dir: /Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/out/ios_Release/
20:30:46  Command: python /Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/build/compute_build_timestamp.py official
20:30:46  Returned 1.
20:30:46  stderr:
20:30:46  
20:30:46  Traceback (most recent call last):
20:30:46    File "/Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/build/compute_build_timestamp.py", line 127, in <module>
20:30:46      sys.exit(main())
20:30:46    File "/Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/build/compute_build_timestamp.py", line 113, in main
20:30:46      last_commit_timestamp = int(open(lastchange_file).read())
20:30:46  IOError: [Errno 2] No such file or directory: '/Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/build/util/LASTCHANGE.committime'
20:30:46  
20:30:46  See //base/BUILD.gn:34:1: whence it was imported.
20:30:46  import("//build/timestamp.gni")
20:30:46  ^-----------------------------
20:30:46  See //BUILD.gn:70:5: which caused the file to be included.
20:30:46      "//base:base_perftests",
20:30:46      ^----------------------
20:30:46  null
20:30:46  null
```

marking to skip all platforms except iOS and restarting CI

**Comment by AlexeyBarabash** [comment]
CI still fails for  iOS
```
02:38:32  Widevine cdm host verification is disabled
02:38:32  /Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src: gn gen /Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/out/ios_Release --args="fieldtrial_testing_like_official_build=true brave_services_key=\"****\" root_extra_deps=[\"//brave\"] is_component_build=false target_cpu=\"x64\" is_official_build=true is_debug=false dcheck_always_on=false brave_channel=\"nightly\" google_api_key=\"****token\" brave_product_name=\"Brave\" brave_project_name=\"brave\" brave_version_major=\"1\" brave_version_minor=\"5\" brave_version_build=\"105\" chrome_version_string=\"80.0.3987.122\" chrome_version_major=\"80\" webcompat_report_api_endpoint=\"https://webcompat.brave.com/1/webcompat\" enable_cdm_host_verification=false skip_signing=true target_os=\"ios\" enable_dsyms=false enable_stripping=false use_xcode_clang=true use_clang_coverage=false ios_deployment_target=\"12.0\" ios_enable_code_signing=false cc_wrapper=\"/Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/brave/script/redirect-cc.py\" "
02:38:32  ERROR at //build/timestamp.gni:31:19: Script returned non-zero exit code.
02:38:32  build_timestamp = exec_script(compute_build_timestamp,
02:38:32                    ^----------
02:38:32  Current dir: /Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/out/ios_Release/
02:38:32  Command: python /Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/build/compute_build_timestamp.py official
02:38:32  Returned 1.
02:38:32  stderr:
02:38:32  
02:38:32  Traceback (most recent call last):
02:38:32    File "/Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/build/compute_build_timestamp.py", line 127, in <module>
02:38:32      sys.exit(main())
02:38:32    File "/Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/build/compute_build_timestamp.py", line 113, in main
02:38:32      last_commit_timestamp = int(open(lastchange_file).read())
02:38:32  IOError: [Errno 2] No such file or directory: '/Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.5.x/src/build/util/LASTCHANGE.committime'
02:38:32  
02:38:32  See //base/BUILD.gn:34:1: whence it was imported.
02:38:32  import("//build/timestamp.gni")
02:38:32  ^-----------------------------
02:38:32  See //BUILD.gn:70:5: which caused the file to be included.
02:38:32      "//base:base_perftests",
02:38:32      ^----------------------
02:38:32  null
```

**Comment by AlexeyBarabash** [comment]
removed b-b branch and restarted

**Comment by AlexeyBarabash** [comment]
this time all CI steps are green, but status is ABORTED, restarting

**Comment by AlexeyBarabash** [comment]
Now I have got version mismatch :(

**Pull request merged**
