### PR TITLE
Uplift 1.41.x Enable Solana dApps by default on desktop (BUNDLE)

### PR DESCRIPTION
**Pull request by darkdh**
We need a bundle of PRs to make it works flawlessly when release.
# Uplifted 11 PRs
## Enable feature by default
1. https://github.com/brave/brave-core/pull/13825 `(T)`
Resolves https://github.com/brave/brave-browser/issues/23520
2. https://github.com/brave/brave-core/pull/13931
Resolves https://github.com/brave/brave-browser/issues/23641

## Renderer crash fix 
1. https://github.com/brave/brave-core/pull/13934 `(T)`
Resolves https://github.com/brave/brave-browser/issues/23645
2. https://github.com/brave/brave-core/pull/13955 `(T)`
Resolves https://github.com/brave/brave-browser/issues/23681
3. https://github.com/brave/brave-core/pull/13962 `(T)`
Resolves https://github.com/brave/brave-browser/issues/23700
4. https://github.com/brave/brave-core/pull/13977 
Resolves https://github.com/brave/brave-browser/issues/23702
(four attempts to fix potential double freeing)
5. https://github.com/brave/brave-core/pull/14018 `(T)`
Resolves https://github.com/brave/brave-browser/issues/23761

## Wallet adapter compatibility
1. https://github.com/brave/brave-core/pull/13939
Resolves https://github.com/brave/brave-browser/issues/23653
2. https://github.com/brave/brave-core/pull/13965
Resolves https://github.com/brave/brave-browser/issues/23705
3. https://github.com/brave/brave-core/pull/14001 `(T)`
Resolves https://github.com/brave/brave-browser/issues/23594

## Audit fix
1. https://github.com/brave/brave-core/pull/13949
Resolves https://github.com/brave/brave-browser/issues/23677

# Test plan
Please use v1.42.41 or higher to test
PR that needs test has `(T)` at the end

### CODE REVIEW

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.42.42 Chromium: 103.0.5060.66 (Official Build) nightly (64-bit)
-- | --
Revision | `20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}`
OS | Windows 11 Version 21H2 (Build 22000.739)


## Enable feature by default
https://github.com/brave/brave-core/pull/13825

<details>
<summary>Verified test plan from PR </summary>

Account Change | Sign Message | Connect-Lock | Connect-Disconnect | Transactions
-- | -- | -- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/176435772-31556a81-d1ee-480b-8f2d-c2a984431bce.mp4> | <video src=https://user-images.githubusercontent.com/17010094/176435778-97f339df-fefc-434f-9957-6c866cf5fb5b.mp4> | <video src=https://user-images.githubusercontent.com/17010094/176435782-0902b859-3e5e-420a-9072-52ac9c4b5851.mp4> | <video src=https://user-images.githubusercontent.com/17010094/176435789-2d9d2ea6-7f8a-4c39-bea0-2c08f17423df.mp4> | <video src=https://user-images.githubusercontent.com/17010094/176435796-2d1f87eb-3773-4101-acdc-23e16f993915.mp4>

</details>

https://github.com/brave/brave-core/pull/13931

- Skipped as linked issue is marked as `QA/No`

## Renderer crash fix
https://github.com/brave/brave-core/pull/13934 
- Verified test plan from [brave/brave-browser#23645](https://github.com/brave/brave-browser/issues/23645)
- Verified no crash when loading `https://att.com/` and navigating to Internet which redirects to `https://att.com/internet/`
- Verified no crash when visiting page `https://att.com/internet/fibre/`
- Additional verification notes [here](https://github.com/brave/brave-browser/issues/23645#issuecomment-1165807056)

https://github.com/brave/brave-core/pull/13955
- Verified test plan from [brave/brave-browser#23645](https://github.com/brave/brave-browser/issues/23645)
- Verified loading a GDoc (50 Mb file) and reloading multiple times doesn't crash the browser/webview
- Verified loading the file on both normal tabs and private tabs doesn't crash the browser/webview

https://github.com/brave/brave-core/pull/13962
- Verified test plan from [brave/brave-browser#23681](https://github.com/brave/brave-browser/issues/23681)
- Verified loading a GDoc (50 Mb file) and reloading multiple times doesn't crash the browser/webview
- Verified loading the file on both normal tabs and private tabs doesn't crash the browser/webview

https://github.com/brave/brave-core/pull/13977
- Skipped as linked issue is marked as `QA/No`

## Wallet adapter compatibility
https://github.com/brave/brave-core/pull/13939
- Skipped as linked issue is marked as `QA/No`

https://github.com/brave/brave-core/pull/13965
- Skipped as linked issue is marked as `QA/No`

## Audit fix
https://github.com/brave/brave-core/pull/13949
- Skipped as linked issue is marked as `QA/No`

**Comment by darkdh** [comment]
Added two new PRs that need test
1. https://github.com/brave/brave-core/pull/14018 `(T)`
2. https://github.com/brave/brave-core/pull/14001 (T)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.42.48 Chromium: 103.0.5060.70 (Official Build) nightly (64-bit) 
-- | --
Revision | `1543faf9f70e61c6f6e9c01ff20a2e3cf2ad55dc-refs/branch-heads/5060_53@{#4}`
OS | Windows 11 Version 21H2 (Build 22000.739)

**https://github.com/brave/brave-core/pull/14018** 
- Verified test plan from PR
- Verified no crash when switching between Solana Accounts 

https://user-images.githubusercontent.com/17010094/176859705-f410647c-869f-43ab-a233-da4887da14b1.mp4


**https://github.com/brave/brave-core/pull/14001** 
- Verified test plan from PR
- Verified able to Swap SOL -> USDC on both `https://radiyum.io/` and `https://orca.so/`

https://user-images.githubusercontent.com/17010094/176860151-c5f93c21-497f-472e-9d2b-c93d27406c99.mp4

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.41.x` approved 👍 QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/14000#issuecomment-1169930436 & https://github.com/brave/brave-core/pull/14000#issuecomment-1172101490.

**Pull request merged**
