### PR TITLE
Disables Leo on Android when a global JS toggle set to blocked

### PR DESCRIPTION
**Pull request by SergeyZhukovsky**
Resolves https://github.com/brave/brave-browser/issues/37146

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
1. Go to 3 dots menu->Settings->Site Settings->Javascript
2. Set the Javascript switch to off
3. Exit menu
4. Check that there is no `Ask Leo` auto suggestion in the URL bar
5. There is no `Leo` in the main menu
6. There is no `Leo` in the 3 dots menu->Setttings

### CODE REVIEW

**Review by deeppandya — APPROVED** [review]
LGTM

**Review by samartnik — APPROVED** [review]
lgtm

**Review by AlexeyBarabash — APPROVED** [review]
++

**Review by tapanmodh — APPROVED** [review]
lgtm

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.66.55 Chromium: 123.0.6312.86 (Official Build) canary (64-bit)
--- | ---
Revision | 7cf963c266f6c171f1115a114dc6be5bafa49ae1
OS | Android 14; Build/AP21.240216.010; 34; REL
```

Reproduced the issue using `1.66.42 Chromium: 123.0.6312.86` with the STR/Cases outlined via https://github.com/brave/brave-core/pull/22820#issue-2211438317 as per the following:

**`Example`** | **`Example`**
----------------|----------------
Screenshot_20240402-230904 | Screenshot_20240402-230914

Using the same STR/Cases outlined above, ensured that `Leo` has been removed from the `Hamburger Menu`, `omnibox` and in the `main menu` when `Disable JS` has been enabled universally as per the following:

* ensured that disabling `JS` via the shields panel doesn't remove `Leo` from `Hamburger Menu`, `omnibox` & `Settings`
* ensured that enable/disabling `JS` via `Settings` correctly hides & unhides `Leo` from `Hamburger Menu`, `omnibox` & `Settings`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------
Screenshot_20240402-231526 | Screenshot_20240402-231538 | Screenshot_20240402-231531 | Screenshot_20240402-231545 | Screenshot_20240402-231708 | Screenshot_20240402-231714

**`Disabling JS via shields panel`**

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------
Screenshot_20240402-231916 | Screenshot_20240402-231922 | Screenshot_20240402-231943

**Pull request merged**
