### PR TITLE
[Uplift 1.67] Merge pull request #23907 from brave/ai-chat-llama-3

### PR DESCRIPTION
**Pull request by petemill**
- Uplift of https://github.com/brave/brave-core/pull/23907
- Resolves https://github.com/brave/brave-browser/issues/38071

### CODE REVIEW

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.67.x` approved 👍 QA has verified the PR on `Nightly` using `1.68.x` as per https://github.com/brave/brave-core/pull/23907#issuecomment-2142939655.

**Comment by I-I-IT** [comment]
@kjozwiak Is this the right place to report the issue ?

**Comment by kjozwiak** [comment]
> @kjozwiak Is this the right place to report the issue ?

Please use https://github.com/brave/brave-browser/issues/new/choose to create new issues 👍 Once created, it will get added https://github.com/brave/brave-browser/issues at which point it will be prioritized.

**Comment by I-I-IT** [comment]
The issue is already fixed.

**Pull request merged**
