### PR TITLE
add package-lock.json

### PR DESCRIPTION
**Pull request by cezaraugusto**
this adds `package-lock.json` and is included in the effort to move from yarn to npm. `yarn.lock` file was kept as an option for people sticking with yarn.

brave-extension part: https://github.com/brave/brave-extension/pull/46

see full convo in https://bravesoftware.slack.com/archives/C7VLGSR55/p1530192665000124

### CODE REVIEW

**Comment by bbondy** [comment]
I worry that keeping yarn and npm lock files at the same time will lead to them being out of sync. Should we remove the yarn.lock file? Maybe @evq knows?

**Comment by bbondy** [comment]
I'll merge for now but we might want to remove the yarn lock file on this and also in brave-extension repo.

**Comment by NejcZdovc** [comment]
I think that we need to decide for one, otherwise people will need to remember to do another that is not in their flow.

**Comment by bbondy** [comment]
I mentioned on Slack in brave-core to remove the yarn.lock ones and update the docs accordingly. Sorry for not following up here.

**Pull request merged**
