### PR TITLE
Fixes upgrade from 0.63.x to 1.3.x AC switch OFF and wallet creation failed - 1.4.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/4449
Fixes https://github.com/brave/brave-browser/issues/7833

### CODE REVIEW

**Comment by bsclifton** [comment]
marked as `blocked` since we'll want to merge https://github.com/brave/brave-core/pull/4449 and check on Nightly 👍

**Comment by tmancey** [comment]
@kjozwiak

- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

**Comment by bsclifton** [comment]
marking as unblocked as this was verified on Nightly 🎉

**Comment by kjozwiak** [comment]
Restarting `Win x64` due to https://ci.brave.com/job/brave-browser-build-pr/job/issues%252F7833-1.4.x/2/execution/node/760/log/ failing.

**Pull request merged**
