### PR TITLE
Update Chrome logo to Brave logo

### PR DESCRIPTION
**Pull request by EnzoItaliano**
Updates Chrome logo to Brave logo on brave://dino at the end scene of the game.

Fixes brave/brave-browser#17124

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by bsclifton** [comment]
This works great for me 😄 Makes a good starting point for some of the other issues we hav
brave-dino
e

**Review by bsclifton — APPROVED** [review]

**Comment by bradleyrichter** [comment]
@bsclifton  Can you use the bitmap file that Sampson and I made for other 1-bit needs?

**Comment by jonathansampson** [comment]
Wonderful job, @EnzoItaliano!

We have been considering updates to this game for a while; I was [experimenting with pixelated Brave adjustments](https://twitter.com/BraveSampson/status/1455364213468278785) earlier last month on Twitter. It is a challenging process; thank you for taking on the effort! (it's not trivial to get the project setup and building either, so great work!)

Here are the sprites I was working on recently:

## 2x

200-offline-sprite

## 1x

100-offline-sprite

## Detail

image

We are currently looking into potential changes to the other sprite-elements as well (dinosaur, pterodactyls, cacti, etc.), so we'd like to hold onto this PR for now to see if we might be able to squeeze-in a bit more work.

**Comment by bsclifton** [comment]
Quick follow up here! Do we know what else we'd like to do @bradleyrichter @jonathansampson?

@EnzoItaliano would you still be up for changes if we had some feedback? 😄

**Comment by EnzoItaliano** [comment]
@bsclifton unfortunately my computer have been very bad these days, I don't know if I am able to run the project anymore

**Comment by bsclifton** [comment]
Closing as stale

**Pull request closed without merging**
