### PR TITLE
reduce background image size on NTP

### PR DESCRIPTION
**Pull request by cezaraugusto**
Cut down all NTP background image size by ~60%.

Image quality doesn't seem to be reduced. Tagging @bradleyrichter to double-check.

@AndriusA mentioned that in devices with lower screen resolution our NTP felt sluggish. This PR aims to improve that.

Added CI skip to all platforms but macOS since it's likely that reviewers are using it and these labels speed up builds considerably.

Below a comparison table regarding image size reduction.

| image | before  | after  |
|---|---|---|
| ntp-1.webp | 1.21 MB | 472 KB |
| ntp-2.webp | 1.47 MB | 703 KB |
| ntp-3.webp  | 1.16 MB | 365 KB |
| ntp-4.webp  | 452 KB | 142 KB |
| ntp-5.webp  | 136 KB | 33.2 KB |
| ntp-6.webp  | 360 KB | 124 KB |
| ntp-7.webp  | 465 KB | 132 KB |
| ntp-8.webp  | 550 KB | 174 KB |
| ntp-9.webp | 1.11 MB | 534 KB |
| ntp-10.webp | 260 KB | 64 KB |
| ntp-11.webp | 493 KB | 177 KB |
| ntp-12.webp | 1.31 MB | 581 KB |
| ntp-13.webp | 1.28 MB | 397 KB |
| ntp-14.webp | 706 KB | 290 KB |
| ntp-15.webp | 275 KB | 99.1 KB |
| ntp-16.webp | 1.19 MB | 441 KB |

### CODE REVIEW

**Comment by petemill** [comment]
Removing ci/skip-windows so we can test builds on low power device

**Comment by petemill** [comment]
@cezaraugusto could you explain which method you used to reduce the size of the webp files?

**Comment by cezaraugusto** [comment]
@petemill I used https://github.com/fengyuanchen/compressorjs.

**Comment by bsclifton** [comment]
Usually when decreasing size, there's going to be a load or processing hit to make up for the difference (ex: decompressing)

Would leave it up to reviewers if this new approach is good 😄 
cc: @petemill @ryanbr @iefremov @simonhong

**Comment by petemill** [comment]
I think we can close this in favor of https://github.com/brave/brave-core/pull/4264

**Comment by bsclifton** [comment]
@petemill SGTM

**Pull request closed without merging**
