### PR TITLE
Fix shields for fingerprinting v2 android

### PR DESCRIPTION
**Pull request by deeppandya**
Resolves https://github.com/brave/brave-browser/issues/10688
Resolves https://github.com/brave/brave-browser/issues/10953 
Resolves https://github.com/brave/brave-browser/issues/11786

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`, `npm run gn_check`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Comment by kjozwiak** [comment]
Verification **PASSED** using the following two devices:

* `Samsung S10+` running `Android 10` using `1.16.43 CR: 86.0.4240.55`
* `Samsung Tablet A` running `Android 10` using `1.16.43 CR: 86.0.4240.55`

Running through https://github.com/brave/brave-browser/issues/10953:

| Samsung S10+ |
|:-------------:|
| Screenshot_20200928-233006_Brave - Nightly| 
| 9ee5db00-01e3-11eb-852a-e4e28677a013.jpg)
Screenshot_20200928-232734_Brave - Nightly | 
| Screenshot_20200928-232506_Brave - Nightly | 

Running through https://github.com/brave/brave-browser/issues/10688:

* ensured that `Block all cookies`, `Block cross-site cookies` or `Allow all cookies` appear as selected under `Advanced Controls` -> `Block Cookies` once the user has selected the setting and clicked on `Done`.
  * ensured that selecting the `<` (back) button also worked as expected
* ensured that `Fingerprinting blocked (strict, may break sites)`, `Fingerprinting blocked (standard)` or `Allow all fingerprinting` appear as selected under `Advanced Controls` -> `Block fingerprinting` once the user has selected the setting and clicked on `Done`.
  * ensured that selecting the `<` (back) button also worked as expected

**Comment by kjozwiak** [comment]
@srirambv mind taking a look at https://github.com/brave/brave-browser/issues/10953 on your tablet? I checked using `1.16.43 CR: 86.0.4240.55` and it seems like the padding looks exactly the same as your original example as per https://github.com/brave/brave-browser/issues/10953#issue-666717189. Here's what I'm seeing on the tablet when using Japanese:

Screenshot_20200929-001624_Brave - Nightly

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.16.43 x64 nightly build

https://github.com/brave/brave-browser/issues/10688
- Verified shields setting heading has proper padding 


English (Cookies) | English (Fingerprinting) | Spanish (Cookies) | Spanish (Fingerprinting) | Japanese (Cookies) | Japanese (Fingerprinting)
-- | -- | -- | -- | -- | --
image | image | image | image | image | image


https://github.com/brave/brave-browser/issues/10953
- Verified selecting individual settings for Cookies/Fingerprinting just says `Block Cookies` or `Block Fingerprinting` instead of selecting the individual setting text 

https://github.com/brave/brave-browser/issues/11786
- Verified selecting different fingerprint settings is retained between page reloads and doesn't retain one setting even if changed to other

Logged https://github.com/brave/brave-browser/issues/11905 as a followup to https://github.com/brave/brave-browser/issues/10688 to add more padding to the done button so that it doesn't look bad on the translated text 


@kjozwiak https://github.com/brave/brave-browser/issues/10688 the title had no padding as compared to what it is now where there is enough padding for the title. Below is a comparison (maybe not very noticeable in the screenshot)

Old | New 
-- | -- 
image | image

**Pull request merged**
