### PR TITLE
Update DEPS for updating omaha

### PR DESCRIPTION
**Pull request by simonhong**
Fix https://github.com/brave/brave-browser/issues/2021

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by simonhong** [comment]
@mbacchi Do you want to this to be uplifted to 0.56.x?
If so, I'll `uplift-request` tag.

**Comment by mbacchi** [comment]
I just added the uplift-request label. I forgot about this yesterday afternoon before the build and it took almost 5 hours. I can't uplift without approval so I'll have to wait till after this build I'm starting now.

**Comment by mbacchi** [comment]
master: 7a3e8dbcc834c535c9a40fe986fffe840e9da83c
0.58.x: d60ec0a3f5434f6d6eaed2cde9d1f339050f61dc

Not cherry picking to 0.57.x or 0.56.x yet awaiting approval to uplift to those branches.

**Comment by srirambv** [comment]
@mbacchi Uplift approved . Confirmed by @rebron

**Pull request merged**
