### PR TITLE
Toolbar Tor profile icon

### PR DESCRIPTION
**Pull request by petemill**
Fix https://github.com/brave/brave-browser/issues/1384

image

Added two sizes of vector icons since it's text and wanted to scale appropriately (the icon displays at different sizes for touch UI vs normal)

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
- Open Tor Window
- Observe that Avatar icon is 'Tor' icon

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by petemill** [comment]
A lot of overhead in this PR since we didn't seem to previously have anywhere to put Brave icons that weren't just replacements for existing Chromium icons. This creates such a project.

**Comment by simonhong** [comment]
Just question, don't we use same theme for guest window?

**Comment by petemill** [comment]
@simonhong I think Guest Window uses a different flag on `profile` since the icon is unchanged:
image

**Comment by petemill** [comment]
0.56.x 2c4f4e20
0.55.x 513d3524

**Comment by bsclifton** [comment]
Added `merged/0.55.x` label 😄

**Comment by petemill** [comment]
@bsclifton I had added the `merged/X` labels on to the issue as I thought that's where they are meant to go since the brave-browser issues are separated from the branches and PR in this repo. Is that not right?

**Pull request merged**
