### PR TITLE
[Android] Brave news re-enables opt-in card

### PR DESCRIPTION
**Pull request by alexsafe**
Resolves https://github.com/brave/brave-browser/issues/22135

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by AlexeyBarabash — APPROVED** [review]
++

**Review by tapanmodh — APPROVED** [review]
LGTM

**Review by deeppandya — APPROVED** [review]
LGTM

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.40.12 Chromium: 101.0.4951.41 (Official Build) canary (32-bit)
--- | ---
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Android 12; Build/SP1A.210812.016
```

**`New Installs/Fresh Profile`**

* ensured that the Brave News opt-in card is somewhat visible under `NTP`
* ensured that scrolling down displays the entire Brave News opt-in card
* ensured that clicking on `x` dismisses the card and doesn't re-appear when opening NTP tabs
* ensured that the Brave News opt-in card didn't re-appear when dismissed and the browser was restarted
* ensured that users can enable Brave News via the `Hamburger Menu` -> `Brave News` if the card was already dismissed
* ensured that users can enable Brave News via `Settings` -> `Brave News` if the card was already dismissed
* ensured that disabling/enabling Brave News doesn't display the opt-in card via NTP as the user already opted-in
* ensured that tapping on `Learn more about your data` opens up `https://brave.com/privacy/browser`
* ensured that tapping on `Show Brave News` via the opt-in card enables/displays the Brave News feed

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
Screenshot_20220426-004944_Brave - Nightly | Screenshot_20220426-004950_Brave - Nightly | Screenshot_20220426-004959_Brave - Nightly

**`Upgrading (Brave News hasn't been enabled`**

* downloaded/installed `1.39.67 Chromium: 101.0.4951.34` and ensured that the opt-in card isn't being displayed under NTP
* upgraded to `1.40.12 Chromium: 101.0.4951.41` and ensured that the opt-in card is being displayed without any issues
* ensured that once upgraded, the user can opt-in into Brave News by tapping on `Show Brave News`
* ensured that once upgraded, users can dismiss the opt-in card via NTP and later enable Brave News via `Settings`

**`Upgrading (Brave News enabled but then disabled by user)`**

* downloaded/installed `1.39.67 Chromium: 101.0.4951.34`
* enabled Brave News via `Settings` and then disabled the the feature via `Settings` (ensured feed isn't appearing under NTP)
* upgraded to `1.40.12 Chromium: 101.0.4951.41`
* ensured that the opt-in card wasn't being displayed as the user already enabled Brave News but decided to disable
* ensure that you can re-enable Brave News via `Settings` without any issues after upgrading

**`Upgrading (Brave News enabled & visible)`**

* downloaded/installed `1.39.67 Chromium: 101.0.4951.34` and enabled Brave News via `Sttings`
* upgraded to `1.40.12 Chromium: 101.0.4951.41`
* ensured that Brave News is still enabled/appearing under NTP 

Created the following issues while going through the above:

* https://github.com/brave/brave-browser/issues/22552
* https://github.com/brave/brave-browser/issues/22553

**Pull request merged**
