### PR TITLE
Sync ignore metadata changes (uplift to 0.61.x)

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Uplift of #1636

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@AlexeyBarabash please add title of the original PR, so that it's easy to know what this PR does. For example `Sync ignore metadata changes (0.61.x)`. Thank you

**Comment by AlexeyBarabash** [comment]
@NejcZdovc thanks, this PR was created with pr.py, I have not yet figured all details

**Comment by AlexeyBarabash** [comment]
@darkdh 
sure, will re-do  this and other uplifts

**Comment by AlexeyBarabash** [comment]
@darkdh , done through merge commit.

**Comment by AlexeyBarabash** [comment]
0.61.x is now beta after migration, mark @bbondy ,  @kjozwiak, @srirambv, @rebron as reviewers.
I want to have this PR be merged into 0.61.x to reduce amount of generated messages to AWS.

**Comment by AlexeyBarabash** [comment]
@kjozwiak thanks.
Sure will look on jenkins error.

**Comment by AlexeyBarabash** [comment]
Closing this, because created https://github.com/brave/brave-core/pull/1740 instead to make jenkins succeed with proper branch name.

**Pull request closed without merging**
