### PR TITLE
Create and upload silent and untagged Windows Omaha installers

### PR DESCRIPTION
**Pull request by mbacchi**
Fixes: https://github.com/brave/brave-browser/issues/2210

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by kjozwiak** [comment]
Approving for uplift to `0.57.x` after deliberating with @srirambv & @rebron 👍

**Comment by mbacchi** [comment]
Thanks @kjozwiak I'll remember that process for the next time. Appreciate your explanation.

**Comment by mbacchi** [comment]
master: e3491eee8557f607b88b24b98196800bfec74a0b
0.58.x: e9088ff2079114a55ecc475133f2cbecf43f0422
0.57.x: d59f4e4b0d40d1ae7f7dcad371e362e9ca52c43c

**Comment by bbondy** [comment]
adding merged label.

**Pull request merged**
