### PR TITLE
Updated Brave Ads UI copy to "Ads received this month" - 1.18.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/7163
Resolves https://github.com/brave/brave-browser/issues/12719

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by LaurenWags** [comment]
Restarted `macOS`, `Linux`, `Windows`.

**Comment by kjozwiak** [comment]
@tmancey looks like the above needs to be rebased.

**Comment by kjozwiak** [comment]
Restarting `Win x64` via https://ci.brave.com/job/pr-brave-browser-issues-12719-1.18.x-windows/4/ due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-issues-12719-1.18.x-windows/3/execution/node/200/log/. Looks like there was issues with the node connectivity.

```
23:56:06  Cannot contact i-0cd34f3da7377796e-windows-swarm-5b16d365: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException
00:01:06  Could not connect to i-0cd34f3da7377796e-windows-swarm-5b16d365 to send interrupt signal to process
```

Restarting `macOS` via https://ci.brave.com/job/pr-brave-browser-issues-12719-1.18.x-macos/4/ due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-issues-12719-1.18.x-macos/3/execution/node/204/log/.

**Comment by kjozwiak** [comment]
`Win x64` failed the S3 upload due to missing source files as per https://ci.brave.com/job/pr-brave-browser-issues-12719-1.18.x-windows/4/execution/node/285/log/. However, quickly checked with @brave/releng and the above doesn't block uplift.

```
05:02:19  Uploading file:/C:/18.x/src/out/Release/brave_installer_87_1_18_61.exe to s3://****/brave-browser-build-pr/issues/12719-1.18.x/de9da66d58f61eed6bd9f5f525cf36b18f0ef801-2f43eb9f54e86026c4dfb9a8ac365f3f9bf19369/windows/ 
05:02:19  Upload failed due to missing source file
```

`macOS` failed `test-browser` due to several intermittent reward failures as per https://ci.brave.com/job/pr-brave-browser-issues-12719-1.18.x-macos/4/execution/node/251/log/. However, these are intermittent and don't block uplift.

```
04:23:21  4 tests failed:
04:23:21      RewardsBrowserTest.ActivateSettingsModal (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:119)
04:23:21      RewardsBrowserTest.UpholdLimitNoBAT (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:397)
04:23:21      RewardsContributionBrowserTest.TipUnverifiedPublisher (../../brave/components/brave_rewards/browser/test/rewards_contribution_browsertest.cc:303)
04:23:21      RewardsPromotionBrowserTest.PromotionRemovedFromEndpoint (../../brave/components/brave_rewards/browser/test/rewards_promotion_browsertest.cc:230)
04:23:21  2 tests timed out:
04:23:21      RewardsBrowserTest.BackupRestoreModalHasNotice (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:303)
04:23:21      RewardsPromotionBrowserTest.ClaimViaSettingsPage (../../brave/components/brave_rewards/browser/test/rewards_promotion_browsertest.cc:195)
04:23:21  1 test crashed:
04:23:21      RewardsBrowserTest.ToggleAutoContribute (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:130)
```

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.18.x` approved after deliberating with @brave/uplift-approvers. QA has also verified the PR on Nightly as per https://github.com/brave/brave-core/pull/7163#issuecomment-732190565.

**Pull request merged**
