### PR TITLE
SKUs: fixes to refresh_order_credentials

### PR DESCRIPTION
**Pull request by evq**
Resolves https://github.com/brave/brave-browser/issues/33948

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
1. Launch the browser with the following flags: `--enable-features=AIChat --env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
2. Purchase Premium Leo or restore an existing Premium Leo subscription at `https://account.bravesoftware.com`
3. Close the browser
4. Edit the `Local State` file, there should be three instances of `"valid_from": "XXX"` and three of `"valid_to": "XXX". Change the dates so that they are in the past.
5. Message @evq or @husobee and have them change the credential dates on the server side.
6. Relaunch the browser and open the Leo panel, it should not show the credential expiry message.
7. Go to `brave://skus-internals` and load the SKUs state. Confirm that there are now six `valid_from` and `valid_to` instances and that three of them are current ( covering today + 2 days ).

### CODE REVIEW

**Review by husobee — COMMENTED** [review]
looks good to break paid and expired up

**Review by antonok-edm — APPROVED** [review]
Rust changes look good

**Comment by stephendonner** [comment]
🎉

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.62.7 Chromium: 119.0.6045.59 (Official Build) nightly (64-bit)
-- | --
Revision | 4e1dd5aa2c0569a7247e8b52d5136a1188907e8b
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

### Steps:
1. installed `1.62.7`
2. launched Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev --enable-logging=stderr --v=1`
3. loaded `account.bravesoftware.com`
4. entered basic-auth username/password
5. entered `leo-oct27@mailinator.com` and clicked on `Get login link`
6. clicked on the link in the resulting email
7. clicked on `Browse plans`
8. clicked on `Buy now` for `Leo Premium`
9. entered test `Stripe` credit-card credentials
10. submitted
11. waited
12. clicked on `Leo` in the sidebar
13. clicked on `Accept and begin`
14. confirmed `Premium` badge



image

**Pull request merged**
