### PR TITLE
Fix #13800

### PR DESCRIPTION
**Pull request by deeppandya**
Resolves https://github.com/brave/brave-browser/issues/13800

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 10` using the following build:

```
1.21.39 CR: 88.0.4324.96
```

**`Example Text Link Fixed`** | **`Example Text Link Fixed`**
--------------------------------|---------------------------------
Screenshot_20210202-150839_Brave - Nightly | Screenshot_20210202-134043_Brave - Nightly

**`Alignment Improved`** | **`Alignment Improved`**
--------------------------------|---------------------------
Screenshot_20210202-134027_Brave - Nightly | Screenshot_20210202-133743_Brave - Nightly

After speaking with @codybanxs & @deeppandya, the "light grey text" that's exampled via https://github.com/brave/brave-browser/issues/13800#issuecomment-768485092 will be addressed in the UI revamp in `1.21.x`.

**Comment by kjozwiak** [comment]
@deeppandya @codybanxs I wouldn't consider this a blocker either way but `Alignment Improved #2` still looks a but unaligned at the bottom where the blue text and the grey bottom text have a small offset. We can create a new issue for the above as https://github.com/brave/brave-browser/issues/13800 was technically about fixing the text so it doesn't look like a hyperlink.

**Comment by deeppandya** [comment]
> @deeppandya @codybanxs I wouldn't consider this a blocker either way but `Alignment Improved #2` still looks a but unaligned at the bottom where the blue text and the grey bottom text have a small offset. We can create a new issue for the above as https://github.com/brave/brave-browser/issues/13800 was technically about fixing the text so it doesn't look like a hyperlink.

@kjozwiak thank you mentioning it. I will definitely take a look and update it in the follow up issue.

**Comment by kjozwiak** [comment]
Sounds good @deeppandya 👍 Created https://github.com/brave/brave-browser/issues/13909 re: alignment issues.

**Pull request merged**
