### PR TITLE
Remove unneccessary resource compilation from android

### PR DESCRIPTION
**Pull request by petemill**
- Settings
- NTP
- Welcome

Fix https://github.com/brave/brave-browser/issues/10479

### CODE REVIEW

**Comment by petemill** [comment]
error in android build
```
16:16:08  FAILED: libmonochrome__combined.so libmonochrome__combined.so.TOC lib.unstripped/libmonochrome__combined.so lib.unstripped/libmonochrome__combined.so.map.gz 
16:16:08  python "../../build/toolchain/gcc_solink_wrapper.py" --readelf="../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-readelf" --nm="../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-nm" --strip=../../buildtools/third_party/eu-strip/bin/eu-strip --sofile="./lib.unstripped/libmonochrome__combined.so" --tocfile="./libmonochrome__combined.so.TOC" --map-file "./lib.unstripped/libmonochrome__combined.so.map.gz" --output="./libmonochrome__combined.so" -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-soname="libmonochrome__combined.so" -Wl,--version-script=gen/chrome/android/libmonochrome_linker_script.txt -Wl,--hash-style=gnu -Wl,-soname,libmonochrome.so --link-only -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=8 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10\%:cache_size_bytes=10g:cache_size_files=100000 -Wl,--lto-O2 -Wl,-mllvm -Wl,-import-instr-limit=5 -Wl,--no-rosegment -Wl,--exclude-libs=libgcc.a -Wl,--exclude-libs=libvpx_assembly_arm.a -Wl,--allow-multiple-definition --target=i686-linux-android16 -m32 -Werror -Wl,--warn-shared-textrel -Wl,-O2 -Wl,--gc-sections -nostdlib++ --sysroot=../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -B../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64 -Wl,--warn-shared-textrel -Wl,--pack-dyn-relocs=android -Wl,-wrap,calloc -Wl,-wrap,free -Wl,-wrap,malloc -Wl,-wrap,memalign -Wl,-wrap,posix_memalign -Wl,-wrap,pvalloc -Wl,-wrap,realloc -Wl,-wrap,valloc -Wl,--dynamic-linker,/system/bin/linker -o "./lib.unstripped/libmonochrome__combined.so" @"./libmonochrome__combined.so.rsp"
16:16:08  ld.lld: error: undefined symbol: BraveNewTabUI::BraveNewTabUI(content::WebUI*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
16:16:08  >>> referenced by brave_web_ui_controller_factory.cc:84 (../../brave/browser/ui/webui/brave_web_ui_controller_factory.cc:84)
16:16:08  >>>               thinlto-cache/Thin-a2539a.tmp.o:(content::WebUIController* (anonymous namespace)::NewWebUI<BasicUI>(content::WebUI*, GURL const&))
16:16:08  clang: error: linker command failed with exit code 1 (use -v to see invocation)
16:16:08  ninja: build stopped: subcommand failed.
```

**Comment by petemill** [comment]
Pushed a fix, waiting for build

**Comment by petemill** [comment]
android passed everything, just macOS test failure 🤷

**Comment by petemill** [comment]
Rebased on master, looks like master fixes those tests

**Comment by petemill** [comment]
uncritical CI failure (unstable status), 1 linux test error:

```
1 test failed:
12:51:46      RewardsBrowserTest.NotVerifiedWallet (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:236)
```

All ✔️ on android.

**Comment by bsclifton** [comment]
Uplifted to 1.11.x with https://github.com/brave/brave-core/pull/5996

**Pull request merged**
