### PR TITLE
Upgrade from Chromium 90 to Chromium 91 (1.25.x)

### PR DESCRIPTION
**Pull request by mkarolin**
Fixes brave/brave-browser#14848
Related PR: brave/brave-browser#15933
Uplift from brave/brave-core#8307

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by mkarolin** [comment]
**CI failures:**
* Linux: 2 `BraveAdsBrowserTest/BraveAdsUpgradeBrowserTest.UpgradePath` browser tests crashed. These are known and unrelated to this PR.
* MacOS: build error. Will push the fix and restart on MacOS only once Window CI finishes.

**Review by tmancey — APPROVED** [review]
LGTM++

**Comment by kjozwiak** [comment]
Restarting `macOS` as it timed out after reaching the 6hr limit as per https://ci.brave.com/job/pr-brave-browser-cr91-1.25.x-macos/4/console.

```
20:10:20  [40036/50977] CXX obj/third_party/blink/renderer/core/core/ng_inline_items_builder.o
Calling Pipeline was cancelled
20:10:22  Sending interrupt signal to process
```

**Comment by kjozwiak** [comment]
Restarting `macOS` as the pipeline timed out again after reaching the 6hr limit as per https://ci.brave.com/job/pr-brave-browser-cr91-1.25.x-macos/5/console.

```
02:13:45  [2786/2787] STAMP obj/brave/components/brave_ads/test/brave_ads_unit_tests.stamp
Calling Pipeline was cancelled
02:19:18  Sending interrupt signal to process
02:19:18  Sending interrupt signal to process
```

**Review by goodov — APPROVED** [review]

**Review by AlexeyBarabash — APPROVED** [review]
++ for sync changes

**Comment by kjozwiak** [comment]
`test-browser` failed on `macOS` as per https://ci.brave.com/job/pr-brave-browser-cr91-1.25.x-macos/8/testReport/. However, this is a known intermittent issue and unrelated to this specific PR.

```
macos-x64 / test-browser / BraveAdsBrowserTest/BraveAdsUpgradeBrowserTest.UpgradePath/PreferencesForVersion070WithRewardsAndAdsEnabled_ForUnsupportedLocale_ForUnsupportedLocale_RewardsShouldBeEnabled_AdsShouldBeDisabled
```

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.25.x` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
