### PR TITLE
[Nala]: Use Material UI variables as base Nala Layer

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Resolves https://github.com/brave/brave-browser/issues/39045

**Notes:**
- https://github.com/brave/leo/pull/695 needs to land in Nala before this will be ready to go
- `Themable` colors are mostly unaffected by this bump. Primitive/gray has been replaced with primitive neutral
- `primitive` color ranges have been approximately inverted by this scale https://www.figma.com/design/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?node-id=1670-13546&m=dev

### Nala Changes
https://github.com/brave/leo/compare/765fc137fcd02d0ce54ee14ddbd38f7380b6d43a...8f981cd78e484cd97348855350ab5ade2f3dc1db
- [[Dropdown]: Update spacing and padding of dropdown options](https://github.com/brave/leo/commit/82fb332844b88b89b959ddcb716be32ebd0be4b6)
- [[Dialog]: Update border and elevation on dialog](https://github.com/brave/leo/commit/8f46bb48e1132b4cbe2060c61a0120e13c5cd5c4)
- [[Input field] Added a quick animation for hover state in inputs](https://github.com/brave/leo/commit/8f0e2baf16a4009cfb9c9fc14e5489f16dbd0643)
- [[Typescript]: Support writing token parsers/scripts in Typescript](https://github.com/brave/leo/commit/570ca747b0b5e34dd52b74b10998f2e582e7c2e6)
- [[Tokens]: Update universal variables with Material Base](https://github.com/brave/leo/commit/8f981cd78e484cd97348855350ab5ade2f3dc1db)

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by zenparsing — APPROVED** [review]
Rewards 👍

**Review by Douglashdaniel — APPROVED** [review]
++ Wallet Front-end

**Review by petemill — APPROVED** [review]
I'm surprised no .scss files needed to be changed, but if it's passing then I guess there were no grays!

**Comment by fallaciousreasoning** [comment]
Hahahaha well @petemill the audit failed and some (s)css grays needed updating!

**Review by kylehickinson — APPROVED** [review]

**Comment by goodov** [comment]
seems like dark mode (private window at least) has incorrect colors after this change.

this is what I'm seeing on Windows
image

**Comment by GeetaSarvadnya** [comment]
The difference found between 1.69.x Vs 1.70.x on Omnibox hover state case colors:
     1. The theme color is Blue instead of Purple
     2. `Import bookmarks now` text is somewhat white in color instead of blue
     3. Active tab color is Blue instead of Purple

image

**Comment by fallaciousreasoning** [comment]
Eagle eyes @GeetaSarvadnya! I checked the Figma and did some color dropping and this matches up so I think its okay :smile: Great work noticing!

**Pull request merged**
