### PR TITLE
Upgrade from Chromium 87 to Chromium 88.0.4324.79 (1.19.x).

### PR DESCRIPTION
**Pull request by mkarolin**
Fixes brave/brave-browser#12331
Fixes brave/brave-browser#13130
Fixes brave/brave-browser#13203
Fixes brave/brave-browser#13281
Fixes brave/brave-browser#13103
Fixes brave/brave-browser#13427
Fixes brave/brave-browser#13443

Related PR: brave/brave-browser#13365
Uplift from #6957
Uplift from #7399
Uplift from #7440
Uplift from #7491
Uplift from #7408
Uplift from #7544
Uplift from #7549

## Submitter Checklist:

- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by AlexeyBarabash — APPROVED** [review]

**Review by emerick — APPROVED** [review]
Rewards changes look good.

**Review by kylehickinson — APPROVED** [review]
iOS++

**Comment by mkarolin** [comment]
**CI:**
* post-init: a known `audit_deps` failure (`smallvec`) - unrelated to the PR
* Linux: failed `audit-network` with a known unrelated to the PR error
* MacOS: browser test failed: `RewardsBrowserTest.UpholdLimitNoBAT`
* Windows: browser tests timing out - will rerun.
* iOS: build failure - will rerun after fixing
Will rerun CI only for Windows and iOS.

**Comment by mkarolin** [comment]
Rebased on `1.19.x` and removed a couple of iOS commits that somehow didn't cherry-pick properly initially.

**Review by simonhong — APPROVED** [review]

**Comment by mkarolin** [comment]
**CI**:
* Windows: browser test failures
<pre>
 7 tests failed:
     RewardsBrowserTest.BackupRestoreModalHasNotice (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:304)
     RewardsBrowserTest.ResetRewardsWithBAT (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:375)
     RewardsBrowserTest.UpholdLimitNoBAT (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:398)
     RewardsContributionBrowserTest.TipConnectedPublisherVerified (../../brave/components/brave_rewards/browser/test/rewards_contribution_browsertest.cc:586)
     RewardsContributionBrowserTest.TipUnverifiedPublisher (../../brave/components/brave_rewards/browser/test/rewards_contribution_browsertest.cc:304)
     RewardsPromotionBrowserTest.ClaimViaSettingsPage (../../brave/components/brave_rewards/browser/test/rewards_promotion_browsertest.cc:196)
     RewardsPromotionBrowserTest.PromotionRemovedFromEndpoint (../../brave/components/brave_rewards/browser/test/rewards_promotion_browsertest.cc:231)
</pre>
However, they all pass locally.
* post-init: a known `audit_deps` failure (`smallvec`) - unrelated to the PR

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.19.x` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
