### PR TITLE
Fixes ads rewards are not refreshed after claiming an ad grant - 1.10.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/5748
Resolves https://github.com/brave/brave-browser/issues/10094

- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by tmancey** [comment]
@kjozwiak @rebron Could this be uplifted for 1.10 hotfix please?

**Comment by tmancey** [comment]
CI failed on Android and Linux, restarting

**Comment by tmancey** [comment]
CI failed on Linux, restarting Linux

**Comment by kjozwiak** [comment]
As per discussion with @rebron and @jsecretan, we'll let https://github.com/brave/brave-core/pull/5748 work it's way through the trains.

**Pull request closed without merging**
