### PR TITLE
Exclude tests from upstream that are known to fail in Brave

### PR DESCRIPTION
**Pull request by mariospr**
Disable a few unit and browser test suites that are known to fail at
the moment for Brave so that we can enable running the remaining ones
at least on CI, in order to increase test coverage.

Resolves https://github.com/brave/brave-browser/issues/20189

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

N/A

### CODE REVIEW

**Comment by mariospr** [comment]
Tested the current exclusions locally on my Linux (desktop) and Windows 10 machines and got all the remaining tests passing, which account for this:
  * Windows
    * Unit tests: 10374
    * Browser Tests: 3931
  * Linux
    * Unit tests: 9807
    * Browser Tests: 3434

**IMPORTANT**: I've only make exclusions to make sure that tests run well on **Release builds only** for now, since getting tests to pass on DCHECK-enabled builds would mean making even more changes to account for things that will get hit by upstream tests, such as accessing unregistered preferences, and so on.

@mkarolin I could not test this on Mac myself, so if you could eventually checkout this PR and run `npm run test unit_tests Release` and `npm run test browser_tests Release -- --test_launcher_jobs=2` in your machine that would be useful.

@wknapik In addition / alternatively, and as we talked about it yesterday on Slack, I think it would be great we could maybe have a pipeline that would run these tests on demand for now (e.g. if a GH tag such as `CI/run-upstream-tests` is present), to know whether the PR works ok on all platforms, so that we have more certainty on how these tests behave before merging.

WDYT?

**Comment by mariospr** [comment]
@mkarolin ran this PR on his Mac yesterday and provided me with a list of extra tests to skip, which I've added a couple of fixups on top of it earlier today. After that @mkarolin reports that running the updated PR passes all unit and browser tests on his Mac, which was the last piece of the puzzle.

As for Linux and Windows, I've rebased the branch on top of the latest `master` earlier this morning and I could confirm it also passed locally for me, with this being the summary of the tests run on each platform:

  * Linux:
    * Unit Tests: 9767 (+2 retries)
    * Browser Tests: 3350 (+1 retry)

  * Windows:
    * Unit Tests: 10373 (+3 retries)
    * Browser Tests: 3911 (+16 retries)

**IMPORTANT**: as mentioned in https://github.com/brave/brave-core/pull/11666#issuecomment-999769323, tests pass for now **on Release builds only**. For DCHECK-enabled builds we'd need to either add more exclusions or to try to fix more things, I'll comment on https://github.com/brave/devops/issues/6380

@mkarolin I'm going OoO for 2 weeks on Friday so, considering that this would not break anything in the pipelines as there's nothing automatically running upstream tests for now, I think we can maybe merge this as-is now so that @wknapik can then work on adding the pipelines that are needed (maybe running some tests first, like the ones in https://github.com/brave/devops/issues/6380#issuecomment-994942264) and enabling them if they are successful, WDYT?

**Comment by mkarolin** [comment]
SGTM

**Review by mkarolin — APPROVED** [review]
++

**Comment by wknapik** [comment]
@mariospr continued [here](https://github.com/brave/devops/issues/6380#issuecomment-1004125373).

**Comment by mariospr** [comment]
> @mariospr continued [here](https://github.com/brave/devops/issues/6380#issuecomment-1004125373).

Great! I see that https://github.com/brave/devops/pull/6638 and https://github.com/brave/brave-core/pull/11724 are also merged now, what would the next steps be?

**Comment by wknapik** [comment]
> what would the next steps be?

Once all enabled upstream tests are passing on all platforms, we should announce in #brave-core that they can now be run in PRs by adding the `CI/run-upstream-tests` label.

If there are any cases where we know we want to run them, we could look into auto-adding the label. Like if certain files are touched, etc.

If everything works in prs, we can look at build times and decide whether to enable them also in public and/or asan pipelines. The desktop planning & triage meeting is tomorrow, this might be a good place to discuss that if we have more info by then.

**Pull request merged**
