### PR TITLE
Private window is using incorrect styling

### PR DESCRIPTION
**Pull request by emerick**
Resolves https://github.com/brave/brave-browser/issues/18743

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

- Visual inspection and confirm settings via DevTools

### CODE REVIEW

**Review by petemill — CHANGES_REQUESTED** [review]
These styles, especially image size and text size, are all used by the other variations of the Private NTP - tor, qwant and qwant-tor and from what I understand, we don't want these styles to apply there.

In fact I can see that #10413 has caused quite a few issues on those other variants that we'll need to fix. Here's an example from the regular tor variation:

image

Release on the right, nightly on the left. Issues I can see:
- float of main image and titles
- spacing between section image and title
- link styling

**Review by petemill — APPROVED** [review]
This does now fix the issue. 
Up to you if you want to rename the variable, as I know there's a time constraint here.
Also as discussed we should make this new version of the variant with completely separate components, not try to shoe-horn in to the existing components that are tied to the variants which now have very different and older styles, not to mention some patterns and practices we want to move away from. We can do that as follow-up.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build:

```
Brave | 1.33.12 Chromium: 95.0.4638.50 (Official Build) nightly (64-bit)
-- | --
Revision | 3e9db37693d0cf8e31a89fbcf50401ae91125cef-refs/branch-heads/4638@{#816}
OS | Windows 11 Version 21H2 (Build 22000.258)
```

As per https://github.com/brave/brave-browser/issues/18743#issue-1025110620, ensured the following:
- The spot graphic is too large (it should be `164px`)
- The font should be `Poppins`
- The title should be `28px`
- No other private windows (Tor, Qwant) should be affected

### Private Window

**`Overview`** | **`Image`** | **`Title`** | **`Text/Summary`**
----------------|--------------|-----------|----------------------
overview | imageSize | title | fontText

### Tor Window

**Comment by rebron** [comment]
Verification **PASSED** on `macOS 10.14.6` using the following build:

```
Brave | 1.33.12 Chromium: 95.0.4638.50 (Official Build) nightly (x86_64)
-- | --
Revision | 3e9db37693d0cf8e31a89fbcf50401ae91125cef-refs/branch-heads/4638@{#816}
OS | mac)S Version 10.14.6 (Build 18G9323)
```

As per https://github.com/brave/brave-browser/issues/18743#issue-1025110620, ensured the following:
- The spot graphic is too large (it should be `164px`)
- The font should be `Poppins`
- The title should be `28px`
- No other private windows (Tor, Qwant) should be affected

**`Overview`** | **`Image`** | **`Title`** | **`Text/Summary`**
----------------|--------------|-----------|----------------------
overview | imageSize | title | fontText

### Tor Window

Ensured that the above changes weren't being applied to Tor windows as per the following:

**`Overview`** | **`Image`** | **`Title`** | **`Text/Summary`**
----------------|--------------|-----------|--------------------
torOverview | torTitle | torImage | torSummary

**Pull request merged**
