### PR TITLE
Modernisation of base::Value use away from deprecated interfaces

### PR DESCRIPTION
**Pull request by cdesouza-chromium**
A significant number of changes relating to base::Value deprecations have already been introduced on `cr104`, due to build failures occasioned by deprecations of base::Value methods. However, it is reasonable to believe that these sort of breakages will keep occurring upstream as time goes by.

This PR proactively tackles code that has not been touched by `cr104`, in order to pro-actively remove the use of deprecated methods/classes from our codebase.

Resolves https://github.com/brave/brave-browser/issues/23636

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by iefremov — DISMISSED** [review]

**Comment by iefremov** [comment]
oh I didn't notice this is WIP. It is not ready yet @cdesouza-chromium ?

**Review by simonhong — APPROVED** [review]
components/brave_referrals: ++

**Review by AlexeyBarabash — APPROVED** [review]
++ for sync changes

**Review by iefremov — APPROVED** [review]
browser/net/* LGTM

**Review by zenparsing — APPROVED** [review]
Rewards 👍

**Review by yrliou — APPROVED** [review]
wallet++

**Comment by bsclifton** [comment]
NOTE: if this is uplifted for some reason, we'll want to also grab https://github.com/brave/brave-core/pull/14136

**Pull request merged**
