### PR TITLE
[Android] Fix crash on not earning dialog

### PR DESCRIPTION
**Pull request by wchen342**
Resolves brave/brave-browser/issues/30821

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

Make sure not earning dialog shows normally if notification is disabled:

1. Enable Rewards in settings.
2. Go to Android system setting -> Apps -> find Brave -> Notification, turn off notifications for Ads.
3. Go back to Brave and go to `brave://rewards`.
4. See the following dialog.

Screenshot

### CODE REVIEW

**Comment by wchen342** [comment]
Updated with screenshot and steps.

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Comment by SergeyZhukovsky** [comment]
Let's uplift that to a stable channel.

**Comment by vlad-hoff** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 UPB2.230407.019 release-keys]
Brave build: 1.54.43
Chromium: 114.0.5735.110 (Official Build) canary (64-bit)
Revision: 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
```

Filed follow-up issue [#30926](https://github.com/brave/brave-browser/issues/30926)

---------------------------

**STEPS:**
1. Launch Brave > Enable Rewards in settings
2. Go to Android system setting > Apps > Find Brave > Notification, turn off notifications for Ads
3. Go back to Brave and go to `brave://rewards` > Verify the dialog 

**ACTUAL RESULTS:**
- Verified that dialog from https://github.com/brave/brave-core/pull/18766#issue-1743404090 is shown
- Verified that app crash is not happening

|1|2|
|:-:|:-:|
|  |  |

https://github.com/brave/brave-core/assets/128532965/9603b33e-0ec5-4739-a5e3-ff3c91815359

**Pull request merged**
