### PR TITLE
Don't install pylint for python3 globally on Linux/MacOS.

### PR DESCRIPTION
**Pull request by mkarolin**
Only install on Windows where python3 from depot_tools is used.
On Linux/MacOS we leave it up to the user to install pylint on their
system.

Fixes brave/brave-browser#16415 

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by wknapik** [comment]
@mkarolin is this PR missing a WIP label? I see this code still performs a global installation of pylint, except now it's only on Windows, which IIUC, is the one platform where we don't need that?

**Comment by mkarolin** [comment]
@wknapik Windows is the only platform on which python3 from `depot_tools` is used, which is why we can install `pylint` without worrying about touching a global python3 installation, if there is one.

**Comment by wknapik** [comment]
@mkarolin ah, I see. So this will install pylint somewhere in the working copy, not globally on the host OS? And otherwise we don't do the installation, so either pylint is there and everything works, or it isn't and we fail? Ok, that sounds fine, approving.

**Review by wknapik — APPROVED** [review]

**Comment by wknapik** [comment]
@mkarolin it may be worth producing a specific error message if pylint is missing on other platforms than Windows. Explain to the user that we're using pylint from $PATH on non-Windows and they need to install it. Up to you, feel free to merge as is.

**Comment by mkarolin** [comment]
@wknapik I think the error python will show (something like pylint module not found) should be sufficient for the user to figure out what to do.

**Pull request merged**
