### PR TITLE
Enable cosmetic filter CSS validation in `adblock-rust`

### PR DESCRIPTION
**Pull request by antonok-edm**
Resolves https://github.com/brave/brave-browser/issues/20043

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by rillian — APPROVED** [review]
> Just a note - adding the cssparser dependency in-browser previously caused GLIBC issues on some Linux platforms. I've since updated the version of cssparser, so hopefully it will not be problematic anymore.

I don't see anything in upstream `cssparser` which suggests they've addressed the glibc issue. However, we have a patch in `build/rust/Cargo.toml` to divert to our own modified version. I'm unclear if that's transitive or not. The `Cargo.lock` update suggests not. OTOH, there's already a copy in the kuchiki speedreader dep, so maybe not?

**Comment by rillian** [comment]
>  OTOH, there's already a copy in the kuchiki speedreader dep, so maybe not?

We had the same diversion in `components/speedreader/rust/ffi/Cargo.toml`.

Maybe the `libc` symbol issue isn't actually fixed then?
```
[2021-12-10T23:45:16.012Z] FAILED: deb_brave.deps 
[2021-12-10T23:45:16.012Z] python3 ../../chrome/installer/linux/debian/calculate_package_deps.py brave ../../build/linux/debian_sid_amd64-sysroot x64 deb_brave.deps --distro-check
[2021-12-10T23:45:16.012Z] Dependency libc6 (>= 2.29) not satisfiable on distro Debian 10 (Buster) caused by binary brave
```

**Comment by antonok-edm** [comment]
yeah, that looks like the same issue :disappointed:

**Comment by rillian** [comment]
The `pow` in `debian_sid_amd64_sysroot` is [from glibc 2.31](https://github.com/chromium/chromium/blob/97.0.4692.36/build/linux/sysroot_scripts/generated_package_lists/sid.amd64#L65-L66), so linking against that won't prevent picking up the `GLIBC_2.29` version of the symbol the packaging scripts are complaining about.

I'm unclear why removing the work-around for this issue in #11582 doesn't trigger an issue with the version in speedreader. The binary just ends up
```
$ objdump -T src/out/Component/brave | grep pow$
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 pow
```
without the additional `GLIBC_2.29  pow` entry I see building with this change.

**Comment by rillian** [comment]
I noticed today that `.cargo_args` has an empty sysroot directory (`"-C link-arg=--sysroot="`). Maybe that will lead to the configuration problem.

**Comment by antonok-edm** [comment]
@rillian nice eye. I updated the PR here to use `$sysroot` instead of `$target-sysroot`, let's see if that improves things.

**Review by bridiver — DISMISSED** [review]

**Comment by rillian** [comment]
The no-platform ci failure is a new audit issue in the sku code, so doesn't need fixing here. Unfortunately the linux failure is the same `glibc >= 2.29` symbol issue.

**Comment by mihaiplesa** [comment]
https://github.com/brave/brave-core/pull/11924 brings 0.4.3.

**Comment by rillian** [comment]
And #11924 is green on CI, but it doesn't have the change to enable the `css-validation` feature. I suggest we land that one first, then rebase here and continue trying to track down the problem.

I went ahead and removed the cssparser fork in #11582 since that PR magically works; can drop that change here.

**Review by rillian — APPROVED** [review]
Looks fine, approving pending rebase.

**Pull request merged**
