### PR TITLE
Hide rewards icon for x86 1.18.x (Uplift  to 1.18.x)

### PR DESCRIPTION
**Pull request by deeppandya**
Resolves https://github.com/brave/brave-browser/issues/13201 https://github.com/brave/brave-browser/issues/13202 

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by LaurenWags** [comment]
Verified a one-off build from @deeppandya

Verified STR from https://github.com/brave/brave-browser/issues/13201#issue-767639301 and confirmed setting is removed:
Screenshot_20201215-130927

Verified scenario 1 from https://github.com/brave/brave-browser/issues/13202#issue-767725891 and confirmed no onboarding shown on chrome://rewards page:
Screenshot_20201215-130945

Verified scenario 2 from https://github.com/brave/brave-browser/issues/13202#issue-767725891 and confirmed launching the app after 4 days does not open the panel on launch.

**Comment by deeppandya** [comment]
PR for master : https://github.com/brave/brave-core/pull/7439

**Comment by kjozwiak** [comment]
Restarting `pre-init` via https://ci.brave.com/job/pr-brave-browser-hide_rewards_icon_for_x86_1.18.x-pre-init/2/ as it failed as per https://ci.brave.com/job/pr-brave-browser-hide_rewards_icon_for_x86_1.18.x-pre-init/1/flowGraphTable/.

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.18.x` approved after deliberating with @brave/uplift-approvers. QA has verified the PR using a build that @deeppandya provided as per https://github.com/brave/brave-core/pull/7445#issuecomment-745507821.

**Pull request merged**
