### PR TITLE
feat(wallet): show solana networks (uplift to 1.42.x)

### PR DESCRIPTION
**Pull request by Pavneet-Sing**
Uplift of #14240
Resolves https://github.com/brave/brave-browser/issues/23647
Resolves https://github.com/brave/brave-browser/issues/24011

Pre-approval checklist: 
- [x] You have tested your change on Nightly. 
- [ ] This contains text which needs to be translated. 
    - [ ] There are more than 7 days before the release. 
    - [ ] I've notified folks in #l10n on Slack that translations are needed. 
- [ ] The PR milestones match the branch they are landing to. 

Pre-merge checklist: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 

Post-merge checklist: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by Pavneet-Sing** [comment]
Will fix, test and update android issues for this uplift branch tomorrow.

**Comment by kjozwiak** [comment]
> Will fix, test and update android CI issues for this uplift branch tomorrow.

Thanks @Pavneet-Sing, looks like it's failing as per the following:

```
 FAILED: obj/chrome/android/chrome_java__errorprone.errorprone.stamp 
21:48:35  python3 ../../build/android/gyp/compile_java.py --depfile=gen/chrome/android/chrome_java__errorprone.d --generated-dir=gen/chrome/android/chrome_java/generated_java --jar-path=obj/chrome/android/chrome_java__errorprone.errorprone.stamp --java-srcjars=\[\"gen/chrome/android/chrome_java.generated.srcjar\"\] --target-name //chrome/android:chrome_java__errorprone --header-jar obj/chrome/android/chrome_java.turbine.jar --classpath=\[\"obj/chrome/android/chrome_java.turbine.jar\"\] --classpath=@FileArg\(gen/chrome/android/chrome_java.build_config.json:deps_info:javac_full_interface_classpath\) --java-version=1.8 --bootclasspath=@FileArg\(gen/chrome/android/chrome_java.build_config.json:android:sdk_interface_jars\) --chromium-code=1 --warnings-as-errors --jar-info-exclude-globs=\[\"\*/AppHooksImpl.class\",\ \"\*/R.class\",\ \"\*/R\\\$\*.class\",\ \"\*/Manifest.class\",\ \"\*/Manifest\\\$\*.class\",\ \"\*/GEN_JNI.class\"\] --processorpath=@FileArg\(gen/tools/android/errorprone_plugin/errorprone_plugin.build_config.json:deps_info:host_classpath\) --enable-errorprone --processor-arg=dagger.fastInit=enabled @gen/chrome/android/chrome_java.sources
21:48:35  Traceback (most recent call last):
21:48:35    File "../../build/android/gyp/compile_java.py", line 808, in <module>
21:48:35      sys.exit(main(sys.argv[1:]))
21:48:35    File "../../build/android/gyp/compile_java.py", line 797, in main
21:48:35      md5_check.CallAndWriteDepfileIfStale(lambda changes: _OnStaleMd5(
21:48:35    File "/home/ubuntu/workspace/pr-brave-browser-pr14240_add-solona-in-network-selector_1.42.x-android/src/build/android/gyp/util/md5_check.py", line 56, in CallAndWriteDepfileIfStale
21:48:35      CallAndRecordIfStale(
21:48:35    File "/home/ubuntu/workspace/pr-brave-browser-pr14240_add-solona-in-network-selector_1.42.x-android/src/build/android/gyp/util/md5_check.py", line 155, in CallAndRecordIfStale
21:48:35      function(*args)
21:48:35    File "../../build/android/gyp/compile_java.py", line 797, in <lambda>
21:48:35      md5_check.CallAndWriteDepfileIfStale(lambda changes: _OnStaleMd5(
21:48:35    File "../../build/android/gyp/compile_java.py", line 429, in _OnStaleMd5
21:48:35      _RunCompiler(changes,
21:48:35    File "../../build/android/gyp/compile_java.py", line 562, in _RunCompiler
21:48:35      build_utils.CheckOutput(cmd,
21:48:35    File "/home/ubuntu/workspace/pr-brave-browser-pr14240_add-solona-in-network-selector_1.42.x-android/src/build/android/gyp/util/build_utils.py", line 274, in CheckOutput
21:48:35      raise CalledProcessError(cwd, args, stdout + stderr)
21:48:35
```

**Comment by Pavneet-Sing** [comment]
> > Will fix, test and update android CI issues for this uplift branch tomorrow.
> 
> Thanks @Pavneet-Sing, looks like it's failing as per the following:
> 
> ```
>  FAILED: obj/chrome/android/chrome_java__errorprone.errorprone.stamp 
> 21:48:35  python3 ../../build/android/gyp/compile_java.py --depfile=gen/chrome/android/chrome_java__errorprone.d --generated-dir=gen/chrome/android/chrome_java/generated_java --jar-path=obj/chrome/android/chrome_java__errorprone.errorprone.stamp --java-srcjars=\[\"gen/chrome/android/chrome_java.generated.srcjar\"\] --target-name //chrome/android:chrome_java__errorprone --header-jar obj/chrome/android/chrome_java.turbine.jar --classpath=\[\"obj/chrome/android/chrome_java.turbine.jar\"\] --classpath=@FileArg\(gen/chrome/android/chrome_java.build_config.json:deps_info:javac_full_interface_classpath\) --java-version=1.8 --bootclasspath=@FileArg\(gen/chrome/android/chrome_java.build_config.json:android:sdk_interface_jars\) --chromium-code=1 --warnings-as-errors --jar-info-exclude-globs=\[\"\*/AppHooksImpl.class\",\ \"\*/R.class\",\ \"\*/R\\\$\*.class\",\ \"\*/Manifest.class\",\ \"\*/Manifest\\\$\*.class\",\ \"\*/GEN_JNI.class\"\] --processorpath=@FileArg\(gen/tools/android/errorprone_plugin/errorprone_plugin.build_config.json:deps_info:host_classpath\) --enable-errorprone --processor-arg=dagger.fastInit=enabled @gen/chrome/android/chrome_java.sources
> 21:48:35  Traceback (most recent call last):
> 21:48:35    File "../../build/android/gyp/compile_java.py", line 808, in <module>
> 21:48:35      sys.exit(main(sys.argv[1:]))
> 21:48:35    File "../../build/android/gyp/compile_java.py", line 797, in main
> 21:48:35      md5_check.CallAndWriteDepfileIfStale(lambda changes: _OnStaleMd5(
> 21:48:35    File "/home/ubuntu/workspace/pr-brave-browser-pr14240_add-solona-in-network-selector_1.42.x-android/src/build/android/gyp/util/md5_check.py", line 56, in CallAndWriteDepfileIfStale
> 21:48:35      CallAndRecordIfStale(
> 21:48:35    File "/home/ubuntu/workspace/pr-brave-browser-pr14240_add-solona-in-network-selector_1.42.x-android/src/build/android/gyp/util/md5_check.py", line 155, in CallAndRecordIfStale
> 21:48:35      function(*args)
> 21:48:35    File "../../build/android/gyp/compile_java.py", line 797, in <lambda>
> 21:48:35      md5_check.CallAndWriteDepfileIfStale(lambda changes: _OnStaleMd5(
> 21:48:35    File "../../build/android/gyp/compile_java.py", line 429, in _OnStaleMd5
> 21:48:35      _RunCompiler(changes,
> 21:48:35    File "../../build/android/gyp/compile_java.py", line 562, in _RunCompiler
> 21:48:35      build_utils.CheckOutput(cmd,
> 21:48:35    File "/home/ubuntu/workspace/pr-brave-browser-pr14240_add-solona-in-network-selector_1.42.x-android/src/build/android/gyp/util/build_utils.py", line 274, in CheckOutput
> 21:48:35      raise CalledProcessError(cwd, args, stdout + stderr)
> 21:48:35
> ```
Thanks, Updated and fixed.

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.42.x` approved 👍 QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/14240#issuecomment-1191776160.

**Pull request merged**
