### PR TITLE
Fixed ad conversions fail for pages which use pushState - 1.13.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/6298
Resolves https://github.com/brave/brave-browser/issues/11012

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by tmancey** [comment]
CI failed on Windows, restarting Windows

**Comment by kjozwiak** [comment]
Restarting `Win x64` once more as we lost the spot instance/agent was removed as per https://ci.brave.com/job/pr-brave-browser-issues-11012-1.13.x/2/execution/node/343/log/

```
17:56:25  Cannot contact i-0218ff1293c91e807: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@2713ec6a:i-0218ff1293c91e807": Remote call on i-0218ff1293c91e807 failed. The channel is closing down or has closed down
18:01:32  Could not connect to i-0218ff1293c91e807 to send interrupt signal to process
```

**Comment by kjozwiak** [comment]
@tmancey mind rebasing this one? Looks we have a merge conflict with `components/brave_ads/browser/ads_tab_helper.cc`.

**Comment by tmancey** [comment]
@kjozwiak Rebased (I did mention in slack but thought best to mention here too)

**Pull request merged**
