### PR TITLE
Development: Add specific `include` targets in tsconfig to allow intellisense

### PR DESCRIPTION
**Pull request by cezaraugusto**
Fix https://github.com/brave/brave-browser/issues/7808

### Test plan

1. Intellisense should work.
2. Build should compile without errors (CI should pass).

### CODE REVIEW

**Comment by petemill** [comment]
@cezaraugusto a good way to test the webpack-typescript build is to just run webpack outside of the brave-browser build.

In your `src/brave` directory, you would run something like:
```
DEPFILE_PATH=$TMPDIR/brave-temp-depfile-webpack DEPFILE_SOURCE_NAME=wtf npm run web-ui -- --mode=production brave_new_tab_ui=$PWD/components/brave_new_tab_ui/brave_new_tab.tsx
```
This allows us to see the time taken, some info about which files were taken (as well as the huge size of our bundles!).

In this case the build is failing for me, both brave-browser and manual webpack run. Looks like it's missing the module definitions path or something.

When I run the above command on master, it takes 12 seconds (to do the new tab page build).

Maybe we should either have an individual tsconfig per project (which extends the root config), or pass arguments in to webpack.

**Comment by cezaraugusto** [comment]
Thanks @petemill. I measured the execution time via `time`, so for NTP the command would be:

```
time DEPFILE_PATH=$TMPDIR/brave-temp-depfile-webpack DEPFILE_SOURCE_NAME=wtf npm run web-ui -- --mode=production brave_new_tab_ui=$PWD/components/brave_new_tab_ui/brave_new_tab.tsx
```

The above added ~10s to the build time (we are coming from ~25s to ~35s) approx. We have eight features using TypeScript, so around ~1m20s would be added to the build time. It sounds good to me personally.

I just shared a message in CI channel whether or not this is a good trade-off. This is a considerable productivity boost to me, and I guess for us all coding TS and using VSCode, so hope we can all agree on this change.

**Comment by cezaraugusto** [comment]
Feedback applied

**Comment by cezaraugusto** [comment]
Cleaning up my assignments, closing this as stale.

**Pull request closed without merging**
