### PR TITLE
Lossless image optimization

### PR DESCRIPTION
**Pull request by FlipFloop**
Resolves 

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@FlipFloop hi, thank you for the PR. Could you please tell us a little bit more how this was done, so that we can check it out?

**Comment by FlipFloop** [comment]
@NejcZdovc Yes, I used algorithms such as [Zopfli](https://github.com/google/zopfli) to remove unnecessary information in the images! SVGCleaner was used for the SVGs!

The images are just reduced in size, and don’t lose quality!

**Comment by NejcZdovc** [comment]
cc @bsclifton @cezaraugusto

**Comment by bsclifton** [comment]
Somewhere we can start would be to create an issue for this work 😄 Each pull request made is always trying to solve an issue. In this particular case, I would be curious what the before/after is in bytes (ex: what is the savings). I don't think decompression times are affected (even though data is better compressed)

@karenkliu what do you think about these changes? As you or others (@bradleyrichter, @jenn-rhim, @jamesmudgett) update assets for projects after they're spec'ed out, these images would likely regress if edited or modified.  Also, are the modifications made to the SVGs OK? (did any metadata get stripped out that's used by internal tools, etc)

All of that aside, I'm curious what a good way would be to verify these changes? As there are 703 entries, someone will need to verify the before and after images are the same to make sure there's not any easter eggs hiding in here 😛

**Comment by FlipFloop** [comment]
Uhm, so the images don’t change visually, check out SVGCleaner, and Zopfli!

**Comment by bsclifton** [comment]
Thanks for the PR - apologies we didn't get around to this ☹️ I think the large scope of this PR was ultimately too big. Targeting specific areas or building the image optimization into the pipeline would be a preferred solution

**Pull request closed without merging**
