### PR TITLE
Brave News: Peek card on NTP (desktop)

### PR DESCRIPTION
**Pull request by petemill**
Adds a prompt to the Desktop NTP where the first Brave News card (a feature article or the "opt-in" card) will _peek_ up after a short delay. This action happens with a slow-ish transition.

Resolves https://github.com/brave/brave-browser/issues/20129

Aims:

With the feature flag on (the default):
- Brave News JS code is still loaded dynamically
- The feed is only requested over mojom IPC once the _peek_ action starts
- The "interaction" event only happens when user scrolls down
- The subsequent items (including and especially the first Ad) are not rendered until the user interacts (scrolls down past the first card)
- Opt-in still works and content is fetched and rendered after opt-in
- Visiting an article and then navigating "back" still scrolls the user down to the visited article in the Brave News feed

With the feature flag off:
- The card does not peek
- The content only loads when the user scrolls down
- The interaction event is still recorded at the same scroll-down gesture

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by simonhong** [comment]
Can you specify the issue link?

**Comment by simonhong** [comment]
When news contents is already visible before peeking, that news content also scrolled up after some delay.
Not sure it's intended behavior? I think peeking transition should be only applied when news content is not shown?

**Comment by petemill** [comment]
> When news contents is already visible before peeking, that news content also scrolled up after some delay.
> Not sure it's intended behavior? I think peeking transition should be only applied when news content is not shown?

Great idea - fixed

**Review by nullhook — APPROVED** [review]
lgtm

**Comment by MadhaviSeelam** [comment]
Verification `In-Progress` 
```
Brave | 1.40.83 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```

**Pull request merged**
