### PR TITLE
Adds correct captcha image

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves brave/brave-browser#928

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Needed or QA/No-QA-Needed) to include the closed issue in milestone 

## Test Plan:

1. clean profile
2. enable rewards
3. click claim grant
4. make sure that you see image with 3 coloured triangles
5. make sure that you can solve captcha

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by jasonrsadler** [comment]
Should we have test plan?

**Comment by ddrager** [comment]
Right now the ledger api returns 404 for QA testing environs: 
https://github.com/brave-intl/bat-ledger/blob/master/ledger/controllers/grants.js#L588
Should this be changed to return a static image that can be tested?

**Comment by NejcZdovc** [comment]
@jasonrsadler test plan added

**Comment by jasonrsadler** [comment]
@ddrager what URL are you using?

**Comment by jasonrsadler** [comment]
master 0623a36
0.55.x: 78f23c61

**Pull request merged**
