### PR TITLE
Updated VPN toolbar button UI

### PR DESCRIPTION
**Pull request by simonhong**
fix https://github.com/brave/brave-browser/issues/42226

No functional changes.

Screenshot 2024-11-19 at 4 45 55 PM
Screenshot 2024-11-19 at 4 45 11 PM
Screenshot 2024-11-19 at 4 54 54 PM
Screenshot 2024-11-19 at 4 45 23 PM

<br>

Screenshot 2024-11-19 at 4 57 59 PM
Screenshot 2024-11-19 at 4 57 23 PM
Screenshot 2024-11-19 at 4 55 29 PM
Screenshot 2024-11-19 at 4 57 38 PM

Resolves

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

Check new VPN UI by not purchased, purchased, connected and error state.

### CODE REVIEW

**Review by aguscruiz — APPROVED** [review]
Looks perfect!

Could you add a screenshot for a themed color too just for reference? But I imagine they'll look good too.

**Comment by simonhong** [comment]
> Looks perfect!
> 
> Could you add a screenshot for a themed color too just for reference? But I imagine they'll look good too.

Built-in themes at brave://settings/manageProfile seems good.
but custom theme that downaloded from webstore works differently.

https://github.com/user-attachments/assets/396408f3-314b-4e92-850f-8b4a7ad27cc0


https://github.com/user-attachments/assets/3cddf254-efb9-4c49-bd15-bc6a63a38625

When custom theme is used, I think we need to pick colors manually. WDYT? @aguscruiz  @fallaciousreasoning

**Comment by aguscruiz** [comment]
Yeah, looks good, great!

**Review by fallaciousreasoning — APPROVED** [review]
looks great!

**Pull request merged**
