### PR TITLE
[Commands]: Whitelist open guest profile command

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Resolves https://github.com/brave/brave-browser/issues/32268

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

1. Open brave://settings/system/shortcuts
2. There should be a shortcut for `Open Guest profile`
3. You should be able to add a shortcut to it
4. The shortcut should open a new guest profile

### CODE REVIEW

**Review by mkarolin — APPROVED** [review]
++

**Comment by mkarolin** [comment]
@fallaciousreasoning also IDC_ADD_NEW_PROFILE may need the same treatment: https://github.com/brave/brave-core/pull/18808/commits/fa5de1e994432a7743418233f9e1584ea9e4f133

**Comment by fallaciousreasoning** [comment]
Nice catch @mkarolin!

**Review by sangwoo108 — APPROVED** [review]
LGTM!

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.59.35 Chromium: 116.0.5845.96 (Official Build) nightly (64-bit)
-- | --
Revision | ee59f36b912d22844907d1339383d3c7ca7bb0d4
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/19725#issue-1853955433, reproduced the original issue using `1.59.26 Chromium: 116.0.5845.96` re: `Open in Guest` shortcut missing as per the following:

guestReproduced

Using the same STR/Cases mentioned above, verified that the `Open in Guest` shortcut is available under `brave://settings/system/shortcuts`. Also ensured that there's no `default` shortcut attached and ensured that you can assign shortcuts without any issues as per the following:

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|-----------------
guestfixed1 | guestfixed2 | guestfixed3

**Pull request merged**
