### PR TITLE
Create Brave product.icon

### PR DESCRIPTION
**Pull request by rossmoody**
Closes: https://github.com/brave/brave-browser/issues/5008
Closes: https://github.com/brave/brave-browser/issues/5058

@simonhong I don't have a Windows machine to test this on. Per your direction I believe this closes both issues and the icon is the same size as the one [I found on cs.chromium](https://cs.chromium.org/chromium/src/ui/message_center/vector_icons/product.icon?q=product.icon&sq=package:chromium&g=0&l=1) but I wasn't able to build to verify.

### CODE REVIEW

**Comment by simonhong** [comment]
@rossmoody Yup. I'll test this on Win. thanks!

**Comment by simonhong** [comment]
@rossmoody Works great! and rebased onto latest master :)
Screen Shot 2019-07-22 at 08 14 12

**Comment by kjozwiak** [comment]
Moving https://github.com/brave/brave-core/pull/2963, https://github.com/brave/brave-browser/issues/5008, https://github.com/brave/brave-browser/issues/5058 into `0.69.x - Nightly` as this landed in `master` as per the above. Please make sure all issues are moved into the appropriate milestones once completed/merged.

**Comment by bsclifton** [comment]
Looks great! Nice work, @rossmoody! ❤️

**Pull request merged**
