### PR TITLE
Updates Toolbar Title to Wallets - Fixes brave/brave-browser#17140

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

This PR Fixes https://github.com/brave/brave-browser/issues/17140

**Screenshot:**
Title Changes from 

image

**to**

image

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
No Tests Includes as The Change was for a title only

### CODE REVIEW

**Comment by bbondy** [comment]
lgtm but I think we actually want Wallet and not Wallets right @jamesmudgett ? The official name of the feature is Brave Wallet and not Brave Wallets. Sorry that the issue had an error in it.

**Comment by adithyaakrishna** [comment]
> lgtm but I think we actually want Wallet and not Wallets right @jamesmudgett ? The official name of the feature is Brave Wallet and not Brave Wallets. Sorry that the issue had an error in it.

No Probs, will change it and Update the PR :)

**Comment by adithyaakrishna** [comment]
Also @srirambv @bbondy How can we sign up in slack? 👀

**Comment by bbondy** [comment]
> @bbondy @srirambv Sorry guys, I completely understand you guys must be very busy but I wanted to know if there's any updates regarding this PR?😶

Hey thanks for the PR, we're planning to take it but I'd like for it to land in 1.32.x which is the version we're expecting to start enabling the native wallet feature.

**Comment by bbondy** [comment]
That will be on Nightly as of September 14, 2021, so pls reping after that if you don't see it being merged. Thanks!

**Comment by bbondy** [comment]
I'm going to use this PR instead https://github.com/brave/brave-core/pull/10029 because we didn't want to change other strings other than the title of the settings. That's where the new Brave wallet UI will live beneath. 

But I cherry-picked the commit so that you'd still show up as the author and get the contribution.

**Comment by adithyaakrishna** [comment]
Thanks @bbondy 🎉

**Pull request closed without merging**
