### PR TITLE
Fixes brave/brave-browser#2763 (Cleanup youtube)

### PR DESCRIPTION
**Pull request by ryanbr**
Given the popularity of youtube, this will fix a few issues of ad elements showing up on youtube. Can be reverted once cosmetic filter lands.

These elements are present in Easylist currently. `##.ytp-ad-module` will fix https://github.com/brave/brave-browser/issues/2763 the rest of the elements will clean up the site caused by any whitespacing or search-ad divs.

### CODE REVIEW

**Comment by snyderp** [comment]
Looks good . As long as all this gets removed once cosmetic filtering is on by default, LGTM!

**Comment by ryanbr** [comment]
I'll submit a revert once cosmetic has been landed on Release, if that all good @bsclifton  ?

**Comment by bsclifton** [comment]
@ryanbr sounds good! 😄

**Comment by bsclifton** [comment]
@ryanbr merged to Nightly/1.4.x (next build will have it).  If we want to uplift this to dev/beta/release, just let me know and I can help get that done

**Pull request merged**
