### PR TITLE
Remove unused cookie exceptions (twitch,bitbucket,ubisoft,amex)

### PR DESCRIPTION
**Pull request by ryanbr**
Resolves https://github.com/brave/brave-browser/issues/14032

Just removing unused cookie exceptions related to twitch, reddit, discord, and bitbucket/atlassian.

### CODE REVIEW

**Comment by ryanbr** [comment]
Removed ubisoft, and squashed. If this looks good for merging @pes10k

**Comment by pes10k** [comment]
If @ryanbr has confirmed that the sites work correctly w/o these exceptions, then the implementation looks good to me

**Review by pes10k — APPROVED** [review]

**Review by mkarolin — APPROVED** [review]
`chromum_src` change LGTM

**Comment by ryanbr** [comment]
Have tested in both compiled and Jenkin builds

**Pull request merged**
