### PR TITLE
Update chromium strings to change 'incognito' to 'private'

### PR DESCRIPTION
**Pull request by petemill**
This is the auto-generated output as a result from https://github.com/brave/brave-browser/pull/1890
Any desired changes to this output will have to result in a change to the re-basing script, and a re-generation of these files.

Re-land https://github.com/brave/brave-core/pull/683
Fix https://github.com/brave/brave-browser/issues/738

**Note that this should probably only land on a release branch where the updated strings will be sent for translation updates. This is because language translations are hashed against the source English string, and therefore will be invalidated by these updates.**

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by petemill** [comment]
@bbondy this is just the generated output from https://github.com/brave/brave-browser/pull/1890 which is still awaiting review

**Comment by bbondy** [comment]
Gotcha, why not the same PR?

**Comment by petemill** [comment]
@bbondy different repo

**Comment by kjozwiak** [comment]
Clearing the `uplift-request/0.57.x-Beta` flag. As per process, please re-submit for approval once this has landed in `master` and requires uplift into `0.57.x`.

**Comment by bbondy** [comment]
Uplifted since this is a strings update.
master: d76c7244f392a6692d5e46ce4bd5f1fee426e8ab
0.58.x: 6dbeae2f70ac6cbc57808403144d55d6867caa84
0.57.x: 6d341e23daf58ae31737ed600a465e23ecb93f2b

**Pull request closed without merging**
