### PR TITLE
Fix BraveBrowserView::OnThemeChanged is called infinitely

### PR DESCRIPTION
**Pull request by simonhong**
Fix https://github.com/brave/brave-browser/issues/1643
Fix https://github.com/brave/brave-browser/issues/1791

In the below situation, BraveBrowserView::OnThemeChanged() is called
infinitely on linux.
* Open normal window and private window and change theme
* Open normal window and guest/tor window

This might be the reason of unresponsiveness of windows icon and
cpu spike.

Instead of notifying to native theme observer in `BraveThemeService::OnThemeChanged()`, `BraveThemeService::OnPreferenceChanged()` would be much better to prevent infinite `OnThemeChanged()` calling.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Windows
  - [x] macOS
  - [x] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [x] Windows
  - [x] macOS
  - [x] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
`yarn test brave_browser_tests --filter=BraveThemeServiceTest.NativeThemeObserverTest`

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by simonhong** [comment]
Maybe I couldn't response review comment because of holidays.
So, I don't mind whoever modifying instead of me.

**Comment by bbondy** [comment]
@petemill do you have any other review comments on this?

**Comment by bbondy** [comment]
Please indicate merge flag

**Comment by kjozwiak** [comment]
Approving uplift to `0.57.x` after deliberating with @rebron 👍 @simonhong next time when requesting approval to the `beta` channel, please make sure you merge the changes into the `dev` channel from `master`.

**Comment by bbondy** [comment]
master: d1787ab5b400dea871af1b8ebbc2831de72b7f7e
0.58.x: 82b9d8ec8b1de8b993269dd87141eb589cf72811
0.57.x: 26b469585ab9f55b5507386b9d4d350ea61c0ec1

**Pull request merged**
