### PR TITLE
Attempt 3: fall through to upstream logic that allows some videos to autoplay muted

### PR DESCRIPTION
**Pull request by darkdh**
Resolves brave/brave-browser#9597

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

### Testing block
1. Go to https://vimeo.com/355789315
2. Set autoplay to block
3. Reload the tab
4. Video should be paused
5. Click on the play button of the video and it should be able to play

### Testing brave together
1. Open http://together.brave.com/
2. Connect with other peer
3. Should be abled to see video on bottom right rectangle and hear from the peer

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by darkdh** [comment]
CI failed at 
```
[1840/1842] LINK ./brave_unit_tests
15:34:39  [1841/1842] ACTION //brave/test:fix_test_install_name_brave_unit_tests(//build/toolchain/mac:clang_x64)
15:34:39  FAILED: alwaysrununittests/fix_test_install_name_brave 
15:34:39  python ../../build/gn_run_binary.py /usr/bin/install_name_tool -change @loader_path/../../Libraries/libadblock.dylib @executable_path/gen/adblock/out/x86_64-apple-darwin/release/libadblock.dylib -change @loader_path/../../Libraries/libchallenge_bypass_ristretto.dylib @executable_path/gen/challenge_bypass_ristretto/out/x86_64-apple-darwin/release/libchallenge_bypass_ristretto.dylib -change @loader_path/../../Libraries/libspeedreader_ffi.dylib @executable_path/gen/speedreader/out/x86_64-apple-darwin/release/libspeedreader_ffi.dylib brave_unit_tests
15:34:39  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: brave_unit_tests (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
15:34:39  /usr/bin/install_name_tool failed with exit code 1
```
on macOS, skip other platforms and rerun CI

**Comment by darkdh** [comment]
still failing at the same place. I make sure local unit test can run and passed.

**Comment by bbondy** [comment]
does it need an uplift?

**Comment by darkdh** [comment]
uplift PR created https://github.com/brave/brave-core/pull/6001

**Comment by kjozwiak** [comment]
@darkdh I know you're on PTO but the first case mentioned in https://github.com/brave/brave-core/pull/5970#issue-441582754 is a bit confusing. The case mentions that we should visit https://vimeo.com/355789315 and set autoplay to `Block`. However, the video never autoplays from the start (tried a clean profile as well). Seems strange. Do we want a video that actually autoplays by default?

Regarding the second case, @rebron and @bbondy got on a call and confirmed everything was working.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.12.77 Chromium: 84.0.4147.68 (Official Build) nightly (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.15.5 (Build 19F101)
```

Went through the STR outlined via https://github.com/brave/brave-core/pull/5970#issue-441582754 without any issues. As per https://github.com/brave/brave-core/pull/5970#issuecomment-655020109, went through Brave Together with @bbondy and @rebron and everything worked as expected.

**Pull request merged**
