### PR TITLE
Sync mobile bookmarks on toolbar

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
## Submitter Checklist:

Fixes https://github.com/brave/brave-browser/issues/2127 . Mobile bookmarks go to `Bookmarks bar` folder.

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [x] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [x] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
Specified in issue https://github.com/brave/brave-browser/issues/2127 .
Auto test:
`npm run test -- brave_unit_tests --filter=BraveBookmarkChangeProcessorTest.ChildrenOfPermanentNodesFromSync:BraveBookmarkChangeProcessorTest.BookmarkFromMobileGoesToToolbar`

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
What is the branch this PR should be merged to? 0.57.x?

**Comment by darkdh** [comment]
just merge to master for now. I'm adding uplift request now

**Comment by AlexeyBarabash** [comment]
master: https://github.com/brave/brave-core/commit/838117f8f9095b4804f852c8f132887508f33730

**Comment by AlexeyBarabash** [comment]
0.59.x: https://github.com/brave/brave-core/commit/2b91224418e100a26ff238cac7905173d2a53aaa

**Comment by kjozwiak** [comment]
@AlexeyBarabash uplift request to `0.58.x` approved after deliberating with @srirambv & @rebron 👍 Please add/remove all needed labels and ensure that the associated issue is moved to the correct milestone once merged.

**Comment by AlexeyBarabash** [comment]
Thanks @kjozwiak @srirambv  @rebron 

0.58.x https://github.com/brave/brave-core/commit/0855b24f6e249f450d457099d129f490e3940b85

**Pull request merged**
