### PR TITLE
fix french translation typo on BAT contribution popup

### PR DESCRIPTION
**Pull request by fakenine**
fixes https://github.com/brave/brave-browser/issues/3913

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [x] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests && npm run test-security`) on
  - [ ] Windows
  - [ ] macOS
  - [x] Linux
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:

1. Open Brave with French set as a language
2. Click on the "Brave Rewards" logo
3. Click on "Envoyer une contribution"

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by fakenine** [comment]
Seems like I cannot tag reviewers. Maybe @petemill ?

**Comment by bsclifton** [comment]
Thanks for the assist, @Liunkae!

@fakenine as called out by @Liunkae, you'll want to sign up for transifex and then we can add you as a contributor (feel free to post here once you've signed up and we can get your permissions sorted)

We pull translations from transifex on an ad-hoc basis and overwrite the files in the repo with what's in transifex 😄 I'll close this PR, but your work is definitely welcomed!

cc: @atsyed87 who might be able to help you with permissions 😄

**Comment by fakenine** [comment]
Hello @bsclifton,

Thank you for the precisions :smile:
My Transifex account can be found here : https://www.transifex.com/user/profile/fakenine/ cc @atsyed87

**Comment by atsyed87** [comment]
Hey @fakenine, I added you to our Transifex. Let me know if you have any problems!

**Comment by fakenine** [comment]
Hello @atsyed87,

Thank you!

I'm having issues accessing the translation page of Transifex. The items do not load and I'm having 403 errors in the console.

Capture d’écran de 2019-04-10 20-01-05

**Pull request closed without merging**
