### PR TITLE
Deny resizing of textarea for sync words

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Resolves https://github.com/brave/brave-browser/issues/24671

Small PR to deny resize of texarea for sync code

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint` - I run only `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
See https://github.com/brave/brave-browser/issues/24671

### CODE REVIEW

**Comment by petemill** [comment]
Is it possible that the sync words could go on to more lines that we show by default? If so, it would be useful for the user to be able to grow the textarea.

**Comment by AlexeyBarabash** [comment]
@petemill 

> Is it possible that the sync words could go on to more lines that we show by default? If so, it would be useful for the user to be able to grow the textarea.

Now we defaulted number of words to 25:
image

But even if somehow the words would not fit the area, then the scrollbar appears on the right and it allows to see all the text:

image

If we use `resize: vertical;`, it works well:

image

but in fact this additional area is not used, sync service will not accept such code, so I have chosen `resize: none;` option

**Comment by petemill** [comment]
@AlexeyBarabash in that case, I would recomment we use `resize: vertical` as there does not seem to be a reason to deny the user resizing, and if it's possible scroll could be introduced, user may wish to expand the textarea. I'm not sure we want to remove a default feature on textareas unless there is a reason to.

**Comment by AlexeyBarabash** [comment]
Thanks for the arguments @petemill , less restrict user's actions seems better. I [force-pushed](https://github.com/brave/brave-core/compare/9218a1a18ed88a463da6b1c579a11501d5786d27..9f5f349043aaa37e0b3e1472a594a5e26546dbfc) `resize: vertical;` change.

**Review by petemill — APPROVED** [review]

**Pull request merged**
