### PR TITLE
Manual uplift of PR 5039 "Implement User wallets (Uphold) on Android" to 1.9.x

### PR DESCRIPTION
**Pull request by gdregalo**
Uplift of PR https://github.com/brave/brave-core/pull/5039
`"Implement User wallets (Uphold) on Android" to 1.9.x`
Fixes https://github.com/brave/brave-browser/issues/8511

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [ ] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
This is waiting on QA to basically run through user wallets on Nightly before approving and merging into `1.9.x`. @LaurenWags mind adding the cases/update that you ran through in this PR?

@gdregalo mind fixing the conflict? Looks like the following files have a conflict:

```
* android/java/res/values/brave_colors.xml
* browser/ui/android/strings/android_brave_strings.grd
```

**Comment by LaurenWags** [comment]
Verification in progress
Uphold wallet checks performed with staging env on LG Nexus 5 w/ Android 5.1 using 

```
Brave | 1.10.22 Chromium: 81.0.4044.129 (Official Build) canary (32-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Android 5.1; Nexus 5 Build/LMY47D
```

- Confirmed can connect KYC'd account.
- Confirmed after connecting KYC'd account uphold sandbox balance is reflected in panel and on chrome://rewards page.
- Confirmed able to one time tip. Confirmed tip is deducted from balance and displayed on the panel summary and on the tips section of chrome://rewards page.
- Confirmed opening panel and tapping on 'Wallet Verified', all options on this popup behaved as expected:
   - Add/Withdraw Funds navigated me to appropriate pages on sandbox.uphold.com.
   - Go to my Uphold account navigated me to sandbox uphold dashboard.
   - Disconnect from Brave Rewards showed Disconnected wallet status on panel.
- Confirmed able to disconnect/reconnect within browser from panel, unable to confirm needing to reconnect in 60 days.
- Confirmed able to remove Brave Browser connection via sandbox.uphold.com (under Authorized Applications). Confirmed able to reconnect via panel on Android.
- Confirmed when in Disconnected state, Uphold sandbox balance is not displayed on panel or chrome://rewards page.
- Confirmed able to add BAT in uphold sandbox and see wallet balance update to reflect the new BAT.
- Confirmed "connected" messaging on panel and tip banner when visiting a publisher who is Brave verified but not KYC'd and only Uphold sandbox BAT exists in the wallet (no Brave controlled funds like ad grants, UGP).
- Confirmed if wallet only has Uphold sandbox BAT, unable to tip a connected publisher. Your balance does not go down, tip does not appear in tips list. Note - we should check that this goes to the pending contributions list. However, this currently does not display on Android. Logged as https://github.com/brave/brave-browser/issues/9331.



TBD - recurring tips (only funded via Uphold sandbox)
TBD - AC (only funded via Uphold sandbox)
TBD - recurring tip + AC (only funded via Uphold sandbox)
TBD - claim UGP and confirm can tip connected (not KYC'd) publishers until UGP runs out.
TBD - login with non KYC'd uphold sandbox act and confirm unable to see wallet balance in rewards
TBD - claim ad grant, sign up for acct. Wait for KYC to go thru. Confirm once KYC goes thru, a) you get notification about this and b) ad grant is moved to Uphold sandbox account.

Logged issues:
- https://github.com/brave/brave-browser/issues/9575 - wallet panel doesn't match desktop when Uphold wallet is connected
- https://github.com/brave/brave-browser/issues/9576 - no notification text when uphold wallet is disconnected

**Comment by srirambv** [comment]
We should probably close this PR as we are still waiting on https://github.com/brave/brave-browser/issues/9636

**Comment by bsclifton** [comment]
This is pushed back to 1.10 at a minimum; going to close this out

**Pull request closed without merging**
