### PR TITLE
Enable Widevine VMP on MacOS and Windows

### PR DESCRIPTION
**Pull request by simonhong**
VMP is enabled with official build and all below envs are set.
SIGN_WIDEVINE_KEY: private key
SIGN_WIDEVINE_CERT: widevine cert
SIGN_WIDEVINE_PASSPHRASE: pass for key

sig generator should be located in
//third_party/widevine/scripts/signature_generator.py before build starts on buildbot.

Issue https://github.com/brave/brave-browser/issues/944

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [x] Windows
  - [ ] macOS
  - [ ] Linux
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
1. Check sig file is in installed folder.
On MacOS, sig file(`Brave Browser Framework.sig`) is in `Brave Browser.app/Contents/Versions/7x.x.x.x/Widevine Resources.bundle/Contents/Resources/Brave Browser Framework.sig`
On Windows, sig files(`brave.exe.sig`, `chrome.dll.sig` and `chrome_child.dll.sig`) are in `C:\Program Files (x86)\BraveSoftware\Brave-Browser-XXX\Application\7x.x.x.x\`

2. Check netflix works
## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by simonhong** [comment]
@darkdh Rebased on master

**Comment by simonhong** [comment]
I'll not merge this now because this PR makes conflict with C74 and C74 will be merged soon.

**Comment by simonhong** [comment]
@darkdh Would you approve again? I rebased this PR on C74.

**Comment by bsclifton** [comment]
Whoops - RE: the above, it needs https://github.com/brave/brave-browser/pull/3903 (which isn't in `enable_cdm_host_verification` branch). Let me merge that commit in and start CI

**Pull request merged**
