### PR TITLE
Fix error message: Brave needs Windows 10, not 7/8

### PR DESCRIPTION
**Pull request by mherrmann**
Resolves https://github.com/brave/brave-browser/issues/28511

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

Please see https://github.com/brave/brave-browser/issues/28511.

### CODE REVIEW

**Comment by mherrmann** [comment]
The PR seems to work. I'm now getting this instead of "requires Windows 7" on Windows 7:

image

**Review by mihaiplesa — APPROVED** [review]

**Comment by mherrmann** [comment]
@mkarolin: @goodov said I should ask you for a review here. I hand-edited the files. @goodov pointed out that the header in `brave_strings.grd` says that the file should not be hand-edited. I did try `npm run chromium_rebase_l10n` but upstream [still has](https://github.com/chromium/chromium/blob/0b5723603bd9a647b726bff4b52ad1ae73bd322b/chrome/app/chromium_strings.grd#L583) "Windows 7" instead of "Windows 10" in those strings. Can you advise what the right approach is here?

**Comment by emerick** [comment]
@mherrmann I think that `brave_generated_resources.grd` is the correct file to use.

https://github.com/brave/brave-browser/wiki/Strings-and-Localization may help to explain it a little.

**Comment by mherrmann** [comment]
@emerick thank you for the comment. Would you please explain in a little more detail? I could trial & error various approaches for hours but feel like you might be able to give the answer in minutes. Do I just add my override for `IDS_INSTALL_OS_NOT_SUPPORTED` to `brave_generated_resources.grd`? Running `chromium_rebase_l10n` after that seems to have no (visible) effect. It almost feels like adding the following to `chromium-rebase-l10n.py` is appropriate:

```
elem1 = xml_tree.xpath(
        '//message[@name="IDS_INSTALL_OS_NOT_SUPPORTED"]')[0]
elem1.text = elem1.text.replace('Windows 7', 'Windows 10')
```

**Comment by mkarolin** [comment]
@mherrmann typically with strings we'd use our own strings file (such as `brave_generated_resources.grd` as @emerick suggested) and then use chromium_src overrides to replace the IDS_ where the string is used. But in this case such an approach might not be the best because the string is used in python scripts to create installer and they'd have to get patched. 
I think your suggestion to change `chromium-rebase-l10n.py` would work the best here.

One thing to note though, since you change the message content the translations id attribute won't match any more. With the new content the `id` should be `4378573854226202617` instead of `95624393026532554`, I believe. Might be best to test this with a non-English version of the installer.

**Comment by mherrmann** [comment]
Thank you @mkarolin, I'll follow the approach you suggested.

**Comment by mherrmann** [comment]
Still works and `brave_strings.grd` is now correctly produced by `chromium-rebase-l10n.py`.

image

@mkarolin can I ask for your review?

**Comment by mherrmann** [comment]
Nevermind @mkarolin, I still need to fix it for other languages. Sorry. Please hold off with the review.

**Review by mkarolin — APPROVED** [review]
LGTM

**Review by emerick — APPROVED** [review]

**Comment by mherrmann** [comment]
Yup, works for other languages as well now. Thank you for the guidance @emerick @mkarolin !

image

**Comment by mherrmann** [comment]
@kjozwiak should this be uplifted?

**Comment by kjozwiak** [comment]
> @kjozwiak should this be uplifted?

Apologies for the late response. Just seeing this now, lets get it uplifted into `1.49.x` 👍 Mind creating the uplift?

**Comment by mherrmann** [comment]
No problem; I'm on PTO this week and could only create the uplift next week, unfortunately.

**Comment by kjozwiak** [comment]
> No problem; I'm on PTO this week and could only create the uplift next week, unfortunately.

no worries 👍 We can leave this in either `1.50.x` or can get it uplifted into the `1.49.x` maintenance release which is scheduled for `March 22, 2023` as per https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 8.1 x64` & `Win 8.1 x86` using the following STR/Cases:

Using https://github.com/brave/brave-browser/releases/tag/v1.51.13, downloaded both `BraveBrowserStandaloneNightlySetup.exe` and `BraveBrowserStandaloneNightlySetup32.exe` and ensured the correct message was appearing via the modal. Also ensured that the strings were translated by spot checking two locales.

### `BraveBrowserStandaloneNightlySetup.exe` 

**`Example`** | **`Example`**
---------------|------------------
Screenshot 2023-03-06 at 3 36 58 PM | Screenshot 2023-03-06 at 4 05 50 PM

### `BraveBrowserStandaloneNightlySetup32.exe` 

**`Example`** | **`Example`**
---------------|------------------
Screenshot 2023-03-07 at 10 12 49 PM | Screenshot 2023-03-07 at 10 23 15 PM

**Pull request merged**
