### PR TITLE
fix deps vulnerabilites

### PR DESCRIPTION
**Pull request by cezaraugusto**
test plan: `npm audit` should return 0 vulnerabilities
closes https://github.com/brave/brave-browser/issues/2010

### CODE REVIEW

**Comment by NejcZdovc** [comment]
master (0.59) 938a556

**Comment by diracdeltas** [comment]
@NejcZdovc @cezaraugusto i think this needs to be uplifted into 0.56, otherwise the 0.56 build should be failing (since @mihaiplesa should have added the `npm run test-security` command to the build pipeline and it fails if there are security issues).

**Comment by diracdeltas** [comment]
once this is fixed, https://github.com/brave/brave-browser/issues/2038 can be closed

**Comment by kjozwiak** [comment]
Approved uplift to `0.56.x`. 👍 Deliberated with @rebron and both in agreement.

**Comment by cezaraugusto** [comment]
master (0.59.x) 938a556
0.58.x 5f5674e7
0.57.x 2efd02c6
0.56.x 18784ccd

**Pull request merged**
