### PR TITLE
Fixes twitch panel (uplift to 0.66.x)

### PR DESCRIPTION
**Pull request by NejcZdovc**
Uplift of #2618

Approved, please ensure that before merging: 
- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
@NejcZdovc looks like the original PR failed due to the following error:

```
FAILED: obj/brave/vendor/bat-native-ledger/ledger/twitch.o 
```

Let me know once you push a new PR and I'll keep an eye on CI 👍

**Comment by NejcZdovc** [comment]
@kjozwiak fixed this error, let's see what CI will tell us now :)

**Comment by kjozwiak** [comment]
@NejcZdovc awesome, thanks @NejcZdovc 👍 I'll keep an eye on `Jenkins` and check once it's completed.

**Comment by kjozwiak** [comment]
@NejcZdovc I took a look at the `Jenkins` failures and saw two `lint` failures which I think are fine and an issue with publishing the `xUnit` report which is I believe is fine as well. Mind doing a quick double check? But I think we should be good to uplift into `0.66.x` 👍

**Comment by NejcZdovc** [comment]
@kjozwiak lint is not related to this PR as we are linting the whole thing. `xUnit` is not related either

**Pull request merged**
