### PR TITLE
Fixed format string for DownloadComponentProgressFragment

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Fixes brave/brave-browser#33386

Wrong format string had percentage sign at the end and this caused `UnknownFormatConversionException`.

Resolves https://github.com/brave/brave-browser/issues/33386

`R.string.download_wallet_data_files_progress` in fact stored  `Downloading wallet data file • %1$d%` and the last percent here without type symbol caused the exception.

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
1. Install Brave browser, but do not launch 
2. Limit speed if the internet connection for the device to 1024kbit/s - this is required to see progress of Wallet component download
3. Enable Wallet, go to `Backup your wallet now screen`
4. Wait till `Download wallet data %` message appears - it should not crash

### CODE REVIEW

**Review by emerick — APPROVED** [review]

**Review by mkarolin — CHANGES_REQUESTED** [review]
Unfortunately, the problem with `%%` was that the upstream code doesn't like that in the localized (.xtb) files. I do not recall the details, but it was causing a build error. Could you, please, try putting %% in the translation of that string in one of the .xtb files and see if  causes an error. If so, would `\u0025\u0025` work?

**Comment by AlexeyBarabash** [comment]
> Could you, please, try putting %% in the translation of that string in one of the .xtb files and see if causes an error.

Yes, 
1. I applied this change
```
--- a/browser/ui/android/strings/translations/android_brave_strings_en-GB.xtb
+++ b/browser/ui/android/strings/translations/android_brave_strings_en-GB.xtb
@@ -928,7 +928,7 @@ If you don't accept this request, VPN will not reconnect and your Internet conne
 <translation id="6044189892950611565">Notification channel for Brave browser</translation>
 <translation id="1173919438868967364">Select account</translation>
 <translation id="8922793255489232731">Couldn't get matching timezone for : <ph name="VALUE"/></translation>
-<translation id="7084757528071133475">Downloading wallet data file \u2022 <ph name="percentage"/>\u0025</translation>
+<translation id="7084757528071133475">Downloading wallet data file \u2022 <ph name="percentage"/>%%</translation>
```
2. removed all `*en-GB*` files from `brave-browser/src/out/android_Debug_arm` dir
3. launched build `npm run build -- Debug  --target_os=android --target_arch=arm      --target_android_output_format=apk   --target_android_base=mono   --ninja=v`
4. Build succeeded

**Comment by mkarolin** [comment]
Maybe something got fixed in upstream code. When I try with cr117:

```
diff --git a/browser/ui/android/strings/android_brave_strings.grd b/browser/ui/android/strings/android_brave_strings.grd
index 5efb140bd0..07df12afde 100644
--- a/browser/ui/android/strings/android_brave_strings.grd
+++ b/browser/ui/android/strings/android_brave_strings.grd
@@ -3118,7 +3118,7 @@ If you don't accept this request, VPN will not reconnect and your internet conne
       Solana
     </message>
     <message name="IDS_DOWNLOAD_WALLET_DATA_FILES_PROGRESS" desc="Caption for displaying download progress of Brave Wallet datafiles component">
-      Downloading wallet data file \u2022 <ph name="percentage">%1$d<ex>37</ex></ph>\u0025
+      Downloading wallet data file \u2022 <ph name="percentage">%1$d<ex>37</ex></ph>%%
     </message>
     <message name="IDS_CONNECTED_TO_HOST" desc="Brave Vpn notification statistics text">
       Connected to <ph name="VALUE">%1$s</ph>
diff --git a/browser/ui/android/strings/translations/android_brave_strings_am.xtb b/browser/ui/android/strings/translations/android_brave_strings_am.xtb
index d43bc193e4..bf5afa9a2e 100644
--- a/browser/ui/android/strings/translations/android_brave_strings_am.xtb
+++ b/browser/ui/android/strings/translations/android_brave_strings_am.xtb
@@ -932,7 +932,7 @@
 <translation id="6044189892950611565">ለ Brave Browser የማስታወቂያ ጣቢያ</translation>
 <translation id="1173919438868967364">መለያ ይምረጡ</translation>
 <translation id="8922793255489232731">የሚዛመደውን የሰዓት ሰቅ ማግኘት አልተቻለም ለ፦ <ph name="VALUE"/></translation>
-<translation id="7084757528071133475">የኪስ ቦርሳ ውሂብ ፋይል በማውረድ ላይ \u2022 <ph name="percentage"/>\u0025</translation>
+<translation id="7084757528071133475">የኪስ ቦርሳ ውሂብ ፋይል በማውረድ ላይ \u2022 <ph name="percentage"/>%%</translation>
 <translation id="6471216025161697462">ከ<ph name="VALUE"/> ጋር ተገናኝቷል</translation>
 <translation id="1968852757206592413">ሙከራ</translation>
 <translation id="7733890291091968191">የዊብ3 ማሳወቂያዎችን አሳይ</translation>
```
and then run:
```
npm run build -- Release --target_arch=arm --target_os=android --target_android_output_format=apk
```
I get:
```
Exception during parsing of translations/android_brave_strings_am.xtb

Error processing node <?xml version="1.0" encoding="UTF-8"?>

<file lang="am" path="translations/android_brave_strings_am.xtb" />: Placeholders do not match.: Translation for message ID 7084757528071133475 had <ph name="percentage"/>, no match
```

I'll retry with cr118.

**Comment by AlexeyBarabash** [comment]
Maybe Release/Debug matter,
I'll try on Release.

**Comment by AlexeyBarabash** [comment]
I also got error ` Placeholders do not match`
with this change at `browser/ui/android/strings/android_brave_strings.grd`
```
-      Downloading wallet data file \u2022 <ph name="percentage">%1$d<ex>37</ex></ph>\u0025
+      Downloading wallet data file \u2022 <ph name="percentage">%1$d<ex>37</ex></ph>%%
```
so I added an extra space between  `</ph>` and `%%` https://github.com/brave/brave-core/pull/20378/files#diff-610aa766aabf8f9f7575fdf7e6c497348a13788e0e1bc2e98868ecc115cedba0R3190 
```
Downloading wallet data file \u2022 <ph name="percentage">%1$d<ex>37</ex></ph> %%
```

**Comment by AlexeyBarabash** [comment]
> I'll try on Release.

Release for me also succeeded

**Comment by mkarolin** [comment]
> so I added an extra space between `</ph>` and `%%`

Well, it'll look a bit odd, but if you are guys ok with it, then maybe that's the easiest solution.

**Review by mkarolin — APPROVED** [review]
`strings` ++, if having a space before the `%%` is ok with everyone else.

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Review by Pavneet-Sing — APPROVED** [review]

**Comment by AlexeyBarabash** [comment]
> Well, it'll look a bit odd

I understood what do you mean, changed in 64f1ee02d6088b5bc8507563199987e43b7fccbe .

```
Downloading wallet data file \u2022 <ph name="percentage">%1$d<ex>37</ex></ph>\u0025\u0025
```
it does build good, it is converted to `Downloading wallet data file • %1$d%%` at runtime and looks better on screen. This is the best option.

in opposite,
```
Downloading wallet data file \u2022 <ph name="percentage">%1$d<ex>37</ex></ph>%%
```
causes `<file lang="am" path="translations/android_brave_strings_am.xtb" />: Placeholders do not match.:`

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.61.1 x64 Nightly build
- Verified steps from PR description
- Verified no crash when Wallet data file component is being downloaded on backup wallet screen
- Verified both during onboarding and manually launching the backup wallet screen when component is being downloaded

**Pull request merged**
