### PR TITLE
iOS Sync Uplift fixes + Fix for BrowserMetrics space usage

### PR DESCRIPTION
**Pull request by Brandon-T**
- iOS Sync Uplift fixes from 1.20.x to 1.16.x
- Fix for BrowserMetrics space usage (PR for master is still in review at the time of this PR: https://github.com/brave/brave-core/pull/7349)
- Removes redundant code for exporting bookmarks on iOS
- Refactored `BookmarkNode` by changing its name to `IOSBookmarkNode`
- Fixes so that stuff compiles, lints, and `gn_check` correct for 1.16.x.

Resolves: https://github.com/brave/brave-ios/issues/3099

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by kjozwiak** [comment]
Restarting `macOS` via https://ci.brave.com/job/pr-brave-browser-ios-sync-uplift-1.16.x-v2-macos/2/ due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-ios-sync-uplift-1.16.x-v2-macos/1/execution/node/204/log/.

```
10:09:42  ERROR Unresolved dependencies.
10:09:42  //brave:brave_app(//build/toolchain/mac:clang_x64)
10:09:42    needs //brave/vendor/sparkle:sparkle_resources_bundle_data(//build/toolchain/mac:clang_x64)
```

**Comment by kjozwiak** [comment]
Going to wait till https://github.com/brave/brave-core/pull/7349 passes review/gets merged into `master` before uplifting into `1.16.x`

**Comment by Brandon-T** [comment]
> Restarting `macOS` via https://ci.brave.com/job/pr-brave-browser-ios-sync-uplift-1.16.x-v2-macos/2/ due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-ios-sync-uplift-1.16.x-v2-macos/1/execution/node/204/log/.
> 
> ```
> 10:09:42  ERROR Unresolved dependencies.
> 10:09:42  //brave:brave_app(//build/toolchain/mac:clang_x64)
> 10:09:42    needs //brave/vendor/sparkle:sparkle_resources_bundle_data(//build/toolchain/mac:clang_x64)
> ```

This isn't part of iOS. My PR doesn't use `sparkle` or `brave_app` or `brave/vendor`.

**Comment by bsclifton** [comment]
Removed `PR/Blocked` as https://github.com/brave/brave-core/pull/7349 was merged
cc: @kjozwiak

**Comment by bsclifton** [comment]
I don't see anything that could have caused macOS problem; pushed some of the same lint fixes we did for master. Worst case, we can leave this as a branch and focus on the other uplifts (1.18/1.19). iOS will need to move to 1.18 soon (maybe for 1.23 release?)

**Comment by bsclifton** [comment]
@kjozwiak maybe let's forget this PR (we can keep branch open, as this is what was included in 1.22.1 build). @Brandon-T I'm going to close this one as we can't merge to 1.16 with this error (we'd need to investigate / resolve)

Most important to focus on 1.18 and 1.19 😄 
- 1.18 brave/brave-core#7371
- 1.19 brave/brave-core#7431

**Pull request closed without merging**
