### PR TITLE
Import with ipns keys

### PR DESCRIPTION
**Pull request by spylogsster**
Resolves https://github.com/brave/brave-browser/issues/15422
This is third and final, second part here https://github.com/brave/brave-core/pull/8660

- Added submenus to publish content to ipfs import items
- if keys are not available, no items added
- Publishes content  under selected key
- Copies published IPNS key to clipboard 

image

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
- Check publishing for all IPFS import local menu items:  folder or file
- If publishing was successful the IPNS link should be copied
- Publishing new content over old one for same key should be successful
- if node stopped or keys are not available, the publishing items should not be added

### CODE REVIEW

**Review by lidel — CHANGES_REQUESTED** [review]
Hm.. IPNS is usually used for publishing websites: standalone HTML file or a directory from a disk  with `index.html` inside.  So having that option in the main browser hamburger menu is easy to understand and  lgtm :+1:  

However, including IPNS in context menu has little utility  – standalone files found on the web are fine with immutable `/ipfs/` namespace, no real value in publishing them under `/ipns/`, it just adds noise and confuses users what IPNS is for. 

Can we keep IPNS only for imports from disk via main browser menu? 
I feel it is a safer way of introducing "mutability" to user's mental model of IPFS.

cc @autonome for sanity check

**Comment by bbondy** [comment]
From a UX perspective I think it makes sense, but is there a protocol-level reason to discourage it?

**Comment by lidel** [comment]
Good question.

Brave users may turn off their machines for longer periods of time, go for vacations etc.
In real life there is a slight risk of IPNS records expiring, and publisher not being around to refresh them:
- When one publish something to IPNS, a record is stored on DHT and its `lifetime` defines when it will expire. 
- That record needs to be republished periodically (default lifetime is 24h), so IPNS makes sense only when  publisher is around and keeps record alive on DHT (iirc we have plans for third-party pinning of IPNS records, but it's not implemented yet).

To mitigate this, we may tweak the `lifetime` parameter passed to `ipfs name publish` and increase it from default `24h` to something like `504h` (three weeks). 

(cc @aschmahmann in case there is a better mitigation given how IPNS works right now)

**Comment by aschmahmann** [comment]
> To mitigate this, we may tweak the lifetime parameter passed to ipfs name publish and increase it from default 24h to something like 504h (three weeks).

This is sort of correct, but the TLDR is that in most cases increasing the lifetime does not effectively make the IPNS record last any longer if the publisher has turned off their machine.

There are two different mechanisms that restrict the duration in which one can find an IPNS record:
1. The lifetime parameter on the record: If exceeded clients will reject the record so if the key holder is offline for more than a day the defaults will make it so the record is unresolvable. The lifetime can be extended arbitrarily although it comes with some tradeoffs. For example, with a short lifetime if a user/record is somehow attacked such that they only receive old records they will get a "not found" error instead of the old data, with a longer lifetime they are more likely to get the old data. How important this is, or which outcome is preferable is fairly use case dependent.
2. DHT record lifetimes: A valid IPNS record can be technically put in the IPFS Public DHT by anyone (even someone who is not the author), although go-ipfs doesn't currently support this. However, IPFS Public DHT server nodes will only hold a record for 36hrs. This means that even if I publish my record with a lifetime of 3 weeks unless a friend republishes the record in the DHT people will not be able to find the record (*there are some caveats if people use IPNS over PubSub but it's likely not worth going into here).

**Comment by autonome** [comment]
This is a beautiful thing to behold!

* Any reason to have separate folder/file menu items instead of a simple "add to ipfs" that detects folder/file?
* Instead of "IPFS" on the subsubmenu, "My shares" or something like that would be more explicit description of what menu contents mean
* This is new and weird enough (relative to typical browser functionality) that I think a documentation link on the submenu is worth considering. There's shares, and keys, etc. Maybe after the items, add separator and a "Learn more".
* Or maybe do above only when there's no items?
* What happens when underlying folders/files are deleted? Tests cover that? (i assume there's state managed somewhere for the list?)
* For deleted-under-us scenario, would be nice if added a ❌ or something on the left of the entry instead of just silent disappear. but that also opens up how to actually remove it... mo clarity, mo problems.
* Is there a naming convention or special folder in the repo these are kept under, so in WebUI it's clear what these are?

**Comment by spylogsster** [comment]
> This is a beautiful thing to behold!
> 
> * Any reason to have separate folder/file menu items instead of a simple "add to ipfs" that detects folder/file?
> * Instead of "IPFS" on the subsubmenu, "My shares" or something like that would be more explicit description of what menu contents mean
> * This is new and weird enough (relative to typical browser functionality) that I think a documentation link on the submenu is worth considering. There's shares, and keys, etc. Maybe after the items, add separator and a "Learn more".
> * Or maybe do above only when there's no items?
> * What happens when underlying folders/files are deleted? Tests cover that? (i assume there's state managed somewhere for the list?)
> * For deleted-under-us scenario, would be nice if added a ❌ or something on the left of the entry instead of just silent disappear. but that also opens up how to actually remove it... mo clarity, mo problems.
> * Is there a naming convention or special folder in the repo these are kept under, so in WebUI it's clear what these are?

```Any reason to have separate folder/file menu items instead of a simple "add to ipfs" that detects folder/file?```
it is separated in the dialog options, Im not sure it is possible in chromium to have one dialog for both

```* Instead of "IPFS" on the subsubmenu, "My shares" or something like that would be more explicit description of what menu contents mean```
"My IPFS shares" maybe? Cc @bbondy 

```> * This is new and weird enough (relative to typical browser functionality) that I think a documentation link on the submenu is worth considering. There's shares, and keys, etc. Maybe after the items, add separator and a "Learn more".```
Which link would be better?

```For deleted-under-us scenario, would be nice if added a ❌ or something on the left of the entry instead of just silent disappear. but that also opens up how to actually remove it... mo clarity, mo problems.```
do you mean we have to some markers for deleted keys in the submenu? 


```Is there a naming convention or special folder in the repo these are kept under, so in WebUI it's clear what these are?```
All imported content saved to /brave-imports/[date]

**Comment by bbondy** [comment]
> it is separated in the dialog options, Im not sure it is possible in chromium to have one dialog for both

Ya I believe the OS level file/folder dialogs are for either file or folder, and there's not an option to select either of them in a single UI.

> * Instead of "IPFS" on the subsubmenu, "My shares" or something like that would be more explicit description of what menu contents mean
> "My IPFS shares" maybe? Cc @bbondy

I think you might not have seen the IPNS key management screen in settings yet.  So the things in that submenu are not previous shares, but they are the keys that are added manually. 

https://user-images.githubusercontent.com/831718/117465635-e4a81600-af1f-11eb-823e-efd7b3a20181.mp4

> > * This is new and weird enough (relative to typical browser functionality) that I think a documentation link on the submenu > is worth considering. There's shares, and keys, etc. Maybe after the items, add separator and a "Learn more".
> Which link would be better?

I think we could have a Learn more about sharing on IPFS submenu that links to another community page link, like the one we have for privacy considerations.   


For the other questions...

Anything selected by the user would be copied into a brave-managed space, so there's no problem if a user later changes the source files.

**Comment by lidel** [comment]
Ack, but this submenu is confusing even when someone knows what IPNS is :)

> 


I suggest we make things more friendly to users:
- Rename "IPFS" to "Import and copy link to snapshot"
- If user has generated keys (other than `self`): add new a divider  and a header  (or a separate submenu?) saying "Import and publish under IPNS key"

Both ways should copy a shareable link to clipboard + open imported directory in webui.

IPNS variant will be a bit awkward because users won't be able to update a published website from webui, but if we don't show "Publish with IPNS key" section  when user has no keys, it should be fine for now.

**Review by bbondy — APPROVED** [review]

**Pull request merged**
