### PR TITLE
NTP: Add "Customize" text to dashboard settings icon

### PR DESCRIPTION
**Pull request by cezaraugusto**
Fix https://github.com/brave/brave-browser/issues/4930

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:

To see changes live without building Brave, run

```
npm run storybook
```
Changes in this PR should match screenshot

Screen Shot 2020-03-30 at 16 16 14

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
oooo this is nice ❤️

**Comment by karenkliu** [comment]
> This'll be a great change, nice work 😄 Besides what @karenkliu shared, I think it might be good to put `user-select: none` on the actual div around `Customize` so that it's not click drag selectable
> 
> Also the focus ring only goes on the icon itself. @karenkliu should this go around the whole thing? or only be on the icon?
> Screen Shot 2020-03-31 at 12 57 55 AM

@bsclifton @cezaraugusto Around the whole thing! The entire clickable button area.
Screen Shot 2020-03-31 at 10 00 37 AM

**Comment by cezaraugusto** [comment]
Thanks team, updated per screenshot. If unsure, `npm run storybook` should display the same output.

Screen Shot 2020-04-01 at 18 44 13

**Comment by cezaraugusto** [comment]
Thanks @karenkliu for the quick review. Feedback applied.

**Current result:**

Screen Shot 2020-04-01 at 19 23 40

**Also looking good in RTL:**

‏لقطة الشاشة ٢٠٢٠-٠٤-٠١ في ١٩ ٢٠ ٣١

**Comment by karenkliu** [comment]
looks good to me!

**Comment by cezaraugusto** [comment]
Thanks team!

**Pull request merged**
