### PR TITLE
Updates brave-ui -> 0.36.0

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/brave/brave-browser/issues/2381

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  -  [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
1. Build brave from this branch
2. Be sure Rewards is enabled
3. Go to a website such as brave.com, click on the wallet panel and hit "Send a Tip"
4. Ensure switching token amounts on the site banner triggers an insufficient funds message if appropriate
5. Ensure there are no issues sending a donation, no console errors etc.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@cezaraugusto can we update to 0.36 (introducing 0.35) where you did a lot of changes in 0.35 for sync v2?

**Comment by petemill** [comment]
This update includes from brave-ui:
 - Site banner icon update @rossmoody 
 - insufficientFunds notification @emerick 
 - use string for amount / tokens @ryanml 
 - Add disabledPanel component @ryanml

**Comment by petemill** [comment]
Seems like this also has sync v2 in it 😬 @cezaraugusto

**Comment by petemill** [comment]
Reverting...

**Comment by petemill** [comment]
Reverted with https://github.com/brave/brave-core/pull/1051/commits/4148df7ac84455cd21d59c5a97e01b6fdd4188b6 via #1051

**Pull request merged**
