### PR TITLE
[1.71.x] Do not use destroyed webcontents in ai chat tab helper.

### PR DESCRIPTION
**Pull request by iefremov**
Resolves https://github.com/brave/brave-browser/issues/41124

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by darkdh — APPROVED** [review]
Please also uplift to release, thanks

**Comment by srirambv** [comment]
Verification  passed on 

Brave | 1.72.48 Chromium: 129.0.6668.70 (Official Build) nightly (64-bit) 
-- | --
Revision | 70b441e85b783a65b0088d92c496fa56d6509945
OS | Linux

- Verified steps from issue description
- Verified no crash when closing tab with sidebar open and Leo set to focus

https://github.com/user-attachments/assets/4fe71d93-d55c-4000-987f-4b91fd46e393

**Comment by bsclifton** [comment]
@srirambv nothing was merged yet? I think Nightly has a different scenario, as captured in https://github.com/brave/brave-browser/issues/41124#issuecomment-2380622236

We'd need to merge this PR in order to do verification (or if reviewer builds and verifies manually)

**Review by bsclifton — APPROVED** [review]
Code changes LGTM

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.71.102 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | d901535b1091c5f39eb2b5426b8fa8e7f3c5edf0
OS | Windows 11 Version 23H2 (Build 22631.4169)

- Verified steps from [brave-browser#41124 (comment)](https://github.com/brave/brave-browser/issues/41124#issuecomment-2364593059)
- Verified no crash when closing the browser with sidebar open
- Encountered [#41320](https://github.com/brave/brave-browser/issues/41320)

https://github.com/user-attachments/assets/0483570e-1d88-44f5-8026-0b1624478ed8

**Pull request merged**
