### PR TITLE
Dismiss Leo if user clicks on URL bar

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Resolves https://github.com/brave/brave-browser/issues/35669

This PR adds url focus change event listener into BraveLeoActivity and when it is fired, hide the Leo activity.

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
See the issue

https://github.com/brave/brave-core/assets/24739341/8d22aaa9-c5c1-447f-b20f-0f3d27eb8f63

### CODE REVIEW

**Review by deeppandya — APPROVED** [review]
LGTM

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Review by samartnik — COMMENTED** [review]
lgtm

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 8` running `Android 14` using the following build(s):

```
Brave | 1.64.65 Chromium: 122.0.6261.29 (Official Build) canary (64-bit)
--- | ---
Revision | a31a4290998445a19f5f22b803256e97ec3036a5
OS | Android 14; Build/UQ1A.240105.004; 34; REL
```

Using the STR/Cases mentioned via https://github.com/brave/brave-browser/issues/35669#issue-2105960433 and the example demonstrated via https://github.com/brave/brave-core/pull/21994#issue-2128687782, ensured that tapping on the `omnibox` while `Leo` is opened closes `Leo` and displays the `OSK` as per the following:

https://github.com/brave/brave-core/assets/2602313/3dbc6635-4793-4b6a-9443-49ca56e4b668

**Pull request merged**
