### PR TITLE
Fix for CAPTCHA problem in Release channel (1.16.x - already fixed in Chromium 87 upgrade)

### PR DESCRIPTION
**Pull request by bsclifton**
Fixes https://github.com/brave/brave-browser/issues/12359

## Test I tried when looking for a fix
I worked back on previous versions of Brave using a simple test:
1. Fresh profile
2. Launch Brave + visit paypal.com
3. Login to real account

After login, you are either shown:
a. SMS 2FA screen (I consider a success)
b. Challenge screen (I consider this a failure)

## When did this problem start?
Using this test, I was able to trace the first Release version that broke down to `1.15.72`. Using Beta/Dev versions I was able to further narrow that down to:
- `1.15.56` does NOT have the problem
- `1.15.59` DOES have the problem

## What this PR includes (and why)

What landed between those versions was Chromium 86 with https://github.com/brave/brave-core/pull/6195.
In Nightly, the overall problem seems to be gone and Nightly was recently upgraded to Chromium 87 with https://github.com/brave/brave-core/pull/6554

In Chromium 86, I saw this commit which caught my eye:
https://github.com/brave/brave-core/pull/6195/commits/ea29650533277ae7bf629184fd63a9c01fb29352

In Chromium 87, this was revisited and fixed properly:
https://github.com/brave/brave-core/pull/6554/commits/0b06833973ed72a373cd0a5dbb5725670501c258

This PR pulled that in along with the following commit from Chromium 87:
https://github.com/brave/brave-core/pull/6554/commits/aadceeb4ba746fa5f557b62536a6e3651ca2ce22

## Steps to verify fix
1. Clone `brave-browser`
2. Check out `1.16.x` branch
3. Edit package.json to point at this branch (`bsc-1.16.x`)
4. Run `npm run init && npm run build -- Release --gn=is_official_build:true`
5. After compile finishes, move your `Brave-Browser` profile (if you have one) so that you have a clean profile
6. Launch using `npm start -- Release`
7. Try PayPal login (described above)
8. You should not be shown a CAPTCHA

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [x] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [x] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`, `npm run gn_check`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [ ] Added appropriate QA labels (`QA/Yes` or `QA/No`) to the associated issue
- [ ] Added appropriate release note labels (`release-notes/include` or `release-notes/exclude`) to the associated issue
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Review by antonok-edm — COMMENTED** [review]
I built and confirmed that this fixed the captcha issues we've been seeing (at least for me!)

**Review by mariospr — APPROVED** [review]
I was not aware of this being an issue but, now I saw this PR, it reminded me that lately I "had the feeling" that I was seeing more captcha challenges than what I recalled in the past... and this PR fixed that for me as well (at least in the cases I normally saw them, in www.correos.es > "Localizar Envío"). LGTM!

**Review by iefremov — APPROVED** [review]

**Comment by iefremov** [comment]
Can't test it myself - don't have a paypal account - but changes look fine

**Review by antonok-edm — APPROVED** [review]

**Comment by bsclifton** [comment]
CI looks good on all platforms (ex: lint/build/unit and browser tests all passed)

Only problem is `audit-deps` which @jumde fixed already in master ([uplift available to 1.16.x here](https://github.com/brave/brave-core/pull/7006))

Audit deps issue:
- [iOS](https://ci.brave.com/job/pr-brave-browser-bsc-1.16.x-ios/6/execution/node/139/log/)
- [Windows](https://ci.brave.com/job/pr-brave-browser-bsc-1.16.x-windows/6/execution/node/158/log/)
- [macOS](https://ci.brave.com/job/pr-brave-browser-bsc-1.16.x-macos/6/execution/node/144/log/)
- [Linux](https://ci.brave.com/job/pr-brave-browser-bsc-1.16.x-linux/6/execution/node/148/log/)
- [Android](https://ci.brave.com/job/pr-brave-browser-bsc-1.16.x-android/6/execution/node/156/log/)

**Pull request merged**
