### PR TITLE
1.19.x - Brave Today production urls (Uplift #7300)

### PR DESCRIPTION
**Pull request by petemill**
Uplift #7300 / brave/brave-browser#12601 to 1.19.x

### CODE REVIEW

**Comment by kjozwiak** [comment]
Restarting `macOS` due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-1.19.x-today-prod-macos/1/execution/node/206/log/.

**Comment by kjozwiak** [comment]
`test-browser` failed on `macOS` due to `RewardsPromotionBrowserTest.ClaimViaSettingsPage` failing as per https://ci.brave.com/job/pr-brave-browser-1.19.x-today-prod-macos/2/execution/node/253/log/. However, the failure is a known intermittent issue and doesn't block uplift.


```
00:13:36  1 test timed out:
00:13:36      RewardsPromotionBrowserTest.ClaimViaSettingsPage (../../brave/components/brave_rewards/browser/test/rewards_promotion_browsertest.cc:196)
```

**Comment by kjozwiak** [comment]
Ready to uplift/merge but going to wait till we get a go ahead from either @jsecretan or @petemill as per the discussion in today's b-c planning/triage meeting. CCing @rebron @bsclifton.

**Comment by petemill** [comment]
Content at this URL looks good to me now, ready to merge IMO https://github.com/brave/brave-core/pull/7300#issuecomment-737589499

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.19.x` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
