### PR TITLE
[iOS] Handle non-passbook attachment downloads correctly

### PR DESCRIPTION
**Pull request by kylehickinson**
Resolves https://github.com/brave/brave-browser/issues/41073

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

From https://community.brave.com/t/downloaded-videos-on-ios/568738/4
- Copy an instagram link (e.g. `https://www.instagram.com/reel/DABSg8nJb4D/`)
- Visit `snapinsta.app` and submit the link to be downloaded
- Click "Download" when it appears

### CODE REVIEW

**Review by Brandon-T — APPROVED** [review]

**Comment by bompao108** [comment]
Still get nothing after finishing download video from Youtube and Tiktok
IMG_0465
IMG_0466
IMG_0467

**Comment by Brandon-T** [comment]
> Still get nothing after finishing download video from Youtube and Tiktok
> 
> IMG_0465
> 
> IMG_0466
> 
> IMG_0467
> 
> 


Can you please provide the steps you took to download the TikTok video?

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.72 (27)`

**Case: snapinsta.app** - **`PASSED`**

- Went through the test steps below and ensured that file is downloaded successfully and shown in `Downloads` folder. 
   - Copy an instagram link (e.g. https://www.instagram.com/reel/DABSg8nJb4D/)
   - Visit snapinsta.app and submit the link to be downloaded
   - Click "Download" when it appears
   
example | example | example
---|---|---
IMG_7380 | IMG_7381 | IMG_7382

**Case: PDF download** - **`PASSED`**

<details>

- Ensured that downloading PDF files is working using `Save to Files` in share menu

example | example
---|---
IMG_7384 | IMG_7385

</details>

**Case: Saving Image to Photos** - **`PASSED`**

<details>

example | example
---|---
IMG_7393 | IMG_7395

</details>
 
 **Case: Add to Wallet** - **`PASSED`**
 
 <details>
 
 example | example
 ---|---
IMG_7387 | IMG_7388

</details>

**Case: Direct Download (unsplash)** - **`PASSED`**

<details>

example | example
---|---
IMG_7389 | IMG_7390

</details>

**Case: App Download** - **`PASSED`***

<details>

example | example
---|---
IMG_7391 | IMG_7392

</details>

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.72 (27)
BraveCore: 1.72.27 (129.0.6668.59)
```
---------------------------

<details>
<summary> Direct Download Picture </summary>

**STEPS:**
1. Launch Brave 
2. Go to https://unsplash.com/
3. Download a random image > *Verify*

**ACTUAL RESULTS:**
- Verified that downloading images directly using the `Download` button works as expected.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
|  |  |  |
</details>

<details>
<summary> App Download </summary>

**STEPS:**
1. Launch Brave 
2. Go to https://apkmirror.com/
3. Download a random app  > *Verify*

**ACTUAL RESULTS:**
- Verified that downloading an app using the `Download` button works as expected.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
|  |  |  |
</details>

<details>
<summary> Instagram Download </summary>

**STEPS:**
1. Launch Brave 
2. Go to https://snapinsta.app/ > Paste the link https://www.instagram.com/p/DABAwvLM41w/?igsh=dmlndm1uM2kxb2pt
3. Download an image > *Verify*

**ACTUAL RESULTS:**
- Verified that downloading an image from `https://snapinsta.app/` works as expected.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
|  |  |  |
</details>

<details>
<summary> PDF download </summary>

**STEPS:**
1. Launch Brave 
2. Go to https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf
3. Save PDF > *Verify*

**ACTUAL RESULTS:**
- Verified that saving PDF works as expected.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
|  |  |  |
</details>

<details>
<summary> Adding ticket/pass to Apple Wallet </summary>

**STEPS:**
1. Launch Brave 
2. Go to https://pub1.pskt.io/4wcEqRJZVWU7XGKbt6sXof on Desktop
3. Scan QR code > Add to Wallet > *Verify*

**ACTUAL RESULTS:**
- Verified that the pass can be downloaded and saved to Apple Wallet.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
|  |  |  |
</details>

<details>
<summary> Song download </summary>

**STEPS:**
1. Launch Brave 
2. Go to https://www.last.fm/ru/music/+free-music-downloads
3. Download a song > *Verify*

**ACTUAL RESULTS:**
- Verified that a song can be downloaded successfully.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
|  |  |  |
</details>

**Comment by bompao108** [comment]
> Verified on `iPhone 14` using version(s):
> 
> ```
> Device/OS: iPhone 14 / iOS 17.7
> Brave build: 1.72 (27)
> BraveCore: 1.72.27 (129.0.6668.59)
> ```
> 
>  Direct Download Picture
>  App Download
>  Instagram Download
>  PDF download
>  Adding ticket/pass to Apple Wallet
>  Song download

Where u download this version of Brave ?

**Comment by kjozwiak** [comment]
> > Verified on `iPhone 14` using version(s):
> > ```
> > Device/OS: iPhone 14 / iOS 17.7
> > Brave build: 1.72 (27)
> > BraveCore: 1.72.27 (129.0.6668.59)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Direct Download Picture
> > App Download
> > Instagram Download
> > PDF download
> > Adding ticket/pass to Apple Wallet
> > Song download
> 
> Where u download this version of Brave ? I'm at 1.69.1 and it's the newest version on appstore

@bompao108 it's on an internal build via TF (TestFlight). We just verified the above fix and merged it into `1.71.x`, `1.70.x` & `1.69.x`. We'll be kicking off RC (Release Candidate) builds in a few moments. We're hoping to push the fixed build for Apple Review and start releasing it sometime today/tomorrow. But it depends on how long it takes Apple to approve the builds.

**Comment by bompao108** [comment]
Finally it works
Thank devs

**Pull request merged**
