### PR TITLE
Upload windows stub/standalone installers to Github.

### PR DESCRIPTION
**Pull request by mbacchi**
Also update DEPS to use the most recent changes that
build and sign the installers during the
`create_dist --build_omaha` step.

Fixes https://github.com/brave/brave-browser/issues/1992

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by simonhong** [comment]
How about appending version to uploaded brave_installer.exe and standalone installer? @bbondy

**Comment by bbondy** [comment]
I think it might be easier for some automation and such to not have the version in the filename, but having the version in the file properties should be there.

**Comment by simonhong** [comment]
I checked that brave_installer.exe alreay has proper version info in file properties.
But, standalone installer has omaha version in file properties.
Created issue for that. https://github.com/brave/brave-browser/issues/2002

**Comment by simonhong** [comment]
I'll pass to @mihaiplesa for reviewing (I don't know much about uploading stuff)

**Comment by kjozwiak** [comment]
Approved uplift to `0.56.x` 👍

**Comment by NejcZdovc** [comment]
master (0.59) cfa1807
0.58.x da23ee0d
0.57.x c7953743
0.56.x some merge conflicts @mbacchi can you please cherry pick it to 56

**Comment by mbacchi** [comment]
0.56.x: 1f389f9cdde17312a397b5a2c3c9a4482c7aae5b  (had to uplift https://github.com/brave/brave-core/pull/747 first to avoid merge conflict)

**Pull request merged**
