### PR TITLE
Fixed crash when fetching Rewards Widget estimated earnings

### PR DESCRIPTION
**Pull request by tmancey**
Resolves https://github.com/brave/brave-browser/issues/14447

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

- Confirm Rewards Widget estimated earnings are updated after a fresh install
- Confirm Rewards Widget estimated earnings are updated after viewing at least 1 ad
- Confirm Rewards Widget estimated earnings are updated after refreshing a new tab page
- Confirm "Restarting ads service" does not appear in the console logs

### CODE REVIEW

**Review by emerick — APPROVED** [review]
LGTM

**Review by zenparsing — APPROVED** [review]

**Review by moritzhaller — APPROVED** [review]
LGTM

**Comment by tmancey** [comment]
CI failed for known audit dep issue

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.23.24 Chromium: 89.0.4389.82 (Official Build) nightly (64-bit)
-- | --
Revision | 8d785cc4e2b89bff35f6a21710215271fb8fd782-refs/branch-heads/4389@{#1433}
OS | Windows 10 OS Version 2009 (Build 19042.844)
```

* ensured that clicking on `Startg using Rewards` via `brave://newtab` works as expected
* ensured that `estiamted earnings` is being updated in a previously opened `brave://newtab` after viewing an ad
* ensured that the correct `estimated earnings` is being displayed when opening a new `brave://newtab` after viewing an ad
* ensured that refreshing `brave://newtab` right after viewing an ad doesn't crash Brave and updates `estiamted earnings` correctly
* ensured that that `estimated earnings` under `brave://rewards` match the value that's being displayed under `brave://newtab`
* ensured that `Restarting ads service` isn't appearing in the CLI/terminal logs


However, ran into https://github.com/brave/brave-browser/issues/14143 while running through the above which appears to be a known issue and not a new regression due to the above PR.

**Comment by tmancey** [comment]
@kjozwiak I did not see the above ticket as it was assigned to the rewards project, however I have closed https://github.com/brave/brave-browser/issues/14143 as it is a duplicate of https://github.com/brave/brave-browser/issues/13267

**Pull request merged**
