### PR TITLE
Period added in Tor/.onion Settings description

### PR DESCRIPTION
**Pull request by tonycoldashian**
Fixes https://github.com/brave/brave-browser/issues/16326

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by bsclifton** [comment]
@tonycoldashian can you please amend your commit to use closing keywords? You'd basically run `git commit --amend` and then for the message you should be able to put:
```
Period added in Tor/.onion Settings description

Fixes https://github.com/brave/brave-browser/issues/16326
```

I'll edit your PR description so it's using that syntax too 😄 Because the issues are in `brave-browser` (and this is `brave-core`) it wasn't able to link by #

**Comment by tonycoldashian** [comment]
Hey @bsclifton, sorry about that.
The problem is , I'm on limited data plan so I couldn't clone the repo, I made the edits from Github itself(used Github1s) and didn't use the terminal in anyway. So, I'm unable to do what you asked (ammending the commit) , sorry :/ 
If there is any other way, please let me know.
Thank You.

**Comment by bsclifton** [comment]
No worries @tonycoldashian - since I made the edit to this PR, it should take effect 😄

**Review by bsclifton — APPROVED** [review]
Change looks great! Thanks 😄

**Comment by tonycoldashian** [comment]
@bsclifton  Thank You! :D

**Comment by bsclifton** [comment]
@tonycoldashian thank you 😄

**Pull request merged**
