### PR TITLE
Implement state level ads delivery - 1.11.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/5602
Resolves https://github.com/brave/brave-browser/issues/9200

- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [ ] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
Asked discussed with @jimmy and @rebron, this isn't making `1.11.x`. However, we'll try getting this into the next `1.11.x` HF once we get a minor CR 84 bump which is bound to happen. At that point, we'll need to rebase the above as there's already a merge conflict as per the above.

**Comment by bbondy** [comment]
@tmancey FYI looks like there's merge conflicts

**Comment by tmancey** [comment]
CI failed for macOS and known audit deps, restarting macOS

**Comment by bsclifton** [comment]
Removing milestone for the moment - 1.11.x is live

**Comment by tmancey** [comment]
Closing as it was decided to let this feature ride the trains

**Pull request closed without merging**
