### PR TITLE
Removes support for legacy anonymous Uphold cards.

### PR DESCRIPTION
**Pull request by szilardszaloki**
Resolves https://github.com/brave/brave-browser/issues/24464.

- Removed:
  - backup tab that we showed only to users who had user funds (i.e. anonymous wallet balance > 0):

    legacy_backup_tab
  - notification that told the user to back up their wallet (should have been shown only to users who had user funds (i.e. anonymous wallet balance > 0) — for regular users, clicking on the `Back up now` button took them to `chrome://rewards#manage-wallet`, where they were told to verify their Rewards wallets):

    notification_backup_wallet
  - P3A (based on @Miyayes' audit):
    - [Q11 - deprecated](https://github.com/brave/brave-browser/wiki/P3A#q11-what-is-the-state-of-your-brave-rewards-wallet) (`Brave.Rewards.WalletState`) and the logic that populated its answers
	- [Q12 - deprecated](https://github.com/brave/brave-browser/wiki/P3A#q12-how-much-bat-excluding-grants-is-in-your-wallet) (`Brave.Rewards.WalletBalance.3`) and the logic that populated its answers
  - prefs:
    - `kBackupNotificationInterval`
	- `kBackupSucceeded`
	- `kFetchOldBalance`
	- `kUserHasClaimedGrant`
	- `kUserHasFunded`
  - anonymous wallet/user funds processor references in the contribution engine
  - `POST /v1/orders/{order_id}/transactions/anonymousCard` endpoint implementation
  - `GET /v3/wallet/uphold/{payment_id}` endpoint implementation
  
- Adjusted:
  - balance fetch
  - Uphold linking
  - wallet creation
  - wallet recovery

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by szilardszaloki** [comment]
@deeppandya @Brandon-T Please let me know if I'm missing any references, or any related parts on mobile that we should get rid of. Thanks!

**Comment by szilardszaloki** [comment]
iOS [build](https://ci.brave.com/job/test-brave-browser-build-ios/151/)

**Review by deeppandya — APPROVED** [review]
Android changes LGTM

**Comment by tmancey** [comment]
@szilardszaloki maybe not for now, but would be good to check if we can remove any #includes

**Review by tmancey — APPROVED** [review]
LGTM++ (see nit)

**Review by emerick — APPROVED** [review]
LGTM

**Comment by szilardszaloki** [comment]
> @szilardszaloki maybe not for now, but would be good to check if we can remove any #includes
@tmancey I did miss a couple. Good catch, thanks!

**Review by zenparsing — APPROVED** [review]
Looks good. For QA'ing, I would suggest maybe testing the uphold linking and draining flow.

**Review by kylehickinson — APPROVED** [review]
iOS++

**Pull request merged**
