### PR TITLE
Fix perf predictor tab helper tests after #7247

### PR DESCRIPTION
**Pull request by antonok-edm**
Fixes test regressions @mkarolin noticed from #7247.

Will need uplift to Beta as well.

### CODE REVIEW

**Review by mkarolin — APPROVED** [review]
These test pass for me now.

**Review by yrliou — APPROVED** [review]
I met this locally and this patch fixed it for me too.

**Comment by kjozwiak** [comment]
Added the correct milestone as it was missing. Just double checking, does this have an associated issue with it?

**Comment by antonok-edm** [comment]
@kjozwiak I didn't bother making an issue since it's such a small test-only change as followup to #7247

**Comment by kjozwiak** [comment]
> @kjozwiak I didn't bother making an issue since it's such a small test-only change as followup to #7247

Sounds good 👍

**Comment by antonok-edm** [comment]
@kjozwiak just a heads up that we now have https://github.com/brave/brave-browser/issues/12995 to track this PR

**Pull request merged**
