### PR TITLE
Start ledger process and load extension (if needed) before opening Rewards panel

### PR DESCRIPTION
**Pull request by emerick**
Resolves https://github.com/brave/brave-browser/issues/21311

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by zenparsing — APPROVED** [review]

**Comment by bsclifton** [comment]
Should this code be changed too?
https://github.com/brave/brave-core/blob/34aa8ac7771b1f7c0a8297958c7662083d64efbb/browser/extensions/brave_component_loader.cc#L150-L157

**Review by bsclifton — APPROVED** [review]
Code here LGTM! 😄 I had deleted some comments when thinking things through (was thinking to self, maybe add pref_change_registrar check for ads preference too)

One thought I did have though `EnsureBrowserContextKeyedServiceFactoriesBuilt` gets called at profile creation. We could add the call to `AddRewardsExtension` in the `RewardsServiceFactory` (ex: inside `BuildServiceInstanceFor`)

**Comment by zenparsing** [comment]
@bsclifton I agree that extension loading should be managed from one place in the code. Unfortunately, as we've baked more UI into the rewards extension, we've added more paths that need the extension loaded. Ultimately though, we'll want to stop using the extension for the panel altogether.

**Comment by emerick** [comment]
@bsclifton @zenparsing If it's OK, I'm going to keep this as-is since the current change is completely isolated to adaptive captcha (that code isn't called from anywhere else) and we want to uplift this into `1.36` ASAP. The Rewards team is meeting today, so I can bring up the long-term plans for extension management (or discuss whether the extension just goes away) at that meeting. Will follow up here with a pointer to issues, etc. post-meeting!

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.38.6 Chromium: 99.0.4844.45 (Official Build) nightly (64-bit)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | Windows 11 Version 21H2 (Build 22000.527)
```

Verification notes can be found via https://github.com/brave/internal/issues/857#issuecomment-1053884823.

**Pull request merged**
