### PR TITLE
Updating fiat currency list for Bitcoin.com [NTP widget]

### PR DESCRIPTION
**Pull request by ryanml**
Fixes brave/brave-browser#12016

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`, `npm run gn_check`)
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [x] Added appropriate QA labels (`QA/Yes` or `QA/No`) to the associated issue
- [ ] Added appropriate release note labels (`release-notes/include` or `release-notes/exclude`) to the associated issue
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
Defined in issue

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Review by emerick — APPROVED** [review]
LGTM

**Comment by srirambv** [comment]
@ryanml we should probably follow the convention mentioned in the link. Currency type is not capitalized its `Australian dollar` instead of `Australian Dollar`

**Comment by srirambv** [comment]
@ryanml we should probably follow the convention mentioned in the link. Currency type is not capitalized its `Australian dollar` instead of `Australian Dollar`

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.17.18 Chromium: 86.0.4240.72 (Official Build) nightly (x86_64) | 1.17.18 Chromium: 86.0.4240.72 (Official Build) nightly (64-bit) | 1.17.18 Chromium: 86.0.4240.72 (Official Build) nightly (64-bit)
-- | -- | -- | --
Revision | `581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}` | `581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}` | `581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}` 
OS | macOS Version 10.15.7 (Build 19H2) | Linux | Windows 10 OS Version 1809 (Build 17763.1457)
Screenshot | image | image | image

- Verified the following list of currencies are listed 

```html
<div class="FiatItems-sc-321kd3 rTUoB">
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">AUD</div><span class="FiatName-sc-131iu93 DZDvN">Australian dollar</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">BGN</div><span class="FiatName-sc-131iu93 DZDvN">Bulgarian lev</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">CAD</div><span class="FiatName-sc-131iu93 DZDvN">Canadian dollar</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">CHF</div><span class="FiatName-sc-131iu93 DZDvN">Swiss franc</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">CNY</div><span class="FiatName-sc-131iu93 DZDvN">Chinese yuan</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">COP</div><span class="FiatName-sc-131iu93 DZDvN">Colombia peso</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">CZK</div><span class="FiatName-sc-131iu93 DZDvN">Czech Koruna</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">DKK</div><span class="FiatName-sc-131iu93 DZDvN">Danish krone</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">DOP</div><span class="FiatName-sc-131iu93 DZDvN">Dominican peso</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">EGP</div><span class="FiatName-sc-131iu93 DZDvN">Egyptian pound</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">EUR</div><span class="FiatName-sc-131iu93 DZDvN">Euro</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">GBP</div><span class="FiatName-sc-131iu93 DZDvN">Pound sterling</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">HKD</div><span class="FiatName-sc-131iu93 DZDvN">Hong Kong dollar</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">HRK</div><span class="FiatName-sc-131iu93 DZDvN">Croatian kuna</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">IDR</div><span class="FiatName-sc-131iu93 DZDvN">Indonesian rupiah</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">ILS</div><span class="FiatName-sc-131iu93 DZDvN">Israeli new shekel</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">JPY</div><span class="FiatName-sc-131iu93 DZDvN">Japanese yen</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">JOD</div><span class="FiatName-sc-131iu93 DZDvN">Jordanian dollar</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">KES</div><span class="FiatName-sc-131iu93 DZDvN">Kenyan shilling</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">KRW</div><span class="FiatName-sc-131iu93 DZDvN">South Korean won</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">KWD</div><span class="FiatName-sc-131iu93 DZDvN">Kuwaiti dinar</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">LKR</div><span class="FiatName-sc-131iu93 DZDvN">Sri Lankan rupee</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">MAD</div><span class="FiatName-sc-131iu93 DZDvN">Moroccan dirham</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">MXN</div><span class="FiatName-sc-131iu93 DZDvN">Mexican peso</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">MYR</div><span class="FiatName-sc-131iu93 DZDvN">Malaysian ringgit</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">NGN</div><span class="FiatName-sc-131iu93 DZDvN">Nigerian naira</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">NOK</div><span class="FiatName-sc-131iu93 DZDvN">Norwegian krone</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">NZD</div><span class="FiatName-sc-131iu93 DZDvN">New Zealand dollar</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">OMR</div><span class="FiatName-sc-131iu93 DZDvN">Omani rial</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">PEN</div><span class="FiatName-sc-131iu93 DZDvN">Peruvian sol</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">PKR</div><span class="FiatName-sc-131iu93 DZDvN">Pakistanee rupee</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">PLN</div><span class="FiatName-sc-131iu93 DZDvN">Polish złoty</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">RON</div><span class="FiatName-sc-131iu93 DZDvN">Romanian leu</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">RUB</div><span class="FiatName-sc-131iu93 DZDvN">Russian ruble</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">SEK</div><span class="FiatName-sc-131iu93 DZDvN">Swedish krona</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">SGD</div><span class="FiatName-sc-131iu93 DZDvN">Singapore dollar</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">THB</div><span class="FiatName-sc-131iu93 DZDvN">Thai baht</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">TRY</div><span class="FiatName-sc-131iu93 DZDvN">Turkish lira</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">TWD</div><span class="FiatName-sc-131iu93 DZDvN">Taiwan dollar</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">USD</div><span class="FiatName-sc-131iu93 DZDvN">United States dollar</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">VND</div><span class="FiatName-sc-131iu93 DZDvN">Vietnamese đồng</span></div>
    <div class="FiatItem-sc-2qhmx4 kdEuAO">
        <div class="FiatSymbol-sc-xnde06 hFhaWa">ZAR</div><span class="FiatName-sc-131iu93 DZDvN">South African rand</span></div>
</div>
```

**Pull request merged**
