### PR TITLE
Clear group id in-advance when tab is moved to pinned container

### PR DESCRIPTION
**Pull request by simonhong**
Our vertical tab uses CompoundTabContainer.
When tab is moved from the group by pinning, it's moved to
pinned TabContainerImpl before its tab group id is cleared.
And it causes runtime crash as using this tab from pinned TabContainerImpl
has assumption that it's not included in any group.
So, clear in-advance when tab enters to pinned TabContainerImpl.

and `BraveTabStripModel::ExecuteContextMenuCommand` changes could be deleted now.
When tab is moved by pinning, `TabStripModel::MoveTabToIndexImpl` clears that tab's group id first from model via `contents_data_->MoveTabRecursive(initial_index, final_index, group, pin)`.
and then moving changes notification is fired. So, we just need to clear `Tab`'s groud id.
`Tab::SetData()` is somewhat general api that can be called from some other places but
it's good place to clear its group id as `SetData()` is called whenever tab moving by pinning.

This PR is based on @Ilie-Lesan 's PR(https://github.com/brave/brave-core/pull/25406).

and I'll f/u this issue in upstream also - https://chromium-review.googlesource.com/c/chromium/src/+/5919961

Resolves https://github.com/brave/brave-browser/issues/40365

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

`VerticalTabStripBrowserTest.PinningGroupedTab`
See the linked issue for manual test

### CODE REVIEW

**Review by goodov — APPROVED** [review]

**Comment by iefremov** [comment]
@simonhong pls make sure to get it uplifted as needed, thanks :)

**Comment by simonhong** [comment]
> @simonhong pls make sure to get it uplifted as needed, thanks :)

Done. uplift PRs for beta/release are ready!

**Comment by Ilie-Lesan** [comment]
@simonhong I had a look and everything looks fine.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.73.12 Chromium: 130.0.6723.44 (Official Build) nightly (x86_64)
-- | --
Revision | a81b2b1b1225ba78f59753b334af02ab4918b139
OS | macOS Version 14.7 (Build 23H124)
```

**Pull request merged**
