### PR TITLE
Sync fix bookmarks object id duplication (uplift to 1.6.x)

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Sync fix bookmarks object id duplication

Uplift of https://github.com/brave/brave-core/pull/4710, created manually because had conflicts.

Fixes https://github.com/brave/brave-browser/issues/8325

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
Restarting `Linux` as both `test-unit` and `test-browser` failed as per the following:

* `test-unit` failure --> https://ci.brave.com/job/brave-browser-build-pr/job/pr4710_sync_fix_obj_id_dup_1.6.x/1/execution/node/309/log/
* `test-browser` failure --> https://ci.brave.com/job/brave-browser-build-pr/job/pr4710_sync_fix_obj_id_dup_1.6.x/1/execution/node/326/log/

Restarting `macOS` as both `test-unit` and `test-browser` failed as per the following:

* `test-unit` failure -->  https://ci.brave.com/job/brave-browser-build-pr/job/pr4710_sync_fix_obj_id_dup_1.6.x/1/execution/node/675/log/
* `test-browser` failure --> https://ci.brave.com/job/brave-browser-build-pr/job/pr4710_sync_fix_obj_id_dup_1.6.x/1/execution/node/692/log/

**Comment by AlexeyBarabash** [comment]
fails unit test 
```
18:20:13  ../../brave/components/brave_sync/brave_sync_service_unittest.cc:1320:3: error: use of undeclared identifier 'AsMutable'
18:20:13    AsMutable(bookmark_a1)->SetMetaInfo("object_id", "object_id_value");
18:20:13    ^
18:20:13  ../../brave/components/brave_sync/brave_sync_service_unittest.cc:1321:3: error: use of undeclared identifier 'AsMutable'
18:20:13    AsMutable(bookmark_a1)->SetMetaInfo("order", "order_value");
18:20:13    ^
18:20:13  ../../brave/components/brave_sync/brave_sync_service_unittest.cc:1322:3: error: use of undeclared identifier 'AsMutable'
18:20:13    AsMutable(bookmark_a1)->SetMetaInfo("sync_timestamp", "sync_timestamp_value");
18:20:13    ^
18:20:13  ../../brave/components/brave_sync/brave_sync_service_unittest.cc:1323:3: error: use of undeclared identifier 'AsMutable'
18:20:13    AsMutable(bookmark_a1)->SetMetaInfo("version", "version_value");
18:20:13    ^
18:20:13  4 errors generated.
```
I must pickup 1.6.x and pull `AsMutable` function because master change were not uplifted yet

**Comment by AlexeyBarabash** [comment]
there were issues with build, lint and tests caused by some stuff from master hasn't been uplifted into 1.6.x, so I remove skip_xxxxx labels

**Comment by AlexeyBarabash** [comment]
CI succeeded for all platforms except macOS
```
18:41:01  ERROR at //build/timestamp.gni:31:19: Script returned non-zero exit code.
18:41:01  build_timestamp = exec_script(compute_build_timestamp,
18:41:01                    ^----------
18:41:01  Current dir: /Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.6.x/src/out/Release/
18:41:01  Command: python /Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.6.x/src/build/compute_build_timestamp.py official
18:41:01  Returned 1.
18:41:01  stderr:
18:41:01  
18:41:01  Traceback (most recent call last):
18:41:01    File "/Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.6.x/src/build/compute_build_timestamp.py", line 127, in <module>
18:41:01      sys.exit(main())
18:41:01    File "/Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.6.x/src/build/compute_build_timestamp.py", line 113, in main
18:41:01      last_commit_timestamp = int(open(lastchange_file).read())
18:41:01  IOError: [Errno 2] No such file or directory: '/Users/jenkins/jenkins/workspace/pr4710_sync_fix_obj_id_dup_1.6.x/src/build/util/LASTCHANGE.committime'
18:41:01  
18:41:01  See //base/BUILD.gn:34:1: whence it was imported.
18:41:01  import("//build/timestamp.gni")
18:41:01  ^-----------------------------
18:41:01  See //BUILD.gn:70:5: which caused the file to be included.
18:41:01      "//base:base_perftests",
18:41:01      ^----------------------
18:41:01  null
18:41:01  null
18:41:01  npm ERR! code ELIFECYCLE
```
Marking to skip all except macOS and restarting.

**Pull request merged**
