### PR TITLE
Use git commit ref for brave-ui dependency instead of npm-published version

### PR DESCRIPTION
**Pull request by petemill**
This is the minimum change necessary to have brave-ui go direct to a specific commit in github, rather than a specific version published to npm.
It clears the way for the branch strategy outlined in https://github.com/brave/brave-browser/issues/2315.

Addresses https://github.com/brave/brave-browser/issues/2315

## Test Plan:
- `npm install` in src/brave (don't remove node_modules first)
- check that it installed the commit-version of brave-ui via:
  - `cat ./node_modules/brave-ui/package.json | grep _from`. You should see `"_from": "github:brave/brave-ui#9be9bee9764c6a1fd329acbe348f91b85142dc33",`
- Check that web unit tests work: `npm run test-unit`
- Check that webui builds work
  - Ensure all webuis re-build by simply re-saving the file at `"components/webpack/webpack.config.js`
  - run `npm run build` from brave-browser
  - should see no error
  - webuis should look ok

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by petemill** [comment]
If / when this is approved a merged, we should pick this up to as many branches as we're aiming to uplift future brave-ui updates to. But in each branch we should change the sha to the git commit ID of where that brave-core branch is currently pointing at brave-ui.

**Comment by petemill** [comment]
@cezaraugusto rebased because package.json had changed on master

**Comment by cezaraugusto** [comment]
master f99f7c6
0.59.x 296dac68

**Comment by petemill** [comment]
Thanks @cezaraugusto. FYI brave-core 0.58.x is on brave-ui 0.34.6 which is 5c2d8a0f669af2e9a68ce0fe38d49a116bc52315

**Comment by kjozwiak** [comment]
@petemill approved uplift to `0.58.x` after deliberating with @rebron 👍 Please add/remove all the needed labels and ensure that the appropriate issue is moved to the correct milestone.

**Comment by petemill** [comment]
0.58 9e43e628

**Pull request merged**
