### PR TITLE
Promo notification bitflyer

### PR DESCRIPTION
**Pull request by deeppandya**
Resolves https://github.com/brave/brave-browser/issues/20725

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Comment by deeppandya** [comment]
@kjozwiak CI fails for the lint error which is not related to PR changes. 


[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-promo_notification_bitflyer-noplatform/detail/pr-brave-browser-promo_notification_bitflyer-noplatform/1/pipeline#step-174-log-1415)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-promo_notification_bitflyer-noplatform/detail/pr-brave-browser-promo_notification_bitflyer-noplatform/1/pipeline#step-174-log-1416)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-promo_notification_bitflyer-noplatform/detail/pr-brave-browser-promo_notification_bitflyer-noplatform/1/pipeline#step-174-log-1417)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-promo_notification_bitflyer-noplatform/detail/pr-brave-browser-promo_notification_bitflyer-noplatform/1/pipeline#step-174-log-1418)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-promo_notification_bitflyer-noplatform/detail/pr-brave-browser-promo_notification_bitflyer-noplatform/1/pipeline#step-174-log-1419)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-promo_notification_bitflyer-noplatform/detail/pr-brave-browser-promo_notification_bitflyer-noplatform/1/pipeline#step-174-log-1420)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-promo_notification_bitflyer-noplatform/detail/pr-brave-browser-promo_notification_bitflyer-noplatform/1/pipeline#step-174-log-1421)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-promo_notification_bitflyer-noplatform/detail/pr-brave-browser-promo_notification_bitflyer-noplatform/1/pipeline#step-174-log-1422)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-promo_notification_bitflyer-noplatform/detail/pr-brave-browser-promo_notification_bitflyer-noplatform/1/pipeline#step-174-log-1423)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-promo_notification_bitflyer-noplatform/detail/pr-brave-browser-promo_notification_bitflyer-noplatform/1/pipeline#step-174-log-1424)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-promo_notification_bitflyer-noplatform/detail/pr-brave-browser-promo_notification_bitflyer-noplatform/1/pipeline#step-174-log-1425)[2022-02-15T16:54:38.313Z] browser/brave_vpn/sources.gni

[2022-02-15T16:54:38.313Z] This change has GN build file diff for browser/brave_vpn/sources.gni

[2022-02-15T16:54:38.313Z] browser/sources.gni

[2022-02-15T16:54:38.313Z] This change has GN build file diff for browser/sources.gni

[2022-02-15T16:54:38.313Z] components/skus/browser/BUILD.gn

[2022-02-15T16:54:38.313Z] This change has GN build file diff for components/skus/browser/BUILD.gn

[2022-02-15T16:54:38.313Z] components/skus/browser/rs/cxx/BUILD.gn

[2022-02-15T16:54:38.313Z] This change has GN build file diff for components/skus/browser/rs/cxx/BUILD.gn

[2022-02-15T16:54:38.313Z] ios/browser/BUILD.gn

[2022-02-15T16:54:38.313Z] This change has GN build file diff for ios/browser/BUILD.gn

[2022-02-15T16:54:38.313Z] 

[2022-02-15T16:54:38.313Z] Format errors detected. Run npm format locally to fix.

**Comment by kjozwiak** [comment]
> @kjozwiak CI fails for the lint error which is not related to PR changes.
> 
> [2022-02-15T16:54:38.313Z] browser/brave_vpn/sources.gni
> 
> [2022-02-15T16:54:38.313Z] This change has GN build file diff for browser/brave_vpn/sources.gni
> 
> [2022-02-15T16:54:38.313Z] browser/sources.gni
> 
> [2022-02-15T16:54:38.313Z] This change has GN build file diff for browser/sources.gni
> 
> [2022-02-15T16:54:38.313Z] components/skus/browser/BUILD.gn
> 
> [2022-02-15T16:54:38.313Z] This change has GN build file diff for components/skus/browser/BUILD.gn
> 
> [2022-02-15T16:54:38.313Z] components/skus/browser/rs/cxx/BUILD.gn
> 
> [2022-02-15T16:54:38.313Z] This change has GN build file diff for components/skus/browser/rs/cxx/BUILD.gn
> 
> [2022-02-15T16:54:38.313Z] ios/browser/BUILD.gn
> 
> [2022-02-15T16:54:38.313Z] This change has GN build file diff for ios/browser/BUILD.gn
> 
> [2022-02-15T16:54:38.313Z]
> 
> [2022-02-15T16:54:38.313Z] Format errors detected. Run npm format locally to fix.

yup 👍 known issues on `1.35.x`.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Andorid 12` using the `1.35.100` Nightly build that @deeppandya provided due to this going directly into `1.35.x` and skipping both `1.37.x` & `1.36x.`.

**`Clean Install - Japan`**

* ensured that the BitFlyer notification only appears after 120min as per https://github.com/brave/brave-browser/issues/20725#issue-1115712252
  * moved the time ~15min ahead and ensured that the notification isn't being displayed
  * moved the time ~1h ahead and ensured that the notification isn't being displayed
  * moved the time ~1.5hrs ahead and ensured that the notification isn't being displayed
* ensured that the BitFlyer notification is being displayed after 120min (2hrs)
* ensured that tapping on the notification opens https://try.bravesoftware.jp/brave_20220121-1
* ensured that the BitFlyer doesn't appear again once it's been displayed once
  * moved the time a few hours ahead and ensured that the BitFlyer notification doesn't re-appear
  * moved the date/time several times and ensured that the BitFlyer notification doesn't re-appear

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
image | image | image

**`Clean Install - USA/Canada`**

* ensured that the BitFlyer notification doesn't appear after launching Brave for the first time
  * moved the time ~15min ahead and ensured that the notification isn't being displayed
  * moved the time ~2hrs ahead and ensured that the notification isn't being displayed
  * moved the time ~4hrs ahead and ensured that the notification isn't being displayed
  * moved the date/time a head a few times (1, 2, 3 days) and ensured that the notification isn't being displayed

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.35.x` approved after deliberating with @brave/uplift-approvers. QA has verified the PR on `1.35.x` using a one off build as per https://github.com/brave/brave-core/pull/12268#issuecomment-1041001367. The remaining checks will be completed via the RC as per https://github.com/brave/brave-browser/issues/20725#issuecomment-1041006055.

**Pull request merged**
