### PR TITLE
Modify reset sync

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Fix https://github.com/brave/brave-browser/issues/7412

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues/7412) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [x] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [x] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
Use steps from https://github.com/brave/brave-browser/issues/7412 

1. Create a sync chain
2. Delete the chain
3. Try re-creating it
4. Add another device to this chain and ensure sync works

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
CI is marked as `Finished: UNSTABLE`.
There two weird errors:
```
Error
hudson.AbortException: No item named brave-browser-build-pr/sync_crash_issue_7412 found
	at org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerStepExecution.start(BuildTriggerStepExecution.java:67)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at jdk.internal.reflect.GeneratedMethodAccessor742.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:160)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:142)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:158)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:162)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.startBraveBrowserBuild(WorkflowScript:198)
	at WorkflowScript.run(WorkflowScript:161)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.
....
```
and
```
0:21:18  + '[' = release ']'
20:21:18  /Users/jenkins/jenkins/workspace/r-build-pr_sync_crash_issue_7412@tmp/durable-d3b5db88/script.sh: line 2: [: =: unary operator expected
20:21:18  ++ tr '[:lower:]' '[:upper:]'
20:21:18  + CHANNEL_CAPITALIZED=
20:21:18  + '[' = release ']'
20:21:18  /Users/jenkins/jenkins/workspace/r-build-pr_sync_crash_issue_7412@tmp/durable-d3b5db88/script.sh: line 3: [: =: unary operator expected
20:21:18  + BROWSER='Brave Browser '
20:21:18  + OUT_DIR=/Users/jenkins/jenkins/workspace/r-build-pr_sync_crash_issue_7412/src/out/
20:21:18  + '[' = true ']'
20:21:18  /Users/jenkins/jenkins/workspace/r-build-pr_sync_crash_issue_7412@tmp/durable-d3b5db88/script.sh: line 5: [: =: unary operator expected
20:21:18  + hdiutil attach -nobrowse '/Users/jenkins/jenkins/workspace/r-build-pr_sync_crash_issue_7412/src/out//Brave Browser .dmg'
20:21:18  hdiutil: attach failed - No such file or directory
```

will try to run t again

**Comment by AlexeyBarabash** [comment]
Now CI failed with 
```

14:06:56  Network audit started. Logging requests for the next 2min or until you quit Brave...
14:06:56  undefined: src/out/Release/brave --enable-logging --v=0 --enable_brave_update --network_log --user_data_dir_name=brave-network-test --output_path=src/out/Release/brave --user-data-dir=/home/ubuntu/.config/BraveSoftware/brave-network-test --log-net-log=/home/ubuntu/jenkins/workspace/r-build-pr_sync_crash_issue_7412/network_log.json --net-log-capture-mode=Everything
14:06:59  Xlib:  extension "XInputExtension" missing on display ":3".
14:06:59  Xlib:  extension "XInputExtension" missing on display ":3".
14:06:59  Xlib:  extension "XInputExtension" missing on display ":3".
14:06:59  Xlib:  extension "XInputExtension" missing on display ":3".
14:06:59  [1852:1852:1224/120658.995654:ERROR:gl_surface_glx.cc(458)] GLX 1.3 or later is required.
14:06:59  [1852:1852:1224/120658.995706:ERROR:gl_initializer_x11.cc(148)] GLSurfaceGLX::InitializeOneOff failed.
14:06:59  [1852:1852:1224/120658.996775:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
14:06:59  Xlib:  extension "XInputExtension" missing on display ":3".
14:06:59  [1822:1889:1224/120659.651793:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
14:06:59  [1822:1889:1224/120659.666198:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
14:06:59  [1822:1889:1224/120659.666228:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
14:06:59  Xlib:  extension "XInputExtension" missing on display ":3".
14:06:59  Xlib:  extension "XInputExtension" missing on display ":3".
14:06:59  [1822:1919:1224/120659.718763:ERROR:rewards_service_impl.cc(206)] Failed to read file: /home/ubuntu/.config/BraveSoftware/brave-network-test/Default/ledger_state
14:06:59  [1916:1916:1224/120659.722343:ERROR:ledger_impl.cc(102)] Failed to initialize wallet
14:08:07  [1822:1822:1224/120759.655834:ERROR:gcm_channel_status_request.cc(145)] GCM channel request failed.
14:08:22  [1822:1822:1224/120821.538481:ERROR:gcm_channel_status_request.cc(145)] GCM channel request failed.
14:09:00  undefined:16328
14:09:00  {"params":{"description":"Closing all sessions.","net_error":-3},"phase":0,"source":{"id":33,"type":9}]}
14:09:00                                                                                                        ^
14:09:00  
14:09:00  SyntaxError: Unexpected token ] in JSON at position 48750448
14:09:00      at JSON.parse (<anonymous>)
14:09:00      at start (/home/ubuntu/jenkins/workspace/r-build-pr_sync_crash_issue_7412/lib/start.js:144:23)
14:09:00      at Command.listener (/home/ubuntu/jenkins/workspace/r-build-pr_sync_crash_issue_7412/node_modules/commander/index.js:315:8)
14:09:00      at Command.emit (events.js:210:5)
14:09:00      at Command.parseArgs (/home/ubuntu/jenkins/workspace/r-build-pr_sync_crash_issue_7412/node_modules/commander/index.js:654:12)
14:09:00      at Command.parse (/home/ubuntu/jenkins/workspace/r-build-pr_sync_crash_issue_7412/node_modules/commander/index.js:474:21)
14:09:00      at Object.<anonymous> (/home/ubuntu/jenkins/workspace/r-build-pr_sync_crash_issue_7412/scripts/commands.js:177:4)
14:09:00      at Module._compile (internal/modules/cjs/loader.js:956:30)
14:09:00      at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
14:09:00      at Module.load (internal/modules/cjs/loader.js:812:32)
14:09:00  npm ERR! code ELIFECYCLE
```

**Comment by AlexeyBarabash** [comment]
Now CI succeeded

**Comment by AlexeyBarabash** [comment]
I had verified the fix succeeded on on a Nightly channel browser after update.

@kjozwiak , @rebron , @srirambv how about uplift it?

**Comment by bsclifton** [comment]
Manually set milestone for this PR to BETA to match issue:
https://github.com/brave/brave-browser/issues/7412

**Pull request merged**
