### PR TITLE
Implement unsupported regions in Rewards linking flow.

### PR DESCRIPTION
**Pull request by szilardszaloki**
Resolves https://github.com/brave/brave-browser/issues/21209, resolves https://github.com/brave-intl/internal/issues/312.

region_not_supported

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

In https://github.com/brave-intl/internal/issues/312.

### CODE REVIEW

**Comment by szilardszaloki** [comment]
`SonarCloud` is reporting duplicated lines due to how we currently structure code in `rewards_reducer.ts` and `wallet_reducer.ts` (both on desktop and Android).

**Review by emerick — APPROVED** [review]
LGTM

**Review by zenparsing — APPROVED** [review]

**Comment by GeetaSarvadnya** [comment]
@szilardszaloki @emerick Can any one of you link the test plan here, please? also could you also mention the list of countries which doesn't support external wallet linkage (e.g Uphold/Gemini/Bitflyer). I have tried testing the PR in the latest nightly build `1.39.35`  I am not getting the unsupported region message when I link Gemini/Uphold KYC accounts. Verified the PH and VN locales. Not sure what I am missing

cc: @LaurenWags @kjozwiak

**Comment by szilardszaloki** [comment]
Hey @GeetaSarvadnya!
I added the test plan to https://github.com/brave-intl/internal/issues/312, but just checked and it seems it got removed.
Reaching out via Slack!

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.39.35 Chromium: 100.0.4896.79 (Official Build) nightly (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 10 Version 21H2 (Build 19044.1586)

```
- Verified the unsupported region linkage error message for the wallet provider Gemini for the locale PH (**Note**: I had a discussion with @szilardszaloki, as per the discussion we have an account set up only for PH locale for Gemini provider, hence verified the PR only for Gemini wallet provider and PH locale)
image

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarmx64.apk_1.39.35`

Verified the unsupported region linkage error message for the wallet provider Gemini for the locale PH
image

**Pull request merged**
