### PR TITLE
Fixes ad notifications should not be served on mobile if a user is opted-in to Brave News and has Brave Ads disabled - 1.27.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/9317
Resolves https://github.com/brave/brave-browser/issues/16739

- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [ ] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
Restarting `macOS` due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-issues-16739-1.27.x-macos/1/execution/node/147/log.

```
 FAILED: obj/components/permissions/permissions/permission_request_impl.o 
```

Restarting `pre-init` as it looks like the node ran out of disk space as per https://ci.brave.com/job/pr-brave-browser-issues-16739-1.27.x-pre-init/1/console.

```
java.nio.file.FileSystemException: /home/ubuntu/workspace/pr-brave-browser-issues-16739-1.27.x-pre-init: No space left on device
```

**Comment by kjozwiak** [comment]
Still waiting on a decision re: https://github.com/brave/brave-core/pull/9282 being merged into `1.27.x`. @tmancey assuming if https://github.com/brave/brave-core/pull/9282 doesn't get uplifted and stays in `1.28.x`, we can close this uplift correct? Or does this need to go into `1.27.x` either way?

**Comment by tmancey** [comment]
@kjozwiak If #9282 is not merged this uplift can be closed. Thanks

**Comment by LaurenWags** [comment]
confirmed with @rebron that we are ok to close this PR. cc @brave/uplift-approvers

**Pull request closed without merging**
