### PR TITLE
set 'component_extensions_auto_granted' to false for all extension features

### PR DESCRIPTION
**Pull request by thirumurugan-git**
Limit extension features to allowlisted extensions.

#### Before changes

image

#### After changes

Screenshot from 2024-06-29 13-40-17

Issue: https://github.com/brave/brave-browser/issues/39478

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [x] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [x] New files have MPL-2.0 license header
- [x] Adequate test coverage exists to prevent regressions
- [x] Major classes, functions and non-trivial code blocks are well-commented
- [x] Changes in component dependencies are properly reflected in `gn`
- [x] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [x] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
See https://github.com/brave/brave-browser/issues/39478

### CODE REVIEW

**Comment by thirumurugan-git** [comment]
@goodov / @simonhong kindly review this PR.

**Comment by simonhong** [comment]
I think we need to accept this chanages as we want to control via allowed list. @goodov WDYT?

**Comment by diracdeltas** [comment]
this does not block this PR (which seems like a good change to me), but don't we also want to set component_extensions_auto_granted to `false` in _brave_talk_api_features.json, and _ipfs*_features.json? looks like only brave wallet already sets it.

**Comment by goodov** [comment]
Test run https://github.com/brave/brave-core/pull/24455 was successful.

**Review by goodov — APPROVED** [review]

**Comment by goodov** [comment]
cc @bsclifton to merge.

**Comment by thirumurugan-git** [comment]
@diracdeltas Thank you for your review. I believe that `_brave_talk_api_features.json` only contains webui features, so there is no need to set `component_extensions_auto_granted` to false. WDYT?

**Comment by diracdeltas** [comment]
@thirumurugan-git thanks i guess fine to skip that one then. i just approved this PR to run in CI but it's not actually working so let me ping devops about it before merge.

**Comment by bsclifton** [comment]
@thirumurugan-git do you have a specific example that you can provide for QA to try?

For example in https://github.com/brave/brave-browser/issues/39478 you call out:
1. Open brave://inspect/#extensions
2. Inspect Brave extension.
3. Now you can access brave rewards API's in brave shields console.

For step 3, what are some things that QA could paste into the console that would work BEFORE this patch but fail AFTER this patch?

Please let us know! I can help update the original issue so our QA can verify the fix. Thanks!

**Comment by bsclifton** [comment]
Doing admin merge - the CI status on GitHub won't be updated unless we make a PR using a branch (not fork) with the same SHA.

**Comment by thirumurugan-git** [comment]
> @thirumurugan-git do you have a specific example that you can provide for QA to try?
> 
> For example in [brave/brave-browser#39478](https://github.com/brave/brave-browser/issues/39478) you call out:
> 
>     1. Open brave://inspect/#extensions
> 
>     2. Inspect Brave extension.
> 
>     3. Now you can access brave rewards API's in brave shields console.
> 
> 
> For step 3, what are some things that QA could paste into the console that would work BEFORE this patch but fail AFTER this patch?
> 
> Please let us know! I can help update the original issue so our QA can verify the fix. Thanks!

@bsclifton 

I apologize for the delay in responding. Previously, if we entered `chrome.braveRewards` in the Brave Shields extension console, we could access it. However, after recent changes, attempting the same will return `undefined` in the console. This adjustment applies not only to the `braveRewards` API but ensures that APIs are now accessible only to extensions that have been allowllisted. The allowlist for specific features can be found in the `_api_features.json` file.

For QA testing purposes, previously all component extensions could access all APIs without restriction. Post-change, only extensions listed in `_api_features.json` can access the specific features mentioned in the file.

**Comment by bsclifton** [comment]
@thirumurugan-git no worries on the delay - thanks for confirming! I tested the steps and updated https://github.com/brave/brave-browser/issues/39478 to capture them 😄 Thanks again!

**Pull request merged**
