### PR TITLE
Splited p3a from crash report option from first run dialog

### PR DESCRIPTION
**Pull request by simonhong**
p3a prefs would not be affected by first run dialog.
crash report checkbox is unchecked by default.

fix https://github.com/brave/brave-browser/issues/14183
fix https://github.com/brave/brave-browser/issues/14160

image
image

Resolves 

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)
- [ ] Requested a security/privacy review as needed

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
1. Launch with clean profile
2. Check crash report checkbox is un-checked by default
3. Check settings reflects properly for crash report checkbox state
3. Check crash report checkbox state doesn't affect p3a prefs state

### CODE REVIEW

**Review by iefremov — APPROVED** [review]

**Comment by iefremov** [comment]
I recall we were thinking about different wording for crash reports, like "if things go wrong" or something :)

**Comment by karenkliu** [comment]
@iefremov I remember that too! No one proposed the official alternate string in the spec though so I left it as is.

**Review by karenkliu — APPROVED** [review]
Looks great Simon! 👍

**Review by mkarolin — APPROVED** [review]
`chromium_src` changes LGTM.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 11.1 x64` using the following build:

```
Brave | 1.22.39 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
--- | ---
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.1 (Build 20C69)
```

### **`Test Case #1`** (leaving crash report unchecked)

* launched `1.22.39 CR: 89.0.4389.58` and ensured that `Help improve Brave by automatically sending crash reports` was not being selected by default 
* ensured that `Automatically send completely private product analytics to Brave` was enabled via `brave://settings/privacy`
* ensured that `Help improve Brave's features and performance` was disabled
* crashed Brave via `brave://crash` and ensured that the crash report appeared under `brave://crashes` but wasn't submitted
* ensured that restarting Brave didn't submit the crash report via `brave://crashes`
* ensured that clicking on `Send now` under `brave://crashes` sends the crash report to BackTrace
* ensured that P3A is working/being updated via `brave://local-state`

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
Screen Shot 2021-02-22 at 10 16 38 PM | Screen Shot 2021-02-22 at 10 23 04 PM | Screen Shot 2021-02-22 at 10 27 53 PM

### **`Test Case #2`** (leaving crash report unchecked)

* launched `1.22.39 CR: 89.0.4389.58` and ensured that `Help improve Brave by automatically sending crash reports` was not being selected by default 
* selected  `Help improve Brave by automatically sending crash reports` and clicked on `Start Brave`
* ensured that `Automatically send completely private product analytics to Brave` was enabled via `brave://settings/privacy`
* ensured that `Help improve Brave's features and performance` was enabled via `brave://settings/privacy`
* crashed Brave via `brave://crash` and ensured that the crash report appeared under `brave://crashes` and was automatically submitted
* ensured that P3A is working/being updated via `brave://local-state`

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
Screen Shot 2021-02-22 at 10 49 45 PM | Screen Shot 2021-02-22 at 10 50 00 PM | Screen Shot 2021-02-22 at 10 50 17 PM

### **`Test Case #3`** (Onboarding)

* ensured that clicking on `completely private product analytics` opens the following:
  * https://brave.com/privacy-preserving-product-analytics-p3a/
* ensured that `Settings` opens `brave://settings/privacy`

Screen Shot 2021-02-22 at 10 31 26 PM

**Pull request merged**
