### PR TITLE
Upgrade from Chromium 109 to Chromium 110 (1.48.x)

### PR DESCRIPTION
**Pull request by emerick**
Resolves https://github.com/brave/brave-browser/issues/27221
Resolves https://github.com/brave/brave-browser/issues/28095
Resolves https://github.com/brave/brave-browser/issues/28099
Resolves https://github.com/brave/brave-browser/issues/28142
Resolves https://github.com/brave/brave-browser/issues/28084
Resolves https://github.com/brave/brave-browser/issues/28176
Resolves https://github.com/brave/brave-browser/issues/28110
Resolves https://github.com/brave/brave-browser/issues/28145
Uplift from https://github.com/brave/brave-core/pull/16324

### CODE REVIEW

**Comment by samartnik** [comment]
Cherry-picked fix for https://github.com/brave/brave-core/pull/16899

**Comment by bsclifton** [comment]
NOTE: we'll want to cherry-pick https://github.com/brave/brave-core/pull/16922 into here

**Comment by samartnik** [comment]
This one also needs to be cherry-picked https://github.com/brave/brave-core/pull/16925

**Comment by bsclifton** [comment]
NOTE: we'll want to cherry-pick https://github.com/brave/brave-core/pull/16944 into here

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.48.x` approved 👍

**Pull request merged**
