### PR TITLE
Add P3A metrics for search conversion banner

### PR DESCRIPTION
**Pull request by DJAndries**
Resolves https://github.com/brave/brave-browser/issues/32130

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by iefremov — APPROVED** [review]

**Comment by iefremov** [comment]
pls complete the checklist

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.60.1 Chromium: 117.0.5938.35 (Official Build) nightly (64-bit)
-- | --
Revision | d50ecb0e74c51a1b522750008a9de6e61e8dabc8
OS | Windows 10 Version 22H2 (Build 19045.3324)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries Few questions regarding the P3A brave search promotion banner test:

1. Does the banner show for any region when the default SE is changed to any third party other than Brave?

Currently, my system region is `India` and default SE is `Brave` for this region and if I change the default SE to any other SE apart from `Brave` I am getting the banner. Is this the correct behavior? As per my understanding the search promotion banner should be shown for the countries where `Brave` is not the default SE, correct me if I am wrong. Thanks!

**Comment by DJAndries** [comment]
@GeetaSarvadnya 

> Currently, my system region is India and default SE is Brave for this region. If I change the default SE to any other SE apart from Brave I am getting the banner. Is this the correct behavior? 

Yes. The banner should not be shown for users that already use Brave as their default.

> As per my understanding the search promotion banner should be shown for the countries where Brave is not the default SE, correct me if I am wrong.

That's correct

**Comment by DJAndries** [comment]
@GeetaSarvadnya 

> Currently, my system region is India and default SE is Brave for this region. If I change the default SE to any other SE apart from Brave I am getting the banner. Is this the correct behavior?

Yes, the banner should only be shown for users who don't have Brave as default.

> As per my understanding the search promotion banner should be shown for the countries where Brave is not the default SE, correct me if I am wrong.

The banner will only be shown for countries with Brave Search as default.

**Pull request merged**
