### PR TITLE
Shields UI fixes (uplift to 1.38x)

### PR DESCRIPTION
**Pull request by nullhook**
Uplift of https://github.com/brave/brave-core/pull/12885 
Uplift of https://github.com/brave/brave-core/pull/12775

Resolves https://github.com/brave/brave-browser/issues/22004
Resolves https://github.com/brave/brave-browser/issues/22012
Resolves https://github.com/brave/brave-browser/issues/22084

Resolves https://github.com/brave/brave-browser/issues/21916
Resolves https://github.com/brave/brave-browser/issues/21926

Pre-approval checklist: 
- [x] You have tested your change on Nightly. 
- [ ] This contains text which needs to be translated. 
    - [ ] There are more than 7 days before the release. 
    - [ ] I've notified folks in #l10n on Slack that translations are needed. 
- [x] The PR milestones match the branch they are landing to. 

Pre-merge checklist: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 

Post-merge checklist: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
@nullhook mind taking a look? Looks like all the OS's are failing due to the following:

```
FAILED: obj/brave/components/content_settings/core/common/common/content_settings_util.obj 
[2022-04-05T06:52:18.551Z] C:\ws\src\brave\buildtools\win\redirect-cc\bin\redirect-cc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe /c ../../brave/components/content_settings/core/common/content_settings_util.cc /Foobj/brave/components/content_settings/core/common/common/content_settings_util.obj /nologo /showIncludes "-imsvc../../../../Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/ATLMFC/include" "-imsvc../../../../Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/include" "-imsvc../../../../Program Files (x86)/Windows Kits/NETFXSDK/4.8/include/um" "-imsvc../../../../Program Files (x86)/Windows Kits/10/include/10.0.19041.0/ucrt" "-imsvc../../../../Program Files (x86)/Windows Kits/10/include/10.0.19041.0/shared" "-imsvc../../../../Program Files (x86)/Windows Kits/10/include/10.0.19041.0/um" "-imsvc../../../../Program Files (x86)/Windows Kits/10/include/10.0.19041.0/winrt" "-imsvc../../../../Program Files (x86)/Windows Kits/10/include/10.0.19041.0/cppwinrt" "-DBRAVE_SERVICES_KEY=\"****\"" "-DUPDATER_DEV_ENDPOINT=\"[https://go-updater-dev.bravesoftware.com/extensions\](https://go-updater-dev.bravesoftware.com/extensions/)"" "-DUPDATER_PROD_ENDPOINT=\"[https://go-updater.brave.com/extensions\](https://go-updater.brave.com/extensions/)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-shields-ui-fixes-1.38.x-windows/detail/pr-brave-browser-shields-ui-fixes-1.38.x-windows/1/pipeline#step-183-log-869)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-shields-ui-fixes-1.38.x-windows/detail/pr-brave-browser-shields-ui-fixes-1.38.x-windows/1/pipeline#step-183-log-870)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-shields-ui-fixes-1.38.x-windows/detail/pr-brave-browser-shields-ui-fixes-1.38.x-windows/1/pipeline#step-183-log-871)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-shields-ui-fixes-1.38.x-windows/detail/pr-brave-browser-shields-ui-fixes-1.38.x-windows/1/pipeline#step-183-log-872)[](https://ci.brave.com/blue/organizations/jenkins/pr-brave-browser-shields-ui-fixes-1.38.x-windows/detail/pr-brave-browser-shields-ui-fixes-1.38.x-windows/1/pipeline#step-183-log-873)"" -DUSE_AURA=1 "-DCR_CLANG_REVISION=\"llvmorg-15-init-1995-g5bec1ea7-1\"" -D_HAS_NODISCARD -D_CRT_NONSTDC_NO_WARNINGS -D_WINSOCK_DEPRECATED_NO_WARNINGS -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_NO_AUTO_LINK -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_VB -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DENABLE_IPC_FUZZER -DWEBP_EXTERN=extern -I../../brave/chromium_src -I../.. -Igen -I../../buildtools/third_party/libc++ -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/third_party/dawn/include -I../../third_party/dawn/include -I../../third_party/dawn/src/include -I../../third_party/libwebp/src -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../.. -fno-delete-null-pointer-checks -fno-ident -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 /clang:-ffp-contract=off -fcomplete-member-pointers /Gy /FS /bigobj /utf-8 /Zc:twoPhase /Zc:sizedDealloc- /D__WRL_ENABLE_FUNCTION_STATICS__ -fmsc-version=1916 -m64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes /W4 -Wimplicit-fallthrough -Wthread-safety -Wextra-semi /WX -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declaration -Wno-nonportable-include-path -Wno-null-pointer-subtraction -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wmax-tokens -Wshadow /O1 /Ob2 /Oy- /Zc:inline /Gw /Oi /Z7 -gcodeview-ghash -Xclang -fuse-ctor-homing -ftrivial-auto-var-init=pattern /guard:cf /MT -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang use-classify-type -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -DPROTOBUF_ALLOW_DEPRECATED=1 /std:c++17 -Wno-trigraphs /Zc:alignedNew- /TP /GR- -I../../buildtools/third_party/libc++/trunk/include /Fd"obj/brave/components/content_settings/core/common/common_cc.pdb"
[2022-04-05T06:52:18.554Z] In file included from ../../brave/components/content_settings/core/common/content_settings_util.cc:11:
[2022-04-05T06:52:18.554Z] ../..\brave/components/brave_shields/common/brave_shield_constants.h(74,39): error: use of undeclared identifier 'IDS_BRAVE_SHIELDS_COOKIES_ALLOWED_ALL'
[2022-04-05T06:52:18.554Z]     {"braveShieldsCookiesAllowedAll", IDS_BRAVE_SHIELDS_COOKIES_ALLOWED_ALL},
[2022-04-05T06:52:18.554Z]                                       ^
[2022-04-05T06:52:18.554Z] 1 error generated.
```

**Comment by kjozwiak** [comment]
Labelling as `PR/Blocked` till the above is fixed 👍

**Comment by nullhook** [comment]
the fail should be fixed

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.38.x` approved 👍 QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/12885#issuecomment-1092069177, https://github.com/brave/brave-core/pull/12885#issuecomment-1092073488, https://github.com/brave/brave-core/pull/12885#issuecomment-1092080321 & https://github.com/brave/brave-core/pull/12775#issuecomment-1092251852.

**Pull request merged**
