### PR TITLE
Allow users to be able to change content settings set by shield extension.

### PR DESCRIPTION
**Pull request by simonhong**
If a setting is not managed by user, editing isn't allowed by the most of user interface.
Because of this reason, users can't edit javascript block settings from settings webui or page info bubble.

To enable editing the shields setting, newly introduced `BraveShields.ContentSetting` will store shields's content settings to user preference store.

Note: We are using two different apis for storing shields's setting.
In shields, `ContentsSettingsStore::SetExtensionContentSetting` is used by `ContentSettingsContentSettingSetFunction`.
In other places, methods of `HostContentSettingsMap` are used.
Each uses different persistent storage.
With this PR, we will use one api -`HostContentSettingsMap` for setting.

This PR doesn't change any behavior w/o https://github.com/brave/brave-extension/pull/63.

Issue: https://github.com/brave/brave-browser/issues/232
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Needed or QA/No-QA-Needed) to include the closed issue in milestone 

## Test Plan:
`yarn test brave_browser_tests --filter=BraveShieldsAPIBrowserTest.ContentSetting*`

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by simonhong** [comment]
@yrliou `BraveContentSettingsStore` is valid when shields doesn't use chrome.contentSettings api?

**Comment by yrliou** [comment]
> @yrliou `BraveContentSettingsStore` is valid when shields doesn't use chrome.contentSettings api?
> With this PR, shields's settings will not be stored via ContentSettingsStore anymore.
They're not needed if we're not using content settings store anymore.

**Comment by bsclifton** [comment]
This PR might also fix https://github.com/brave/brave-browser/issues/1198 - going to build locally and verify 😄

**Comment by bsclifton** [comment]
Confirmed this does NOT fix https://github.com/brave/brave-browser/issues/1198 ☹️ I thought that perhaps since a full schema (that includes Scope) for the extension was provided, it might treat the content settings as per-session (which it doesn't seem to)

**Comment by bbondy** [comment]
Force pushed rebase on master tip fyi.

**Comment by bbondy** [comment]
Code looks good, tested and it works great too. Tested against default shield settings and it is good too.

**Comment by bbondy** [comment]
master: d160950992c508ace65490d441ffaacee92000a0
0.56.x: 8de1937e1f431fd3796e43a56e0ec8c720231620
0.55.x: fd63dd2cee344443685cd756f513723d9f090c99

**Comment by bbondy** [comment]
And DEPs updated commit here:
master: f8150eb9da980b14fb4ad9db20231f69b1c0ae38
0.56.x: cd5eff8ddcda456f76fa677be62cb93034cd53be
0.55.x: cab9e098d138f8031772a0abc5ef38c02ba632e1

**Pull request merged**
