### PR TITLE
Fixes to uplift script

### PR DESCRIPTION
**Pull request by bsclifton**
## Description
A few important updates:
- Script renamed to `uplift.py`
- Argument `--uplift-using-pr` is no longer optional; **_you can ONLY uplift MERGED pull requests_**
- Commits for uplifts are squashed and PR number is linked / release channel is mentioned (ex: `Uplift of #1762 (squashed) to dev`)
- Removed `--reviewers` argument and instead assign the [Uplift Approvers team](https://github.com/orgs/brave/teams/uplift-approvers)
- Script now works properly for https 😄 (which means we can use in Jenkins)

## Actions to take after merge
- [ ] Finalize the Jenkins job: https://staging.ci.brave.com/view/wip/job/mihai-create-uplift-prs/
- [ ] Update the documentation: https://github.com/brave/brave-browser/wiki/Uplifting-a-pull-request

### CODE REVIEW

**Comment by bsclifton** [comment]
For an example of commits being squashed, see https://github.com/brave/brave-core/pull/1776

**Comment by bsclifton** [comment]
Marking as WIP - got some additional feedback 😄

**Comment by bsclifton** [comment]
Updated after more feedback 😄 👍 
cc: @darkdh @mihaiplesa

**Comment by bsclifton** [comment]
Got to work out a problem here with Python (it's complaining about `Requests` module not found), but you can try this out here:
https://staging.ci.brave.com/view/wip/job/mihai-create-uplift-prs/build?delay=0sec

**Comment by mihaiplesa** [comment]
We should install it via `pip` on the Mac nodes.

**Comment by bsclifton** [comment]
@mihaiplesa fixed it by specifying the full path to Python. You can see a run here:
https://staging.ci.brave.com/view/wip/job/mihai-create-uplift-prs/21/console

**Comment by bsclifton** [comment]
Ready for review 👍

**Pull request merged**
