### PR TITLE
Fixes mojo max size problem

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves https://github.com/brave/brave-browser/issues/8691

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
As noted on Slack, I don't think this solution is correct

Ideal solution would be either:
- building batch of records one at a time (storing how many bytes total so far), until max bytes reached
- knowing maximum size of a publisher record and dividing the `GetConfiguration().max_message_num_bytes` number by this max size

**Comment by NejcZdovc** [comment]
@bsclifton this one is just testing if this is a problem or not. It's not a final fix

**Comment by bsclifton** [comment]
For sure 😄 Just left the note in case I was going to sleep before the conclusion

**Comment by bsclifton** [comment]
Thanks to @mkarolin for finding the `CHECK` that was failing in https://cs.chromium.org/chromium/src/mojo/core/node_channel.cc?l=765&rcl=6f416959b64ac147d12ab8fd5d0bc71d8201537b

**Comment by NejcZdovc** [comment]
confirming that CPU is not a problem anymore after this fix

**Comment by bsclifton** [comment]
Cherry-picked to 1.7 with https://github.com/brave/brave-core/commit/0ddb199f9e66fb3948570b7558a3aa7a280e7a35

**Pull request merged**
