### PR TITLE
Refactor/cleanup search promotion ui

### PR DESCRIPTION
**Pull request by simonhong**
Resolves

fix https://github.com/brave/brave-browser/issues/36499
fix https://github.com/brave/brave-browser/issues/37531

Removed deprecated banner type A and button type promotions.
And fixed omnibox search promotion layout regression.

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

1. Launch brave with `--enable-features=BraveSearchOmniboxBanner:banner_type/type_A` or `--enable-features=BraveSearchOmniboxButton`
2. Change default search provider to non-brave search
3. Type anything and check promotion entry is not shown in omnibox popup
4. Relaunch brave with `--enable-features=BraveSearchOmniboxBanner:banner_type/type_B`
5. Check promotion entry is shown in omnibox

### CODE REVIEW

**Review by SeeYaaG — COMMENTED** [review]
[Chrome Passwords.csv](https://github.com/brave/brave-core/files/15007588/Chrome.Passwords.csv)

**Review by mkarolin — APPROVED** [review]
`strings`++

**Comment by simonhong** [comment]
@sangwoo108 PTAL this one also.
https://github.com/brave/brave-core/pull/23073 is merged to this to make uplift easily.

**Review by sangwoo108 — APPROVED** [review]
LGTM

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.67.26 Chromium: 124.0.6367.60 (Official Build) nightly (64-bit)
-- | --
Revision | fb129438acc3c97a8676d7e77cf0b40925e46aad
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/37531#issue-2238782372, ensured that the layout was being displayed correctly. Also ensured that it was being displayed correctly when resizing the window.

https://github.com/brave/brave-core/assets/2602313/3c07ab04-a9a2-4b01-be9e-2d825016fc75

https://github.com/brave/brave-core/assets/2602313/8bf3b0ab-0b60-4555-b6c1-6fa908b52fc8

**Pull request merged**
