### PR TITLE
Update bookmarks toolbar folder icons

### PR DESCRIPTION
**Pull request by bsclifton**
- Windows icons are back to yellow
- macOS and Linux use a gray colored icon (Linux has slightly different dimensions)

Having a proper icon solves the visibility issue for sub-folders on
private window.

Fixes https://github.com/brave/brave-browser/issues/17463
Fixes https://github.com/brave/brave-browser/issues/17214

### Windows
image
image

### macOS
Screen Shot 2021-09-11 at 9 05 41 AM
Screen Shot 2021-09-11 at 9 05 58 AM

## Linux
Screenshot from 2021-09-11 09-26-45
Screenshot from 2021-09-11 09-27-14

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
TBD

### CODE REVIEW

**Comment by bsclifton** [comment]
Ready for review! 😄 @simonhong @mariospr would you all be able to help me get a screenshot for Linux / macOS? (light mode, dark mode). You can edit the top post and share there

**Review by karenkliu — APPROVED** [review]
Windows looks as expected! 🚀

**Review by mkarolin — APPROVED** [review]
LGTM

**Review by simonhong — APPROVED** [review]
++ - attached screenshots from macOS and linux

**Comment by kjozwiak** [comment]
### Test Case 1 - https://github.com/brave/brave-browser/issues/17463

Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.31.35 Chromium: 93.0.4577.63 (Official Build) nightly (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 10 OS Version 2009 (Build 19042.1165)
```

Ensured that the bookmark icons are matching the ones via https://github.com/brave/brave-core/pull/10037#issue-992993885 when upgrading and installing a new profile. Examples:

**`Upgrade Case`**

**`Example`** | **`Example`**
---------------|----------------
beforeUpdate | afterUpdate

**`Clean Install`**

**`Example`** | **`Example`**
---------------|----------------
lightTheme | darkTheme
lightTheme2 | darkTheme2

**Pull request merged**
