### PR TITLE
Upgrade from Chromium 73.0.3683.75 to Chromium 74.0.3729.40

### PR DESCRIPTION
**Pull request by mkarolin**
Fixes brave/brave-browser#3502
Related: brave/brave-browser#3931

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Windows
  - [x] macOS
  - [x] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests && npm run test-security`) on
  - [x] Windows
  - [ ] macOS
  - [x] Linux
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by bsclifton** [comment]
Blocked on https://github.com/brave/brave-core/pull/2114

**Comment by bsclifton** [comment]
I pulled down locally and it builds great + unit tests pass. Getting some rewards related browser tests failing though. Do you experience those too, @mkarolin ?

**Comment by mkarolin** [comment]
@bsclifton, no all unit and browser tests are passing on Windows, but I rebased over master locally a few times since the last push.

**Comment by mkarolin** [comment]
Passed CI build with pinned brave-browser (https://staging.ci.brave.com/job/brave-core-build-pr/job/PR-2117/7/ and https://staging.ci.brave.com/job/brave-browser-build-pr/job/PR-3931/8/).

**Comment by bsclifton** [comment]
Great assist here too, @petemill 😄👍

**Pull request merged**
