### PR TITLE
Fixes for hidden wallet networks

### PR DESCRIPTION
**Pull request by supermassive**
Resolves https://github.com/brave/brave-browser/issues/27058

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

1) Test networks now by default are marked as hidden . Applied to new profiles, or for profiles where hide/show network buttons(in settings) were never clicked.
2) Portfolio(and nft) network picker component shows test networks(when not hidden) in separate section 
image
3) Eye button in network list is always visible and shows proper tooltip

https://user-images.githubusercontent.com/168356/205573443-10b1f509-0a16-4447-af12-6ed5a1b53115.mp4

4) Removed 'Show test networks' toggle with migration: if toggle was on all test networks are removed from hidden networks lists.

### CODE REVIEW

**Comment by yrliou** [comment]
Backend code LGTM but I would like to make sure we have consensus that we're okay with hiding all test networks for users who manually enable the "show test networks" toggle before this. Should we show all test networks instead if they enabled the "show test networks" toggle before so it won't impact their current behavior? cc @jamesmudgett @Douglashdaniel

**Comment by supermassive** [comment]
> Backend code LGTM but I would like to make sure we have consensus that we're okay with hiding all test networks for users who manually enable the "show test networks" toggle before this. Should we show all test networks instead if they enabled the "show test networks" toggle before so it won't impact their current behavior? cc @jamesmudgett @Douglashdaniel My reason to show these if they enabled the toggle before is because, some users might be confusing about not seeing them and might be told to enable the toggle back then, they will unlikely know what happened if these test networks are suddenly gone again, and don't know they have to go to the network settings page to enable what they want one by one.

Will add some migration

**Review by yrliou — APPROVED** [review]
LGTM

**Review by onyb — APPROVED** [review]
Looks good!

**Review by josheleonard — APPROVED** [review]
frontend LGTM

**Pull request merged**
