### PR TITLE
Adding option to restore excluded pubs

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/brave/brave-browser/issues/936

# Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Needed or QA/No-QA-Needed) to include the closed issue in milestone 

## Test Plan:
1. Build Brave from this branch, and start with a clean profile
2. Enable rewards
3. Visit 7 - 10 sites so that they get added to the contribution table
4. Exclude some sites.
5. Hit the `Restore` action under the modal title
6. Ensure the excluded sites are restored.
7. Ensure that those sites can be re-excluded then restored.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by ryanml** [comment]
@jasonrsadler - I can, but the additional commit was an existing issue within the publisher db logic and I wanted to leave it up for visibility. Let me know what you think, thanks!

**Comment by jasonrsadler** [comment]
No prob. Was going off check off list up top. Leave as is. 👍

**Comment by jasonrsadler** [comment]
Is the text coming later or should it already be there?

screen shot 2018-09-13 at 5 38 31 pm

**Comment by jasonrsadler** [comment]
Do we plan to allow excluding if we have less than 6 publishers? Also, how do we unexclude if we remove publishers to having less than 6. Is that all addressed on a separate issue?

**Comment by ryanml** [comment]
@jasonrsadler I may have to address this issue in brave-ui, as only the modal has UX for the restore button

**Comment by ryanml** [comment]
@jasonrsadler locales added in to core

screen shot 2018-09-13 at 3 32 34 pm

**Comment by ryanml** [comment]
@jasonrsadler media publishers should be removable now

**Comment by jasonrsadler** [comment]
0.55.x: 5630677c

**Pull request merged**
