### PR TITLE
Add fingerprinting exception for Uphold

### PR DESCRIPTION
**Pull request by diracdeltas**
Fix https://github.com/brave/brave-browser/issues/4139

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [x] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:

1. Go to uphold.com. Make an account and login.
2. Click on the link to verify your identity (as shown in https://github.com/brave/brave-browser/issues/4139#issuecomment-502964448)
3. When it asks you to submit ID, allow camera access
4. You should be able to take a picture of your ID

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
rebased so this can re-run CI

**Comment by bsclifton** [comment]
Followed the steps outlined here - ran into an issue...
- created account 👍 
- verified email, etc
- logged in, clicked begin verify
- picked drivers license
- browser asked for camera access 👍 I clicked allow
- my camera light did come on!
- because I launched via `npm run start -- Release` the OS then asked me "iTerm is trying to access the camera"
- I clicked "okay" (or whatever it presented). I think it was just an acknowledgement. Does macOS require you to grant access via Accessibility on Mojave?
- Uphold camera process timed out at this point- camera light turned itself off
- verification kicked out saying it would be manually reviewed 🙀 

Screen Shot 2019-06-26 at 12 15 38 AM


At this point, I can't start the process over again ☹️

**Comment by corymcdonald** [comment]
@bsclifton @diracdeltas  Does this PR also address the following? 

https://github.com/brave/brave-browser/issues/2993

I've also had experiences where i've been able to get past this but my document actually didn't upload 😭

**Comment by diracdeltas** [comment]
@corymcdonald yes that's the same issue

**Comment by diracdeltas** [comment]
if anyone else gets stuck in verification while trying to test this and can't retry, ask in the uphold slack channel for someone to reset your verification state.

**Comment by bsclifton** [comment]
(code changes look great too - sorry for the mean mugging)

**Pull request merged**
