### PR TITLE
Enable split ABIs for bundle

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
This PR enables [ABI split](https://developer.android.com/build/configure-apk-splits#configure-abi-split) for Brave Browser.

The main change is a patch at `rules.gni`.
The rest changes are done to deal with [OS Bugs => System.loadLibrary() Broken for Libraries in Splits ](https://source.chromium.org/chromium/chromium/src/+/main:docs/android_isolated_splits.md;l=128;drc=b27071598a6b291a7319d99ce7aa4af81ebc060f;bpv=0;bpt=0).
Also `BundleUtils` class relies on `ContextUtils.getApplicationContext()` which is unavailable for zygote process, so for zygote there is a duplicated methods to get lib path at `BraveLibraryLoader`.

Resolves https://github.com/brave/brave-browser/issues/32468

Related issue: https://github.com/brave/brave-browser/issues/26792

From my tests split ABIs allow to decrease size 263 MB => 185 MB which is 78MB on arm. So only arm64 libs are installed and arm32 - are not.

Device&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|before|after
---|---|---
Pixel&nbsp;6,&nbsp;Android&nbsp;14|01-Pixel6-master-appsize|02-Pixel6-PR-appsize
mi4c,&nbsp;Android&nbsp;9,&nbsp;app&nbsp;size|03-mi4c-master-appsize|04-mi4c-PR-appsize
mi4c,&nbsp;Android&nbsp;9,&nbsp;/data/app&nbsp;folder|05-mi4c-master-app-folder|06-mi4c-PR-app-folder
App size in Google Play|0f-GP-screenshots|to be updated

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
The test plan is to ensure that:
1. app installed;
2. app didn't crash on launch. 

Script to install app from bundle is:
```
java -jar ./src/third_party/android_build_tools/bundletool/bundletool.jar  \
build-apks --connected-device                                                        \
--overwrite \
--bundle=./src/out/android_Release_arm64/apks/BraveMonoarm64.aab                     \
--output=./src/out/android_Release_arm64/apks/BraveMonoarm64.apks                    \
--adb=./src/third_party/android_sdk/public/platform-tools/adb                        \
--aapt2=./src/third_party/android_build_tools/aapt2/aapt2                            \


java -jar ./src/third_party/android_build_tools/bundletool/bundletool.jar  \
install-apks                                                                         \
--apks=./src/out/android_Release_arm64/apks/BraveMonoarm64.apks                      \
--adb=./src/third_party/android_sdk/public/platform-tools/adb
```

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
Found it crashes on one of my devices - Samsung Note8, it goes somewhere around `monochrome_64_vr_partition` . All other devices and the emulator work fine.
```
08-22 14:05:03.375: A/DEBUG(1052): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-22 14:05:03.375: A/DEBUG(1052): Build fingerprint: 'samsung/greatltexx/greatlte:8.0.0/R16NW/N950FXXS5CSA1:user/release-keys'
08-22 14:05:03.375: A/DEBUG(1052): Revision: '9'
08-22 14:05:03.376: A/DEBUG(1052): ABI: 'arm64'
08-22 14:05:03.376: A/DEBUG(1052): pid: 870, tid: 870, name: m.brave.browser  >>> com.brave.browser <<<
08-22 14:05:03.376: A/DEBUG(1052): signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x76d152a1d0
08-22 14:05:03.376: A/DEBUG(1052):     x0   0000000000000000  x1   0000000000000001  x2   0000000000000000  x3   00000076d15fb0f0
08-22 14:05:03.376: A/DEBUG(1052):     x4   00000076fef5e290  x5   00000076fea2dcf0  x6   636f6e6f6d62696c  x7   34365f656d6f7268
08-22 14:05:03.376: A/DEBUG(1052):     x8   000000000063a960  x9   000000000000a9b7  x10  000000000063a8d4  x11  0000000000000090
08-22 14:05:03.376: A/DEBUG(1052):     x12  0000000000000000  x13  00000076fef62000  x14  00000076fef5e000  x15  0000000000000000
08-22 14:05:03.376: A/DEBUG(1052):     x16  00000076d4d711c0  x17  00000076cf326180  x18  85263e47cb29b6ea  x19  00000076f96d6200
08-22 14:05:03.376: A/DEBUG(1052):     x20  0000007400a942e0  x21  00000076cd2b3b81  x22  0000007fea347c0c  x23  0000007400a942f8
08-22 14:05:03.376: A/DEBUG(1052):     x24  000000000000000c  x25  00000076f96c0a98  x26  0000000000000000  x27  0000000000000000
08-22 14:05:03.376: A/DEBUG(1052):     x28  0000000000000003  x29  0000007fea347920  x30  00000076d152a0a0
08-22 14:05:03.376: A/DEBUG(1052):     sp   0000007fea3478a0  pc   00000076d152a1d0  pstate 0000000080000000
08-22 14:05:03.378: A/DEBUG(1052): backtrace:
08-22 14:05:03.378: A/DEBUG(1052):     #00 pc 00000000044851d0  /data/app/com.brave.browser-sMEYLXCbVXhV2MVCayLbGA==/split_config.arm64_v8a.apk (offset 0x12000)
08-22 14:05:03.378: A/DEBUG(1052):     #01 pc 000000000448509c  /data/app/com.brave.browser-sMEYLXCbVXhV2MVCayLbGA==/split_config.arm64_v8a.apk (offset 0x12000)
```

**Review by samartnik — APPROVED** [review]
Java patching ++

**Review by simoarpe — APPROVED** [review]
👍 Java part looks good.

**Review by bridiver — APPROVED** [review]
patch and chromium_src ok

**Comment by AlexeyBarabash** [comment]
Android browser tests are broken with this PR, crashing at point 
https://source.chromium.org/chromium/chromium/src/+/main:chrome/app/chrome_main_delegate.cc;l=1556;drc=bb2d66f5c212d3b5883fac31d6ce20f1164d693f
```
#if BUILDFLAG(IS_ANDROID)
  CHECK_EQ(base::android::GetLibraryProcessType(),
           process_type.empty() ? base::android::PROCESS_BROWSER
                                : base::android::PROCESS_CHILD);
#endif  // BUILDFLAG(IS_ANDROID)
```
`base::android::GetLibraryProcessType()` give `PROCESS_UNINITIALIZED` at the PR.

**Pull request merged**
