### PR TITLE
changed return type of NTPBackgroundPrefs::GetSelectedValue() to std:…

### PR DESCRIPTION
**Pull request by vednp**
…:string

Resolves brave/brave-browser#25602

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by vednp** [comment]
I am a beginner this is my first pull request, please help me if I messed up I would love to contribute more.

**Comment by sangwoo108** [comment]
Hi, @vednp ! Thank you for your help. I hit a button to trigger our CI bots. But I'm wondering if you happened to build this PR on your machine. I don't see any changes of call sites. We'll see if CI succeed.

**Comment by vednp** [comment]
Can you please explain what you mean by building the PR on machine

**Comment by sangwoo108** [comment]
> Can you please explain what you mean by building the PR on machine

I tried fetching your branch and building, but it seemed to fail

```
1/56] CXX obj/chrome/browser/bro...kground_images_service_delegate.o
../../brave/browser/ntp_background/ntp_custom_background_images_service_delegate.cc:95:15: error: no matching function for call to 'get'
  auto name = absl::get<std::string>(prefs.GetSelectedValue());
              ^~~~~~~~~~~~~~~~~~~~~~
../../third_party/abseil-cpp/absl/types/variant.h:300:14: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T& get(variant<Types...>& v) {  // NOLINT
             ^
../../third_party/abseil-cpp/absl/types/variant.h:308:15: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T&& get(variant<Types...>&& v) {
              ^
../../third_party/abseil-cpp/absl/types/variant.h:315:20: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T& get(const variant<Types...>& v) {
                   ^
../../third_party/abseil-cpp/absl/types/variant.h:323:21: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T&& get(const variant<Types...>&& v) {
                    ^
../../third_party/abseil-cpp/absl/types/variant.h:330:56: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>& get(
                                                       ^
../../third_party/abseil-cpp/absl/types/variant.h:338:57: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>&& get(
                                                        ^
../../third_party/abseil-cpp/absl/types/variant.h:345:62: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>& get(
                                                             ^
../../third_party/abseil-cpp/absl/types/variant.h:353:63: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>&& get(
                                                              ^
../../brave/browser/ntp_background/ntp_custom_background_images_service_delegate.cc:110:10: error: no matching function for call to 'holds_alternative'
  DCHECK(absl::holds_alternative<std::string>(selected_value));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../base/check.h:188:7: note: expanded from macro 'DCHECK'
      condition)
      ^~~~~~~~~
../../base/check.h:136:56: note: expanded from macro 'CHECK_FUNCTION_IMPL'
    if (const bool checky_bool_lol = static_cast<bool>(condition); \
                                                       ^~~~~~~~~
../../third_party/abseil-cpp/absl/types/variant.h:264:16: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr bool holds_alternative(const variant<Types...>& v) noexcept {
               ^
../../brave/browser/ntp_background/ntp_custom_background_images_service_delegate.cc:111:10: error: no matching function for call to 'get'
  return absl::get<std::string>(selected_value);
         ^~~~~~~~~~~~~~~~~~~~~~
../../third_party/abseil-cpp/absl/types/variant.h:300:14: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T& get(variant<Types...>& v) {  // NOLINT
             ^
../../third_party/abseil-cpp/absl/types/variant.h:308:15: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T&& get(variant<Types...>&& v) {
              ^
../../third_party/abseil-cpp/absl/types/variant.h:315:20: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T& get(const variant<Types...>& v) {
                   ^
../../third_party/abseil-cpp/absl/types/variant.h:323:21: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T&& get(const variant<Types...>&& v) {
                    ^
../../third_party/abseil-cpp/absl/types/variant.h:330:56: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>& get(
                                                       ^
../../third_party/abseil-cpp/absl/types/variant.h:338:57: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>&& get(
                                                        ^
../../third_party/abseil-cpp/absl/types/variant.h:345:62: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>& get(
                                                             ^
../../third_party/abseil-cpp/absl/types/variant.h:353:63: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>&& get(
                                                              ^
../../brave/browser/ntp_background/ntp_custom_background_images_service_delegate.cc:125:28: error: no matching function for call to 'get_if'
  if (auto* selected_url = absl::get_if<GURL>(&selected_value))
                           ^~~~~~~~~~~~~~~~~~
../../third_party/abseil-cpp/absl/types/variant.h:393:34: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr absl::add_pointer_t<T> get_if(variant<Types...>* v) noexcept {
                                 ^
../../third_party/abseil-cpp/absl/types/variant.h:400:40: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr absl::add_pointer_t<const T> get_if(
                                       ^
../../third_party/abseil-cpp/absl/types/variant.h:372:1: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
get_if(variant<Types...>* v) noexcept {
^
../../third_party/abseil-cpp/absl/types/variant.h:383:1: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
get_if(const variant<Types...>* v) noexcept {
^
../../brave/browser/ntp_background/ntp_custom_background_images_service_delegate.cc:137:26: error: no matching function for call to 'get'
  const auto image_url = absl::get<GURL>(selected_value);
                         ^~~~~~~~~~~~~~~
../../third_party/abseil-cpp/absl/types/variant.h:300:14: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T& get(variant<Types...>& v) {  // NOLINT
             ^
../../third_party/abseil-cpp/absl/types/variant.h:308:15: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T&& get(variant<Types...>&& v) {
              ^
../../third_party/abseil-cpp/absl/types/variant.h:315:20: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T& get(const variant<Types...>& v) {
                   ^
../../third_party/abseil-cpp/absl/types/variant.h:323:21: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T&& get(const variant<Types...>&& v) {
                    ^
../../third_party/abseil-cpp/absl/types/variant.h:330:56: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>& get(
                                                       ^
../../third_party/abseil-cpp/absl/types/variant.h:338:57: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>&& get(
                                                        ^
../../third_party/abseil-cpp/absl/types/variant.h:345:62: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>& get(
                                                             ^
../../third_party/abseil-cpp/absl/types/variant.h:353:63: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>&& get(
                                                              ^
5 errors generated.
[2/56] CXX obj/brave/browser/ui/ui/brave_new_tab_page_handler.o
../../brave/browser/ui/webui/new_tab_page/brave_new_tab_page_handler.cc:305:9: error: no matching function for call to 'get'
        absl::get<std::string>(background_pref.GetSelectedValue()) ==
        ^~~~~~~~~~~~~~~~~~~~~~
../../third_party/abseil-cpp/absl/types/variant.h:300:14: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T& get(variant<Types...>& v) {  // NOLINT
             ^
../../third_party/abseil-cpp/absl/types/variant.h:308:15: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T&& get(variant<Types...>&& v) {
              ^
../../third_party/abseil-cpp/absl/types/variant.h:315:20: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T& get(const variant<Types...>& v) {
                   ^
../../third_party/abseil-cpp/absl/types/variant.h:323:21: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T&& get(const variant<Types...>&& v) {
                    ^
../../third_party/abseil-cpp/absl/types/variant.h:330:56: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>& get(
                                                       ^
../../third_party/abseil-cpp/absl/types/variant.h:338:57: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>&& get(
                                                        ^
../../third_party/abseil-cpp/absl/types/variant.h:345:62: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>& get(
                                                             ^
../../third_party/abseil-cpp/absl/types/variant.h:353:63: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>&& get(
                                                              ^
../../brave/browser/ui/webui/new_tab_page/brave_new_tab_page_handler.cc:327:12: error: no matching function for call to 'holds_alternative'
    DCHECK(absl::holds_alternative<std::string>(selected_value));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../base/check.h:188:7: note: expanded from macro 'DCHECK'
      condition)
      ^~~~~~~~~
../../base/check.h:136:56: note: expanded from macro 'CHECK_FUNCTION_IMPL'
    if (const bool checky_bool_lol = static_cast<bool>(condition); \
                                                       ^~~~~~~~~
../../third_party/abseil-cpp/absl/types/variant.h:264:16: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr bool holds_alternative(const variant<Types...>& v) noexcept {
               ^
../../brave/browser/ui/webui/new_tab_page/brave_new_tab_page_handler.cc:328:35: error: no matching function for call to 'get'
    const std::string file_name = absl::get<std::string>(selected_value);
                                  ^~~~~~~~~~~~~~~~~~~~~~
../../third_party/abseil-cpp/absl/types/variant.h:300:14: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T& get(variant<Types...>& v) {  // NOLINT
             ^
../../third_party/abseil-cpp/absl/types/variant.h:308:15: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T&& get(variant<Types...>&& v) {
              ^
../../third_party/abseil-cpp/absl/types/variant.h:315:20: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T& get(const variant<Types...>& v) {
                   ^
../../third_party/abseil-cpp/absl/types/variant.h:323:21: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T&& get(const variant<Types...>&& v) {
                    ^
../../third_party/abseil-cpp/absl/types/variant.h:330:56: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>& get(
                                                       ^
../../third_party/abseil-cpp/absl/types/variant.h:338:57: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>&& get(
                                                        ^
../../third_party/abseil-cpp/absl/types/variant.h:345:62: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>& get(
                                                             ^
../../third_party/abseil-cpp/absl/types/variant.h:353:63: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>&& get(
                                                              ^
../../brave/browser/ui/webui/new_tab_page/brave_new_tab_page_handler.cc:341:12: error: no matching function for call to 'holds_alternative'
    DCHECK(absl::holds_alternative<std::string>(selected_value));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../base/check.h:188:7: note: expanded from macro 'DCHECK'
      condition)
      ^~~~~~~~~
../../base/check.h:136:56: note: expanded from macro 'CHECK_FUNCTION_IMPL'
    if (const bool checky_bool_lol = static_cast<bool>(condition); \
                                                       ^~~~~~~~~
../../third_party/abseil-cpp/absl/types/variant.h:264:16: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr bool holds_alternative(const variant<Types...>& v) noexcept {
               ^
../../brave/browser/ui/webui/new_tab_page/brave_new_tab_page_handler.cc:342:20: error: no matching function for call to 'get'
    value->color = absl::get<std::string>(selected_value);
                   ^~~~~~~~~~~~~~~~~~~~~~
../../third_party/abseil-cpp/absl/types/variant.h:300:14: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T& get(variant<Types...>& v) {  // NOLINT
             ^
../../third_party/abseil-cpp/absl/types/variant.h:308:15: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T&& get(variant<Types...>&& v) {
              ^
../../third_party/abseil-cpp/absl/types/variant.h:315:20: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T& get(const variant<Types...>& v) {
                   ^
../../third_party/abseil-cpp/absl/types/variant.h:323:21: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T&& get(const variant<Types...>&& v) {
                    ^
../../third_party/abseil-cpp/absl/types/variant.h:330:56: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>& get(
                                                       ^
../../third_party/abseil-cpp/absl/types/variant.h:338:57: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>&& get(
                                                        ^
../../third_party/abseil-cpp/absl/types/variant.h:345:62: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>& get(
                                                             ^
../../third_party/abseil-cpp/absl/types/variant.h:353:63: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>&& get(
                                                              ^
../../brave/browser/ui/webui/new_tab_page/brave_new_tab_page_handler.cc:371:20: error: no matching function for call to 'get'
  auto image_url = absl::get<GURL>(selected_value);
                   ^~~~~~~~~~~~~~~
../../third_party/abseil-cpp/absl/types/variant.h:300:14: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T& get(variant<Types...>& v) {  // NOLINT
             ^
../../third_party/abseil-cpp/absl/types/variant.h:308:15: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr T&& get(variant<Types...>&& v) {
              ^
../../third_party/abseil-cpp/absl/types/variant.h:315:20: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T& get(const variant<Types...>& v) {
                   ^
../../third_party/abseil-cpp/absl/types/variant.h:323:21: note: candidate template ignored: could not match 'variant' against 'basic_string'
constexpr const T&& get(const variant<Types...>&& v) {
                    ^
../../third_party/abseil-cpp/absl/types/variant.h:330:56: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>& get(
                                                       ^
../../third_party/abseil-cpp/absl/types/variant.h:338:57: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr variant_alternative_t<I, variant<Types...>>&& get(
                                                        ^
../../third_party/abseil-cpp/absl/types/variant.h:345:62: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>& get(
                                                             ^
../../third_party/abseil-cpp/absl/types/variant.h:353:63: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'I'
constexpr const variant_alternative_t<I, variant<Types...>>&& get(
                                                              ^
6 errors generated.
[7/56] AR obj/chrome/browser/libbrowser.a
```

I think you should visit all callsites of the changed API. Could you make sure that your patch doesn't break the build?

**Comment by vednp** [comment]
Screenshot 2023-03-26 at 12 23 54 PM

It is giving me this error when I try to build it 
@sangwoo108 can you help?

**Comment by sangwoo108** [comment]
I wonder if you `run npm run sync` or `num run init` .

**Comment by harshul786** [comment]
Hello @sangwoo108!! I did the same as the docs said, but after that too I am getting the same errors @vednp mentioned,

my directory after setting up looks like: 

brave-browser:
    |
    -> src
           |
           -> brave
                  |
                  -> git cloned brave/brave-core root directories like src, ui, script, utility

(i renamed brave-core to brave assuming scripts have the same thing though)
also getting tons of error doing npm i in brave-core 😮‍💨

**Comment by sangwoo108** [comment]
Hi @harshul786 ! Building the chromium-based browser for the first time is pretty painful, isn't it? 😂 It's hard for me to tell what happened for now. Let's try finding out.

So, I expect the directories would be like

```
src
  |- chrome/
  |- brave/     <- this directory is where brave-core repository is mounted
  |    |- README.md   <- it might be worth checking if you can find README.md of brave-core here.
  |
  |- content/
  |- ui/
  |-
  ...
```

This is my dev env
image


Once you confirm that directories are correct, or you have `src/brave/` properly but can't see others like `src/chrome`, you can try syncing again.

```sh
$ cd src/brave  # I usually prefer running our script here
$ npm install
$ npm run init
```

And after it's done, you can try building
```sh
$ npm run build
```

**Pull request closed without merging**
