### PR TITLE
refactor ntp to use brave-ui

### PR DESCRIPTION
**Pull request by cezaraugusto**
screen shot 2019-01-11 at 7 11 00 pm

Changes in this pull-request: 

* Replace all legacy LESS files for NTP
* Make NTP responsive
* Simplify logic for background images
* Remove leftover files

## Test Plan 1 - change default new tab and private new tab structure

- New tab (default) should render;
- Private tab (default) should render;
- Private tab (default) shoud toggle between default search engine/ddg;
- Tor window should render.

## Test Plan 2 - refactor new tab page to use brave-ui

close https://github.com/brave/brave-browser/issues/633

- All interactions in new tab top sites should work
  - Tile links to its website;
  - Pinning/unpinning;
  - Bookmarking/un-bookmarking;
  - Removing
    - All actions in the removal notification should work

- Background should change upon browser refresh
- Background should load even without internet connection
- Links in footer should go to their own links

## Test Plan 3 - remove leftover files from ntp

- Ensure everything builds -- should be catched by CI

## Test Plan 4 - adapt favicon size to 64px to match tile icon size

This is a tentative to make favicons look better without much success, but since favicon image wrapper has 64px I thought to be a good idea to have the same size fetched by Brave

### CODE REVIEW

**Comment by petemill** [comment]
@cezaraugusto nice refactoring - is this ready for review?

**Comment by petemill** [comment]
@cezaraugusto ...or does it depend on https://github.com/brave/brave-ui/pull/344?

**Comment by cezaraugusto** [comment]
hey @petemill yes ready now. re brave/brave-ui#344 it has some breaking changes that would be better landing once this PR is reviewed. here I'm using the `sha` from that PR so not required to have it merged to check out this branch

**Comment by cezaraugusto** [comment]
after a push force github auto closed this pr and can't let me re-open. I'll create a new one

**Comment by cezaraugusto** [comment]
new PR https://github.com/brave/brave-core/pull/1339

**Pull request closed without merging**
