### PR TITLE
[Nala]: Kill material overrides which were breaking Chromium bumps

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Resolves https://github.com/brave/brave-browser/issues/41462
Resolves https://github.com/brave/brave-browser/issues/41455

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

1. Bubble views should look fine (like GeoLocation prompts, or update notifications)
2. Native buttons should look normal
3. Bookmarks dialog should look normal
4. Task manager should look normal

### CODE REVIEW

**Review by emerick — APPROVED** [review]
LGTM, but would just like to understand the original impetus for Simon's change too so we can make sure nothing falls through the cracks here.

**Comment by simonhong** [comment]
> LGTM, but would just like to understand the original impetus for Simon's change too so we can make sure nothing falls through the cracks here.

The purpose of overriding the the upstream `AddMaterialUiColorMixer()` is for using our colors instead of upstream's because it overrides colors after ui mixer is called.
However, it causes to show red colors(showing at undefined color) frequently as upstream set new colors from there.
With this PR, we'll not see red color anymore but could see upstream color.
I think we also need to have `AddBraveMaterialColorMixer()` like this?
and some(or all) of the color overrides from the deleted method to `AddBraveMaterialColorMixer()` should be moved?
```
void AddMaterialUiColorMixer(ColorProvider* provider, const ColorProviderKey& key) {
  AddMaterialUiColorMixer_Chromium(provider, key);
  AddBraveMaterialColorMixer(provider, key);
}
```

**Comment by fallaciousreasoning** [comment]
So I think we originally stopped applying Chromium's mixer in
https://github.com/brave/brave-browser/issues/37515

What was to fix the dialogs having Blurple text, but that was actually being caused by this override:
https://github.com/brave/brave-core/pull/25863/files#diff-17fd4da36cdf1a037a341f4921067e0f0b8fb1e67ce732ee8edd6ad9a89e4ff7L53

Before that we were just replacing a couple of colors:
- kColorToggleButtonHover (before and after the views toggle hover looks bad, but unchanged)
- kColorListItemUrlFaviconBackground (doesn't seem to be used by us, or by upstream)

I've had a look at a bunch of the other colors we have in there and **most** of them seem to be just copy pasted from upstream (or copy pasted, and changed upstream so we're out of sync).

There are a few I'm unsure about, but now we have the Nala blurple theme as the base color in the Material theme, most of the things we would have overridden will naturally look fine. I'd be keen to land this as is, and if we notice something glaring add back overrides on a case by case basis.

Quite a few of these seem to have fallen out of sync during the CR2023 refresh so it's hard to find what we've changed on purpose, and what's just fallen out of sync.

**Comment by simonhong** [comment]
> I'd be keen to land this as is, and if we notice something glaring add back overrides on a case by case basis.

++

**Review by simonhong — APPROVED** [review]

**Comment by fallaciousreasoning** [comment]
Thanks @simonhong & @emerick - lets see how this goes :laughing:

**Pull request merged**
