### PR TITLE
Don't allow AIChat in private windows

### PR DESCRIPTION
**Pull request by petemill**
Resolves https://github.com/brave/brave-browser/issues/33853

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
On issue

### CODE REVIEW

**Review by simonhong — APPROVED** [review]

**Review by sangwoo108 — APPROVED** [review]
LGTM 👍

**Review by iefremov — APPROVED** [review]

**Comment by ShivanKaul** [comment]
@petemill can you confirm this also wouldn't activate in [Request OTR](https://brave.com/privacy-updates/26-request-off-the-record/)?

**Comment by petemill** [comment]
@ShivanKaul I'm afraid I don't know much about that. Can a profile be Request OTR? Seems like that's a feature of a Tab and not a browser profile. The AI Chat feature (and this PR's disabling) is for the window, not inside a tab. However, we do extract content for the active Tab for the conversation context for that Tab. I don't see why it wouldn't do it if the Tab was OTR. But not sure how to test. Sounds like the preference would be for AI Chat to not use page content for Conversations on Tabs that are OTR. But wouldn't the user want the option to ask Leo about the content? It doesn't save locally.

**Comment by ShivanKaul** [comment]
If it doesn't save locally, then what about the plans for SKU?
@pes10k any thoughts?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64`using the following build(s):

```
Brave | 1.62.2 Chromium: 119.0.6045.33 (Official Build) nightly (64-bit)
-- | --
Revision | 1ae4cbaeb4186df008e4562ed006f2c70a9beea8
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

Using the cases via https://github.com/brave/brave-browser/issues/33853#issue-1958269424, ensured the following for `Private Tabs`, `Guest Mode` and `Tor`:

* `Leo` button via the sidebar is disabled/can't be activated/clicked on
* `Leo` doesn't appear via the `omnibar`
* ensured that `chrome-untrusted://chat` is blocked

### `Private Tabs/Windows`

**`Example`** | **`Example`**
----------------|----------------
disabledLeoPrivate1 | disabledLeoPrivate2

### `Guest Mode`

**`Example`** | **`Example`**
----------------|----------------
disabledLeoGuest1 | disabledLeoGuest2

### `Tor Mode`

**`Example`** | **`Example`**
----------------|----------------
image | image

**Comment by pes10k** [comment]
thank you for raising this @ShivanKaul.  The important boundary for Request-OTR is the origin suggesting Request-OTR. In Request-OTR mode, _nothing_ relating to the origin can persist beyond the lifetime of the Request-OTR'ed origin's top-level frames.

So if this feature is pulling content from a page that has been Request-OTR'ed, its important to clear it from disk / any persistant stores once those pages are closed.

Does that help? Happy to try and explain more @petemill if it'd be helpful

**Pull request merged**
