### PR TITLE
Updated Rewards to now respect main toggle and autocontribute toggle

### PR DESCRIPTION
**Pull request by jasonrsadler**
Resolves brave-intl/bat-native-ledger#58
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Needed or QA/No-QA-Needed) to include the closed issue in milestone 

## Test Plan:

1. Start Brave with a clean profile.
2. Opt in to rewards.
3. Navigate to a web site and wait the required time.
4. Verify site was added to autocontribute table.
5. Disable autocontribute and repeat step 3.
6. Verify site was not added to autocontribute table.
7. Enable autocontribute and disable rewards and repeat step 3 and 6.
8. Repeat tests by adding the step of disabling/enabling rewards and/or autocontribute, then closing browser and reopening to verify that sites were added/not added

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by jasonrsadler** [comment]
Blocked on https://github.com/brave-intl/bat-native-ledger/pull/87

**Comment by jasonrsadler** [comment]
Ready for Review

**Comment by jasonrsadler** [comment]
Resolved in brave-intl/bat-native-ledger#87

**Comment by jasonrsadler** [comment]
Pending resolve on `DEPS`

**Comment by jasonrsadler** [comment]
Blocked on #433

**Comment by jasonrsadler** [comment]
Ready for review

**Comment by petemill** [comment]
0.55.x 8ac7beae

**Pull request merged**
