### PR TITLE
Remove exception for Tracking Protection

### PR DESCRIPTION
**Pull request by bbondy**
Fix: https://github.com/brave/brave-browser/issues/3475
Related PR: https://github.com/brave/adblock-lists/pull/45

Related issue: https://github.com/brave/brave-browser/issues/1108

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by diracdeltas** [comment]
For transparency, I would like to keep our documentation up-to-date on what Brave unblocks for webcompatibility that is not blocked in upstream adblock/tp. https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection should be updated when this is merged to say that as of `<date this was merged>`, exceptions to tracking protection are handled by being added in adblock exceptions (to https://github.com/brave/adblock-lists/blob/master/brave-unbreak.txt ?)

**Comment by diracdeltas** [comment]
+1 on this approach though

**Comment by bbondy** [comment]
Just adding some tests, so I don't want approvals until that's done, but the code changes and plan are ready.  See https://github.com/brave/brave-browser/issues/3475 for a detailed description of everything.

**Comment by bbondy** [comment]
This is ready to go, tests were added.

**Pull request merged**
