### PR TITLE
Expose navigator.brave in workers

### PR DESCRIPTION
**Pull request by spylogsster**
Resolves https://github.com/brave/brave-browser/issues/28101

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
- go to search.brave.com
- open devtools and in top selector select the service worker script, or any other way to execute code in service worker
- type in the console: `navigator.brave.isBrave().then(console.log)` - should print `true`

### CODE REVIEW

**Comment by spylogsster** [comment]
> why this had to be implemented in a very different way? Why `partial interface WorkerNavigator` approach didn't work?

implemented similar way as others in WorkerNavigator

**Comment by pes10k** [comment]
as long as this test passes, then looks good to me! https://dev-pages.brave.software/dom-properties/controlled.html

**Review by pes10k — APPROVED** [review]
im not qualified to review the implementation, but the test is if this passes: https://dev-pages.brave.software/dom-properties/controlled.html

**Comment by goodov** [comment]
> > why this had to be implemented in a very different way? Why `partial interface WorkerNavigator` approach didn't work?
> 
> implemented same way as others in WorkerNavigator, https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/workers/worker_navigator.idl;l=36

I don't understand why we extend the normal `Navigator` only with this:
```
[
    ImplementedAs=NavigatorBrave
] partial interface Navigator {
    readonly attribute Brave brave;
};
```

but in case of WorkerNavigator we had to use `WorkerNavigator includes ...` syntax.

**Comment by goodov** [comment]
why not just use `NavigatorBase`? all this can be done much simpler: https://github.com/brave/brave-core/compare/master...issues/28101

**Comment by pes10k** [comment]
@goodov @spylogsster , if we now have a new, simpler way of adding properties in storage workers, could i ask one of you to knock out https://github.com/brave/brave-browser/issues/28885 too? (or, if not, to make sure @antonok-edm is aware of the correct method for modifying SW environments)?

**Comment by goodov** [comment]
> > why not just use `NavigatorBase`? all this can be done much simpler: [master...issues/28101](https://github.com/brave/brave-core/compare/master...issues/28101)
> 
> I see, looks much better, mind to create a separate PR with that solution @goodov ? I think we can close this one

created https://github.com/brave/brave-core/pull/17473

**Comment by spylogsster** [comment]
Closing this due to https://github.com/brave/brave-core/pull/17473

**Pull request closed without merging**
