### PR TITLE
Adds claim api for brave wallet (uplift to 1.17.x)

### PR DESCRIPTION
**Pull request by NejcZdovc**
Uplift of #6952
Resolves brave/brave-browser#12313

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
@NejcZdovc believe this one will need to be rebased. Mind taking a look? `init` failed on every platform and failed to apply patches.

**Comment by NejcZdovc** [comment]
done

**Comment by kjozwiak** [comment]
Restarting `macOS` via https://ci.brave.com/job/pr-brave-browser-claim-ios-17-macos/3/ using `WIPE_WORKSPACE` due to `init` failing as per https://ci.brave.com/job/pr-brave-browser-claim-ios-17-macos/2/execution/node/111/log/.

```
01:41:03  Error: Command 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --directory --recursive --no_auth --num_threads=16 --bucket chromium-apache-mac src/third_party/apache-mac' returned non-zero exit status 1 in /Users/jenkins/jenkins/workspace/pr-brave-browser-claim-ios-17-macos
01:41:03  Hook 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --directory --recursive --no_auth --num_threads=16 --bucket chromium-apache-mac src/third_party/apache-mac' took 39.06 secs
```

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.17.x` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
