### PR TITLE
Upgrade node module @types/chrome to the latest version

### PR DESCRIPTION
**Pull request by mariospr**
Due to a recent change in the DefinitelyTyped project [1], the `id`
property of the chrome.windows.Window interface can be undefined,
which is breaking the build for shieldsPanelReducer.ts and
rewards_panel_reducer.ts unless we add some checks to avoid
using invalid values.

Additionally, that upgrade also breaks `npm run tslint` on that it
now spits quite a few errors that would need to be fixed as well.

This PR fixes both issues and restores the upgrade of the
@types/chrome node module to version 0.0.147.

[1] https://github.com/DefinitelyTyped/DefinitelyTyped/commit/ad4b187c

Resolves https://github.com/brave/brave-browser/issues/17051

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

N/A

### CODE REVIEW

**Review by emerick — APPROVED** [review]
LGTM

**Comment by mariospr** [comment]
@emerick @petemill After talking to @Douglashdaniel today, I confirmed that this fix is not the only one we need to implement to be able to unlock the upgrade ofr the @types/chrome node module from 0.0.133 to 0.0.147, because somehow that upgrade would be causing quite a few errors running `npm run tslint`.

Therefore, and after double-checking with @mihaiplesa as well, I've filed a new ticket to associate to this PR (instead of the original one from yesterday), with slightly wider focus beyond simply adding these checks for the undefined value: https://github.com/brave/brave-browser/issues/17051

Basically, the idea is to use that issue to do **three things at once**:
1. Re-land the upgrade of @types/chrome from 0.0.133 to 0.0.147
2. Fix the undefined value (what I already have in https://github.com/brave/brave-core/pull/9491)
3. Fix the npm run tslint errors you found (thanks again)

As it stands right now, this PR already fixes (2), so I'm going to add another commit reverting https://github.com/brave/brave-core/pull/9487 to fix (1) and then I'll work on fixing (3) and adding a third commit for that.

Once that's fixed, if no more errors show up, we'll be able to review and merge this PR, but not before then.

Thanks and sorry for the back and forth!

**Comment by mariospr** [comment]
> Basically, the idea is to use that issue to do **three things at once**:
> 
> 1. Re-land the upgrade of @types/chrome from 0.0.133 to 0.0.147
> 2. Fix the undefined value (what I already have in [Upgrade node module @types/chrome to the latest version #9491](https://github.com/brave/brave-core/pull/9491))
> 3. Fix the npm run tslint errors
> 
> As it stands right now, this PR already fixes (2), so I'm going to add another commit reverting #9487 to fix (1) and then I'll work on fixing (3) and adding a third commit for that.
> 
> Once that's fixed, if no more errors show up, we'll be able to review and merge this PR, but not before then.

@petemill Just updated the PR to include a fix to problem (3), as per our conversation on Slack, after checking locally that I can both build Brave and that `npm run tslint` passes successfully now after locally upgrading to @types/chrome 0.0.147.

PTAL when you have a moment, thanks!

**Comment by mariospr** [comment]
@mihaiplesa Also pulling you in to this for a quick review of the first commit, the one that re-upgrades @type/chrome to 0.0.147, thanks!

**Review by mihaiplesa — APPROVED** [review]

**Review by petemill — APPROVED** [review]
Thank you!

**Pull request merged**
