### PR TITLE
several shields panel improvements

### PR DESCRIPTION
**Pull request by cezaraugusto**
## Submitter Checklist:

fix https://github.com/brave/brave-browser/issues/1894
fix https://github.com/brave/brave-browser/issues/1892
fix https://github.com/brave/brave-browser/issues/2488
fix https://github.com/brave/brave-browser/issues/2565

## Test Plan:

1. Ensure all features on shields work
  - Ads/Trackers should bump in sites such as https://wired.com
  - HTTPSE should respond to https://https-everywhere.badssl.com
  - Cookies should respond to http://www.html-kit.com/tools/cookietester/
  - Fingerprinting should respond to https://codepen.io/run-time/pen/XJNXWV

2. Ensure shields is accessible via keyboard using <kbd>tab</kbd> for navigation, <kbd>space</kbd> for actions. <kbd>enter</kbd> should work for buttons as well.

3. Ensure the general (not scripts) blocked list (accessed via arrow down icon) can be scrolled both horizontally and vertically

4. Issue brave/brave-browser#2488 is being set as fixed as scripts now use a toggle instead of a select element

5. Shields should look like the original spec [available here](https://brave.github.io/brave-ui/?selectedKind=Feature%20Components%2FShields&selectedStory=Enabled&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel&background=%23E9ECEF)

6. Ensure that once a given resource stat reach 0, the option to show resources blocked should have no interactions other than toggling switch on/off

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by bsclifton** [comment]
@cezaraugusto does 3rd party device recognition blocking work? (should it be included?)
Screen Shot 2019-03-11 at 4 14 59 PM

**Comment by bsclifton** [comment]
When going into a details screen (ex: in the above screenshot, you can expand `2` to see the list of `3rd-party trackers blocked`), there isn't really a keyboard shortcut (that I found) for going "back" to the general shields screen. If you hit escape, it closes the shields menu completely (pushing <kbd>enter</kbd> didn't engage the button for me).  However, if you manually choose the `Go Back` button and hit space, it works as expected. Or also if you hit tab at least once and then hit enter

**Comment by cezaraugusto** [comment]
@bsclifton re third-party scripts this is something I'm investigating but it has the same behavior in current release so if that's a bug it isn't new.

re keyboard shortcut there's no immediate closing but you can do it via <kbd>space</kbd> bar in the arrow's row or by <kbd>space</kbd>/<kbd>enter</kbd> in the bottom button. <kbd>esc</kbd> closes the extension but I think this is the default behavior

**Comment by cezaraugusto** [comment]
re fingerprinting I created https://github.com/brave/brave-browser/issues/3698 to keep track. 

since test plan works, PR is reviewed and both product and design agree with changes applied here I'm going to hit merge. if for some reason other reviewers still have feedback to give please comment and I can come with a follow-up. thanks all!

**Pull request merged**
