### PR TITLE
Update help link to be relevant for Windows users

### PR DESCRIPTION
**Pull request by bsclifton**
Fixes https://github.com/brave/brave-browser/issues/11746

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [x] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`, `npm run gn_check`)
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
1. Be on Windows
2. Have a fully built version
3. Try to do an update - update must fail
4. Verify link shown under `Learn more` goes to correct place

Would be great if there was a debug way to show the full status - but I find anything unfortunately

I tested myself on Windows by applying this patch manually:
```diff
diff --git a/patches/chrome-browser-resources-settings-about_page-about_page.html.patch b/patches/chrome-browser-resources-settings-about_page-about_page.h ml.patch
index 5d1e21798d..3a4d208479 100644
--- a/patches/chrome-browser-resources-settings-about_page-about_page.html.patch
+++ b/patches/chrome-browser-resources-settings-about_page-about_page.html.patch
@@ -1,13 +1,29 @@
 diff --git a/chrome/browser/resources/settings/about_page/about_page.html b/chrome/browser/resources/settings/about_page/about_page.html
-index e8299dcfeb8bda338290bd0f89811ca2e613be9f..888ce6e999104bb3ec2ae187213badde20d61be7 100644
+index e8299dcfeb8bda338290bd0f89811ca2e613be9f..ba9e1ba66b44388add93d47a9d853d2358cdd8e3 100644
 --- a/chrome/browser/resources/settings/about_page/about_page.html
 +++ b/chrome/browser/resources/settings/about_page/about_page.html
-@@ -72,9 +72,10 @@
+@@ -57,7 +57,7 @@
+           when update is done) or set the src (when it's updating). -->
+ <if expr="not chromeos">
+         <div class="icon-container"
+-            hidden="[[!shouldShowIcons_(showUpdateStatus_)]]">
++            hidden="[[shouldShowIcons_(showUpdateStatus_)]]">
+           <iron-icon
+               icon$="[[getUpdateStatusIcon_(
+                   obsoleteSystemInfo_, currentUpdateStatusEvent_)]]"
+@@ -67,14 +67,15 @@
+ </if>
+         <div class="flex cr-padded-text">
+ <if expr="not chromeos">
+-          <div id="updateStatusMessage" hidden="[[!showUpdateStatus_]]">
++          <div id="updateStatusMessage" hidden="[[showUpdateStatus_]]">
+             <div
                  inner-h-t-m-l="[[getUpdateStatusMessage_(
                      currentUpdateStatusEvent_)]]">
              </div>
-+<if expr="is_win"><a hidden$="[[!shouldShowLearnMoreLink_(currentUpdateStatusEvent_)]]" target="_blank" href="https://support.brave.com/hc/en-us/articles 360042816611-Why-isn-t-Brave-updating-automatically-on-Windows-"></if><if expr="not is_win">
-             <a hidden$="[[!shouldShowLearnMoreLink_(
+-            <a hidden$="[[!shouldShowLearnMoreLink_(
++<if expr="is_win"><a hidden$="[[shouldShowLearnMoreLink_(currentUpdateStatusEvent_)]]" target="_blank" href="https://support.brave.com/hc/en-us/articles/ 60042816611-Why-isn-t-Brave-updating-automatically-on-Windows-"></if><if expr="not is_win">
++            <a hidden$="[[shouldShowLearnMoreLink_(
                  currentUpdateStatusEvent_)]]" target="_blank"
 -                href="https://support.google.com/chrome?p=update_error">
 +                    href="https://community.brave.com?p=update_error"></if>
```

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by mkarolin** [comment]
I am wondering if it would be possible to implement this via https://github.com/brave/brave-core/blob/master/browser/resources/settings/brave_overrides/about_page.js and get rid of the patch altogether.

**Comment by bsclifton** [comment]
@mkarolin oh wow- yeah that should definitely work 😄 Good call! Will look at that approach

**Comment by bsclifton** [comment]
@mkarolin updated! 😄

**Review by mkarolin — APPROVED** [review]
LGTM 👍

**Comment by bsclifton** [comment]
cc: @bridiver on patch removal 😄

**Review by bridiver — APPROVED** [review]
patch change is good, but @petemill should probably checkoff the actual changes

**Review by petemill — APPROVED** [review]
++

**Pull request merged**
