### PR TITLE
fix npm audit errors (uplift to 1.25.x)

### PR DESCRIPTION
**Pull request by diracdeltas**
Resolves brave/brave-browser#16272

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by mihaiplesa — APPROVED** [review]

**Comment by mihaiplesa** [comment]
We're doing channel migrations tomorrow and this will be uplifted naturally, we could even close this PR to save some CI load.

**Comment by kjozwiak** [comment]
@mihaiplesa we can get it into `1.25.x` just in case we have another CR bump or need a `1.25.x` HF. We have https://github.com/brave/brave-core/pull/9114 that's going to be merged into `1.25.x` in case there's a CR bump or a need for another `1.25.x` release.

**Comment by kjozwiak** [comment]
Restarting `macOS` due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-fix-16272-1.25.x-macos/1/execution/node/146/log/.

```
 FAILED: obj/brave/browser/ui/sidebar/sidebar/sidebar_utils.o 
```

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.25.x` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
