### PR TITLE
Toolbar Icon Updates

### PR DESCRIPTION
**Pull request by rossmoody**
Partial updates for icon related refinement away from Chrome iconography in the toolbar. 

Getting more familiar with icon structure and Skia rendering in core and updated a few select icons in toolbar to reflect .23x icon styling/sizing. 

Could use a gander from @AlexeyBarabash and @petemill 

image

Fix https://github.com/brave/brave-browser/issues/422

### CODE REVIEW

**Comment by rossmoody** [comment]
Could possibly close #brave/brave-browser#270

**Comment by petemill** [comment]
Thanks @rossmoody - this is awesome! Still waiting to complete a build but I'll check if it fixes the huge icon issue on the Views UI (windows / linux / future mac), but I don't think it necessarily would.

**Comment by AlexeyBarabash** [comment]
@rossmoody icons on screenshot looks much better than before.

**Comment by AlexeyBarabash** [comment]
Looked on different platforms.
Linux before 
screenshot from 2018-06-23 23-07-16
Linux after
screenshot from 2018-06-23 23-16-17

macOS before
screen shot 2018-06-23 at 2 22 18 pm

macOS after
screen shot 2018-06-23 at 3 12 55 pm

Windows, 1920x1200 before PR
scale 100%
original_scale100
scale 125%
original_scale125
scale 150%
original_scale150
scale 200%
original_scale200

Windows, 1920x1200 after PR
scale 100%
ross_scale100

scale 125%
ross_scale125

scale 150%
ross_scale150

scale 200%
ross_scale200

Added myself and @bradleyrichter  as reviewers.

**Comment by AlexeyBarabash** [comment]
The next step after this PR  get merge is fix for https://github.com/brave/brave-browser/issues/270 by merging `*.1x.icon` files.

**Comment by bbondy** [comment]
merged, thanks @rossmoody

**Comment by srirambv** [comment]
Looks a little too bold on Windows 100% DPI (1920x1200). in comparision to bookmark icon in urlbar. @rossmoody icon could use a reduction in boldness 
image

**Comment by rossmoody** [comment]
@srirambv i agree. i think a little bold in general everywhere

**Pull request merged**
