### PR TITLE
Fixes ad notifications are not shown on Windows until a non ad notification has been authorized - 1.8.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/5131
Resolves https://github.com/brave/brave-browser/issues/8932

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by tmancey** [comment]
Windows FAILED CI, other platforms PASSED. Restarting Windows

**Comment by kjozwiak** [comment]
Looks like `Win x64` failed again as per https://ci.brave.com/job/brave-browser-build-pr/job/issues%252F8932-1.8.x/2/execution/node/312/log/. Restarting.

**Comment by kjozwiak** [comment]
@tmancey looks like it failed again on `Win x64` after a restart as per https://ci.brave.com/job/brave-browser-build-pr/job/issues%252F8932-1.8.x/4/execution/node/297/log/. Mind taking a look? Looks like it keeps failing at the same spot every time.

**Comment by kjozwiak** [comment]
QA went through the PR on Nightly via https://github.com/brave/brave-core/pull/5131#issuecomment-610723481 and didn't find any issues.

**Pull request merged**
