### PR TITLE
Fixes Brave Ads intermittently crashes when opening a new tab - 1.12.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/6304
Resolves https://github.com/brave/brave-browser/issues/9393

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by tmancey** [comment]
CI failed for known Brave Rewards browser test issue

**Comment by kjozwiak** [comment]
Currently `PR/Blocked` due to not being able to QA https://github.com/brave/brave-core/pull/6284 until https://github.com/brave/brave-core/pull/6248 has been fixed on Nightly.

**Comment by LaurenWags** [comment]
The following platforms failed CI and are being restarted:
* Android failed  --> https://ci.brave.com/job/pr-brave-browser-issues-9393-1.12.x/1/execution/node/444/log/
* Linux failed --> https://ci.brave.com/job/pr-brave-browser-issues-9393-1.12.x/1/execution/node/413/log/
* macOS failed --> https://ci.brave.com/job/pr-brave-browser-issues-9393-1.12.x/1/execution/node/322/log/
* Win x64 failed --> https://ci.brave.com/job/pr-brave-browser-issues-9393-1.12.x/1/execution/node/540/log/

**Comment by kjozwiak** [comment]
Looks like it failed at the same exact spot on all the platforms other than `iOS`. Looks like it's failing the `build` process due to the following failure:

```
16:31:17  FAILED: obj/brave/components/brave_ads/browser/browser/ads_service_impl.o
```

@tmancey mind taking a look when you're around? Adding `PR/Blocked` for now.

**Comment by tmancey** [comment]
@kjozwiak Issue resolved and builds restarted

**Pull request merged**
