### PR TITLE
Fixes padding in Rewards Panel

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/brave/brave-browser/issues/2590
Also Reverts https://github.com/brave/brave-core/pull/1072

This is meant to be a hardened fix for the rewards panel padding issue, the fix should persist beyond implementing the toggle tips component.

**Reviewer note: Do not merge. This must be additionally uplifted in brave-ui upon uplift approval in core. The ui hash will be finalized then.**

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
Defined in issue

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@ryanml can you please do the revert in a separate commit

**Comment by ryanml** [comment]
@NejcZdovc done

**Comment by kjozwiak** [comment]
@ryanml once this passes review and tests, you're free to uplift into `0.58.x` after deliberating with @rebron. Please make sure that all the required labels have been added/removed and the associated issue is added into the correct milestone.

**Comment by ryanml** [comment]
(0.61/master): 21fc9822b2618b1052e77c9bdc352f855ff601a9

**Comment by kjozwiak** [comment]
@ryanml did this land in `dev` & `beta` yet? Approved request [above](https://github.com/brave/brave-core/pull/1111#issuecomment-448110088).

**Pull request merged**
