### PR TITLE
Update AppMenu background

### PR DESCRIPTION
**Pull request by sangwoo108**
Set toolbar colors to App menu's background

Resolves https://github.com/brave/brave-browser/issues/37190

### Before
image

### After
image

It's subtle but changed to a little bit more grayish color by using kColorToolbar instead of White. This also affect other menu, such as back/forward menu

image

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by aguscruiz — APPROVED** [review]
Perfect! You're the best! Does it still look ok in dark / private / tor? 

I have the examples here if you want
https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=229%3A18699&mode=design&t=4nWGxyeCPpVYrp8Q-1

**Comment by sangwoo108** [comment]
Yeah looks like so

image

image

image

**Comment by aguscruiz** [comment]
> Yeah looks like so
> 
> image image image

Going a bit on a tangent, but the icons should also have the same color that they do in the toolbars when you're in private/tor. See how they're purple there? Should be the same in the menu

**Comment by sangwoo108** [comment]
Yeah the gray lines were getting on my nerves. Let my try again.

**Comment by sangwoo108** [comment]
Huh? I didn't mean to merge this but accidentally merged sorry 😢 will follow up

**Comment by sangwoo108** [comment]
aaa

**Comment by sangwoo108** [comment]
@aguscruiz This would be what we want

Light
image

Dark
image


Private
image



Tor
image

**Review by simonhong — APPROVED** [review]
👍🏼

**Comment by aguscruiz** [comment]
> Yeah looks like so
> 
> image image image

Perfect :Chefskiss:

**Pull request merged**
