### PR TITLE
Disable flaky tests.

### PR DESCRIPTION
**Pull request by iefremov**
Resolves https://github.com/brave/brave-browser/issues/12994

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by zenparsing — APPROVED** [review]

**Review by bbondy — APPROVED** [review]

**Comment by kjozwiak** [comment]
`test-browser` failed on `macOS` due to several reward failures as per https://ci.brave.com/job/pr-brave-browser-ie_disable_flaky-macos/1/execution/node/253/log/. However, these are known intermittent issues and don't block uplift. Some of these are being addressed in this specific PR as well.

```
11:54:30  4 tests failed:
11:54:30      RewardsBrowserTest.ActivateSettingsModal (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:120)
11:54:30      RewardsBrowserTest.ResetRewards (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:354)
11:54:30      RewardsContributionBrowserTest.TipConnectedPublisherVerified (../../brave/components/brave_rewards/browser/test/rewards_contribution_browsertest.cc:586)
11:54:30      RewardsContributionBrowserTest.TipUnverifiedPublisher (../../brave/components/brave_rewards/browser/test/rewards_contribution_browsertest.cc:304)
11:54:30  2 tests timed out:
11:54:30      RewardsBrowserTest.BackupRestoreModalHasNotice (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:304)
11:54:30      RewardsPromotionBrowserTest.ClaimViaSettingsPage (../../brave/components/brave_rewards/browser/test/rewards_promotion_browsertest.cc:196)
11:54:30  1 test crashed:
11:54:30      RewardsBrowserTest.ToggleAutoContribute (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:131)
```

**Comment by bsclifton** [comment]
Did restart of macOS with `WIPE_WORKSPACE` after it ran into issues with browser tests. It was running the `DISABLED_` ones for some reason

**Comment by bsclifton** [comment]
Restarted macOS after it got stuck

**Comment by bsclifton** [comment]
CI looks good! Likely had a bad run there

**Pull request merged**
