### PR TITLE
When using vertical tabs pinning a tab that is part of a group crashes the browser

### PR DESCRIPTION
**Pull request by Ilie-Lesan**
Resolves https://github.com/brave/brave-browser/issues/40365

I've used a fresh build of Chromium that use `CompoundTabContainer`(`tabs::kSplitTabStrip` enabled) and have the same problem.
Since `TabContainerImpl`(used in horizontal tabs) is using the `BrowserTabStripController`  and `PinnedTabContainerController  `from `CompoundTabContainer` is relaying on the same controller, I think is pretty safe to use it until we have an upstream fix. 

@sangwoo108 Is there any reason vertical tabs doesn't use `TabContainerImpl`, are there any benefits :) ?

@sangwoo108 @bsclifton a review please. thanks!

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by simonhong** [comment]
Sorry for the late reply.
Looking at this issue and I think the root cause is target tab's group id seems not cleared when it's unpinned.
Investigating what's happneing there.

**Comment by simonhong** [comment]
Can you test this changes instead of patch files?
I found that this crash comes frome the mismatch of grouped state between `Tab` and pinned `TabContainerImpl` in `CompundTabContainer`. When tab is moved by pinning, target tab is moved to pinned `TabContainerImpl` before
that tab's group state is updated. So, we need to update group id in advance.
```
diff --git a/browser/ui/views/tabs/brave_tab.cc b/browser/ui/views/tabs/brave_tab.cc
index 8456749ec90..08eb6913d34 100644
--- a/browser/ui/views/tabs/brave_tab.cc
+++ b/browser/ui/views/tabs/brave_tab.cc
@@ -193,3 +193,15 @@ void BraveTab::UpdateShadowForActiveTab() {
     DestroyLayer();
   }
 }
+
+void BraveTab::SetData(TabRendererData data) {
+  const bool data_changed = data != data_;
+  Tab::SetData(std::move(data));
+
+  if (data_changed &&
+      tabs::utils::ShouldShowVerticalTabs(controller()->GetBrowser()) &&
+      data_.pinned) {
+    // Clear group if pinned.
+    set_group(std::nullopt);
+  }
+}
diff --git a/browser/ui/views/tabs/brave_tab.h b/browser/ui/views/tabs/brave_tab.h
index 7c48417ee12..8bd14932d8c 100644
--- a/browser/ui/views/tabs/brave_tab.h
+++ b/browser/ui/views/tabs/brave_tab.h
@@ -40,6 +40,7 @@ class BraveTab : public Tab {
   void MaybeAdjustLeftForPinnedTab(gfx::Rect* bounds,
                                    int visual_width) const override;
   gfx::Insets GetInsets() const override;
+  void SetData(TabRendererData data) override;

  private:
   friend class BraveTabTest;
diff --git a/chromium_src/chrome/browser/ui/views/tabs/tab.h b/chromium_src/chrome/browser/ui/views/tabs/tab.h
index 7e2b795d6a0..8cc15a690dc 100644
--- a/chromium_src/chrome/browser/ui/views/tabs/tab.h
+++ b/chromium_src/chrome/browser/ui/views/tabs/tab.h
@@ -18,6 +18,7 @@ class BraveTab;
 #define GetWidthOfLargestSelectableRegion \
   virtual GetWidthOfLargestSelectableRegion

+#define SetData virtual SetData
 #define ActiveStateChanged virtual ActiveStateChanged
 #define GetGroupColor virtual GetGroupColor
 #define UpdateIconVisibility virtual UpdateIconVisibility
@@ -33,5 +34,6 @@ class BraveTab;
 #undef ActiveStateChanged
 #undef GetWidthOfLargestSelectableRegion
 #undef kMinimumContentsWidthForCloseButtons
+#undef SetData

 #endif  // BRAVE_CHROMIUM_SRC_CHROME_BROWSER_UI_VIEWS_TABS_TAB_H_

```

**Comment by simonhong** [comment]
@Ilie-Lesan I opened another PR(https://github.com/brave/brave-core/pull/25983) with my changes based on this PR as this crash happens more frequently we need to speed up. Thanks for sending this PR! and PTAL that PR also.

**Comment by Ilie-Lesan** [comment]
@simonhong, it is probably a bit too late, but I will do some testing anyway. Thanks!

**Pull request closed without merging**
