### PR TITLE
Sync clear orders map

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Fixes https://github.com/brave/brave-browser/issues/2367 .

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [x] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [x] Linux
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
1. Create sync chain on device 1
2. Join device 2 and add a bookmark on device 2, gets sync'd to device 1
3. Import 5000 bookmark HTML file on device 1, wait for a really long time to sync bookmarks into device 2 
4. Expand the very nested folder in bookmarks on device 2, see some bookmarks at a wrong position compare to device 1

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
Done force push of change `OrdersMap => OrderMap`  according to the review.

**Comment by AlexeyBarabash** [comment]
master: https://github.com/brave/brave-core/commit/a11bb37c5657a06ff37939c0a3c3bb10a4164c54 
0.60.x: https://github.com/brave/brave-core/commit/daa3fa0816f56b1ac5d6883b21d6629f0472ac14

**Comment by AlexeyBarabash** [comment]
0.59.x: https://github.com/brave/brave-core/commit/085f376b44347b1a212f049a7d55df46962a0d3a

**Comment by rebron** [comment]
After deliberating with @kjozwiak, keep this pr in 59.x and uplift-approved. @darkdh don't set the uplift-approved flags, just uplift-requests. We'll get to them quickly. We need to see and control what's getting in during the freeze period.

**Comment by darkdh** [comment]
sorry, I was putting the wrong label. I meant to put uplift-request

**Pull request merged**
