### PR TITLE
Fixes Brave Ads fails to upgrade segment database table from 1.19.x to 1.20.x and above - 1.20.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/7678
Resolves https://github.com/brave/brave-browser/issues/13719

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
Looks like there was a few `lint` errors when running `post-init` as per https://ci.brave.com/blue/rest/organizations/jenkins/pipelines/pr-brave-browser-issues-13719-1.20.x-post-init/runs/4/nodes/113/log/?start=0.

```
[2021-01-23T11:04:34.594Z] Running cpplint...
[2021-01-23T11:04:34.594Z] Skipping file components/brave_ads/test/BUILD.gn
[2021-01-23T11:04:34.594Z] vendor/bat-native-ads/src/bat/ads/internal/database/tables/ad_events_database_table_unittest.cc:23:  Add #include <memory> for unique_ptr<>  [build/include_what_you_use] [4]
[2021-01-23T11:04:34.594Z] Done processing vendor/bat-native-ads/src/bat/ads/internal/database/tables/ad_events_database_table_unittest.cc
[2021-01-23T11:04:34.594Z] vendor/bat-native-ads/src/bat/ads/internal/database/tables/campaigns_database_table_unittest.cc:23:  Add #include <memory> for unique_ptr<>  [build/include_what_you_use] [4]
[2021-01-23T11:04:34.594Z] Done processing vendor/bat-native-ads/src/bat/ads/internal/database/tables/campaigns_database_table_unittest.cc
[2021-01-23T11:04:34.594Z] vendor/bat-native-ads/src/bat/ads/internal/database/tables/creative_ads_database_table_unittest.cc:23:  Add #include <memory> for unique_ptr<>  [build/include_what_you_use] [4]
[2021-01-23T11:04:34.594Z] Done processing vendor/bat-native-ads/src/bat/ads/internal/database/tables/creative_ads_database_table_unittest.cc
[2021-01-23T11:04:34.594Z] vendor/bat-native-ads/src/bat/ads/internal/database/tables/dayparts_database_table_unittest.cc:23:  Add #include <memory> for unique_ptr<>  [build/include_what_you_use] [4]
[2021-01-23T11:04:34.594Z] Done processing vendor/bat-native-ads/src/bat/ads/internal/database/tables/dayparts_database_table_unittest.cc
[2021-01-23T11:04:34.594Z] vendor/bat-native-ads/src/bat/ads/internal/database/tables/geo_targets_database_table_unittest.cc:23:  Add #include <memory> for unique_ptr<>  [build/include_what_you_use] [4]
[2021-01-23T11:04:34.594Z] Done processing vendor/bat-native-ads/src/bat/ads/internal/database/tables/geo_targets_database_table_unittest.cc
[2021-01-23T11:04:34.594Z] Done processing vendor/bat-native-ads/src/bat/ads/internal/database/tables/segments_database_table.cc
[2021-01-23T11:04:34.594Z] vendor/bat-native-ads/src/bat/ads/internal/database/tables/segments_database_table_unittest.cc:23:  Add #include <memory> for unique_ptr<>  [build/include_what_you_use] [4]
[2021-01-23T11:04:34.594Z] Done processing vendor/bat-native-ads/src/bat/ads/internal/database/tables/segments_database_table_unittest.cc
[2021-01-23T11:04:34.594Z] Skipping clang/gn format check because base_branch is origin/1.20.x instead of refs/remotes/origin/master
[2021-01-23T11:04:34.594Z] cpplint errors found: 6
```

**Comment by tmancey** [comment]
@kjozwiak Fixed linter issues and merged

**Comment by kjozwiak** [comment]
`test-browser` failed on `macOS` due to `RewardsPromotionBrowserTest.ClaimViaPanel ` failing as per the following:

* https://ci.brave.com/blue/rest/organizations/jenkins/pipelines/pr-brave-browser-issues-13719-1.20.x-macos/runs/4/nodes/197/log/?start=0

```
[2021-01-26T20:07:13.834Z] [  FAILED  ] RewardsPromotionBrowserTest.ClaimViaPanel, where TypeParam =  and GetParam() =  (31052 ms)

[2021-01-26T20:07:13.834Z] [669/669] RewardsPromotionBrowserTest.ClaimViaPanel (31143 ms)

[2021-01-26T20:07:13.834Z] 1 test failed:

[2021-01-26T20:07:13.834Z]     RewardsPromotionBrowserTest.ClaimViaPanel (../../brave/components/brave_rewards/browser/test/rewards_promotion_browsertest.cc:204)
```

However, this is a known intermittent issue as per https://github.com/brave/brave-browser/issues/12605 and doesn't block uplift.

**Comment by kjozwiak** [comment]
@tmancey mind taking a look at this one? It keeps failing `Win`:

```
23:28:12  SignTool Error: No certificates were found that met all the given criteria.
23:28:12  scons: *** [scons-out\opt-win\obj\google_update\BraveUpdate_signed.exe] Error 1
23:28:12  scons: building terminated because of errors.
23:28:12  Traceback (most recent call last):
23:28:12    File "../../brave/vendor/omaha/build_omaha.py", line 200, in <module>
23:28:12      sys.exit(Main(sys.argv))
23:28:12    File "../../brave/vendor/omaha/build_omaha.py", line 193, in Main
23:28:12      Tagging(args, omaha_dir, False)
23:28:12    File "../../brave/vendor/omaha/build_omaha.py", line 130, in Tagging
23:28:12      sp.check_call(command, stderr=sp.STDOUT)
23:28:12    File "C:\20.x\src\brave\vendor\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\lib\subprocess.py", line 185, in check_call
23:28:12      retcode = call(*popenargs, **kwargs)
23:28:12    File "C:\20.x\src\brave\vendor\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\lib\subprocess.py", line 172, in call
23:28:12      return Popen(*popenargs, **kwargs).wait()
23:28:12    File "C:\20.x\src\brave\vendor\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\lib\subprocess.py", line 394, in __init__
23:28:12      errread, errwrite)
23:28:12    File "C:\20.x\src\brave\vendor\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\lib\subprocess.py", line 644, in _execute_child
23:28:12      startupinfo)
23:28:12  WindowsError: [Error 2] The system cannot find the file specified
23:28:12  ninja: build stopped: subcommand failed.
23:28:12  null
23:28:12  powershell.exe : null
23:28:12  At C:\20.x@tmp\durable-b3677b15\powershellWrapper.ps1:3 char:1
23:28:12  + & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Comm ...
23:28:12  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23:28:12      + CategoryInfo          : NotSpecified: (null:String) [], RemoteException
23:28:12      + FullyQualifiedErrorId : NativeCommandError
```

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.20.x` approved after deliberating with @brave/uplift-approvers. QA has also verified the PR on Nightly as per https://github.com/brave/brave-core/pull/7678#issuecomment-767715479.

**Pull request merged**
