### PR TITLE
[Commands]: Don't allow editing of unmodifiable commands

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Resolves https://github.com/brave/brave-browser/issues/31353

Removes a number of commands which weren't really doing anything and marks some commands as unmodifiable on macOS

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by sangwoo108 — APPROVED** [review]
LGTM 👍 Have no objection for this

**Comment by fallaciousreasoning** [comment]
@simonhong would you mind checking to see if this works for you too?

**Comment by simonhong** [comment]
> @simonhong would you mind checking to see if this works for you too (I don't have a Mac sorry)?

Works well for me also. Remove circle is only shown for custom shortcut.

**Review by mkarolin — APPROVED** [review]
`strings`++

**Comment by kjozwiak** [comment]
Verification **PASSED**

```
Brave | 1.55.97 Chromium: 115.0.5790.56 (Official Build) nightly (x86_64)
--- | ---
Revision | 471581719570c2b56ee852bd7e44c2b2d143801b
OS | macOS Version 13.4 (Build 22F66)
```

Reproduced the original issue on `1.55.80 Chromium: 115.0.5790.40` using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/31353#issue-1778037810 as per the following:

* enable to remove `CMD` + `T` (shouldn't be allowed as per the issue/PR)
* enable to add/assign `Command` + `T` to other shortcuts (shouldn't be allowed as per the issue/PR)

**`Example`** | **`Example`**
----------------|-----------------
Screenshot 2023-07-05 at 12 40 11 AM | Screenshot 2023-07-05 at 12 41 06 AM

Verified using the STR/Cases mentioned above as per the following:

* ensured that you cannot remove `Command` + `T`
* ensured that you cannot remove `Command` + `P`
* ensured that you cannot remove `Command` + `V`
* ensured that you cannot remove `Command` + `]`
* ensured that you can still add other shortcuts that don't appear via the menu's into the above

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------
Screenshot 2023-07-05 at 12 45 14 AM | Screenshot 2023-07-05 at 12 46 22 AM | Screenshot 2023-07-05 at 12 47 36 AM | Screenshot 2023-07-05 at 12 46 40 AM | Screenshot 2023-07-05 at 12 47 11 AM

**Pull request merged**
