### PR TITLE
Binance widget no connection state android 1 17 x (uplift to 1.17.x)

### PR DESCRIPTION
**Pull request by deeppandya**
Uplift of #7178 
Resolves https://github.com/brave/brave-browser/issues/12733 
Resolves https://github.com/brave/brave-browser/issues/12736 
Resolves https://github.com/brave/brave-browser/issues/12735 
Resolves https://github.com/brave/brave-browser/issues/12720 
Resolves https://github.com/brave/brave-browser/issues/12757

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
Restarting `Android` via https://ci.brave.com/job/pr-brave-browser-binance_widget_no_connection_state_android_1_17_x-android/2/ due to `dist` failing as per https://ci.brave.com/job/pr-brave-browser-binance_widget_no_connection_state_android_1_17_x-android/1/execution/node/201/log/.

```
14:43:02  ninja: error: '../../brave/android/java/org/chromium/chrome/browser/BraveRewardsOnboardingPagerAdapter.java', needed by 'obj/chrome/android/chrome_java.turbine.jar', missing and no known rule to make it
```

**Comment by deeppandya** [comment]
> Restarting `Android` via https://ci.brave.com/job/pr-brave-browser-binance_widget_no_connection_state_android_1_17_x-android/2/ due to `dist` failing as per https://ci.brave.com/job/pr-brave-browser-binance_widget_no_connection_state_android_1_17_x-android/1/execution/node/201/log/.
> 
> ```
> 14:43:02  ninja: error: '../../brave/android/java/org/chromium/chrome/browser/BraveRewardsOnboardingPagerAdapter.java', needed by 'obj/chrome/android/chrome_java.turbine.jar', missing and no known rule to make it
> ```

@kjozwiak i have updated the PR.

**Comment by kjozwiak** [comment]
Restarting `Linux` as it looks like it failed to fetch the needed repo's as per https://ci.brave.com/job/pr-brave-browser-binance_widget_no_connection_state_android_1_17_x-linux/3/execution/node/85/log/.

```
16:42:58  ERROR: Error fetching remote repo 'origin'
16:42:58  hudson.plugins.git.GitException: Failed to fetch from https://github.com/brave/devops.git
```

**Comment by kjozwiak** [comment]
Restarting `Win x64` as `build` failed due to connectivity issues with the instance as per https://ci.brave.com/job/pr-brave-browser-binance_widget_no_connection_state_android_1_17_x-windows/3/execution/node/200/log.

```
17:08:03  Cannot contact i-0391abd8a424e71e4-windows-swarm-3e222429: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException
17:13:03  Could not connect to i-0391abd8a424e71e4-windows-swarm-3e222429 to send interrupt signal to process
```

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.17.x` approved after deliberating with @brave/uplift-approvers. QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/7178#issuecomment-730092513.

**Pull request merged**
