### PR TITLE
Pulled l10n for 1.37.x release (Chromium 100). Part II.

### PR DESCRIPTION
**Pull request by mkarolin**
Fixes https://github.com/brave/brave-browser/issues/22185
Fixes https://github.com/brave/brave-browser/issues/21808
Fixes https://github.com/brave/brave-browser/issues/21980
Fixes https://github.com/brave/brave-browser/issues/22104

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by emerick — APPROVED** [review]
LGTM

**Comment by Tonev** [comment]
@mkarolin 

This l10n pull also resolves https://github.com/brave/brave-browser/issues/21808. You might like to include it in your description so merging will close the issue :+1:

**Review by szilardszaloki — APPROVED** [review]
++

**Comment by kjozwiak** [comment]
@mkarolin assuming we'll want this in the `1.37.x` maintenance release. Looks like there's a bunch of failures on all the platforms:

```
 FAILED: gen/brave/components/resources/strings_grit.d.stamp gen/components/grit/brave_components_strings.h gen/components/brave_components_strings_am.pak gen/components/brave_components_strings_ar.pak gen/components/brave_components_strings_bg.pak gen/components/brave_components_strings_bn.pak gen/components/brave_components_strings_ca.pak gen/components/brave_components_strings_cs.pak gen/components/brave_components_strings_da.pak gen/components/brave_components_strings_de.pak gen/components/brave_components_strings_el.pak gen/components/brave_components_strings_en-GB.pak gen/components/brave_components_strings_en-US.pak gen/components/brave_components_strings_es.pak gen/components/brave_components_strings_es-419.pak gen/components/brave_components_strings_et.pak gen/components/brave_components_strings_fa.pak gen/components/brave_components_strings_fi.pak gen/components/brave_components_strings_fil.pak gen/components/brave_components_strings_fr.pak gen/components/brave_components_strings_gu.pak gen/components/brave_components_strings_he.pak gen/components/brave_components_strings_hi.pak gen/components/brave_components_strings_hr.pak gen/components/brave_components_strings_hu.pak gen/components/brave_components_strings_id.pak gen/components/brave_components_strings_it.pak gen/components/brave_components_strings_ja.pak gen/components/brave_components_strings_kn.pak gen/components/brave_components_strings_ko.pak gen/components/brave_components_strings_lt.pak gen/components/brave_components_strings_lv.pak gen/components/brave_components_strings_ml.pak gen/components/brave_components_strings_mr.pak gen/components/brave_components_strings_ms.pak gen/components/brave_components_strings_nb.pak gen/components/brave_components_strings_nl.pak gen/components/brave_components_strings_pl.pak gen/components/brave_components_strings_pt-BR.pak gen/components/brave_components_strings_pt-PT.pak gen/components/brave_components_strings_ro.pak gen/components/brave_components_strings_ru.pak gen/components/brave_components_strings_sk.pak gen/components/brave_components_strings_sl.pak gen/components/brave_components_strings_sr.pak gen/components/brave_components_strings_sv.pak gen/components/brave_components_strings_sw.pak gen/components/brave_components_strings_ta.pak gen/components/brave_components_strings_te.pak gen/components/brave_components_strings_th.pak gen/components/brave_components_strings_tr.pak gen/components/brave_components_strings_uk.pak gen/components/brave_components_strings_vi.pak gen/components/brave_components_strings_zh-CN.pak gen/components/brave_components_strings_zh-TW.pak gen/components/brave_components_strings_ar-XB.pak gen/components/brave_components_strings_en-XA.pak gen/components/brave_components_strings_am.pak.info gen/components/brave_components_strings_ar.pak.info gen/components/brave_components_strings_bg.pak.info gen/components/brave_components_strings_bn.pak.info gen/components/brave_components_strings_ca.pak.info gen/components/brave_components_strings_cs.pak.info gen/components/brave_components_strings_da.pak.info gen/components/brave_components_strings_de.pak.info gen/components/brave_components_strings_el.pak.info gen/components/brave_components_strings_en-GB.pak.info gen/components/brave_components_strings_en-US.pak.info gen/components/brave_components_strings_es.pak.info gen/components/brave_components_strings_es-419.pak.info gen/components/brave_components_strings_et.pak.info gen/components/brave_components_strings_fa.pak.info gen/components/brave_components_strings_fi.pak.info gen/components/brave_components_strings_fil.pak.info gen/components/brave_components_strings_fr.pak.info gen/components/brave_components_strings_gu.pak.info gen/components/brave_components_strings_he.pak.info gen/components/brave_components_strings_hi.pak.info gen/components/brave_components_strings_hr.pak.info gen/components/brave_components_strings_hu.pak.info gen/components/brave_components_strings_id.pak.info gen/components/brave_components_strings_it.pak.info gen/components/brave_components_strings_ja.pak.info gen/components/brave_components_strings_kn.pak.info gen/components/brave_components_strings_ko.pak.info gen/components/brave_components_strings_lt.pak.info gen/components/brave_components_strings_lv.pak.info gen/components/brave_components_strings_ml.pak.info gen/components/brave_components_strings_mr.pak.info gen/components/brave_components_strings_ms.pak.info gen/components/brave_components_strings_nb.pak.info gen/components/brave_components_strings_nl.pak.info gen/components/brave_components_strings_pl.pak.info gen/components/brave_components_strings_pt-BR.pak.info gen/components/brave_components_strings_pt-PT.pak.info gen/components/brave_components_strings_ro.pak.info gen/components/brave_components_strings_ru.pak.info gen/components/brave_components_strings_sk.pak.info gen/components/brave_components_strings_sl.pak.info gen/components/brave_components_strings_sr.pak.info gen/components/brave_components_strings_sv.pak.info gen/components/brave_components_strings_sw.pak.info gen/components/brave_components_strings_ta.pak.info gen/components/brave_components_strings_te.pak.info gen/components/brave_components_strings_th.pak.info gen/components/brave_components_strings_tr.pak.info gen/components/brave_components_strings_uk.pak.info gen/components/brave_components_strings_vi.pak.info gen/components/brave_components_strings_zh-CN.pak.info gen/components/brave_components_strings_zh-TW.pak.info gen/components/brave_components_strings_ar-XB.pak.info gen/components/brave_components_strings_en-XA.pak.info 
20:16:02  python3 ../../tools/grit/grit.py -i ../../brave/components/resources/brave_components_strings.grd build -o gen/components --depdir . --depfile gen/brave/components/resources/strings_grit.d --write-only-new=1 --depend-on-stamp -E root_gen_dir=gen -E root_src_dir=../../ -D SHARED_INTERMEDIATE_DIR=gen -D DEVTOOLS_GRD_PATH=gen/third_party/devtools-frontend/src/front_end/devtools_resources -D scale_factors=2x -D use_titlecase -D _chromium -E CHROMIUM_BUILD=chromium -D toolkit_views -D enable_speedreader=true -D enable_ipfs=true -D ethereum_remote_client_enabled=true -D decentralized_dns_enabled=true -D crypto_dot_com_enabled=true -D enable_tor=true -D enable_sidebar=true -D enable_ftx=true -D enable_brave_vpn=true -f ../../brave/browser/resources/resource_ids -p ../../tools/gritsettings/startup_resources_mac.txt --assert-file-list obj/brave/components/resources/strings_expected_outputs.txt
20:16:02 
 ERROR: 'he' translation of message id 7709075156958117386 does not match
```

**Comment by mkarolin** [comment]
Windows CI failed in unrelated browser tests (`BraveNavigatorUserAgentFarblingBrowserTest.AddBraveToNavigatorUserAgentBrandList`).

**Pull request merged**
