### PR TITLE
Fix front-end bug with max fee not updating with base fee  (uplift to 1.36.x)

### PR DESCRIPTION
**Pull request by onyb**
Uplift of https://github.com/brave/brave-core/pull/12054/commits/af20334847dcac173f3e6afce5dcf654c35dc8d7 to **`1.36.x`** (cherry-picked from https://github.com/brave/brave-core/pull/12054).

Resolves https://github.com/brave/brave-browser/issues/21105.

Pre-approval checklist: 
- [x] You have tested your change on Nightly. 
- [ ] This contains text which needs to be translated. 
    - [ ] There are more than 7 days before the release. 
    - [ ] I've notified folks in #l10n on Slack that translations are needed. 
- [x] The PR milestones match the branch they are landing to. 

Pre-merge checklist: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 

Post-merge checklist: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Review by Douglashdaniel — APPROVED** [review]
++

**Review by bbondy — APPROVED** [review]
Thank you!

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.37.52 Chromium: 98.0.4758.102 (Official Build) nightly (64-bit)
-- | --
Revision | `273bf7ac8c909cde36982d27f66f3c70846a3718-refs/branch-heads/4758@{#1151}`
OS | Windows 11 Version Dev (Build 22543.1000)

- Verified the base fee updates every 15 secs
- Verified `Per-gas price limit` updates as and when base fee updates
- Verified suggested fee is also showing correct values

https://user-images.githubusercontent.com/17010094/154288522-0ec90103-6401-4e08-b900-6aac79effb7a.mov

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.36.x` approved after deliberating with @brave/uplift-approvers. QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/12264#issuecomment-1041565073.

**Pull request merged**
