### PR TITLE
Android decrease symbols

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Resolves https://github.com/brave/brave-browser/issues/9168

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues/9168) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
See https://github.com/brave/brave-browser/issues/9168

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by AlexeyBarabash** [comment]
Failed: android s3-upload, linux was aborted, windows was aborted.
Succeeded: macOS, iOS.
Skipping macOS and iOS and restarting.

**Comment by AlexeyBarabash** [comment]
Last failed error is for Android S3 upload, 
```
The user-provided path src/out/android_Release_arm/dist/Defaultarmclassic does not exist.
```
which makes sense, because I renamed the archive Defaultarmclassic => Defaultarmclassic.tar.

So I also need to rename at https://github.com/brave/brave-browser/blob/master/Jenkinsfile#L155 . - this is a CI build.

But there are also production builds, which generates apks and symbols.
@mihaiplesa where I must apply rename of symbol files like `Defaultarmclassic => Defaultarmclassic.tar.` for production builds?

**Comment by AlexeyBarabash** [comment]
Related PR in b-b is https://github.com/brave/brave-browser/pull/9175

**Comment by AlexeyBarabash** [comment]
android dist failed to sign
```
using sccache
21:49:29  signing ...
21:49:29  /home/ubuntu/jenkins/workspace/brave-browser-build-pr_PR-9175/src: ninja -C /home/ubuntu/jenkins/workspace/brave-browser-build-pr_PR-9175/src/out/android_Release_arm sign_app
21:49:29  ninja: Entering directory `/home/ubuntu/jenkins/workspace/brave-browser-build-pr_PR-9175/src/out/android_Release_arm'
21:49:30  [1/2] ACTION //brave/build/android:sign_app(//build/toolchain/android:android_clang_arm)
21:49:30  FAILED: apks/ChromePublic.apk-singed 
21:49:30  python ../../brave/build/android/sign_apk.py ../../third_party/android_sdk/public/build-tools/29.0.2/zipalign ../../third_party/android_sdk/public/build-tools/29.0.2/apksigner apks/ChromePublic.apk ../../brave/build/android   
21:49:30  usage: sign_apk.py [-h]
21:49:30                     zipalign_path apksigner_path unsigned_apk_path key_path
21:49:30                     key_passwd prvt_key_passwd key_name
21:49:30  sign_apk.py: error: too few arguments
21:49:30  ninja: build stopped: subcommand failed.
```
Linux failed to init
```
21:13:15  fatal: unable to access 'https://chromium.googlesource.com/chromium/tools/depot_tools.git/': The requested URL returned error: 429
21:13:15  fatal: clone of 'https://chromium.googlesource.com/chromium/tools/depot_tools.git' into submodule path '/home/ubuntu/jenkins/workspace/brave-browser-build-pr_PR-9175/vendor/depot_tools' failed
```
restarting

**Comment by AlexeyBarabash** [comment]
Windows and Linux succeeded.
Android  failed at create_dist, the same error with signing
```
00:12:34  signing ...
00:12:34  /home/ubuntu/jenkins/workspace/brave-browser-build-pr_PR-9175/src: ninja -C /home/ubuntu/jenkins/workspace/brave-browser-build-pr_PR-9175/src/out/android_Release_arm sign_app
00:12:34  ninja: Entering directory `/home/ubuntu/jenkins/workspace/brave-browser-build-pr_PR-9175/src/out/android_Release_arm'
00:12:35  [1/2] ACTION //brave/build/android:sign_app(//build/toolchain/android:android_clang_arm)
00:12:35  FAILED: apks/ChromePublic.apk-singed 
00:12:35  python ../../brave/build/android/sign_apk.py ../../third_party/android_sdk/public/build-tools/29.0.2/zipalign ../../third_party/android_sdk/public/build-tools/29.0.2/apksigner apks/ChromePublic.apk ../../brave/build/android   
00:12:35  usage: sign_apk.py [-h]
00:12:35                     zipalign_path apksigner_path unsigned_apk_path key_path
00:12:35                     key_passwd prvt_key_passwd key_name
00:12:35  sign_apk.py: error: too few arguments
00:12:35  ninja: build stopped: subcommand failed.
```

**Comment by AlexeyBarabash** [comment]
Skipped Linux and will rebase b-c and b-b branches.

**Comment by mihaiplesa** [comment]
@AlexeyBarabash have added `*` to end in all public build pipelines https://github.com/brave/devops/pull/2920/files#diff-0020e5232546336f22222ecd073d72f4R217

You might want to do the same in the Jenkinsfile in this PR.

**Comment by AlexeyBarabash** [comment]
Thanks @mihaiplesa ,
I will update https://github.com/brave/brave-browser/pull/9175/files in the same way you just shown

**Pull request merged**
