### PR TITLE
Added npm scripts to run pylint and added .pylintrc to control suppressions and other options.

### PR DESCRIPTION
**Pull request by wknapik**
Resolves https://github.com/brave/devops/issues/4784

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by mihaiplesa — APPROVED** [review]

**Review by mihaiplesa — APPROVED** [review]

**Comment by wknapik** [comment]
Part of the implementation is in the devops repo and that is already merged to master. This can merged when approved.

**Review by antonok-edm — APPROVED** [review]
Just gave this a try. I didn't actually have `pylint` installed on my machine, so it failed immediately with

```
./script/pylint.sh: line 67: exec: pylint: not found
```

Not sure if there is a vendored version we should use, or if this is acceptable.

Otherwise, after installing pylint, it looks like it works quite well :smile:

**Comment by wknapik** [comment]
Thanks for testing @antonok-edm!

@mihaiplesa do you think it's reasonable to just expect anyone trying to run pylint to have it installed, or should the tool be vendored in the repo? IMO the former would be fine, but maybe there's a precedent, or a good reason for vendoring?

@mihaiplesa also, a test on macOS would be nice - could you check how this works for you? tl;dr - `npm run pylint:help` for help, `npm run pylint -- --compare-with master` to analyse files changed since branching off of master and `npm run pylint` to analyse all files.

**Comment by mihaiplesa** [comment]
```
> brave-core@1.25.7 pylint:help /Users/exit/work/brave-core
> ./script/pylint.sh --help

USAGE: pylint.sh --help
       pylint.sh [--compare-with <base_branch> [--only-new]] [--report]

Run pylint on python files in: build components installer script tools

--compare-with <base_branch>: only analyse files changed compared to base_branch
--only-new: exclude old findings from <base_branch> (NOT IMPLEMENTED YET)
--report: produce a parseable report file

Calling via `npm run', e.g.:
npm run pylint
npm run pylint -- --compare-with master
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave-core@1.25.7 pylint:help: `./script/pylint.sh --help`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave-core@1.25.7 pylint:help script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/exit/.npm/_logs/2021-04-09T22_10_51_153Z-debug.log
zenair:brave-core exit$ npm run pylint -- --compare-with master

> brave-core@1.25.7 pylint /Users/exit/work/brave-core
> ./script/pylint.sh "--compare-with" "master"

No pylint findings compared with master in: build components installer script tools
```

You can also test in the workspace of the PR builds or just on any macOS node.

**Review by mihaiplesa — APPROVED** [review]

**Comment by wknapik** [comment]
@mihaiplesa thanks. The error message from npm should be fixed.

**Review by mihaiplesa — APPROVED** [review]
Tested again on macOS, all commands work fine now.

**Review by mihaiplesa — APPROVED** [review]

**Review by mihaiplesa — APPROVED** [review]

**Pull request merged**
