### PR TITLE
Removing back arrow in asset detail view, updating top buy link [crypto.com widget]

### PR DESCRIPTION
**Pull request by ryanml**
Fixes: https://github.com/brave/brave-browser/issues/12277
Fixes: https://github.com/brave/brave-browser/issues/12304

Screen Shot 2020-10-23 at 1 55 12 PM

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`, `npm run gn_check`)
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [ ] Added appropriate QA labels (`QA/Yes` or `QA/No`) to the associated issue
- [ ] Added appropriate release note labels (`release-notes/include` or `release-notes/exclude`) to the associated issue
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
Defined in respective issues

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Review by AlanBreck — APPROVED** [review]

**Review by emerick — APPROVED** [review]
LGTM

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:


**`Case #1`** - https://github.com/brave/brave-browser/issues/12277

* Verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/12277#issue-727475691 and ensured there was only a single `<` (back button).

**`BAT`** | **`BTC`** | **`ETH`**
-----------|-----------|-----------
Screen Shot 2020-10-25 at 11 59 44 AM | Screen Shot 2020-10-25 at 11 59 59 AM | Screen Shot 2020-10-25 at 12 00 10 PM

**Comment by kjozwiak** [comment]
@rebron mind checking https://github.com/brave/brave-browser/issues/12304? You have the most context but I'm basically seeing the following link on every button:

```
https://auth.crypto.com/users/sign_up?utm_campaign=Brave%3AWW-en%3ATrading-Widget_MVP_InitialWidgetState_BuyButton_Top&utm_content=MVP_InitialWidgetState_BuyButton_Top&utm_medium=Trading+Widget&utm_source=Brave
```

Mine are also appearing as `https://auth.crypto.com/users/sign_up` but all your examples are showing `https://auth.crypto.com/exchange/signup`.

**Comment by rebron** [comment]
Pass on macOS 1.18.10 for all four links. Note to QA that need to clear cookies/data before clicking each link otherwise will see the same one. 

Brave | 1.18.10 Chromium: 86.0.4240.111 (Official Build) nightly (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.16 (Build 20A5395g)
JavaScript | V8 8.6.395.17
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

`https://auth.crypto.com/users/sign_up?utm_campaign=Brave%3AWW-en%3ATrading-Widget_MVP_InitialWidgetState_BuyButton_Top&utm_content=MVP_InitialWidgetState_BuyButton_Top&utm_medium=Trading+Widget&utm_source=Brave`

`https://auth.crypto.com/users/sign_up?utm_campaign=Brave%3AWW-en%3ATrading-Widget_MVP_InitialWidgetState_BuyButton_Bottom&utm_content=MVP_InitialWidgetState_BuyButton_Bottom&utm_medium=Trading+Widget&utm_source=Brave`

`https://auth.crypto.com/users/sign_up?utm_campaign=Brave%3AWW-en%3ATrading-Widget_MVP_CryptoDetails_BuyButton_Top&utm_content=MVP_CryptoDetails_BuyButton_Top&utm_medium=Trading+Widget&utm_source=Brave`

`https://auth.crypto.com/users/sign_up?utm_campaign=Brave%3AWW-en%3ATrading-Widget_MVP_CryptoDetails_BTC%2FUSDT&utm_content=MVP_CryptoDetails_BTC%2FUSDT&utm_medium=Trading-Widget&utm_source=Brave`

**Pull request merged**
