### PR TITLE
Use proper product logo images

### PR DESCRIPTION
**Pull request by simonhong**
* Use different logo for different release channels in about page
* Use proper sized image (product_logo_128_XXX.png should be 128x128)

Close https://github.com/brave/brave-browser/issues/504

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions

### CODE REVIEW

**Comment by darkdh** [comment]
where do we use product 128 logos?

**Comment by simonhong** [comment]
@darkdh it's used for window icon on linux.

**Comment by darkdh** [comment]
I mean where is the BUILD.gn that we access it?

**Comment by simonhong** [comment]
It is used by `brave_views_delegate_linux.cc`. and it is included in `deps` of `brave/browser/ui/BUILD.gn` - `brave_unscaled_resources`.

**Pull request merged**
