### PR TITLE
Adds QR code modal to rewards

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves https://github.com/brave/brave-browser/issues/12176

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`, `npm run gn_check`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [x] Added appropriate QA labels (`QA/Yes` or `QA/No`) to the associated issue
- [x] Added appropriate release note labels (`release-notes/include` or `release-notes/exclude`) to the associated issue
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
- enable rewards
- go to rewards page
- make sure that you see QR box
- open dialog and scan QR code with a phone
- make sure that you see your payment id

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Review by emerick — APPROVED** [review]
LGTM

**Comment by zenparsing** [comment]
Code looks good, but if possible we should generate the QR code on the C++ side (which we already do for [sync](https://github.com/brave/brave-core/blob/f1d11e27cdbb53bf78f8dc2780bc0fe7d38c361c/browser/ui/webui/settings/brave_sync_handler.cc#L117)). If we do that, it seems like we might be able to replace the "getPaymentId" webUI handler with just "getPaymentQR" or something like that.

**Review by ryanml — APPROVED** [review]
lgtm, as discussed in slack a QR API will be created in a separate PR, and this work will be refactored slightly to use it. this is okay to merge if all other feedback is addressed

**Review by zenparsing — APPROVED** [review]

**Comment by kjozwiak** [comment]
Ran into https://github.com/brave/brave-browser/issues/12232 when running through the above verification. Looks like the QR code doesn't get updated when restoring wallets. It basically uses the first `paymentId` that was generated even if you restore several wallets.

Should we get that fixed before we uplift into `1.16.x`? Seems like a potentially bad bug.

Went through the following verifications:

* launched brave using the following flags/switches:

```
--args --enable-logging=stderr --vmodule="*/bat-native-ads/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6 --rewards=staging=true --brave-ads-staging
```

* enabled rewards and noted the `paymentId` via the terminal/CLI as per the following:

```
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/brave
> Result: Success
> HTTP Code: 201
> Body: {"paymentId":"1b0951ef-9c75-440a-87a3-d2b5b70b563e","walletProvider":{"id":"","name":"brave"},"altcurrency":"BAT","publicKey":"9331............"}
```

* Clicked on `QR code` and ensured that it matches the above `paymentId`

**`Rewards Page`** | **`QR Scan Result`**
---------------------|----------------------
Screen Shot 2020-10-20 at 7 07 49 PM | 6FA24A5A-8A0F-42D0-95F7-DA33A66115BC

Once you restore another wallet, you'll notice that `1b0951ef-9c75-440a-87a3-d2b5b70b563e` is being used despite:
* refreshing the `brave://rewards`
* closing/re-opening the `brave://rewards` page
* restarting the browser

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.7 x64` using the following build:

```
Brave | 1.18.3 Chromium: 86.0.4240.111 (Official Build) nightly (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.15.7 (Build 19H2)
```

* Verified that the QR code is being updated when restoring wallets via https://github.com/brave/brave-core/pull/6910#issuecomment-714199161
* ensured that clicking on `QR Code` opens the modal with the QR code
* ensured that clicking on `X` closes the modal without issues
* ensured that the QR `paymentId` matches the `paymendId` being listed under `brave://rewards`

**Pull request merged**
