### PR TITLE
Adding Bitcoin.com widget to NTP [1.16]

### PR DESCRIPTION
**Pull request by ryanml**
Uplift of: https://github.com/brave/brave-core/pull/6681, https://github.com/brave/brave-core/pull/6747, https://github.com/brave/brave-core/pull/6756, https://github.com/brave/brave-core/pull/6754
Issue: https://github.com/brave/brave-browser/issues/11982

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
Restarting `Win x64` via https://ci.brave.com/job/pr-brave-browser-bitcoin.com-1.16-windows/3/ due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-bitcoin.com-1.16-windows/2/execution/node/187/log/.

```
02:03:04  FAILED: obj/brave/browser/extensions/extensions/brave_prefs_util.obj 
```

Restarting `Linux` via https://ci.brave.com/job/pr-brave-browser-bitcoin.com-1.16-linux/3/ due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-bitcoin.com-1.16-linux/2/execution/node/205/log/.

```
01:54:59  FAILED: obj/brave/browser/extensions/extensions/brave_prefs_util.o 
```

Restarting `macOS` via https://ci.brave.com/job/pr-brave-browser-bitcoin.com-1.16-macos/3/ using `WIPE_WORKSPACE` due to `init` failing as per https://ci.brave.com/job/pr-brave-browser-bitcoin.com-1.16-macos/2/execution/node/104/log/.

```
01:40:05  Error: Command 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --directory --recursive --no_auth --num_threads=16 --bucket chromium-apache-mac src/third_party/apache-mac' returned non-zero exit status 1 in /Users/jenkins/jenkins/workspace/pr-brave-browser-bitcoin.com-1.16-macos
```

**Comment by kjozwiak** [comment]
@ryanml looks like `Linux` failed again after the rebase with the same error mentioned via https://github.com/brave/brave-core/pull/6745#issuecomment-702867167 as per https://ci.brave.com/job/pr-brave-browser-bitcoin.com-1.16-linux/4/execution/node/205/log/. Example:

```
14:20:26  FAILED: obj/brave/browser/extensions/extensions/brave_prefs_util.o 
```

**Comment by ryanml** [comment]
All platforms pass, restarting MacOS due to unrelated failure

**Comment by kjozwiak** [comment]
> All platforms pass, restarting MacOS due to unrelated failure

Looks like `macOS` passed 👍 Other platforms passed as well as per the above. Adding links to the other passed platforms to make it easier for @brave/uplift-approvers.

* `Win x64` - https://ci.brave.com/job/brave-core-build-pr-windows/job/PR-6745/5/
* `Linux` - https://ci.brave.com/job/brave-core-build-pr-linux/job/PR-6745/5/
* `iOS` - https://ci.brave.com/job/brave-core-build-pr-ios/job/PR-6745/4/
* `Android` - https://ci.brave.com/job/brave-core-build-pr-android/job/PR-6745/4/

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.16.x` approved after deliberating with @brave/uplift-approvers. QA has also verified the PR on Nightly as per https://github.com/brave/brave-core/pull/6681#issuecomment-702733984, https://github.com/brave/brave-core/pull/6756#issuecomment-703378187 & https://github.com/brave/brave-core/pull/6754#issuecomment-703378336.

**Pull request merged**
