### PR TITLE
Fixed sentence casing on Always Show Full URLs in brave://settings/appearance

### PR DESCRIPTION
**Pull request by deepxcode**
Fixes issue [#16939](https://github.com/brave/brave-browser/issues/16939)
Changed  "Always Show Full URLs" to "Always show full URLs"

Resolves [#16939](https://github.com/brave/brave-browser/issues/16939)

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by deepxcode** [comment]
@petemill  and @stephendonner  Can you review this PR?

**Review by swarup4741 — COMMENTED** [review]
@deepxcode here we have a `expr="not use_titlecase"` for which we have the desired text casing and for `expr="use_titlecase"`... i think we must have capitalized format.. otherwise both are becoming the same essentially.... 

correct me if i'm wrong ....

**Comment by deepxcode** [comment]
> @deepxcode here we have a `expr="not use_titlecase"` for which we have the desired text casing and for `expr="use_titlecase"`... i think we must have capitalized format.. otherwise both are becoming the same essentially....
> 
> https://github.com/brave/brave-core/blob/2d6b3a2afabf25c28866f4b7590a0afb4a993e67/app/generated_resources.grd#L5226-L5235
> 
> correct me if i'm wrong ....

Yes, @swarup4741, You were right, made the requested changes

**Comment by swarup4741** [comment]
> > @deepxcode here we have a `expr="not use_titlecase"` for which we have the desired text casing and for `expr="use_titlecase"`... i think we must have capitalized format.. otherwise both are becoming the same essentially....
> > https://github.com/brave/brave-core/blob/2d6b3a2afabf25c28866f4b7590a0afb4a993e67/app/generated_resources.grd#L5226-L5235
> > 
> > correct me if i'm wrong ....
> 
> Yes, @swarup4741, You were right, made the requested changes

Then i think we don't require lines `5231` to `5235`

**Review by swarup4741 — CHANGES_REQUESTED** [review]
since we have `expr="not use_titlecase"` then i think in `desc` we don't need "In Title Case"

**Review by swarup4741 — COMMENTED** [review]
It looks good 💪🏼 ... Now just squash all the commits into one

**Review by swarup4741 — APPROVED** [review]
Looks fine with the changes

**Review by bsclifton — APPROVED** [review]
LGTM! 👍

**Comment by bsclifton** [comment]
@deepxcode can you please give this a rebase? Sorry that it took a while to review

**Comment by deepxcode** [comment]
@bsclifton I won't be able to give a rebase to it,  ran out of storage space while installing brave's  repo😅

**Comment by bsclifton** [comment]
@deepxcode ok no worries; I got you

**Pull request merged**
