### PR TITLE
Remove extra escaping from Ecosia search term (Uplift to 1.19.x)

### PR DESCRIPTION
**Pull request by bsclifton**
Uplift of https://github.com/brave/brave-core/pull/7600
Resolves https://github.com/brave/brave-browser/issues/13568

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
Restarting `macOS` as `build` failed as per https://ci.brave.com/job/pr-brave-browser-bsc-ecosia-fix-1.19.x-macos/1/execution/node/155/log/.

```
13:34:34  FAILED: gen/chrome/browser/resources/settings/settings.rollup.js gen/chrome/browser/resources/settings/lazy_load.rollup.js gen/chrome/browser/resources/settings/shared.rollup.js gen/chrome/browser/resources/settings/build_manifest.json 
```

**Comment by kjozwiak** [comment]
`test-browser` failed on `Win x64` due to several reward failures/timeouts as per https://ci.brave.com/job/pr-brave-browser-bsc-ecosia-fix-1.19.x-windows/1/execution/node/215/log/. However, these are known intermittent issues and will be addressed in `1.19.x` via https://github.com/brave/brave-core/pull/7607.

```
15:32:08  6 tests failed:
15:32:08      RewardsBrowserTest.BackupRestoreModalHasNotice (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:304)
15:32:08      RewardsBrowserTest.ResetRewardsWithBAT (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:375)
15:32:08      RewardsBrowserTest.UpholdLimitNoBAT (../../brave/components/brave_rewards/browser/test/rewards_browsertest.cc:398)
15:32:08      RewardsContributionBrowserTest.TipConnectedPublisherVerified (../../brave/components/brave_rewards/browser/test/rewards_contribution_browsertest.cc:586)
15:32:08      RewardsContributionBrowserTest.TipUnverifiedPublisher (../../brave/components/brave_rewards/browser/test/rewards_contribution_browsertest.cc:304)
15:32:08      RewardsPromotionBrowserTest.ClaimViaSettingsPage (../../brave/components/brave_rewards/browser/test/rewards_promotion_browsertest.cc:196)
15:32:08  1 test timed out:
15:32:08      RewardsPromotionBrowserTest.PromotionRemovedFromEndpoint (../../brave/components/brave_rewards/browser/test/rewards_promotion_browsertest.cc:231)
```

Restarting `macOS` due to `build` failing as per https://ci.brave.com/job/pr-brave-browser-bsc-ecosia-fix-1.19.x-macos/2/execution/node/155/log/.

```
15:39:20  FAILED: gen/chrome/browser/resources/settings/settings.rollup.js gen/chrome/browser/resources/settings/lazy_load.rollup.js gen/chrome/browser/resources/settings/shared.rollup.js gen/chrome/browser/resources/settings/build_manifest.json 
```

**Comment by kjozwiak** [comment]
@bsclifton looks like it failed again on `macOS` due to the following:

```
17:12:26  FAILED: gen/chrome/browser/resources/settings/settings.rollup.js gen/chrome/browser/resources/settings/lazy_load.rollup.js gen/chrome/browser/resources/settings/shared.rollup.js gen/chrome/browser/resources/settings/build_manifest.json 
```

I'll restart it one more time but seems like there's an issue with the PR on `macOS`. I'll restarted using `WIPE_WORKSPACE` this time around.

**Comment by bsclifton** [comment]
macOS will continue to fail until https://github.com/brave/brave-core/pull/7599 is merged + uplifted; we should be good to go otherwise

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.19.x` approved after deliberating with @brave/uplift-approvers. QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/7600#issuecomment-760613900 & https://github.com/brave/brave-core/pull/7600#issuecomment-760617760.

**Pull request merged**
