### PR TITLE
Publishers can now be included and excluded

### PR DESCRIPTION
**Pull request by jasonrsadler**
Resolves https://github.com/brave/brave-browser/issues/1283

Ledger native https://github.com/brave-intl/bat-native-ledger/pull/144

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:

1. Start Brave
2. Add publishers to rewards auto-contribution
3. Visit an added publisher and open Rewards panel
4. Click 'Include in auto-contribute'
5. Check publisher_info_db and ensure that excluded was changed to 1
6. Click 'Include in auto-contribute' in panel for same site
7. Check publisher_info_db and ensure that excluded was changed to 2

~Toggle switch currently does not slide and will be handled in future PR.
(Based on native and script type mismatches)~

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by bbondy** [comment]
needs a rebase

**Comment by jasonrsadler** [comment]
Rebased.

**Comment by jasonrsadler** [comment]
https://github.com/brave-intl/bat-native-ledger/pull/144 goes with it.

**Comment by NejcZdovc** [comment]
master 831c60d
0.57.x 871cc0a7
0.56.x 7a5ac9a8
0.55.x 9bea9926

**Pull request merged**
