### PR TITLE
Update patches from Chromium 76.0.3809.132 to Chromium 77.0.3865.75 (uplift to 0.68.x)

### PR DESCRIPTION
**Pull request by bsclifton**
Uplift of https://github.com/brave/brave-core/pull/3358 and https://github.com/brave/brave-core/pull/3400
Fixes https://github.com/brave/brave-browser/issues/5375
Fixes https://github.com/brave/brave-browser/issues/5966
Related https://github.com/brave/brave-browser/pull/5943

Approved, please ensure that before merging: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

--------
This includes the following uplifts:
- [Brave syncer (uplift to 0.69.x)](https://github.com/brave/brave-core/pull/3230)
- [Network Service 0.69.x](https://github.com/brave/brave-core/pull/3291)
- [Update patches from Chromium 76.0.3809.132 to Chromium 77.0.3865.65 (0.69.x)](https://github.com/brave/brave-core/pull/3383)
- [Issue 2351: NetworkService: Untie shield callbacks from net::URLRequest.](https://github.com/brave/brave-core/pull/2764)
- [Untie more network callbacks from net::URLRequest](https://github.com/brave/brave-core/pull/2908)
- [Uplift omaha update(prepare 10.0.18362.0 SDK update) to 0.69](https://github.com/brave/brave-core/pull/3363)
- [Sync: never show service error status in browser UI](https://github.com/brave/brave-core/pull/3357)
- [Update logic for GetPatternFromURL to take port into account](https://github.com/brave/brave-core/pull/3405)
- [Generate symbols using single thread](https://github.com/brave/brave-core/pull/3356)

And then the following PRs created against this branch:
- [Reader Mode: remove UI button (0.68.x)](https://github.com/brave/brave-core/pull/3396)
- [C77 0.68.x ntp api](https://github.com/brave/brave-core/pull/3395) (a 0.68.x specific uplift of https://github.com/brave/brave-core/pull/2957)
- [Fixes blank panel (uplift to 0.68.x)](https://github.com/brave/brave-core/pull/3412)

### CODE REVIEW

**Comment by crazy-max** [comment]
Looks like upgrading to Chromium 77.0.3865.75 breaks #795 :eyes: (see portapps/brave-portable#33)
Maybe a patch has not been updated? Any clue @bsclifton? Thanks!

**Comment by bsclifton** [comment]
cc: @mkarolin

**Comment by mkarolin** [comment]
The patches and chromium_src overrides from #795 are in place and at least --disable-machine-id gets the override triggered. Haven't checked the encryption flag, but the patch/override are still in place.

**Comment by crazy-max** [comment]
@mkarolin Just check and `--disable-machine-id` works yes but `--disable-encryption-win` don't.

**Comment by crazy-max** [comment]
@mkarolin @bsclifton Do you have any clue to fix this? I would like to help but there are many changes in this PR.

**Comment by webgoto** [comment]
I have a problem that --disable-encryption-win doesn't work because I'm using a Brave portable.

**Comment by crazy-max** [comment]
@mkarolin @bsclifton I've createda PR #4194 to fix this issue if you want to take a look. Thanks!

**Pull request merged**
