### PR TITLE
WIP: remove pdf.js

### PR DESCRIPTION
**Pull request by bsclifton**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests && npm run test-security`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by bsclifton** [comment]
Still working through this one... Here's where I'm at:
- PDF.js is removed (see changes for this PR)
- `Chromium PDF Viewer` was removed from blacklist and added to whitelist (including the vendor/whitelist component)
- `Chromium PDF Viewer` shows up in brave://extensions and IPC events like `OnLoaded` are dispatched for it (`mhjfbmdgcfjbbpaeojofohoefgiehjai`) on startup
- Using File => Open and choosing a simple PDF completely hangs. 
- If you open the debug tools and use network inspector (under `timing`, trying to open a PDF shows this:
    (note: it never finishes; `Content Download` never happens)
    image
- If you open a PDF document in Chromium for example, it works and you'll see this in network inspector:
    Screen Shot 2019-04-08 at 4 49 45 PM
- Per @iefremov 's request, I tried loading PDF while recording results using brave://net-export/
    - This seems to get blocked:
    ```
    file:///Users/clifton/Desktop/pdf.pdf
    Start Time: 2019-04-02 23:23:11.133
    
    t=10433 [st= 0] +REQUEST_ALIVE  [dt=52]
                     --> priority = "HIGHEST"
                     --> url = "file:///Users/clifton/Desktop/pdf.pdf"
    t=10433 [st= 0]    NETWORK_DELEGATE_BEFORE_URL_REQUEST  [dt=1]
    t=10434 [st= 1]    URL_REQUEST_START_JOB  [dt=0]
                       --> load_flags = 9216 (MAIN_FRAME_DEPRECATED | MAYBE_USER_GESTURE)
                       --> method = "GET"
                       --> privacy_mode = 0
                       --> url = "file:///Users/clifton/Desktop/pdf.pdf"
   t=10435 [st= 2]   +URL_REQUEST_DELEGATE_RESPONSE_STARTED  [dt=45]
   t=10435 [st= 2]      DELEGATE_INFO  [dt=0]
                        --> delegate_blocked_by = "MimeSniffingResourceHandler"
   t=10436 [st= 3]      DELEGATE_INFO  [dt=43]
                        --> delegate_blocked_by = "MojoAsyncResourceHandler"
   ```
    - [Code related to this can be found here](https://cs.chromium.org/chromium/src/content/browser/loader/mime_sniffing_resource_handler.cc?q=mime_sniff&sq=package:chromium&g=0&l=523)

**Comment by simonhong** [comment]
Still debugging with this PR.
When clicks the pdf link, navigation is finished and then enters loading phase.
But it doesn't make any loading progress.
Need to find the reason why it can't make progress after entering loading phase.

**Comment by simonhong** [comment]
Below is `chrome://net-export` logs from brave and pure chromium when clicking pdf document link.
In brave log, stream request header has below header value that chromium header doesn't have. The value of `Range` in header seems invalid.
```
Range: bytes=1318020-1318020
If-Range: "5349f-2b4c0d-3c8cb72e"
```
Also, there is no `-REQUEST_ALIVE` in brave log. It is logged in dtor of `URLRequest` object. Isn't it destroyed properly? If so, something blocks it?


* Brave log
```
t=2346 [st=   1]   +URL_REQUEST_START_JOB  [dt=594]
                    --> load_flags = 9216 (MAIN_FRAME_DEPRECATED | MAYBE_USER_GESTURE)
                    --> method = "GET"
                    --> privacy_mode = 0
                    --> url = "http://devernay.free.fr/cours/IHM/GTK/GGAD.pdf"
t=2346 [st=   1]      NETWORK_DELEGATE_BEFORE_START_TRANSACTION  [dt=0]
t=2347 [st=   2]      HTTP_CACHE_GET_BACKEND  [dt=0]
t=2347 [st=   2]      HTTP_CACHE_OPEN_ENTRY  [dt=4]
t=2351 [st=   6]      HTTP_CACHE_ADD_TO_ENTRY  [dt=2]
t=2353 [st=   8]      HTTP_CACHE_READ_INFO  [dt=2]
t=2355 [st=  10]     +HTTP_STREAM_REQUEST  [dt=289]
t=2355 [st=  10]        HTTP_STREAM_JOB_CONTROLLER_BOUND
                        --> source_dependency = 561 (HTTP_STREAM_JOB_CONTROLLER)
t=2644 [st= 299]        HTTP_STREAM_REQUEST_BOUND_TO_JOB
                        --> source_dependency = 562 (HTTP_STREAM_JOB)
t=2644 [st= 299]     -HTTP_STREAM_REQUEST
t=2644 [st= 299]     +HTTP_TRANSACTION_SEND_REQUEST  [dt=1]
t=2644 [st= 299]        HTTP_TRANSACTION_SEND_REQUEST_HEADERS
                        --> GET /cours/IHM/GTK/GGAD.pdf HTTP/1.1
                            Host: devernay.free.fr
                            Connection: keep-alive
                            Upgrade-Insecure-Requests: 1
                            User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.61 Safari/537.36
                            Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
                            Referer: https://www.google.com/
                            Accept-Encoding: gzip, deflate
                            Accept-Language: en-US,en;q=0.9,ko;q=0.8
                            Range: bytes=1318020-1318020
                            If-Range: "5349f-2b4c0d-3c8cb72e"
t=2645 [st= 300]     -HTTP_TRANSACTION_SEND_REQUEST
t=2645 [st= 300]     +HTTP_TRANSACTION_READ_HEADERS  [dt=293]
t=2645 [st= 300]        HTTP_STREAM_PARSER_READ_HEADERS  [dt=293]
t=2938 [st= 593]        HTTP_TRANSACTION_READ_RESPONSE_HEADERS
                        --> HTTP/1.1 206 Partial Content
                            Date: Mon, 22 Apr 2019 02:39:14 GMT
                            Server: Apache/ProXad [Jul 22 2015 14:50:04]
                            Last-Modified: Mon, 11 Mar 2002 13:54:54 GMT
                            ETag: "5349f-2b4c0d-3c8cb72e"
                            Connection: close
                            Accept-Ranges: bytes
                            Content-Length: 1
                            Content-Range: bytes 1318020-1318020/2837517
                            Content-Type: application/pdf
t=2938 [st= 593]     -HTTP_TRANSACTION_READ_HEADERS
t=2938 [st= 593]      HTTP_CACHE_WRITE_INFO  [dt=1]
t=2939 [st= 594]      NETWORK_DELEGATE_HEADERS_RECEIVED  [dt=0]
t=2940 [st= 595]   -URL_REQUEST_START_JOB
t=2940 [st= 595]   +URL_REQUEST_DELEGATE_RESPONSE_STARTED  [dt=6]
```

* Chromium log
```
t=  54 [st=   0] +REQUEST_ALIVE  [dt=3870]
                  --> priority = "HIGHEST"
                  --> url = "http://devernay.free.fr/cours/IHM/GTK/GGAD.pdf"
t=  55 [st=   1]    NETWORK_DELEGATE_BEFORE_URL_REQUEST  [dt=0]
t=  56 [st=   2]   +URL_REQUEST_START_JOB  [dt=647]
                    --> load_flags = 9216 (MAIN_FRAME_DEPRECATED | MAYBE_USER_GESTURE)
                    --> method = "GET"
                    --> privacy_mode = 0
                    --> url = "http://devernay.free.fr/cours/IHM/GTK/GGAD.pdf"
t=  56 [st=   2]      NETWORK_DELEGATE_BEFORE_START_TRANSACTION  [dt=0]
t=  56 [st=   2]      HTTP_CACHE_GET_BACKEND  [dt=0]
t=  56 [st=   2]      HTTP_CACHE_OPEN_OR_CREATE_ENTRY  [dt=3]
t=  59 [st=   5]      HTTP_CACHE_ADD_TO_ENTRY  [dt=4]
t=  63 [st=   9]     +HTTP_STREAM_REQUEST  [dt=289]
t=  63 [st=   9]        HTTP_STREAM_JOB_CONTROLLER_BOUND
                        --> source_dependency = 576 (HTTP_STREAM_JOB_CONTROLLER)
t= 352 [st= 298]        HTTP_STREAM_REQUEST_BOUND_TO_JOB
                        --> source_dependency = 577 (HTTP_STREAM_JOB)
t= 352 [st= 298]     -HTTP_STREAM_REQUEST
t= 352 [st= 298]     +HTTP_TRANSACTION_SEND_REQUEST  [dt=1]
t= 353 [st= 299]        HTTP_TRANSACTION_SEND_REQUEST_HEADERS
                        --> GET /cours/IHM/GTK/GGAD.pdf HTTP/1.1
                            Host: devernay.free.fr
                            Connection: keep-alive
                            Upgrade-Insecure-Requests: 1
                            User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3769.0 Safari/537.36
                            Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
                            Referer: https://www.google.com/
                            Accept-Encoding: gzip, deflate
                            Accept-Language: en-US,en;q=0.9
t= 353 [st= 299]     -HTTP_TRANSACTION_SEND_REQUEST
t= 353 [st= 299]     +HTTP_TRANSACTION_READ_HEADERS  [dt=349]
t= 353 [st= 299]        HTTP_STREAM_PARSER_READ_HEADERS  [dt=349]
t= 702 [st= 648]        HTTP_TRANSACTION_READ_RESPONSE_HEADERS
                        --> HTTP/1.1 200 OK
                            Date: Tue, 23 Apr 2019 03:37:22 GMT
                            Server: Apache/ProXad [Jul 22 2015 14:50:04]
                            Last-Modified: Mon, 11 Mar 2002 13:54:54 GMT
                            ETag: "5349f-2b4c0d-3c8cb72e"
                            Connection: close
                            Accept-Ranges: bytes
                            Content-Length: 2837517
                            Content-Type: application/pdf
t= 702 [st= 648]     -HTTP_TRANSACTION_READ_HEADERS
t= 702 [st= 648]      HTTP_CACHE_WRITE_INFO  [dt=0]
t= 702 [st= 648]      HTTP_CACHE_WRITE_DATA  [dt=1]
t= 703 [st= 649]      HTTP_CACHE_WRITE_INFO  [dt=0]
t= 703 [st= 649]      NETWORK_DELEGATE_HEADERS_RECEIVED  [dt=0]
t= 703 [st= 649]   -URL_REQUEST_START_JOB
```

**Comment by simonhong** [comment]
After clearing disk cache, I confirmed that same request header is set. (same as chromium) and header response seems valid. Invalid request header is set when that is not the first request since clearing disk cache. I think un-finished `URLRequest` (that is lack of `-REQUEST_ALIVE` in the log) causes this invalid request header. Need to find why `URLRequest` is not destroyed.
```
t= 1848 [st=    0] +REQUEST_ALIVE  [dt=15624+]
                    --> priority = "HIGHEST"
                    --> url = "http://devernay.free.fr/cours/IHM/GTK/GGAD.pdf"
t= 1849 [st=    1]    NETWORK_DELEGATE_BEFORE_URL_REQUEST  [dt=1]
t= 1851 [st=    3]   +URL_REQUEST_START_JOB  [dt=615]
                      --> load_flags = 9216 (MAIN_FRAME_DEPRECATED | MAYBE_USER_GESTURE)
                      --> method = "GET"
                      --> privacy_mode = 0
                      --> url = "http://devernay.free.fr/cours/IHM/GTK/GGAD.pdf"
t= 1851 [st=    3]      NETWORK_DELEGATE_BEFORE_START_TRANSACTION  [dt=0]
t= 1851 [st=    3]      HTTP_CACHE_GET_BACKEND  [dt=0]
t= 1851 [st=    3]      HTTP_CACHE_OPEN_ENTRY  [dt=3]
                        --> net_error = -2 (ERR_FAILED)
t= 1854 [st=    6]      HTTP_CACHE_CREATE_ENTRY  [dt=2]
t= 1856 [st=    8]      HTTP_CACHE_ADD_TO_ENTRY  [dt=1]
t= 1857 [st=    9]     +HTTP_STREAM_REQUEST  [dt=296]
t= 1858 [st=   10]        HTTP_STREAM_JOB_CONTROLLER_BOUND
                          --> source_dependency = 524 (HTTP_STREAM_JOB_CONTROLLER)
t= 2153 [st=  305]        HTTP_STREAM_REQUEST_BOUND_TO_JOB
                          --> source_dependency = 525 (HTTP_STREAM_JOB)
t= 2153 [st=  305]     -HTTP_STREAM_REQUEST
t= 2153 [st=  305]     +HTTP_TRANSACTION_SEND_REQUEST  [dt=2]
t= 2153 [st=  305]        HTTP_TRANSACTION_SEND_REQUEST_HEADERS
                          --> GET /cours/IHM/GTK/GGAD.pdf HTTP/1.1
                              Host: devernay.free.fr
                              Connection: keep-alive
                              Upgrade-Insecure-Requests: 1
                              User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.61 Safari/537.36
                              Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
                              Referer: http://devernay.free.fr/
                              Accept-Encoding: gzip, deflate
                              Accept-Language: en-US,en;q=0.9
t= 2155 [st=  307]     -HTTP_TRANSACTION_SEND_REQUEST
t= 2155 [st=  307]     +HTTP_TRANSACTION_READ_HEADERS  [dt=309]
t= 2155 [st=  307]        HTTP_STREAM_PARSER_READ_HEADERS  [dt=309]
t= 2464 [st=  616]        HTTP_TRANSACTION_READ_RESPONSE_HEADERS
                          --> HTTP/1.1 200 OK
                              Date: Tue, 23 Apr 2019 06:41:29 GMT
                              Server: Apache/ProXad [Jul 22 2015 14:50:04]
                              Last-Modified: Mon, 11 Mar 2002 13:54:54 GMT
                              ETag: "5349f-2b4c0d-3c8cb72e"
                              Connection: close
                              Accept-Ranges: bytes
                              Content-Length: 2837517
                              Content-Type: application/pdf
t= 2464 [st=  616]     -HTTP_TRANSACTION_READ_HEADERS
t= 2464 [st=  616]      HTTP_CACHE_WRITE_INFO  [dt=0]
t= 2464 [st=  616]      HTTP_CACHE_WRITE_DATA  [dt=0]
t= 2464 [st=  616]      HTTP_CACHE_WRITE_INFO  [dt=2]
t= 2466 [st=  618]      NETWORK_DELEGATE_HEADERS_RECEIVED  [dt=0]
t= 2466 [st=  618]   -URL_REQUEST_START_JOB
t= 2466 [st=  618]   +URL_REQUEST_DELEGATE_RESPONSE_STARTED  [dt=5]
```

**Comment by simonhong** [comment]
Found the cause.
So far, we've used different set of available plugin list at the same time.
For example, when `MimeSniffingResourceHandler` checks whether available plugin is exists for response, `PluginService::GetPluginInfo` is used. and available plugin list is filtered by `ChromePluginServiceFilter::IsPluginAvailable()`.
However, when we get plugin list by `BravePluginRegistryImpl::GetPlugins()`, only flash plugin can be available because we use customized filter(`BravePluginRegistryImpl::GetPluginsComplete()`) instead of `ChromePluginServiceFilter::IsPluginAvailable()`. Because of this, we can get different set of available plugin list at the same time.

**Comment by simonhong** [comment]
https://github.com/brave/brave-core/pull/2342 will handle instead of this for deleting pdf.js

**Pull request closed without merging**
