### PR TITLE
package-lock.json v2 via npm 8 and use --no-save option in npm i

### PR DESCRIPTION
**Pull request by petemill**
Resolves https://github.com/brave/brave-browser/issues/20550

~Whilst doing this I tried removing our forced resolutions and `npm run audit_deps` didn't complain. Was confusing since that still seemed to result in immer 8.x contained in the package-lock.json. I've left our forced resolutions in for now. It would be nice to remove npm-force-resolutions, but we can wait until we figure out why we don't need it anymore and also wait for node LTS to contain npm 8.3 which has it's own support for forced transient dependency versions via "overrides" property in package.json~

I've ended up removing npm-force-resolutions because it was causing issues. Instead, I upgraded Storybook to remove the bad version of immer. I also had to regenerate the package-lock.json because of some bad dependency chains that resulted in some (storybook) webpack builds not working. This shouldn't be an issue since we pin many dependencies in package.json itself, and this PR will see if we have further audit issues (locally I have no new ones). At least the package-lock format v2 is more reproducible in that it apparenlty more fully describes the sturcture of node_modules.

- Removed npm-force-resolutions due to issues with transient dependency versions with storybook's builder-webpack4 not getting the correct version of terser-webpack-plugin
- Updated storybook minor version to remove the audit issue that npm-force-resolutions was fixing.

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by mihaiplesa — APPROVED** [review]

**Comment by petemill** [comment]
error during iOS build
```

[2022-01-19T00:00:12.436Z] npm WARN tarball tarball data for brave-ui@git+ssh://git@github.com/brave/brave-ui.git#5b2069a51eea6ec4577b433bb9e48b5ab2aabbe9 (sha512-aneDBbG9L9iF7kzF+VD2Oc+3FUdWzc3AWQF7s4EuvFgEdP5psiRWQ5Lia2XFseYJ87FjYf41roAuayizJX6Z5g==) seems to be corrupted. Trying again.

[2022-01-19T00:00:12.436Z] npm WARN tarball tarball data for brave-ui@git+ssh://git@github.com/brave/brave-ui.git#5b2069a51eea6ec4577b433bb9e48b5ab2aabbe9 (sha512-aneDBbG9L9iF7kzF+VD2Oc+3FUdWzc3AWQF7s4EuvFgEdP5psiRWQ5Lia2XFseYJ87FjYf41roAuayizJX6Z5g==) seems to be corrupted. Trying again.

[2022-01-19T00:00:12.436Z] npm ERR! code EINTEGRITY
```

**Comment by petemill** [comment]
CI is suffering from this issue wrt brave-ui github-installed dep https://github.com/npm/cli/issues/2846

Going to try to remove the integrity field for that package

**Comment by petemill** [comment]
Now the issue is that storybook's JS bundle is failing. I think that when the package-lock.json was upgraded then a package got automatically updated to a later version but another one didn't and the versions are incompatible with each other. Checking...

**Comment by petemill** [comment]
Pushed a (hopeful) fix and updated the PR description to describe what was done:

> I've ended up removing npm-force-resolutions because it was causing issues. Instead, I upgraded Storybook to remove the bad version of immer. I also had to regenerate the package-lock.json because of some bad dependency chains that resulted in some (storybook) webpack builds not working. This shouldn't be an issue since we pin many dependencies in package.json itself, and this PR will see if we have further audit issues (locally I have no new ones). At least the package-lock format v2 is more reproducible in that it apparenlty more fully describes the sturcture of node_modules.
> 
> - Removed npm-force-resolutions due to issues with transient dependency versions with storybook's builder-webpack4 not getting the correct version of terser-webpack-plugin
> - Updated storybook minor version to remove the audit issue that npm-force-resolutions was fixing.

**Comment by petemill** [comment]
noplatform failure is simply an unrelated warning generated by pylint

**Comment by petemill** [comment]
IT's hard to keep up with this PR since the nightly build process keeps modifying the version in the package-lock.json and then I have to rebase and push and wait for CI. 

Therefore I'm marking to skip CI since it's all passed and I just need to push an updated version number.

**Pull request merged**
