### PR TITLE
Add Privacy Pass extension

### PR DESCRIPTION
**Pull request by durch**
This PR addresses https://github.com/brave/brave-browser/issues/1677 by adding Privacy Pass extension. Extension is added as a regular extension installed from the [Chrome store](https://chrome.google.com/webstore/detail/privacy-pass/ajhmfdgkijocedmfjonnpjfojldioehi), in a fashion identical to the IPFS Companion extension.

After https://github.com/brave/brave-browser/issues/2307 has been implemented this will allow users to have a hassle free experience in all contexts. For now it works in normal and incognito modes, but not in Tor mode.

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests && npm run test-security`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
1. Visit brave://settings/extensions and toggle Privacy Pass switch, a prompt as below will be shown if Privacy Pass extension is not currently installed.
Screenshot 2019-06-03 at 14 50 20
2. Click "Cancel" in the prompt, the Privacy Pass switch should be changed back to off.
3. Toggle it on again, and click "Add extension" in the prompt to install it, Privacy Pass extension should now be installed and enabled.
4. Left click Privacy Pass icon opens current status report, as shown below
Screenshot 2019-06-03 at 14 53 39
5. In brave://settings/extensions, toggle Privacy Pass switch off again and visit brave://extensions, Privacy Pass extension should be shown disabled.
6. Enable Privacy Pass switch toggle in brave://settings/extensions again,Privacy Pass extension should be shown enabled in brave://extensions.
7. Remove Privacy Pass extension in brave://extensions, Privacy Pass extension switch toggle in brave://settings/extensions should be shown off.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by rulatir** [comment]
Is this PR abandoned?

**Comment by durch** [comment]
@rulatir I really hope not...

**Comment by riastradh-brave** [comment]
Our main interest in having PrivacyPass included, rather than as just another extension like any other, is for use in private windows with Tor, to reduce the number of captchas that are presented to Tor users by Cloudflare.  However, currently private windows with Tor can't use extensions at all.  We are working on changing the architecture of private windows with Tor so that they can use extensions, but it's a lot of work with complicated internal design consequences, and it's not ready yet.  See https://github.com/brave/brave-browser/issues/1677 and https://github.com/brave/brave-browser/issues/2307 for more details.

**Comment by bsclifton** [comment]
Closing as this is a bit stale (needs rebase) and there are the complications that @riastradh-brave mentioned above (not being able to run extensions in Tor private window)

**Comment by durch** [comment]
@bsclifton we were just in the process of rebasing, we've done it once already.  How do you propose we proceed, is there anything we can do to help with the refactor of Tor windows?

**Comment by tomlowenthal** [comment]
Even once the Tor refactor is complete and extensions are usable in Tor windows, this PR doesn't hit all the UX needs, and there are a couple of technical improvements which would be desirable too.

- [ ] Flipping the switch shouldn't show the extension installation prompt. It should just activate the extension like all the other switches in that section.
- [ ] The Privacy Pass UI needs to actually be integrated, not just shown as an installed extension like this. So it needs to match the design of the rest of the browser, including light/dark mode, &c.
- [ ] @bridiver raised a concern with the use of `localstorage` to keep the passes — that's not an ideal location, and in particular causes trouble sharing passes between Tor and non-Tor contexts.

**Comment by durch** [comment]
@tomlowenthal thank you for the feedback. We'll get right to work shipping at least the UX improvements. 

@bridiver agree that `localstorage` is not the best place for keeping the passes. We'll be sure to go over that with the CF team as well, any suggestions as to the better location, at least in the context of Tor vs non-Tor?

**Comment by rulatir** [comment]
Am I correct in assuming that we are finally days away from HAVING™ this, or will some other issue pop up that will block this feature for another half-year?

**Comment by riastradh-brave** [comment]
I'm hoping we'll be able to take advantage of this soon but there are still some issues remaining with getting extensions running in private windows with Tor.

**Comment by NumDeP** [comment]
> The Privacy Pass UI needs to actually be integrated, not just shown as an installed extension...

Perhaps it can take the place of the BAT icon in the URL bar.

**Comment by bsclifton** [comment]
Closing as Privacy pass is installable from the Chrome Web Store. It works great in Tor tabs too

I don't think we want to build this into the browser by default
cc: @rebron @diracdeltas

**Pull request closed without merging**
