### PR TITLE
fix node package vulns found by npm audit

### PR DESCRIPTION
**Pull request by cezaraugusto**

### CODE REVIEW

**Comment by diracdeltas** [comment]
i think this did the same thing as my PR? https://github.com/brave/brave-core/pull/1665

**Comment by diracdeltas** [comment]
if not, is there an open issue for what this is fixing?

**Comment by cezaraugusto** [comment]
@diracdeltas yes I think we both run `npm audit --fix`. my bad that I didn't check your PR first. just saw the call in slack and committed.

**Comment by diracdeltas** [comment]
@cezaraugusto got it. i will close the original issue and my PR. next time please look for an open issue and see if anyone is assigned

**Pull request merged**
