### PR TITLE
Fixes duplicate/bad confirmations retry logic - 1.7.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/5260/files
Resolves https://github.com/brave/brave-browser/issues/9242

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by bsclifton** [comment]
macOS actually ran great here 🎉 there was a "Publish xUnit Test" failure which is not a problem. iOS failed though, timing out during fetch ☹️

**Comment by bsclifton** [comment]
Passed on all except iOS; marking skip for others and re-running

**Comment by kjozwiak** [comment]
Looks like `iOS` is failing `init` due to `Timeout has been exceeded` as per https://ci.brave.com/job/brave-browser-build-pr/job/issues%252F9242-1.7.x/6/execution/node/323/log/. I'm not sure if restarting as most PRs are failing due to this issue but giving it a shot. Hopefully it doesn't timeout as it's a bit later and there's less users using `CI`.

**Comment by kjozwiak** [comment]
Just an FYI, https://github.com/brave/brave-core/pull/5260/ hasn't landed in `master`.

**Comment by kjozwiak** [comment]
QA verified https://github.com/brave/brave-core/pull/5260 on Nightly as per https://github.com/brave/brave-core/pull/5260/#issuecomment-615456746.

**Pull request merged**
