### PR TITLE
[Nala]: Bump to latest & migrate off createEventDispatcher

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Changes https://github.com/brave/leo/compare/adbd7ca81aa7df671c7b16b7d111bef097d22fb9...58a07d5a8f3fea5aff6327d64ad0b58657111c29
- [Icons]: Assorted updates
- [Dependencies]: Rennovate & dependabot updates
- [RTL]: Improve RTL support for Toggle, NavDots & Dialog
- [FormItem]: Customizable background colors
- [ButtonMenu]: Make controlled ButtonMenu work better
- [ButtonMenu]: Add support for an explicit maximum height
- **BREAKING** [Svelte]: Migrate off deprecated `createEventDispatcher` API
- [Storybook]: Enable autodocs

### CODE REVIEW

**Comment by fallaciousreasoning** [comment]
@fmarier for @brave/js-deps-reviewers 
@Douglashdaniel for @brave/crypto-wallets-front-end 
@zenparsing for @brave/rewards-client

**Review by Douglashdaniel — APPROVED** [review]
++ Wallet Front-end

**Comment by fallaciousreasoning** [comment]
@brave/rewards-client ptal

**Review by bsclifton — APPROVED** [review]
rewards client LGTM! 👍

**Comment by fallaciousreasoning** [comment]
@nullhook I'm merging this.

**Pull request merged**
