### PR TITLE
1.18.x - Brave Today production urls (Uplift #7300)

### PR DESCRIPTION
**Pull request by petemill**
Uplift https://github.com/brave/brave-core/pull/7300 / https://github.com/brave/brave-browser/issues/12601 to 1.18.x

### CODE REVIEW

**Comment by kjozwiak** [comment]
`test-browser` failed on `Linux` due to `RewardsPublisherBrowserTest.PanelShowsCorrectPublisherData` failing as per https://ci.brave.com/job/pr-brave-browser-1.18.x-today-prod-linux/1/execution/node/253/log/. However, it's a known intermittent issue and doesn't block uplift.

```
18:20:35  1 test failed:
18:20:35      RewardsPublisherBrowserTest.PanelShowsCorrectPublisherData (../../brave/components/brave_rewards/browser/test/rewards_publisher_browsertest.cc:100)
```

**Comment by kjozwiak** [comment]
Ready to uplift/merge but going to wait till we get a go ahead from either @jsecretan or @petemill as per the discussion in today's b-c planning/triage meeting. CCing @rebron @bsclifton.

**Comment by petemill** [comment]
Content at this URL looks good to me now, ready to merge IMO https://github.com/brave/brave-core/pull/7300#issuecomment-737589499

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.18.x` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
