### PR TITLE
Fix promoted card url

### PR DESCRIPTION
**Pull request by abhiklodh**
Promoted news card now loads https://brave.com/brave-news.

Resolves https://github.com/brave/brave-browser/issues/17584

After enabling Brave News, scrolling down to a promoted article and hovering on the 'Promoted' tag on the bottom right,  https://brave.com/brave-today appears as the URL and clicking on it leads to the article page. 

I went through the code and changed the promotedInfoUrl to https://brave.com/brave-news and made sure that simply clicking on the Promoted tag leads to https://brave.com/brave-news instead of the article. 

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [x] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [x] New files have MPL-2.0 license header
- [x] Adequate test coverage exists to prevent regressions
- [x] Major classes, functions and non-trivial code blocks are well-commented
- [x] Changes in component dependencies are properly reflected in `gn`
- [x] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [x] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
A detailed test plan is described in the issue.

### CODE REVIEW

**Comment by abhiklodh** [comment]
From what I can understand, I may have accidentally changed the functionality of the 'Promoted' button to something I wanted it to be and not something that I should have done. I am going to start working on the actual issue asap.

**Comment by abhiklodh** [comment]
My new commit now fixes the original issue.

**Comment by abhiklodh** [comment]
@nullhook I have had severe storage issues that are preventing me from further maintaining the entire codebase on my work computer. Hence I had to shift my repository to my laptop and I am facing Git issues that are not letting me squash my commits. 
Could you kindly review my code after squashing the commits?

**Comment by bsclifton** [comment]
Closing - apologies we didn't get a chance to properly review. We've removed the promoted functionality and https://github.com/brave/brave-browser/issues/17584 has been closed

**Pull request closed without merging**
