### PR TITLE
[Android] Uplift of PRs: 4345 4346 4675 4678 4823 4841  into 1.5.x.

### PR DESCRIPTION
**Pull request by gdregalo**
Uplift of:
https://github.com/brave/brave-core/pull/4346
https://github.com/brave/brave-core/pull/4345
https://github.com/brave/brave-core/pull/4675
https://github.com/brave/brave-core/pull/4678
https://github.com/brave/brave-core/pull/4823
https://github.com/brave/brave-core/pull/4841

Fixes:
https://github.com/brave/brave-browser/issues/8816
https://github.com/brave/brave-browser/issues/8818
https://github.com/brave/brave-browser/issues/8283
https://github.com/brave/brave-browser/issues/8284
https://github.com/brave/brave-browser/issues/8509
https://github.com/brave/brave-browser/issues/8502
https://github.com/brave/brave-browser/issues/8541

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [ ] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by bsclifton** [comment]
@gdregalo can you also link to each of the issues this fixes? We'll need to check test plans on those and adjust milestone if uplift approved

**Comment by gdregalo** [comment]
@bsclifton 
Each PR is linked to the corresponding brave-browser issue. 
Also post them here:
https://github.com/brave/brave-browser/issues/8816
https://github.com/brave/brave-browser/issues/8818
https://github.com/brave/brave-browser/issues/8283
https://github.com/brave/brave-browser/issues/8284
https://github.com/brave/brave-browser/issues/8509
https://github.com/brave/brave-browser/issues/8502
https://github.com/brave/brave-browser/issues/8541

**Comment by bsclifton** [comment]
@gdregalo right- I can see that if I take the time to follow them, which takes quite a while. I went ahead and did this and edited original post. Can you please make sure each issue linked is marked as `QA/Yes` or `QA/No` and has detailed information about the problem and steps to reproduce / test plan?

**Comment by kjozwiak** [comment]
`Travis` is failing `TEST_SUITE=test-security` due to the `minimist` npm package being vulnerable. It's a known issue as per https://github.com/brave/brave-browser/issues/8722 and doesn't block the PR from being uplifted.

**Pull request merged**
