### PR TITLE
Add p3a ActiveAccounts for BTC and ZEC

### PR DESCRIPTION
**Pull request by supermassive**
Resolves https://github.com/brave/brave-browser/issues/32723

Privacy review: https://github.com/brave/reviews/issues/1519

## Submitter Checklist:

- [x] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by yrliou — APPROVED** [review]
LGTM for active accounts, are we going to have a separate PR for TransactionSent?

**Review by kdenhartog — APPROVED** [review]
Approving for privacy team. This looks fine to me.

**Comment by supermassive** [comment]
> LGTM for active accounts, are we going to have a separate PR for TransactionSent once it's been moved to core?

Let's wait it gets into core, or even handle new coins in it

**Review by iefremov — APPROVED** [review]

**Comment by GeetaSarvadnya** [comment]
@supermassive: Can you please add the test plan? Thanks!

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.65.55 Chromium: 122.0.6261.94 (Official Build) nightly (64-bit)
-- | --
Revision | 9a86526618f02bd5e1426d128d18ecf0de8f21cd
OS | Windows 10 Version 22H2 (Build 19045.4046)
```
Verified the test plan from https://github.com/brave/brave-core/pull/22114#issue-2138462102

**Note**: Account balance screenshots are not added in the cases as the issue is tested using mainnet

<details>
<summary>Brave.Wallet.ActiveBtcAccounts_metrics not shown_PASSED</summary>

1. Clean profile 1.65.55
2. Create a wallet 
3. Visit brave://wallet/crypto/portfolio/assets
4. Open brave://local-state and look for `Brave.Wallet.ActiveBtcAccounts`
5. Confirmed that the metrics `Brave.Wallet.ActiveBtcAccounts` is not shown on local state file

Example | Example
----------|---------
image | image


</details>

<details>
<summary>Brave.Wallet.ActiveBtcAccounts = 2_PASSED</summary>

1. Clean profile 1.65.55
2. Import QA wallet from 1Password
3. Visit brave://wallet/crypto/portfolio/assets
4. Search by `BTC`
5. Confirmed that BTC wallet balance is shown on the assets page
6. Open brave://local-state and look for `Brave.Wallet.ActiveBtcAccounts`
7. Confirmed that the metrics `Brave.Wallet.ActiveBtcAccounts` response value is `2` as expected [As two BTC wallets have the account balance]

image

</details>


<details>
<summary>Brave.Wallet.ActiveZecAccounts = metrics not shown_PASSED</summary>

1. Clean profile 1.65.55
2. Create a wallet 
3. Visit brave://wallet/crypto/portfolio/assets
4. Open brave://local-state and look for `Brave.Wallet.ActiveBtcAccounts`
5. Confirmed that the metrics `Brave.Wallet.ActiveBtcAccounts` is not shown on local state file

image

</details>

<details>
<summary>Brave.Wallet.ActiveZecAccounts = 1_PASSED</summary>

1. Clean profile 1.65.55
2. Import QA wallet from 1Password
3. Create a Zec account
4. Visit brave://wallet/crypto/portfolio/assets
5. Search by `Zec`
6. Confirmed that Zec account is displayed with account balance
7. Open brave://local-state and look for `Brave.Wallet.ActiveZecAccounts`
8. Confirmed that the metrics `Brave.Wallet.ActiveZecAccounts` response value is `1` as expected [As one Zec account has the account balance]

image

</details>

<details>
<summary>Brave.Wallet.ActiveZecAccounts = 2_PASSED</summary>

1. Clean profile 1.65.55
2. Import QA wallet from 1Password
3. Create two Zec account
4. Visit brave://wallet/crypto/portfolio/assets
5. Search by `Zec`
6. Confirmed that Zec account is displayed with account balance
7. Click on the Zec account and confirmed that two Zec accounts have the balance
8. Open brave://local-state and look for `Brave.Wallet.ActiveZecAccounts`
9. Confirmed that the metrics `Brave.Wallet.ActiveZecAccounts` response value is `2` as expected [As two Zec accounts have the account balance]

image


</details>

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.66.19 Chromium: 123.0.6312.46 (Official Build) nightly (64-bit)
-- | --
Revision | f059d55f6082b23ef003e2f3010ebe1ea50d5b54
OS | Windows 10 Version 22H2 (Build 19045.4046)
```

**Pull request merged**
