### PR TITLE
Remove dynamic margin

### PR DESCRIPTION
**Pull request by deeppandya**
Resolves https://github.com/brave/brave-browser/issues/25091

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [x] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [x] New files have MPL-2.0 license header
- [x] Adequate test coverage exists to prevent regressions
- [x] Major classes, functions and non-trivial code blocks are well-commented
- [x] Changes in component dependencies are properly reflected in `gn`
- [x] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [x] Test plan is specified in PR before merging

## After-merge Checklist:

- [x] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [x] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by tapanmodh — APPROVED** [review]
LGTM

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.45.15 Chromium: 105.0.5195.68 (Official Build) canary (32-bit)
--- | ---
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Android 12; Build/SP1A.210812.016
```

### `Test Case #1` - https://github.com/brave/brave-browser/issues/25091

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/25091#issue-1356354422 and ensured that Brave wasn't crashing.

https://user-images.githubusercontent.com/2602313/187741896-4dc5d8f9-d9dc-4466-8142-ee980ab20cde.mp4

### `Test Case #2` - https://github.com/brave/brave-browser/issues/25059

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/25059#issue-1355086510 and ensured that Brave wasn't crashing.

https://user-images.githubusercontent.com/2602313/187745091-f06b2975-bcf3-4d1e-a1e7-bd0c4f1ca291.mp4

**Comment by kjozwiak** [comment]
Because the above is a significant change that can affect an important feature, going through the STR/Cases via https://github.com/brave/brave-core/pull/14350#issuecomment-1231063327.

Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.45.15 Chromium: 105.0.5195.68 (Official Build) canary (32-bit)
--- | ---
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Android 12; Build/SP1A.210812.016
```

### `Test Case #1` (Supported Regions - US/CA/DE/FR/UK/AT/ES/MX)

* installed `1.45.15 Chromium: 105.0.5195.68`
* ensured that the system language is set to either `US`, `CA`, `DE`, `FR`, `UK`, `AT`, `ES` or `MX`
* launched brave and changed the default SE from `Brave` to anything else within the list (Google, DDG, Startpage etc..)
* added `--enable-features=BraveSearchOmniboxBanner` into `Command Line String` via `QA Preferences`
* re-launched the browser tapped on the URL bar and ensured that the Brave search promo is displayed via the omnibox
* ensured that the Brave search promo appears when tapping/editing a URL and the promo hasn't been closed/dismissed
* ensured that the Brave search promo doesn't appear if `Private` is set to another SE but `Standard` is still selected as `Brave`
* ensured that tapping on `Maybe Later` closes the promo within the omnibox and doesn't appear again within the session
  * ensured that it doesn't appear via the omnibox via NTP when starting to enter a URL/search term
  * ensured that tapping on a URL in an existing tab doesn't display the promo
* ensured that tapping on `Try Brave Search` opens `https://search.brave.com/search?q=motorsport&action=makeDefault`
  * ensured that the search term is also appended as per `search?q=motorsport`
  * ensured that tapping on `Try Brave Search` adds `action=makeDefault` into the URL

**`France`**

**`Example`** | **`Example`** | **`Example`** |  **`Example`** | **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------|----------------|-----------------|----------------|---------------
Screenshot_20220831-153646_Brave - Nightly | Screenshot_20220831-153712_Brave - Nightly | Screenshot_20220831-153724_Brave - Nightly | Screenshot_20220831-153753_Brave - Nightly | Screenshot_20220831-153831_Brave - Nightly | Screenshot_20220831-153840_Brave - Nightly | Screenshot_20220831-153846_Brave - Nightly

### `Test Case #2` (Regions that don't have Brave Search as default SE/Still use SE onboarding)

* installed `1.45.15 Chromium: 105.0.5195.68`
* ensured that the system language is set to the correct locale (in this case, `Korea`)
* launched brave and added `--enable-features=BraveSearchOmniboxBanner` into `Command Line String` via `QA Preferences`
* re-launched the browser tapped on the URL bar twice and ensured that the SE onboarding screen is displayed
* ensured that Google was selected as the default via the onboarding screen
* ensured that Google is default SE for both `Standard` & `Private` windows once the onboarding screen has been dismissed
* ensured that the Brave search promo isn't appearing via the omnibox when a text/search term is entered

**`Korea`**

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
---------------|-----------------|----------------|----------------
Screenshot_20220831-154959_Brave - Nightly | Screenshot_20220831-155010_Brave - Nightly | Screenshot_20220831-155024_Brave - Nightly | Screenshot_20220831-155032_Brave - Nightly

### `Test Case #3` (Maybe Later & Dismiss)

* ensured that closing the Brave search promo via `Maybe Later` doesn't re-appear in the same session
  * ensure the promo is not re-appearing when typing into the omnibox via NTP
  * ensure the promo  is not re-appearing when taping on a URL on an existing opened tab
* ensured that the promo re-appears again when the browser is re-launched after tapping on `Maybe Later`
  * ensure that the `Dismiss` button is visible and not the `Maybe Later` as per https://github.com/brave/brave-core/pull/14350#issue-1319129566
* ensured that once a user taps/clicks on `Dismiss`, the promo never re-appears (tried via several re-launches)

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
---------------|-----------------|----------------|----------------
Screenshot_20220829-225327_Brave - Nightly |  Screenshot_20220829-225716_Brave - Nightly | Screenshot_20220829-225641_Brave - Nightly | Screenshot_20220829-225725_Brave - Nightly

### `Test Case #4` (Automatically dismiss after 15 days)

* installed `1.45.15 Chromium: 105.0.5195.68`
* ensured that the system language is set to either `US`, `CA`, `DE`, `FR`, `UK`, `AT`, `ES` or `MX`
* launched brave and changed the default SE from `Brave` to anything else within the list (Google, DDG, Startpage etc..)
* added `--enable-features=BraveSearchOmniboxBanner` into `Command Line String` via `QA Preferences`
* re-launched the browser tapped on the URL bar and ensured that the Brave search promo is displayed via the omnibox
* moved the time/date on the device ahead ~16 days and re-launched the browser
* ensured that the Brave search promo doesn't appear via the omnibox when tapping via NTP
* ensured that the Brave search promo doesn't appear when tapping on the omnibox if an already opened tab

**Pull request merged**
