### PR TITLE
Rename `Brave Sync` to `Sync` in settings

### PR DESCRIPTION
**Pull request by cezaraugusto**
fix https://github.com/brave/brave-browser/issues/2592

Test Plan

1. Go to brave://settings
2. Ensure Sync is shown as `Sync` and not `Brave Sync`

### CODE REVIEW

**Comment by darkdh** [comment]
what about `<message name="IDS_SHOW_BRAVE_SYNC" desc="The show brave sync menu in the app menu">`?
screen shot 2018-12-17 at 11 31 36

**Comment by cezaraugusto** [comment]
way to go

**Comment by cezaraugusto** [comment]
master eaf047f
0.60.x 04145ada
0.59.x uplift request

**Comment by rebron** [comment]
Approving uplift-request for 0.59.x-beta. cc: @kjozwiak cc: @srirambv

**Pull request merged**
