### PR TITLE
[Android] Settings toggle android app links

### PR DESCRIPTION
**Pull request by tapanmodh**
Resolves https://github.com/brave/brave-browser/issues/25863

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
1. Toggle setting to allow/block Android "app links" under settings -> brave shields & privacy -> other privacy settings.
Copy: "Allow app links to open in apps outside of Brave"
Default state: disabled.
2. Enabled (Allow) state: app links open in external app.
3. Disabled state: app links open in Brave.

### CODE REVIEW

**Review by mkarolin — APPROVED** [review]
`strings`++

**Review by deeppandya — APPROVED** [review]
LGTM

**Review by deeppandya — CHANGES_REQUESTED** [review]
@tapanmodh need to update tests for privacy settings

**Review by sujitacharya2005 — APPROVED** [review]

**Review by AlexeyBarabash — APPROVED** [review]
LGTM
@tapanmodh could you also fix these checkstyle warnings
```
** Presubmit Warnings: 1 **
  android/java/org/chromium/chrome/browser/externalnav/BraveExternalNavigationHandler.java:19: Public classes and interfaces require JavaDoc comments.
  android/java/org/chromium/chrome/browser/externalnav/BraveExternalNavigationHandler.java:60: Use SharedPreferencesManager instead to access app-wide SharedPreferences from //src/chrome.
  android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:46: Public classes and interfaces require JavaDoc comments.
  android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:135:23: Non-public, non-static field names start with m.
  android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:136:23: Non-public, non-static field names start with m.
  android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:137:23: Non-public, non-static field names start with m.
  android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:414: Use SharedPreferencesManager instead to access app-wide SharedPreferences from //src/chrome.
  android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:423: Use SharedPreferencesManager instead to access app-wide SharedPreferences from //src/chrome.
  android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:630: Use SharedPreferencesManager instead to access app-wide SharedPreferences from //src/chrome.
  android/javatests/org/chromium/chrome/browser/privacy/settings/BravePrivacySettingsTest.java:28: Public classes and interfaces require JavaDoc comments.
  android/javatests/org/chromium/chrome/browser/privacy/settings/BravePrivacySettingsTest.java:45:24: Static field names start with s.
```
?

**Comment by tapanmodh** [comment]
> LGTM @tapanmodh could you also fix these checkstyle warnings
> 
> ```
> ** Presubmit Warnings: 1 **
>   android/java/org/chromium/chrome/browser/externalnav/BraveExternalNavigationHandler.java:19: Public classes and interfaces require JavaDoc comments.
>   android/java/org/chromium/chrome/browser/externalnav/BraveExternalNavigationHandler.java:60: Use SharedPreferencesManager instead to access app-wide SharedPreferences from //src/chrome.
>   android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:46: Public classes and interfaces require JavaDoc comments.
>   android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:135:23: Non-public, non-static field names start with m.
>   android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:136:23: Non-public, non-static field names start with m.
>   android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:137:23: Non-public, non-static field names start with m.
>   android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:414: Use SharedPreferencesManager instead to access app-wide SharedPreferences from //src/chrome.
>   android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:423: Use SharedPreferencesManager instead to access app-wide SharedPreferences from //src/chrome.
>   android/java/org/chromium/chrome/browser/privacy/settings/BravePrivacySettings.java:630: Use SharedPreferencesManager instead to access app-wide SharedPreferences from //src/chrome.
>   android/javatests/org/chromium/chrome/browser/privacy/settings/BravePrivacySettingsTest.java:28: Public classes and interfaces require JavaDoc comments.
>   android/javatests/org/chromium/chrome/browser/privacy/settings/BravePrivacySettingsTest.java:45:24: Static field names start with s.
> ```
> 
> ?

sure, I'll do it

**Comment by tapanmodh** [comment]
@AlexeyBarabash regarding this warning `Use SharedPreferencesManager instead to access app-wide SharedPreferences from //src/chrome`. We should update in separate PR in the whole app as it is used in the other classes as well.

**Comment by AlexeyBarabash** [comment]
@tapanmodh , I agree, lets fix it later as it is not a trivial thing to fix.

**Pull request merged**
