### PR TITLE
Fixes Tor avatar menu after c78 bump.

### PR DESCRIPTION
**Pull request by mkarolin**
Also, removed no longer used override in chromium_src's profiles_state.cc.

Fixes brave/brave-browser#6451

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Android
  - [x] iOS
  - [x] Linux
  - [x] macOS
  - [x] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [x] iOS
  - [x] Linux
  - [x] macOS
  - [x] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
1. Start Brave.
2. Open Tor window.
3. Verify that the avatar button in Tor window only has Tor icon.
4. Click on the avatar button.
5. Verify that the menu contains `Tor` and `Exit Tor` options.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
Seeing an issue with this one on Private windows; it'll always show Tor in the profile menu with this change:
Screen Shot 2019-10-11 at 11 17 43 PM

Tor properly shows only Tor profile:
Screen Shot 2019-10-11 at 11 18 38 PM

**Comment by mkarolin** [comment]
@bsclifton, yep, I might have skipped a return 🤣

**Comment by mkarolin** [comment]
Only lint and unrelated browser test failed in CI.

**Comment by bsclifton** [comment]
Changes work great 😄 

While testing this, I noticed a weird regression - cc: @yrliou who has done Tor work in Nightly (it may be due to that work? or Chromium 78? not sure)

Basically, in Dev channel for example (C77), when in a private window with Tor, you're not given the option to create a regular private window
- via the hamburger menu
    Screen Shot 2019-10-14 at 9 27 54 AM
- via the menu (macOS)
    Screen Shot 2019-10-14 at 9 30 17 AM

On master/Nightly, when in a private window with Tor, you're shown the option to open a new private window. If you do choose this, it opens a private window with Tor, NOT a regular private window.
- hamburger menu
    Screen Shot 2019-10-14 at 9 28 07 AM
- via the menu (macOS)
    Screen Shot 2019-10-14 at 9 30 37 AM



@yrliou is this related to the work you did? Either way, I think I'll create an issue 😄

**Pull request merged**
