### PR TITLE
Hide QR code in Rewards Settings

### PR DESCRIPTION
**Pull request by bsclifton**
Fixes https://github.com/brave/brave-browser/issues/13053

## Submitter Checklist:

- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed).
- [ ] Requested a security/privacy review as needed.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by emerick — APPROVED** [review]
LGTM

**Review by marshall — APPROVED** [review]

**Comment by bsclifton** [comment]
Here's how it looks:
image

**Comment by bsclifton** [comment]
- [Unrelated browser test error on Linux](https://ci.brave.com/job/pr-brave-browser-bsc-remove-qr-code-linux/1/execution/node/251/log/)
```
18:06:14  1 test failed:
18:06:14      SearchEngineProviderP3ATest.DefaultSearchEngineP3A (../../brave/browser/search_engines/search_engine_tracker_browsertest.cc:30)
```
- macOS ran into a compile error; restarted

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following build:

```
Brave | 1.20.13 Chromium: 87.0.4280.88 (Official Build) nightly (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2009 (Build 19042.630)
```

* Updated from `1.20.12 CR: 87.0.4280.88` to `1.20.13 CR: 87.0.4280.88` and ensured the QR code was removed from `brave://rewards`
* launched a new profile and ensured that the QR code was removed from `brave://rewards`
  * ensured that the QR code wasn't visible when ads/a-c were disabled and the user didn't opt-in
  * ensured that the QR code wasn't visible when opting into ads/a-c by clicking on `Start using Brave Rewards`

**Pull request merged**
