### PR TITLE
Enable p3a by default android (Uplift to 1.19.x)

### PR DESCRIPTION
**Pull request by deeppandya**
Uplift of #7565
Resolves https://github.com/brave/brave-browser/issues/13486

Approved, please ensure that before merging: 
- [ ] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 
- [ ] You have tested your change on Nightly. 
- [ ] The PR milestones match the branch they are landing to. 

After you merge: 
- [ ] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by deeppandya** [comment]
Added commit here : https://github.com/brave/brave-core/pull/7563/commits/c261046438eeb6397b835deb36d1d8b31854ec09 so closing this PR

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `Bravearm 1.20.74.apk`

- Verified https://github.com/brave/brave-browser/issues/12723#issue-744089839
- Verified https://github.com/brave/brave-browser/issues/12723#issuecomment-755630759

Logged :
https://github.com/brave/brave-browser/issues/13537
https://github.com/brave/brave-browser/issues/13539
https://github.com/brave/brave-browser/issues/13540
https://github.com/brave/brave-browser/issues/13541

**New user**
- Verified the initial welcome screen display with P3A checkbox after app launch
image
- Verified that for new users who viewed and clicked on the `Continue` button in the onboarding screen, the stats  `p3a.enabled`  and `notice_acknowledged` are returng `true` value in local-state file
image

- Verified that, click on the `Private product analytics` link redirects to https://brave.com/p3a
- In a clean profile `1.20.74` after app launch, uncheck the P3A checkbox and open brave://local-state file and ensured that `p3a.enabled` is returning `false` and `p3a.notice_acknowledged ` is equal to  `true`
image


**Existing user**
- Verified that the P3A checkbox modal is shown for the existing users on the next app launch
image
- Verified the Graphics displayed on the P3A screen with Figma doc

**Comment by GeetaSarvadnya** [comment]
@AlexeyBarabash @deeppandya I have set Brave Nightly `1.20.74` as the default browser in Android, the chrome://local-state file is returning the value as `0`  for the default browser stats `Brave.Core.IsDefault`. Looks like P3A stats are not returning correct values in Android. The same thing works fine in Desktop

image

**Comment by AlexeyBarabash** [comment]
@GeetaSarvadnya 
you are right, for now not all the metrics are supported in Android, https://github.com/brave/brave-core/pull/7016#issuecomment-721420347

**Comment by GeetaSarvadnya** [comment]
@AlexeyBarabash Can you please specify which metrics are supported in Android right now? So that we can test in this milestone.

**Comment by AlexeyBarabash** [comment]
@GeetaSarvadnya the metrics table is in message https://github.com/brave/brave-core/pull/7016#issuecomment-721420347 .

The supported are:
```
Brave.Core.BookmarksCountOnProfileLoad.2
Brave.Core.TabCount
Brave.P3A.SentAnswersCount
Brave.Rewards.AdsState.2
Brave.Rewards.AutoContributionsState.2
Brave.Rewards.TipsState.2
Brave.Rewards.WalletBalance.2
Brave.Savings.BandwidthSavingsMB
Brave.Search.DefaultEngine.2
Brave.P2A.TotalAdOpportunities
Brave.P2A.AdOpportunitiesPerSegment.*
Brave.P2A.TotalAdImpressions
Brave.P2A.AdImpressionsPerSegment.*
```

**Comment by GeetaSarvadnya** [comment]
Verified the metrics mentioned in the https://github.com/brave/brave-core/pull/7566#issuecomment-759451887

**_1. Brave.Core.BookmarksCountOnProfileLoad.2_**

- Ensured that the response value for `BookmarksCountOnProfileLoad=0` when there is no bookmarks in on profile load.
image
- Ensured that the response value for `BookmarksCountOnProfileLoad=1` when the bookmarks count is in the range 0-5
image
- Ensured that the response value for `BookmarksCountOnProfileLoad=2` when the bookmarks count is in the range 21-100
image

**_2. Brave.Core.TabCount_**
- Ensured that the response value for `Brave.Core.TabCount=0` when tab count is in the range 0-1
image
- Ensured that the response value for `Brave.Core.TabCount=1` when tab count is in the range 2-5
image

**Pull request closed without merging**
