### PR TITLE
Expand Rewards to three decimal places - 1.11.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/5699
Resolves https://github.com/brave/brave-browser/issues/10027

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by tmancey** [comment]
CI failed on Linux and macOS, restarting

**Comment by kjozwiak** [comment]
Looks like `test-browser` failed on both `Linux` & `macOS` as per https://ci.brave.com/job/pr-brave-browser-issues-10027-1.11.x/6/execution/node/391/log/ & https://ci.brave.com/job/pr-brave-browser-issues-10027-1.11.x/6/execution/node/450/log/. Example:

```
04:10:15  ../../brave/components/brave_rewards/browser/rewards_service_browsertest_utils.cc:123: Failure
04:10:15  Expected equality of these values:
04:10:15    true
04:10:15    result
04:10:15      Which is: a JavaScript error:
04:10:15  Error: Timed out waiting for '[data-test-id='activity-table-body'] tr:nth-of-type(1) td:nth-of-type(3)' to equal '20.0BAT28.60 USD'
04:10:15      at eval (__const_std::string&_script__:45:24)
04:10:15  
04:10:15  Stack trace:
04:10:15  #0 0x5602b5ae49e9 (/home/ubuntu/jenkins/workspace/pr-brave-browser-issues-10027-1.11.x/src/out/Release/brave_browser_tests+0x5b999e8)
04:10:15  
04:10:15  ../../brave/components/brave_rewards/browser/rewards_service_browsertest_utils.cc:123: Failure
04:10:15  Expected equality of these values:
04:10:15    true
04:10:15    result
04:10:15      Which is: a JavaScript error:
04:10:15  Error: Timed out waiting for '[data-test-id='activity-table-body'] tr:nth-of-type(2) td:nth-of-type(3)' to equal '30.0BAT42.90 USD'
04:10:15      at eval (__const_std::string&_script__:45:24)
04:10:15  
04:10:15  Stack trace:
04:10:15  #0 0x5602b5ae49e9 (/home/ubuntu/jenkins/workspace/pr-brave-browser-issues-10027-1.11.x/src/out/Release/brave_browser_tests+0x5b999e8)
04:10:15  
04:10:15  [  FAILED  ] BraveRewardsBrowserTest.SplitProcessOneTimeTip, where TypeParam =  and GetParam() =  (12060 ms)
04:10:15  [596/596] BraveRewardsBrowserTest.SplitProcessOneTimeTip (12319 ms)
04:10:15  1 test failed:
04:10:15      BraveRewardsBrowserTest.SplitProcessOneTimeTip (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:2936)
```

I haven't seen the above failure before. @NejcZdovc is this a known intermittent issue? Possible that the above PR regressed ` BraveRewardsBrowserTest.SplitProcessOneTimeTip `?

**Comment by kjozwiak** [comment]
@tmancey looks like `CI/skip-android`, `CI/skip-ios`, and `CI/skip-windows` were removed ~8 days ago as per https://github.com/brave/brave-core/pull/5835#event-3452173231. However, https://ci.brave.com/job/pr-brave-browser-issues-10027-1.11.x/6/ looks like the last run which skipped the above platforms. Was the above also meant to run on these? Maybe the labels were removed after the 6th was restarted/relaunched?

**Comment by NejcZdovc** [comment]
@tmancey you need do adjust values for `SplitProcessOneTimeTip` test as well. Currently they are set to 1 decimal place

**Pull request merged**
