### PR TITLE
add codesign requirements to match upstream

### PR DESCRIPTION
**Pull request by bridiver**
Resolves https://github.com/brave/brave-browser/issues/21302

## Submitter Checklist:

- [ ] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by mkarolin — APPROVED** [review]
LGTM

**Review by bsclifton — APPROVED** [review]
@justnom helped us get a build which was Nightly and did the proper signing (build 615). I tested it out and it worked great for me on macOS (using Twitter as the example steps for pinning a PWA in new window).

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 12.2.1 x64 Monterey` using the following build(s):

```
Brave | 1.38.6 Chromium: 99.0.4844.45 (Official Build) nightly (x86_64)
-- | --
Revision | edbc0b8343c7b10fddb0e1b4efb280b0f6e38cab-refs/branch-heads/4844@{#788}
OS | macOS Version 12.2.1 (Build 21D62)
```

* ensured that creating a PWA via `Hamburger` -> `More Tools` -> `Create Shortcut...` works without issues
* ensured that the PWA launches without issues once it's created
* ensured that selecting `Open as window` works/opens the PWA in a new window as expected

@bsclifton doing a quick check, looks resolved 👍 We'll run through the above more thoroughly once we get an official Nightly with the fix including upgrade cases.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 12.2.1 x64 Monterey` using the following build(s):

```
Brave | 1.38.12 Chromium: 99.0.4844.51 (Official Build) nightly (x86_64)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | macOS Version 12.2.1 (Build 21D62)
```

#### `Test Case #1` ("Open as window" selected) - PASSED

* visit https://www.cnn.com
* create a PWA via `Hamburger Menu` -> `More Tools` -> `Create Shortcut...` (`Open as window` selected)
* ensured that CNN is launched in a separate window once the PWA is created
* ensured that launching the PWA via the shortcut works without issues when Brave is opened & closed
* ensured that you can move around the PWA shortcut to different locations and it still works as expected
* ensured that you can uninstall the PWA via the `Hamburger Menu` (need to be within the PWA window)

#### `Test Case #2` ("Open as window" not selected) - PASSED

* visit https://www.cnn.com
* create a PWA via `Hamburger Menu` -> `More Tools` -> `Create Shortcut...` (`Open as window` not selected)
* ensured that clicking on the PWA shortcut opens a https://www.cnn.com tab within an existing window
* ensured that you can move around the PWA shortcut to different locations and it still works as expected

#### `Test Case #3` (Upgrade Case) - PASSED

* download/install `1.38.10 Chromium: 99.0.4844.45` (PWA via `Open as window` broken on this build)
* visit https://www.cnn.com and create a PWA using `Open as window` (you'll notice it's broken)
* upgrade to `1.38.12 Chromium: 99.0.4844.51`
* click on the previously created PWA shortcut and a PWA window should launch with CNN opened

**Pull request merged**
