### PR TITLE
Remove chrome-browser-browsing_data-chrome_browsing_data_remover_delegate_factory.cc.patch

### PR DESCRIPTION
**Pull request by mariospr**
This patch could be removed in favour of a chromium_src override that
would define its version of ChromeBrowsingDataRemoverDelegateFactory's
BuildServiceInstanceFor() to simply return an instance of
BraveBrowsingDataRemoverDelegate(), instead of patching the original
method from upstream (which doesn't do anything else other than
returning an instance of ChromeBrowsingDataRemoverDelegate).

Resolves https://github.com/brave/brave-browser/issues/14819

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

See Test plan from https://github.com/brave/brave-core/pull/4624

### CODE REVIEW

**Comment by simonhong** [comment]
Changes looks good to me. but there is gn_check failure. it seems we need to put something to chromium_src/..../DEPS.
```
[2021-03-18T20:42:35.355Z] ERROR in C:\4819\src\brave\chromium_src\chrome\browser\browsing_data\chrome_browsing_data_remover_delegate_factory.cc

[2021-03-18T20:42:35.355Z]   Illegal include: "components/feed/buildflags.h"

[2021-03-18T20:42:35.355Z]     Because of no rule applying.

[2021-03-18T20:42:35.355Z]   Illegal include: "components/feed/feed_feature_list.h"

[2021-03-18T20:42:35.355Z]     Because of no rule applying.

[2021-03-18T20:42:35.355Z] 

[2021-03-18T20:42:35.355Z] FAILED
```

**Comment by mariospr** [comment]
> Changes looks good to me. but there is gn_check failure. it seems we need to put something to chromium_src/..../DEPS.

@simonhong @mkarolin  Sorry I've overlooked this (also on the other PRs), fixed now. PTAL, thanks!

**Review by bridiver — CHANGES_REQUESTED** [review]
Same as the other PR, overriding that particular method seems too risky and issues will only be caught at runtime

**Comment by mariospr** [comment]
> Same as the other PR, overriding that particular method seems too risky and issues will only be caught at runtime

Sounds good, thanks. Will close the issue and try to avoid it in the future

**Pull request closed without merging**
