### PR TITLE
Cleanup deprecated prefs

### PR DESCRIPTION
**Pull request by supermassive**
Resolves https://github.com/brave/brave-browser/issues/35004

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by goodov — APPROVED** [review]
`chromium_src` lgtm

**Comment by thypon** [comment]
> * MaybeMigratePBKDF2Iterations

Isn't this one required anymore @kdenhartog ?

**Review by StephenHeaps — APPROVED** [review]
iOS++

**Comment by kdenhartog** [comment]
> > * MaybeMigratePBKDF2Iterations
> 
> Isn't this one required anymore @kdenhartog ?

Pretty sure it would still be needed. We can't be certain that all users who created a wallet before the update was added have migrated to the new larger number of iterations, so removing this could keep users on the older less secure number of iterations.

**Comment by supermassive** [comment]
> > > * MaybeMigratePBKDF2Iterations
> > 
> > 
> > Isn't this one required anymore @kdenhartog ?
> 
> Pretty sure it would still be needed. We can't be certain that all users who created a wallet before the update was added have migrated to the new larger number of iterations, so removing this could keep users on the older less secure number of iterations.

a) `could keep users on the older less secure number of iterations`. This just won't work. We don't support legacy number of iterations and per keyring nonce in a way other than migration. 
b) chromium has a policy to cleanup such prefs migrations after a year being in release channel. This is to prevent 'dead' code being there for years, to avoid migrations on top of migrations if prefs change again, and to avoid spent QA resources on testing upgrading from very old versions.

@yrliou @bbondy @srirambv thoughts?

**Comment by yrliou** [comment]
@supermassive Is my understanding correct that without migration, 
```
bool KeyringService::CreateEncryptorForKeyring(const std::string& password,
                                               mojom::KeyringId keyring_id) {
  if (password.empty()) {
    return false;
  }

-  // Added 08.08.2022
-  MaybeMigratePBKDF2Iterations(password);
-
  encryptors_[keyring_id] = PasswordEncryptor::DeriveKeyFromPasswordUsingPbkdf2(
      password, GetOrCreateSaltForKeyring(keyring_id), GetPbkdf2Iterations(),
      kPbkdf2KeySize);
  return encryptors_[keyring_id] != nullptr;
}
```
DeriveKeyFromPasswordUsingPbkdf2 will return nullptr and CreateEncryptorForKeyring would return false, hence operation would just fail rather than letting user to able to continue use the legacy iterations? Or is there a possibility it might not be nullptr?

I think in general it makes sense to have a defined minimum period we should wait before deprecating migrations and prefs rather than having them forever. Is 1 year after release as Chromium does enough for us, @kdenhartog?
And in this particular case, if it would just fail and can't be used actually, then there should be no issue. cc @supermassive to confirm above.

**Comment by kdenhartog** [comment]
> I think in general it makes sense to have a defined minimum period we should wait before deprecating migrations and prefs rather than having them forever. Is 1 year after release as Chromium does enough for us, @kdenhartog?

Yeah agreed that makes sense to me. The part that worries me here is I don't want to encounter an issue where the user is unable to log back into their wallet and think they've been locked out. This would be even worse if the user didn't backup their seed phrase properly. As long as we can avoid these user scenarios then getting rid of this migration seems ideal.

> hence operation would just fail rather than letting user to able to continue use the legacy iterations? Or is there a possibility it might not be nullptr, if so, do we have a deterministic way to identify if it's legacy and fail the operation if so?

I think this would mean the user would lose access to login because the password would never generate the proper key to decrypt the keyring. Am I understanding that correctly? In that case, a user that has properly backed up their wallet can just re-provision their wallet by resetting the wallet and restoring from the seed phrase. I really hope this isn't the case, but that's what I'm understanding the code to do right now.

**Comment by supermassive** [comment]
@kdenhartog @yrliou 
After some thinking I'm [reverting deprecating this migration](https://github.com/brave/brave-core/pull/21441/commits/28e907b4154f2d08541b587ad4692cbffe790661) Let's make an exception for this one a keep for another year or more or it starts adding costs to support it. That would be not ok for user to lose their hd accounts or imported accounts(which might not be backed up).

**Comment by kdenhartog** [comment]
> @kdenhartog @yrliou After some thinking I'm [reverting deprecation of this migration](https://github.com/brave/brave-core/pull/21441/commits/28e907b4154f2d08541b587ad4692cbffe790661) Let's make an exception for this one and keep for another year or more or it starts adding costs to support it. That would be not ok for user to lose their hd accounts or imported accounts(which might not be backed up).

We should probably put in a P3A question for this to see how often it's still occurring. Once we get the amount low enough ( >.5% or something like that) we could remove this flag and setup a manual support process where if a user contacts us with this issue the user support team can help them migrate it manually by guiding the user through to run a script. Having something like this in place would be useful anyways because at some point (say in like a 2034) the 300k iterations we have today won't be enough either so this will be a good way to always make it possible to rotate this properly.

**Review by cypt4 — APPROVED** [review]
++

**Comment by cypt4** [comment]
We need to add test plan to test if wallet is not broken when updated from an old version

**Pull request merged**
