### PR TITLE
Update welcome shields text

### PR DESCRIPTION
**Pull request by rossmoody**
Resolves: https://github.com/brave/brave-browser/issues/4511

### CODE REVIEW

**Comment by rossmoody** [comment]
Rebased. Could use a +1

**Comment by cezaraugusto** [comment]
@rossmoody please update it in brave-ui also if you didn't already. thanks!

**Comment by bsclifton** [comment]
Updated milestone to 0.68.x since we ran branch migrations today 😄

**Comment by rossmoody** [comment]
TY for both updates.

**Pull request merged**
