### PR TITLE
Misc fixes for DeAMP

### PR DESCRIPTION
**Pull request by ShivanKaul**
Resolves https://github.com/brave/brave-browser/issues/22262

1. Tweak DeAMP regexes to be lazy
2. The `amp` html attribute might have empty value i.e. `amp=""`
3. Move DeAMP (from Security & Privacy section) and ReduceLanguage (from bottom of brave://settings/shields) settings to be near-top of brave://settings/shields so as to separate them from other per-site privacy settings 

For 3, this is what the brave://settings/shields page looks like now:
image

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

1. Go to 
https://amp.theguardian.com/us-news/commentisfree/2016/feb/16/thomas-piketty-bernie-sanders-us-election-2016
https://www.buzzfeed.com/amphtml/hbraga/your-new-favorite-products 
https://www.foxnews.com/world/russian-crematoria-mariupol-new-auschwitz-mayor.amp
https://www.nbcnews.com/news/amp/rcna23233 and make sure that they all load non-AMP version instead (i.e. view source should not have <html ... amp> anywhere
2. `Auto-redirect AMP pages` no longer lives in brave://settings/privacy but instead lives in brave://settings/shields, and `Prevent sites from fingerprinting me based on my language preferences` setting is next to the former setting.

### CODE REVIEW

**Review by pes10k — APPROVED** [review]
As long as those regex's do what they say on the tin, LGTM

**Comment by aguscruiz** [comment]
Added the AMP option here:
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=1874%3A32653

image

---------------------

Screen without the option
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=1832%3A32253

image

**Comment by ShivanKaul** [comment]
@aguscruiz I think that mockup might also need to include Reduce Language setting that @pilgrim-brave added in https://github.com/brave/brave-core/pull/12234:
image

**Comment by aguscruiz** [comment]
Ok, added. @rebron would you confirm that's right? I can always revert

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.40.5 Chromium: 101.0.4951.41 (Official Build) nightly (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)
```

Ensured that `Auto-redirect AMP pages` was moved from `brave://settings/privacy` -> `brave://settings/shields`

**`Before`** | **`After`**
-------------|--------------
image | image
image | image

Also as per https://github.com/brave/brave-core/pull/12999#issue-1202435157, went thorough the websites and ensured that they're loading the `de-amp` website and `<html ... amp>` shouldn't be visible.

**`de-AMP Disabled`** | **`de-AMP Enabled`**
----------------|----------------
image | image
image | image
image | image
image | image

**Pull request merged**
