### PR TITLE
Fixes Brave Rewards service is associated to Tor Profiles - 1.13.x

### PR DESCRIPTION
**Pull request by tmancey**
Uplift of https://github.com/brave/brave-core/pull/6418
Resolves https://github.com/brave/brave-browser/issues/11223
Resolves https://github.com/brave/brave-browser/issues/11042

- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR.
- [x] You have tested your change on Nightly. 
- [x] The PR milestones match the branch they are landing to. 

After you merge: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by kjozwiak** [comment]
@tmancey mind taking a look? Looks like `macOS`, `Linux` and `Android` failed `test-unit` due to the following:

```
16:42:48  Retrying 1 test (retry #0)
16:42:48  [ RUN      ] BatAdsTabsTest.TabUpdated
16:42:48  ../../brave/vendor/bat-native-ads/src/bat/ads/internal/ads_tabs_unittest.cc:117: Failure
16:42:48  Mock function called more times than expected - returning directly.
16:42:48      Function call: Log(0x117ec3fce pointing to "../../brave/vendor/bat-native-ads/src/bat/ads/internal/ads_impl.cc", 313, 3, @0x7ffee07e2988 "Event log: {\"data\":{\"type\":\"foreground\",\"timestamp\":\"0 hours, 0 minutes, 0 seconds at 2:39 AM\"}}")
16:42:48           Expected: to be called twice
16:42:48             Actual: called 3 times - over-saturated and active
16:42:48  Stack trace:
16:42:48  0   brave_unit_tests                    0x000000010f79471c brave_unit_tests + 3659548
16:42:48  1   brave_unit_tests                    0x000000010f797993 brave_unit_tests + 3672467
16:42:48  2   brave_unit_tests                    0x0000000112335a02 brave_unit_tests + 49408514
16:42:48  3   brave_unit_tests                    0x00000001112088d0 brave_unit_tests + 31398096
16:42:48  4   brave_unit_tests                    0x0000000111209ed3 brave_unit_tests + 31403731
16:42:48  5   brave_unit_tests                    0x00000001123589f7 brave_unit_tests + 49551863
16:42:48  
16:42:48  [  FAILED  ] BatAdsTabsTest.TabUpdated (2 ms)
16:42:48  [1010/1010] BatAdsTabsTest.TabUpdated (2 ms)
16:42:48  1 test failed:
16:42:48      BatAdsTabsTest.TabUpdated (../../brave/vendor/bat-native-ads/src/bat/ads/internal/ads_tabs_unittest.cc:115)
16:42:48  Tests took 5 seconds.
```

`Win x64` failed `build` but I'm not going to restart as it will probably fail again `test-unit` as per the above.

**Comment by tmancey** [comment]
@kjozwiak Fixed and pushed change

**Comment by kjozwiak** [comment]
`tets-browser` failed on `Win x64` due to both `SpeedReaderBrowserTest.SmokeTest` and `GreaselionServiceTest.ScriptInjectionWithPrecondition` failing as per https://ci.brave.com/job/pr-brave-browser-issues-11223-1.13.x-windows/4/execution/node/216/log/. However, this is a known intermittent issue and doesn't block uplft.

```
19:49:38  [  FAILED  ] SpeedReaderBrowserTest.SmokeTest, where TypeParam =  and GetParam() =  (3431 ms)
19:49:38  
19:49:38  [606/606] SpeedReaderBrowserTest.SmokeTest (3619 ms)
19:49:38  2 tests failed:
19:49:38      GreaselionServiceTest.ScriptInjectionWithPrecondition (../../brave/browser/greaselion/greaselion_browsertest.cc:263)
19:49:38      SpeedReaderBrowserTest.SmokeTest (../../brave/browser/speedreader/speedreader_browsertest.cc:71)
```

`test-install` failed on `Win x64` as per https://ci.brave.com/job/pr-brave-browser-issues-11223-1.13.x-windows/4/execution/node/240/log/. However, this is a known intermittent issue and doesn't block uplift.

```
20:08:30  powershell.exe : Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
20:08:30  At C:\13.x@tmp\durable-593e4a66\powershellWrapper.ps1:3 char:1
20:08:30  + & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Comm ...
20:08:30  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20:08:30      + CategoryInfo          : NotSpecified: (Start-Process :...file specified.:String) [], RemoteException
20:08:30      + FullyQualifiedErrorId : NativeCommandError
20:08:30   
20:08:30  At C:\13.x@tmp\durable-593e4a66\powershellScript.ps1:10 char:17
20:08:30  + ...             Start-Process "C:\Users\Administrator\AppData\Local\Brave ...
20:08:30  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20:08:30      + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
20:08:30  
20:08:30      + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.13.x` approved after deliberating with @brave/uplift-approvers. QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/6418#issuecomment-689825301.

**Pull request merged**
