### PR TITLE
fix(webtorrent): add disabled state for "Save all files" while downloading

### PR DESCRIPTION
**Pull request by panoplied**
Resolves https://github.com/brave/brave-browser/issues/24958

Add proper disabled state for "Save all files" button in Web Torrent when torrent files aren't yet downloaded (thus can't be zipped and saved).

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [x] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [x] New files have MPL-2.0 license header
- [x] Adequate test coverage exists to prevent regressions
- [x] Major classes, functions and non-trivial code blocks are well-commented
- [x] Changes in component dependencies are properly reflected in `gn`
- [x] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [x] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by fallaciousreasoning — APPROVED** [review]
LGTM, I'm just kicking off a build. If it passes I'll land it for you :smile: Thanks for the contribution!

**Review by fallaciousreasoning — APPROVED** [review]
Still LGTM, sorry @panoplied

**Comment by fallaciousreasoning** [comment]
@panoplied sorry CI doesn't seem to be running on this PR, I think because you're an external contributor - I've made a copy of the PR with your commit on it https://github.com/brave/brave-core/pull/16002

I promise I'll get this merged, sorry it's taking so long

**Comment by fallaciousreasoning** [comment]
Finally merged (https://github.com/brave/brave-core/pull/14977?notification_referrer_id=NT_kwDOAHUoSLI0MzI0NjE3NDk1Ojc2NzgwMjQ#pullrequestreview-1183269187) @panoplied! Thanks for the contribution, and sorry for the delay in getting it landed, I've been a bit busy and forgot about it.

**Comment by panoplied** [comment]
Great. Nice to see it's fixed. Thanks!

**Pull request closed without merging**
