### PR TITLE
use single process for generate_bindings on mac because using a pool …

### PR DESCRIPTION
**Pull request by bridiver**
…can cause slowdowns or freezes

Resolves https://github.com/brave/brave-browser/issues/22618

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by bridiver** [comment]
even using a relatively small pool like 5 the build still ends up being slower and occasionally beachballs. With single process it runs without any glitches

**Comment by bridiver** [comment]
> have you tried "spawn" pool instead of default "fork"? Maybe it will fix the issue? this is what I got with `spawn`: `62.4 weighted s`

@goodov I can try that, but my build is super fast now and previously I couldn't build at all. I'll try your change, but if not I could put some guards around `single_process` based on number of cpus so it doesn't impact lower powered machines.

**Comment by bridiver** [comment]
> > have you tried "spawn" pool instead of default "fork"? Maybe it will fix the issue? this is what I got with `spawn`: `62.4 weighted s`
> 
> @goodov I can try that, but my build is super fast now and previously I couldn't build at all. I'll try your change, but if not I could put some guards around `single_process` based on number of cpus so it doesn't impact lower powered machines.

Unfortunately this doesn't work on its own, but is ok in conjunction with https://github.com/brave/brave-core/pull/11953 so I think we should merge for now (the total time is likely not affected because there are other concurrent tasks running) and possibly make a change when we merge https://github.com/brave/brave-core/pull/11953

**Comment by goodov** [comment]
Screenshot 2022-04-30 at 10 16 29

`--single-process` should be guarded with some ifs to not slow down everyone who have no the issue we're trying to fix here. We can see how the whole build's just waiting for the step to finish, this is definitely a bottleneck.

Regarding python freezes/hangs when a lot of copies of it running. I assume we use different versions/builds, some of us use MacOS-bundled, some of us use dmg-installed from the official website, some of us use brew-distributed version.
It's possible that one of this versions is buggy while the other is not.
Can you try different binaries before going with `--single-process` flag? On my machine I see that brew-installed version used now and I haven't see any issues.
Could it be possible that `PYTHONPATH` that we're adding forces the python to do a lot of unnecessary stuff? Maybe we should look into it?

**Comment by bridiver** [comment]
> `--single-process` should be guarded with some ifs to not slow down everyone who have no the issue we're trying to fix here. We can see how the whole build's just waiting for the step to finish, this is definitely a bottleneck.
> 
I disagree that it's a bottleneck. I think the bottleneck is the process pool which effectively increases `-j` beyond the intended value. In my testing on my m1 laptop the build is faster with `--single_process`. It's also noticeably faster even after fixing the python3 path as mentioned below. 

> Regarding python freezes/hangs when a lot of copies of it running: I assume we use different versions/builds, some of us use MacOS-bundled, some of us use dmg-installed from the official website, some of us use brew-distributed version. It's possible that one of this versions is buggy while the other is not. Can you try different binaries before going with `--single-process` flag? On my machine I see that brew-installed version is used now and I haven't seen any issues.
I'm not going to create another dependency on a specific version of python3, but I did notice that the python3 path set in config.js is no longer correct because at some point they changed it from `python3-bin` -> `python2-bin`

> Could it be possible that `PYTHONPATH` that we're adding forces the python to do a lot of unnecessary stuff (i.e. looking at another `/Volume` triggers some OS-level lock on each python launch?)? Maybe we should look into it?
I had the same problem building with brave in my boot volume

**Comment by bridiver** [comment]
python3 path fixed here https://github.com/brave/brave-core/pull/13212/files#diff-4a7ab71a64ac5712bb35fb91782847039cf2def6ee9c3d64a7efa66562a99acfR906

**Comment by goodov** [comment]
> I disagree that it's a bottleneck. I think the bottleneck is the process pool which effectively increases `-j` beyond the intended value and overloads the machine with context switching. In my testing on my m1 laptop the build is faster with `-single_process`. It's also noticeably faster even after fixing the python3 path as mentioned below.

The ninja profile screenshot from the previous message shows a huge white area in the black row. It means that the build is not parallelised during that period, it waits for the single build step alone for more than two minutes. Looks as a solid bottleneck to me. Please test with goma and local cache enabled, the 2-minute pause during the build is very noticeable.

Full rebuild with/without single-process takes ~770 seconds vs ~630 seconds on my machine (goma, native redirect cc):

I think the better approach would be to limit the pool to some reasonable size such as 4 (the single-process/default pool ratio is ~5.5: 325.4s vs 59.1s for me on this build step)? In this case we shouldn't lose too much on parallelism (v8_bindgen step will still be fast), won't disrupt too much the desired `-j` value, but at the same time won't trigger a lot of hangs/freezes. The build time in this case ~625 seconds for me.

```
single-process:
771.8 s weighted time (63449.6 s elapsed time sum, 82.2x parallelism)

default pool:
629.7 s weighted time (69443.9 s elapsed time sum, 110.3x parallelism)

pool size 4:
626.4 s weighted time (68290.2 s elapsed time sum, 109.0x parallelism)
```

**Comment by bridiver** [comment]
> I think the better approach would be to limit the pool to some reasonable size such as 4 (the single-process/default pool ratio is ~5.5: 325.4s vs 59.1s for me on this build step). In this case we shouldn't lose too much on parallelism (`v8_bindgen` step will still be fast), won't disrupt too much the desired `-j` value, but at the same time won't trigger a lot of hangs/freezes. The build time in this case ~625 seconds for me.

I already tried limiting the pool size and it didn't help (strangely). I can try again now that I have fixed the python3 path and see if it runs smoothly.

**Comment by bridiver** [comment]
> 
> The ninja profile screenshot from the previous message shows a huge white area in the black row. It means that the build is not parallelised during that period, it waits for the single build step alone for more than two minutes. Looks as a solid bottleneck to me. Please test with goma and local cache enabled, the 2-minute pause during the build is very noticeable.
> 
Throwing goma into the mix adds too many variables that can't be easily controlled. Was the build faster because of the pool size or because of goma response times? Did you get the same local and remote cache hits on both builds?

**Comment by bridiver** [comment]
> > I think the better approach would be to limit the pool to some reasonable size such as 4 (the single-process/default pool ratio is ~5.5: 325.4s vs 59.1s for me on this build step). In this case we shouldn't lose too much on parallelism (`v8_bindgen` step will still be fast), won't disrupt too much the desired `-j` value, but at the same time won't trigger a lot of hangs/freezes. The build time in this case ~625 seconds for me.
> 
> I already tried limiting the pool size and it didn't help (strangely). I can try again now that I have fixed the python3 path and see if it runs smoothly.

Looks like it's ok in conjunction with the python3 path fix. There is minimal beach-balling with the existing redirect script and runs smoothly with native redirect cc so I'll set a max of 4 as you suggested

**Comment by bridiver** [comment]
> > I think the better approach would be to limit the pool to some reasonable size such as 4 (the single-process/default pool ratio is ~5.5: 325.4s vs 59.1s for me on this build step). In this case we shouldn't lose too much on parallelism (`v8_bindgen` step will still be fast), won't disrupt too much the desired `-j` value, but at the same time won't trigger a lot of hangs/freezes. The build time in this case ~625 seconds for me.
> 
> I already tried limiting the pool size and it didn't help (strangely). I can try again now that I have fixed the python3 path and see if it runs smoothly.

Initially I thought this was ok, but I had a local file patched and didn't realize it. Even with a pool size of 4 it still has a significant impact on the build and usability of the machine. Also @spylogsster is now seeing this issue on a laptop so this doesn't appear to be related to number of cpus. If there is some negative impact on other machines that is just something we're going to have to live with for now because other people can't run builds at all without this change.

**Comment by bridiver** [comment]
we can revisit after the native redirect cc is merged

**Comment by bridiver** [comment]
@goodov gave approval in DM so admin merging

**Review by goodov — COMMENTED** [review]
yep, I confirm that this was approved via DM discussion. This is not the best solution, because it does slow down the idl compilation, which is really noticeable during the work on IDL files, but in other cases this should be hidden by other parallel build steps.

It may be possible that the native redirect_cc will improve things so we can drop this change in future. Or maybe an upstream will parallelise the problematic step in a proper way.

**Pull request merged**
