### PR TITLE
update 'safe browsing' option in settings to 'google safe browsing'

### PR DESCRIPTION
**Pull request by MatthewZito**
This commit updates the settings option string 'Safe Browsing' to 'Google Safe Browsing'

Resolves https://github.com/brave/brave-browser/issues/8002

Brave1 8002

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [x] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
cc: @jumde to check the text. Should we also update the label underneath the setting?

**Comment by jumde** [comment]
Text looks good to me. @bsclifton we can update the label below to say Google instead of Brave since the hashes reach Safe Browsing servers after hitting the fastly proxy. Do you have any additional suggestion? cc: @tomlowenthal

**Comment by bsclifton** [comment]
Per https://twitter.com/naan_Anto/status/1233272316366245888, I think we should update the subtext.

Right now for `IDS_SETTINGS_SAFEBROWSING_ENABLEPROTECTION_DESC` it has:
`Sends URLs of some pages you visit to Brave, when your security is at risk`

Maybe we can update to something like:
`Anonymously sends URLs of some pages you visit to Google, when your security is at risk`

@MatthewZito thanks for the PR 😄 Do you think you can change this too?

**Comment by MatthewZito** [comment]
@bsclifton Not a problem! I've added the commit to this PR. Thanks for the patience; I was remote for a couple days.

**Comment by bsclifton** [comment]
Congrats on your first contribution, @MatthewZito! 😄👍

**Pull request merged**
