### PR TITLE
Disable CNAME uncloaking when DoH is enabled with an HTTPS proxy

### PR DESCRIPTION
**Pull request by antonok-edm**
Resolves https://github.com/brave/brave-browser/issues/15038

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

1. Find an HTTPS proxy with a location distinct from your own internet provider. Some free public ones are available at https://geonode.com/free-proxy-list, but be warned - they are slow and unreliable!
2. Enable this as a "system proxy". On Linux, you can do this by exporting the `https_proxy` environment variable before starting the browser, e.g. `export https_proxy=https://127.0.0.1:8080` (replace the IP and port as necessary). On Windows and macOS, visit brave://settings, search for `proxy`, and select `Open your computer's proxy settings`, then configure it there.
3. Once the proxy is configured (it might require a browser restart on macOS/Windows - I'm not sure), visit https://dnsleaktest.com. If the proxy is configured correctly, the page should show the proxy's public IP address rather than your own.
4. Run the `Standard test` to completion. In my experience, this takes a _very_ long time to complete using free public proxies, sometimes failing and requiring multiple refreshes. The test should complete with at least 1 `Servers found`.
5. Once the test is completed, you should see the list of servers appear. Verify that they are _all_ in the proxy's region, rather than near your physical location.

### CODE REVIEW

**Comment by diracdeltas** [comment]
this approach sgtm but i wonder if the `ProxySettingsAllowUncloaking` checks can be refactored into a general-purpose method, like `ShouldAllowResolveDNS`, which must be called before Brave issues a DNS request that isn't usually  issued - for instance in https://github.com/brave/brave-core/pull/8068. cc @spylogsster

**Comment by iefremov** [comment]
it looks good, can we add a test?

**Comment by antonok-edm** [comment]
@iefremov we weren't able to add proxy setting tests when I investigated last time, but I added `StubResolverConfigReader` to our unit tests.

**Review by iefremov — APPROVED** [review]

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Steps:
1. new profile
2. find and use a SOCKS5 proxy server from the list at `https://geonode.com/free-proxy-list`
3. load `dnsleaktest.com`
4. click on `Standard test`
5. wait
6. confirm your DNS resolvers aren't found and listed; instead, it should show the server's IPs

Screen Shot 2021-12-28 at 4 31 51 PM

**Pull request merged**
