### PR TITLE
Remove chrome-browser-net-net_error_tab_helper.cc.patch file

### PR DESCRIPTION
**Pull request by Gyuyoung**
This patch file is to return a false in NetErrorTabHelper::ProbesAllowed().
But, Brave has been disabling |embedder_support::kAlternateErrorPagesEnabled|
pref in RegisterProfilePrefs(). Then, |resolve_errors_with_web_service_|
should be false. Thus, it looks like we don't need to return a false
explictly using a patch file.

Resolves brave/brave-browser#12121.

Resolves 

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`, `npm run gn_check`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Requested a security/privacy review as needed.
- [ ] Added appropriate QA labels (`QA/Yes` or `QA/No`) to the associated issue
- [ ] Added appropriate release note labels (`release-notes/include` or `release-notes/exclude`) to the associated issue
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by mkarolin** [comment]
Makes sense to me, but would like to check with @diracdeltas if there were extra reasons to do it this way in https://github.com/brave/brave-core/pull/1605.

**Comment by diracdeltas** [comment]
@mkarolin @Gyuyoung IIRC i added this patch in case there's a way for users to override the default `resolve_errors_with_web_service_` pref. i'm not sure if there is/was. however i was paranoid because this comment suggests that it's tied to a setting that the user can change: https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/net/net_error_tab_helper.h;l=156-157;drc=f0b032cd66ff1c7ec17de90441a70832f6267842

the reason we wanted to disable DNS probing even if the user changes this setting is because it leaks domain names from Tor windows, which somewhat defeats the purpose of Tor. 

so i would say we can delete this patch if we are 100% sure there's no way for users to override the pref.

**Comment by Gyuyoung** [comment]
@diracdeltas Thanks for sharing the original reason to return false there. I've tried to find whether user can change the setting value. It looks like user can change the value through **chrome.privacy.alternateErrorPagesEnabled**

  - https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/extensions/api/privacy.json;l=52?q=privacy.json&ss=chromium
  - https://developers.chrome.com/extensions/privacy

Then, it looks like I need to begin to find how to disable the API without touching //brave/patches folder.

**Comment by diracdeltas** [comment]
@Gyuyoung if that extension API is the only way that the setting value can be overridden, maybe there's a way to not allow that extension permission in incognito/Tor tabs?

**Comment by Gyuyoung** [comment]
@diracdeltas Sorry for too late reply. I was working on other PRs first. I'm not fully sure if we can block that user changes the value via chrome.privacy.alternateErrorPagesEnabled. So, I just override NetErrorTabHelper::ProbesAllowed() in //chromium_src/chrome/browser/net/net_error_tab_helper.cc/h. WDYT?

**Comment by diracdeltas** [comment]
sgtm

**Comment by Gyuyoung** [comment]
> sgtm

@mkarolin What do you think about this approach?

**Comment by Gyuyoung** [comment]
I left Brave project from yesterday. So, I would like to close this PR. But, please feel free to re-open this PR if someone want to work on it.

**Pull request closed without merging**
