### PR TITLE
Removed ntp tile outline

### PR DESCRIPTION
**Pull request by simonhong**
fix https://github.com/brave/brave-browser/issues/14802

Resolves 
image

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/handbook/blob/master/development/security.md#when-is-a-security-review-needed), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by bsclifton** [comment]
I don't think we need this anymore - looks fixed w/ Chromium 90. @simonhong can you verify? Tiles PR was in 1.23 which will also feature Chromium 90

**Comment by simonhong** [comment]
@bsclifton Confirmed that latest nightly (c90) still has this issue.

**Review by bsclifton — APPROVED** [review]
Works great! 😄

**Comment by simonhong** [comment]
re-run macos CI only. others are fine with previous run.

**Comment by bsclifton** [comment]
Looking at the change a bit further (and trying things with dev tools). The right kind of fix might be to instead specify `outline:none` for the anchor tag. `unset` does work but feels like when you want it to fall back to default (versus not show at all)

**Review by bsclifton — APPROVED** [review]
Perfect 😄 
edit: found a problem maybe 10 seconds after approving lol
image

I think the first line edited (removal of `unset`) should be kept. I think we just need the 2nd line of change

**Review by bsclifton — CHANGES_REQUESTED** [review]
see comment (my bad)

**Review by bsclifton — APPROVED** [review]
Looks great! 😄 
image

**Comment by simonhong** [comment]
Two below browser tests are failed only on linux and both are definitely not related with this PR's change. Merged.
`BraveNavigatorPluginsFarblingBrowserTest.FarbleNavigatorPluginsReset`
`RewardsContributionBrowserTest.AutoContributionMultiplePublishersUphold`

**Pull request merged**
