### PR TITLE
Changed GetSelectedValue() signature to return String

### PR DESCRIPTION
**Pull request by ajayseeker**
Resolves https://github.com/brave/brave-browser/issues/25602

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Comment by sangwoo108** [comment]
I ran CI, let's see the result

**Comment by ajayseeker** [comment]
Hey @sangwoo108 , I see that two of the tests are failing. I can't see the details. Can you please share the details of what went wrong?

**Comment by sangwoo108** [comment]
> Hey @sangwoo108 , I see that two of the tests are failing. I can't see the details. Can you please share the details of what went wrong?

Sure, It seems presubmit script didn't pass. Can you run `npm run presubmit` and `npm run format` from `src/brave/` and fix them?

**Comment by ajayseeker** [comment]
Hi @sangwoo108, 

- I ran _npm run format_ command and it succeeded (I had to perform git fetch to get master branch locally)
- I ran _npm run presubmit_ and it failed due to some issues in few .js files which were not affected by my changes.

I also observed that there was another PR raised around the same time which too failed similar checks but then the subsequent ones passed. I believe they necessary .js corrected. 

Probably, if we once again run the checks I'm optimistic that they will pass. Can you please run them again?

Also, while running _npm run presubmit_ command there were other files (not concerned with my changes) which got formatted. I think these formatting changes are good to have in these files so I pushed them too.

**Comment by sangwoo108** [comment]
@ajayseeker , thanks! I reported similar things earlier today. I'll let you know when I got feedback.

**Comment by sangwoo108** [comment]
Do you mind if I try cherry pick your the initial commit and try fixing the problem?

**Comment by ajayseeker** [comment]
> Do you mind if I try cherry picking your the initial commit and try fixing the problem?

sure! No Problem.

**Comment by sangwoo108** [comment]
Closing this PR as it was merged from https://github.com/brave/brave-core/pull/22721

**Pull request closed without merging**
