### PR TITLE
Fix wrong cast exception on Android 5; fixes brave/brave-browser#17735

### PR DESCRIPTION
**Pull request by AlexeyBarabash**
Resolves https://github.com/brave/brave-browser/issues/17735

Crash happened because with the issue's STR  `BraveShieldsHandler.scanForActivity` gave result of  `android.app.ContextImpl` which was impossible to cast to `Activity`. Since `mContext` can be null, this PR adds additional check for safe casting.

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [+/- ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint` // only run npm run lint
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:
See the issue https://github.com/brave/brave-browser/issues/17735 .

### CODE REVIEW

**Review by SergeyZhukovsky — APPROVED** [review]
++

**Review by samartnik — APPROVED** [review]
lgtm

**Comment by AlexeyBarabash** [comment]
Verified on https://github.com/brave/brave-browser/releases/tag/v1.31.10, preparing the uplift PRs

**Comment by kjozwiak** [comment]
Verification **PASSED** on a `Nexus 7 (2012)` emulator running `Android 5.0 (Google APIs)` with the following build:

```
1.31.12 Chromium: 93.0.4577.58
```

Reproduced the original issue using the STR/Cases mentioned via https://github.com/brave/brave-browser/issues/17735#issue-981406563 with `1.28.106 Chromium: 92.0.4515.159` and ensured I couldn't reproduce it with `1.31.12 Chromium: 93.0.4577.58`.

**`1.28.106 Chromium: 92.0.4515.159 (broken)`** | **`1.31.12 Chromium: 93.0.4577.58`**
------------------------------------------------------|-------------------------------------------
image | image

**Pull request merged**
