### PR TITLE
Enbl `SkipUndecryptablePasswords` on Linux & macOS

### PR DESCRIPTION
**Pull request by szilardszaloki**
Resolves https://github.com/brave/brave-browser/issues/33548.

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

Fresh profile:
1. open the browser
2. go to `brave://password-manager/passwords`
3. add two passwords:
    1. password
        1. Site: `aaaaa.com`
        2. Username: `aaaaa`
        3. Password: `aaaaa`
    2. password
        1. Site: `bbbbb.com`
        2. Username: `bbbbb`
        3. Password: `bbbbb`
4. close the browser
5. open `~/Library/Application Support/BraveSoftware/Brave-Browser/Default/Login Data` in [DB Browser for SQLite](https://sqlitebrowser.org)
6. go to `Execute SQL`
7. paste
    ```
    UPDATE logins SET password_value = x'7631301f2bb0cc71024cedf754d0992d32' WHERE username_value = 'aaaaa'
    ```
     hit `F5`, then save (e.g. `Cmd` + `S`)
8. close [DB Browser for SQLite](https://sqlitebrowser.org)
9. open the browser
10. make sure the password for `bbbbb.com` is still showing

### CODE REVIEW

**Review by bsclifton — APPROVED** [review]
LGTM - until approved/merged/uplifted, we have raised the Griffin PRs here:
- https://github.com/brave/brave-variations/pull/1165
- https://github.com/brave/brave-variations/pull/1166

**Review by bcaller — APPROVED** [review]
Approved for sec-team

**Review by goodov — APPROVED** [review]

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.70.60 Chromium: 128.0.6613.18 (Official Build) nightly (arm64) 
Revision	f110df81ade140122b1c2a8cf40f7d25ef15b1bc
OS	macOS Version 14.6.1 (Build 23G93)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.70.60 Chromium: 128.0.6613.18 (Official Build) nightly (64-bit)
-- | --
Revision | f110df81ade140122b1c2a8cf40f7d25ef15b1bc
OS | Linux
```

Reproduced the issue of passwords not being displayed under `brave://password-manager/passwords` using `1.70.58 Chromium: 128.0.6613.18` and test plan from https://github.com/brave/brave-core/pull/25040#issue-2455036334:

Step 3 | Step 7 | Step 10
--- | --- | ---
 |  | 


<details>
<summary>Upgrade profile - PASSED</summary>

Using `1.70.60 Chromium: 128.0.6613.18` and continuing from above profile, after updating to `1.70.60`, confirmed password for `bbbbb.com` was displayed under `brave://password-manager/passwords` as expected:

Screenshot 2024-08-09 at 10 30 13 AM

</details>

**Pull request merged**
