### PR TITLE
Retain publisher status data on migration to publisher list v4

### PR DESCRIPTION
**Pull request by zenparsing**
Resolves https://github.com/brave/brave-browser/issues/10840

- Modified migration logic so that `server_publisher_info` is retained for verified publishers that occur in the `publisher_info` table.
- Disabled purging of expired `server_publisher_info` records on prefix list update.
- Updated database test along with modifications to the 27 test database files.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:

- Install 1.11.x (current release channel version), enable Rewards, confirm entire publisher list is downloaded.
- Visit some sites (mix of verified and unverified) to populate your AC table.
- Upgrade to latest.
- Navigate to `brave://rewards`.
  - Verify that verified checkmark appears for all verified publisher icons.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by zenparsing** [comment]
Added records to `server_publisher_*` tables that will get deleted based on there not being a corresponding entry in `publisher_info`.

**Comment by zenparsing** [comment]
Build passed on all platforms except windows, restarting on windows.

**Comment by LaurenWags** [comment]
Verification is in progress

```
Brave | 1.13.51 Chromium: 84.0.4147.105 (Official Build) nightly (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from description

* Set up AC and recurring tips for a mix of publishers with 1.11.104:
1 11 104-a
1 11 104-b

* Updated to 1.13.51 and confirmed publisher verified status was retained on AC and recurring tips list:
1 30 50-a
1 30 50-b

* Also confirmed if AC is off but there are recurring tips set up on 1.11.x, when upgrading to 1.13.x the verified status is retained for currently set up recurring tips.

* However, after updating and visiting some new sites, the panel isn't showing publisher info as below. Have reached out to @zenparsing and he is investigating.

**Comment by zenparsing** [comment]
Below is a redacted log filtered for rewards service events, corresponding to the case @LaurenWags mentioned above:

```
[22676:775:0728/165312.973506:WARNING:account_consistency_mode_manager.cc(198)] Desktop Identity Consistency cannot be enabled as no OAuth client ID and client secret have been configured.
[22676:775:0728/165313.006442:VERBOSE1:rewards_service_impl.cc(435)] Starting ledger process
[22676:775:0728/165313.773113:VERBOSE1:database_migration.cc(113)] DB: Migrated to version 27
[22676:775:0728/165313.776702:VERBOSE1:database_migration.cc(113)] DB: Migrated to version 28
[22676:775:0728/165313.937677:VERBOSE5:ledger_impl.cc(475)] 
[ REQUEST ]
> URL: https://grant.rewards.brave.com/v3/wallet/uphold/{wallet-id}
> Method: UrlMethod::GET
[22676:775:0728/165314.272937:VERBOSE6:wallet_balance.cc(58)] 
[ RESPONSE - OnFetch ]
> Url: https://grant.rewards.brave.com/v3/wallet/uphold/{wallet-id}
> Result: Success
> HTTP Code: 200
> Body: {"total":9,"spendable":9,"confirmed":9,"unconfirmed":0}
[22676:775:0728/165314.568126:VERBOSE5:ledger_impl.cc(475)] 
[ REQUEST ]
> URL: https://grant.rewards.brave.com/v3/wallet/uphold/{wallet-id}
> Method: UrlMethod::GET
[22676:775:0728/165314.677551:VERBOSE6:wallet_balance.cc(58)] 
[ RESPONSE - OnFetch ]
> Url: https://grant.rewards.brave.com/v3/wallet/uphold/{wallet-id}
> Result: Failure
> HTTP Code: 429
> Body: limit exceeded
[22676:775:0728/165314.677650:INFO:wallet_balance.cc(63)] Couldn't fetch wallet balance
[22676:775:0728/165314.677707:ERROR:validation_errors.cc(76)] Invalid message: VALIDATION_ERROR_UNEXPECTED_NULL_POINTER (null field 2)
[0728/165314.685614:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee0d24000, 0x2000): (os/kern) invalid address (1)
[22676:29187:0728/165314.832933:ERROR:browser_child_process_host_impl.cc(726)] Terminating child process for bad message: Received bad user message: Validation failed for bat_ledger.mojom.BatLedger response [VALIDATION_ERROR_UNEXPECTED_NULL_POINTER (null field 2)]
[22676:775:0728/165315.833352:VERBOSE1:rewards_service_impl.cc(428)] Ledger process is already running
```

It appears that for this case we have the following sequence of events:

- Ledger send off two requests for uphold wallet info.
- The second request is rate-limit blocked with a 429 error.
- This causes an empty wallet struct pointer to get passed back through mojo.
- This causes a validation error which crashes the ledger process.
- The ledger process is not restarted for some reason, and therefore the prefix list is never downloaded.

I think this behavior is unrelated to the PR, and is initiated by the 429 error returned from the server. We should separately take a look at more gracefully dealing with these errors, though, and perhaps deduping the requests to the wallet endpoint.

cc @NejcZdovc

**Pull request merged**
