### PR TITLE
Fix bug where some iron icons weren't showing up properly.

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Resolves https://github.com/brave/brave-browser/issues/24872
Resolves https://github.com/brave/brave-browser/issues/24944

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

Navigate to brave://settings/privacy and confirm that the clear browsing data, security & site and shields settings icons are visible.

### CODE REVIEW

**Review by sangwoo108 — APPROVED** [review]
LGTM! So the cause was that the invisible icons didn't have '#selectedGradient` def, right?

**Comment by fallaciousreasoning** [comment]
Yeah it was :laughing: I've been running into so many issues with `iron-icons` I'm tempted to try and replace it with a React/Svelte component. Not sure how nice it'll play with the Polymer UI though :cry:

**Comment by petemill** [comment]
> Yeah it was 😆 I've been running into so many issues with `iron-icons` I'm tempted to try and replace it with a React/Svelte component. Not sure how nice it'll play with the Polymer UI though 😢

I think this is a good ambition, especially for the menu where we've almost completely customized it anyway. Well, good except from the react part!

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.45.30 Chromium: 105.0.5195.102 (Official Build) nightly (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.918)
```

### `Test Case #1 - brave://settings/privacy` - https://github.com/brave/brave-browser/issues/24872

**`Example`** | **`Example`**
---------------|----------------
PrivacySettingsFixedLight | PrivacySettingsFixedDark

### `Test Case #2 - brave://settings/importData` - https://github.com/brave/brave-browser/issues/24944

**`Chrome Import`** | **`Chrome Import`**
------------------------|-------------------------
chromeImport | chromeImportDark

**`Edge Import`** | **`Edge Import`**
--------------------|-------------------------
MSedge | MSedgeDark

**`Firefox Import`** | **`Firefox Import`**
--------------------|-------------------------
firefoxImport | firefoxImportDark

**Pull request merged**
