### PR TITLE
Adds support for non-verified flag

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves https://github.com/brave/brave-browser/issues/2111

Native ledger: https://github.com/brave-intl/bat-native-ledger/pull/200/commits
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Test Plan:
- enable rewards
- visit slo-tech.com for 10s
- make sure that this site is listed in the table
- go to auto contribute settings
- disable non verified sites
- make sure that ac table reflects the change
- visit 3zsistemi.si for 10s
- make sure that is listed in the table
- visit clifton.io for 10s
- make sure that is not listed in the table
- go to ac settings and enable non verified sites
- make sure that both slo-tech.com and 3zsistemi.si are listed

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by ryanml** [comment]
0.61 (master): e17fdede116f407a9aa5724f4227332ba1c92416
0.60: 315a32b865f52c4b5db7eeccc331be6a9bb1d70a

**Comment by srirambv** [comment]
@NejcZdovc need clarrification
disable non verified sites
make sure that ac table reflects the change
visit 3zsistemi.si for 10s
make sure that is listed in the table   -  **shouldn't list because disabled non verified sites in settings**
visit clifton.io for 10s
make sure that is not listed in the table - **should list because its a verified pub**
go to ac settings and enable non verified sites
make sure that both slo-tech.com and 3zsistemi.si are listed - **shouldnt it be slo-tech.com and clifton.io because 3zsistemi.si was logged when non-verified pubs was disabled**

**Comment by NejcZdovc** [comment]
@srirambv test plan is for staging where 3zsistemi.si is verified

**Comment by NejcZdovc** [comment]
yup, just replace 3zsistemi.si with clifton.io in my test plan if checking on production

**Pull request merged**
