### PR TITLE
Fix error message: Brave needs Windows 10, not 7/8 (uplift to 1.49.x)

### PR DESCRIPTION
**Pull request by mherrmann**
Uplift of https://github.com/brave/brave-core/pull/17234
Resolves https://github.com/brave/brave-browser/issues/28511

Pre-approval checklist: 
- [x] You have tested your change on Nightly. 
- [ ] This contains text which needs to be translated. 
    - [ ] There are more than 7 days before the release. 
    - [ ] I've notified folks in #l10n on Slack that translations are needed. 
- [x] The PR milestones match the branch they are landing to. 

Pre-merge checklist: 
- [x] You have checked CI and the builds, lint, and tests all pass or are not related to your PR. 

Post-merge checklist: 
- [x] The associated issue milestone is set to the smallest version that the changes is landed on.

### CODE REVIEW

**Comment by mherrmann** [comment]
Looking good on (German) Windows 8:

image

**Comment by mherrmann** [comment]
Windows 10 still works as expected:
image

**Comment by mherrmann** [comment]
(This PR can be tested by running BraveBrowserStandaloneNightlySetup.exe from https://ci.brave.com/job/test-brave-browser-build-windows-x64/806/ on Windows 7/8/10/11. The standalone binaries produced by the PR builder don't work because they are not Release builds.)

**Review by kjozwiak — APPROVED** [review]
Uplift into `1.49.x` approved 👍 QA has verified the PR on Nightly as per https://github.com/brave/brave-core/pull/17234#issuecomment-1459302105.

**Pull request merged**
