### PR TITLE
Remove Windows-specific adjustment for scaled resolutions when solving captchas

### PR DESCRIPTION
**Pull request by emerick**
Resolves https://github.com/brave/brave-browser/issues/17476

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [x] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [x] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by zenparsing — APPROVED** [review]
❤️

**Review by bsclifton — APPROVED** [review]
Tested at 100%, 125%, 150%, 175%, and 200% - all worked great 😄 (I usually use 100%)

I didn't log out and log back in after changing resolution though (this can make a difference in some cases)

**Review by szilardszaloki — APPROVED** [review]
* `1920 x 1200`:
  * 100% :white_check_mark:
  * 125% :white_check_mark:
  * 150% :white_check_mark:
  * 175% :white_check_mark:
  * 200% :white_check_mark:
* `5120 x 1440`:
  * 100% :white_check_mark:
  * 125% :white_check_mark:
  * 150% :white_check_mark:
  * 175% :white_check_mark:
  * 200% :white_check_mark:
  * 225% :white_check_mark:

**Comment by emerick** [comment]
Tested 3x at 100%, 125%, 150%, 175%, and 200% logging out between each change and it seems good.

**Comment by GeetaSarvadnya** [comment]
Great Job! @emerick 

Verification passed on

```
Brave | 1.31.50 Chromium: 94.0.4606.50 (Official Build) nightly (64-bit)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | Windows 10 Version 21H1 (Build 19043.1165)
```
- Verified the issue against the `Display resolution 1920 x 1080` with 125%, 150%, 175% and 100% app resolution

**_125 % resolution - Captch test_**
125% Resolution-Captcha test

**_150 % resolution - Captch test_**
150% Resolution-Captcha test

**_175 % resolution - Captch test_**
175% Resolution-Captcha test

**_100 % resolution - Captch test_**
100% Resolution-Captcha test

**Pull request merged**
