### PR TITLE
allow first party subdomains when blocking 3rd-party cookies to match…

### PR DESCRIPTION
**Pull request by bridiver**
… default 3rd-party cookie blocking policy

fix https://github.com/brave/brave-browser/issues/9337

Resolves 

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- [x] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by pes10k** [comment]
lgtm

**Comment by bridiver** [comment]
unrelated test failures in CI

**Comment by kjozwiak** [comment]
## `Desktop Cases:`

Reproduced the issue on `macOS 10.15.4 x64` using the following build:

```
Brave | 1.10.3 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.15.4 (Build 19E287)
```

* Visit Twitter and set `All Cookies Allowed` as per https://github.com/brave/brave-browser/issues/9337#issuecomment-617273393 before logging into Twitter
* Login into Twitter (ensuring that `All Cookies Allowed` is set)
* Once logged in, change the shields settings to `Cross-site cookies blocked`

Screen Shot 2020-04-26 at 6 20 30 PM

Verification **PASSED** on `macOS 10.15.4 x64` using the following build:

```
Brave | 1.10.11 Chromium: 81.0.4044.122 (Official Build) nightly (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.15.4 (Build 19E287)
```

* ensured that the above STR wasn't reproducible on a clean profile
  * ensured that switching between `All Cookies Allowed` & `Cross-site cookies blocked` didn't cause Twitter displaying `Something went wrong` as per the above.
* ensured that upgrading from `1.10.3 Chromium: 81.0.4044.113` to a newer version of Nightly fixed the `Something went wrong` issue.
    * ensured that switching between `All Cookies Allowed` & `Cross-site cookies blocked` didn't cause any issues

**Comment by kjozwiak** [comment]
I can still reproduce this on `Samsung S10+` with `Android 10` using the following build:

```
Brave - Nightly 1.10.11 CR: 81.0.4044.122
```

Example of the issue occurring: https://youtu.be/tTkfAaGITc0

@bridiver assuming this should have landed in `Brave - Nightly 1.10.11 CR: 81.0.4044.122` as it's working on desktop via `1.10.11 Chromium: 81.0.4044.122`.

@srirambv can you reproduce the issue on your device?

**Comment by bsclifton** [comment]
@kjozwiak per commit log https://github.com/brave/brave-core/commits/37110161e042202ace67a2ea49991c7d97210d9c

This has been in since `1.10.5`. So it's definitely there- not sure why Android isn't working though

**Comment by srirambv** [comment]
Reproduced on 1.10.11 x64 nightly build. Noticed it sometimes starts working if I switch to desktop site.

**Comment by kjozwiak** [comment]
> @kjozwiak per commit log https://github.com/brave/brave-core/commits/37110161e042202ace67a2ea49991c7d97210d9c
> 
> This has been in since `1.10.5`. So it's definitely there- not sure why Android isn't working though

yup, assumed once it landed it should be in both desktop and Android. Seems like this PR doesn't fix the problem on Android though. Looks like @srirambv can also reproduce as per the above.

**Comment by GeetaSarvadnya** [comment]
Reproduce in Android - `Brave 1.5.113` - Running on `Samsung Galaxy J3`
Reproduce in Android - `Brave 1.10.11` - Running on `Samsung Galaxy J3`
Reproduce in Desktop - `Brave Nightly 1.10.2` and  `Brave Nightly 1.10.3` -Running on `Windows 10 x64 ` upgrade to `Nightly 1.10.11` fixed the issue
Not Reproduced in Desktop - `Brave Nightly 1.10.11` - Running on `Windows 10 x64`

**Pull request merged**
