### PR TITLE
Revert "Extend tab hit box to top of tabstrip when maximized"

### PR DESCRIPTION
**Pull request by zenparsing**
This reverts commit f92e0154a3a2fe487bda7dcf7894acd77cc52099.

Resolves https://github.com/brave/brave-browser/issues/34137
Resolves https://github.com/brave/brave-browser/issues/34141

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run lint`, `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

### CODE REVIEW

**Review by sangwoo108 — APPROVED** [review]
My bad, I didn't thought it'd affect the vertical tabs like that. Thanks!

**Review by mkarolin — APPROVED** [review]
`chromium_src`++

**Comment by zenparsing** [comment]
@sangwoo108 Nope - my bad! Made sure to test all the horizontal tab cases but forgot to test vertical tabs as well.

**Comment by zenparsing** [comment]
The issue is that upstream will hide tab icons if the tab view's height is less than the value of the `TAB_HEIGHT` layout constant. Vertical tabs are 36px tall, whereas the `TAB_HEIGHT` constant is 44 in order to account for the padding above and below the tabs visual shape.

https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/tabs/tab.cc;l=999?q=tab.cc&ss=chromium

To keep things consistent between horizontal tabs and vertical tabs they should be the same height in both modes. This means that vertical tabs will also have to maintain a vertical padding (which will need to overlap as well).

**Comment by sangwoo108** [comment]
@zenparsing We're overriding UpdateIconVisibility() from BraveTab for vertical tabs. Do you think it's possible to make favicon and close button visible while keeping layout as is?

**Comment by zenparsing** [comment]
@sangwoo108 Unfortunately, that early return when it checks the tab view's height will prevent us from using almost all of the upstream logic in `UpdateIconVisibility`.

**Comment by sangwoo108** [comment]
@zenparsing Ah yeah, you're right. It'll end up with cribbing upstream code to BraveTab. But I'm still a little bit hesitant to bring back the overlap to vertical tabs, because there could be a lot of side effects from it, such as DnD, painting order, and etc. So I think it might be better to add a patch so that the early return doesn't work for vertical tabs.

**Comment by zenparsing** [comment]
@sangwoo108  I've created a PR with a patch that just comments out the early return here: https://github.com/brave/brave-core/pull/20813. Let me know what you think.

**Pull request merged**
