### PR TITLE
Default shield advanced view to TRUE for existing users.

### PR DESCRIPTION
**Pull request by bsclifton**
Fixes https://github.com/brave/brave-browser/issues/5582

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [x] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
1. Have an existing profile (before 0.69.x)
1. Launch this version
1. Look in brave://settings and confirm advanced view is chosen
1. Open brave.com and click shields. Verify advanced view is shown
1. Close Brave
1. New profile and launch
1. Look in brave://settings and confirm simple view is chosen
1. Open brave.com and click shields. Verify simple view is shown

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
ah- good catch... thanks! 😄 Will address

**Comment by bsclifton** [comment]
Some lint failures - not sure on the other failures here. Will fix the lints soon and push again later tonite

**Comment by cezaraugusto** [comment]
confirmed manual test works. ++ once tests are passing

**Comment by bsclifton** [comment]
Build worked great (all tests + lint passed), except for android. Need to troubleshoot this:
https://staging.ci.brave.com/job/brave-browser-build-pr/job/bsc-shields-advanced-default-change/4/execution/node/425/log/

**Comment by bsclifton** [comment]
OK this should be G2G now - let's let CI finish 😄

**Comment by bsclifton** [comment]
@petemill @cezaraugusto can you please re-review? 😄

**Comment by mkarolin** [comment]
@bsclifton `BraveProfilePrefsBrowserTest.AdvancedShieldsExistingUserValue` is crashing for me on Windows. CI doesn't run browser tests on Windows :(.

**Comment by bsclifton** [comment]
@mkarolin oh no! Thanks for the heads up

**Comment by bsclifton** [comment]
update: I ran tests on Win64 (in release mode) and it worked great. Might be a DCHECK failure. Will compile debug and re-run

**Comment by bsclifton** [comment]
Error looks like this:
```
[8784:8388:0819/155955.045:ERROR:brave_static_redirect_network_delegate_helper.cc(185)] URL not allowed from system network delegate: http://update.googleapis.com/service/update2/json
[8784:8388:0819/155955.048:ERROR:brave_static_redirect_network_delegate_helper.cc(185)] URL not allowed from system network delegate: http://update.googleapis.com/service/update2/json
[8784:8388:0819/155955.049:ERROR:brave_static_redirect_network_delegate_helper.cc(185)] URL not allowed from system network delegate: http://update.googleapis.com/service/update2/json
[8784:8388:0819/155955.050:ERROR:brave_static_redirect_network_delegate_helper.cc(185)] URL not allowed from system network delegate: http://update.googleapis.com/service/update2/json
[8784:8388:0819/155955.361:FATAL:thread_restrictions.cc(76)] Check failed: !g_blocking_disallowed.Get().Get(). Function marked as blocking was called from a scope that disallows blocking! If this task is running inside the ThreadPool, it needs to have MayBlock() in its TaskTraits. Otherwise, consider making this blocking work asynchronous or, as a last resort, you may use ScopedAllowBlocking (see its documentation for best practices).
g_blocking_disallowed currently set to true by
```

**Comment by bsclifton** [comment]
Created https://github.com/brave/brave-browser/issues/5736 to track this problem; will fix ASAP 😄

**Pull request merged**
