### PR TITLE
Default OOP rasterization to off (original value)

### PR DESCRIPTION
**Pull request by bsclifton**
OOP rasterization is causing issues for some users (artifacts, crashes)

Resolves problems some users are having with crashes and graphic artifacts (blurred or wrong pixel values). Removing the flag for this would regress performance for folks not affected. We may want to look at a different (safer) way to solve https://github.com/brave/brave-browser/issues/6613 (which I believe that Chrome is solving via field trials)

[Deviations page](https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)) doesn't need updating, since details about force enabling weren't originally added 

Fixes https://github.com/brave/brave-browser/issues/7581
Fixes https://github.com/brave/brave-browser/issues/6979

Reverts https://github.com/brave/brave-core/pull/3793
Unfixes https://github.com/brave/brave-browser/issues/6613

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protection-Mode
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:
TBD

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by bsclifton** [comment]
@bbondy if this is approved/merged, should we re-open https://github.com/brave/brave-browser/issues/6613?

**Comment by bsclifton** [comment]
`test-install` failed on macOS, otherwise CI did great 👍 (all platforms built / tests pass)

**Comment by iefremov** [comment]
@bsclifton Does it really fix the mentioned issues? There is some feedback saying it doesn't. I'm basically OK with merging it (since it seems it is still in trials in Chrome), just want to understand trade-offs.

**Comment by bsclifton** [comment]
@iefremov it does indeed fix both display glitches and specific crash situations (most which have been fixed are Linux). But it doesn't fix as many situations as I had hoped. That said, it still is a deviation from Chromium in an area which I'm personally not sure if it makes sense to differentiate

I believe there have been about 4 reports which I have been able to confirm that disabling fixed the problem. The tradeoff would be: for folks not experiencing crash or graphical artifacts, there would be a slight performance loss

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.2 x64` using the following build:

Brave | 1.5.25 Chromium: 79.0.3945.117 (Official Build) nightly (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57)

* ensured that `Hardware Protected Video Decode: Unavailable` was disabled under `brave://gpu`
* ensured that `--enable-oop-rasterization=enabled` wasn't being displayed under `brave://version` as per the test plan outlined under https://github.com/brave/brave-core/pull/4318#issue-360127918.

**Pull request merged**
