### PR TITLE
Fixes 503 response does not add confirmation to queue - 0.69.x

### PR DESCRIPTION
**Pull request by tmancey**
Fixes https://github.com/brave/brave-browser/issues/5599
Uplift request for https://github.com/brave/brave-core/pull/3126

### CODE REVIEW

**Comment by tmancey** [comment]
> Talked to @jsecretan on Friday and we decided that #3126 can go through the trains until it's released in `0.70.x` on `October 1, 2019`. The situation with the backend sending back `500` and `503` errors has improved. If the need to get this into the release channel arises again, we can revisit.

Speaking with @jsecretan this ideally needs uplifting due to issues at the weekend where 5xx errors were reported from the server

**Comment by kjozwiak** [comment]
@tmancey looks like there's some browser failures via https://staging.ci.brave.com/job/brave-browser-build-pr/job/issues%252F5599-0.69.x/1/execution/node/495/log/:

```
12:07:45  [ RUN      ] SecurityIndicatorTest.CheckIndicatorText
12:07:45  [19/222] SecurityIndicatorTest.CheckIndicatorText (TIMED OUT)
12:07:45  [ RUN      ] BraveContentSettingsRegistryBrowserTest.WithoutWildcardContentSetting
12:07:45  [20/222] BraveContentSettingsRegistryBrowserTest.WithoutWildcardContentSetting (TIMED OUT)
12:07:45  [ RUN      ] NavigatorBluetoothDisabledTest.IsDisabled
12:07:45  [21/222] NavigatorBluetoothDisabledTest.IsDisabled (TIMED OUT)
12:07:45  [ RUN      ] BraveContentSettingsRegistryBrowserTest.WithWildcardContentSetting
12:07:45  [22/222] BraveContentSettingsRegistryBrowserTest.WithWildcardContentSetting (TIMED OUT)
12:07:45  Too many badly broken tests (22), exiting now.
```

**Comment by tmancey** [comment]
> @tmancey looks like there's some browser failures via https://staging.ci.brave.com/job/brave-browser-build-pr/job/issues%252F5599-0.69.x/1/execution/node/495/log/:
> 
> ```
> 12:07:45  [ RUN      ] SecurityIndicatorTest.CheckIndicatorText
> 12:07:45  [19/222] SecurityIndicatorTest.CheckIndicatorText (TIMED OUT)
> 12:07:45  [ RUN      ] BraveContentSettingsRegistryBrowserTest.WithoutWildcardContentSetting
> 12:07:45  [20/222] BraveContentSettingsRegistryBrowserTest.WithoutWildcardContentSetting (TIMED OUT)
> 12:07:45  [ RUN      ] NavigatorBluetoothDisabledTest.IsDisabled
> 12:07:45  [21/222] NavigatorBluetoothDisabledTest.IsDisabled (TIMED OUT)
> 12:07:45  [ RUN      ] BraveContentSettingsRegistryBrowserTest.WithWildcardContentSetting
> 12:07:45  [22/222] BraveContentSettingsRegistryBrowserTest.WithWildcardContentSetting (TIMED OUT)
> 12:07:45  Too many badly broken tests (22), exiting now.
> ```

These are unrelated, thanks

**Comment by kjozwiak** [comment]
@tmancey looks like it failed at the same spot as https://github.com/brave/brave-core/pull/3127#issuecomment-526263695. Any idea's why those tests would be failing?

**Comment by tmancey** [comment]
> @tmancey looks like it failed at the same spot as [#3127 (comment)](https://github.com/brave/brave-core/pull/3127#issuecomment-526263695). Any idea's why those tests would be failing?

@kjozwiak I have rebased and started a new build. Speaking with @NejcZdovc he had same issues this week and just had to keep restarting the build

**Comment by kjozwiak** [comment]
@tmancey rerunning it again... There were a few failures. Hopefully this one passes everything 👍 Seems like tests just keep timing out even after @mihaiplesa restarted those specific nodes causing the timeouts.

**Comment by tmancey** [comment]
> @tmancey rerunning it again... There were a few failures. Hopefully this one passes everything 👍 Seems like tests just keep timing out even after @mihaiplesa restarted those specific nodes causing the timeouts.

Failed again on macOS, passed on others. Failure was unrelated.

**Comment by tmancey** [comment]
I can confirm these failures passed in previous checks. I am merging and will update as necessary. Thanks

**Pull request merged**
