### PR TITLE
Language change: one time tip => one-time tip

### PR DESCRIPTION
**Pull request by rbrishabh**
Fixes [16387](https://github.com/brave/brave-browser/issues/16387)

Hi @stephendonner!
How does this look? Let me know if this needs any changes!
Thanks

### CODE REVIEW

**Comment by bsclifton** [comment]
Hi @rbrishabh - thanks for the PR 😄 

Can you update your commit so that you're only changing the English version of the files? The others will automatically get populated when we pull our translations down from the vendor. Thanks again 😄

**Comment by rbrishabh** [comment]
Sure! will do

**Comment by rbrishabh** [comment]
hey @bsclifton - thanks for your review! I have made the changes!

**Review by bsclifton — APPROVED** [review]
LGTM! 😄

**Comment by bsclifton** [comment]
Changes LGTM; added @stephendonner to give it a once-over 😄

**Comment by stephendonner** [comment]
@bsclifton thanks for taking care of this - and thanks to @rbrishabh for the fixes!  I'm way behind on GitHub notifications; trying to catch up!

**Pull request merged**
