### PR TITLE
pinned depot_tools

### PR DESCRIPTION
**Pull request by mihaiplesa**
Resolves https://github.com/brave/brave-browser/issues/8850

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

### CODE REVIEW

**Comment by simonhong** [comment]
We also need this changes.
```
diff --git a/build/commands/lib/config.js b/build/commands/lib/config.js
index 282b03c7bb..b762f1dbb6 100755
--- a/build/commands/lib/config.js
+++ b/build/commands/lib/config.js
@@ -603,6 +603,7 @@ Object.defineProperty(Config.prototype, 'defaultOptions', {
     env = this.addPythonPathToEnv(env, path.join(this.srcDir, 'third_party', 'depot_tools'))
     env.GCLIENT_FILE = this.gClientFile
     env.DEPOT_TOOLS_WIN_TOOLCHAIN = '0'
+    env.DEPOT_TOOLS_UPDATE = '0'
     env.PYTHONUNBUFFERED = '1'
     env.TARGET_ARCH = this.gypTargetArch // for brave scripts
     env.GYP_MSVS_VERSION = env.GYP_MSVS_VERSION || '2017' // enable 2017
```

**Comment by mkarolin** [comment]
I don't imagine we'd want to have depot_tools pinned forever, so what will be process of updating to later versions?
If we do want to pin it, perhaps we can add a periodic job on CI could verify that the latest depot tools don't break our builds and update the version if it passes?
I am worried that we will have builds broken more often because we didn't update depot tools than because we did.

**Comment by mihaiplesa** [comment]
@mkarolin you're right, and this solution fails now on Windows with:

```
20:22:47  > gclient sync --reset --nohooks --revision src/brave@mplesa-depot-tools-pin --revision src@refs/tags/85.0.4183.59 --force --with_tags --with_branch_heads --upstream
20:22:47  The system cannot find the file C:\-pin\src\brave\vendor\depot_tools\python3_bin_reldir.txt.
20:22:47  
20:23:05  [E2020-08-13T19:23:03.842686Z 6800 0 annotate.go:241] original error: exec: "C:\\-pin\\src\\brave\\vendor\\depot_tools\\python3.exe": file does not exist
20:23:05  
```

**Comment by bsclifton** [comment]
Closing as I closed https://github.com/brave/brave-browser/issues/8850 as `wontfix`

**Pull request closed without merging**
