### PR TITLE
update DEPS for brave-extension

### PR DESCRIPTION
**Pull request by cezaraugusto**
ref https://github.com/brave/brave-extension/commit/038a43af5294150d48ce94a326290f70aa001cd0

in this change:

* add deeplink to the shields section https://github.com/brave/brave-extension/pull/80
* disallow click event when stats are 0 https://github.com/brave/brave-extension/pull/81
* set stats to 99+ if resource is aboce that number https://github.com/brave/brave-extension/pull/82

### CODE REVIEW

**Comment by cezaraugusto** [comment]
master 0c6fe70
0.58.x 1fa00afc
0.57.x uplift request

**Comment by bsclifton** [comment]
Added `merged/0.58.x-Dev` to reflect where it's at currently 👍

**Comment by kjozwiak** [comment]
Approved uplift to `0.57.x` after deliberating with @srirambv & @rebron

**Comment by bbondy** [comment]
only 1 merge label for smallest version, thanks!

**Pull request merged**
