### PR TITLE
Update omaha repo to support silent tag

### PR DESCRIPTION
**Pull request by simonhong**
Fix https://github.com/brave/brave-browser/issues/2356

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [x] Windows
  - [ ] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [x] Windows
  - [ ] macOS
  - [ ] Linux
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

**Comment by NejcZdovc** [comment]
master (0.60) a001451

**Comment by simonhong** [comment]
@rebron @kjozwiak @srirambv Uplift requested

**Comment by srirambv** [comment]
Uplift approved after discussing with @rebron and @kjozwiak. Please update labels once commit added to `0.57.x`

**Comment by bsclifton** [comment]
master a00145141cfcc32c063ec3eeefa8a97b3ed4345b
0.59.x 462cf5f8f7c2c2022adcb3b7021e1ce05ef5515c
0.58.x be9bd266b83a129c7e498ca14804f9dd2704cc17
0.57.x 48a1f1632915c45dd4d5dc97f2439d63ae4e28c3

**Pull request merged**
